### ISSUE TITLE
Mypy crashes when a function is defined within a function decorated with no_type_check

### ISSUE THREAD

**Issue by RobertCraigie** [python/mypy#10025]
**Crash Report**

Title doesn't tell the full story, for example, mypy does not crash in this situation

```py
from typing import no_type_check

@no_type_check
def foo() -> None:
    def bar() -> None:
        pass
```

**Traceback**

```
File "/usr/local/lib/python3.6/dist-packages/mypy/nodes.py", line 2660, in __getattribute__
   raise AssertionError(object.__getattribute__(self, 'msg'))
AssertionError: fallback can't be filled out until semanal
```
<details>
  <summary>Click to show full traceback</summary>
  
   ```
  Traceback (most recent call last):
    File "/usr/local/bin/mypy", line 11, in <module>
      load_entry_point('mypy==0.790', 'console_scripts', 'mypy')()
    File "/usr/local/lib/python3.6/dist-packages/mypy/__main__.py", line 8, in console_entry
      main(None, sys.stdout, sys.stderr)
    File "/usr/local/lib/python3.6/dist-packages/mypy/main.py", line 90, in main
      res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
    File "/usr/local/lib/python3.6/dist-packages/mypy/build.py", line 181, in build
      sources, options, alt_lib_path, flush_errors, fscache, stdout, stderr, extra_plugins
    File "/usr/local/lib/python3.6/dist-packages/mypy/build.py", line 254, in _build
      graph = dispatch(sources, manager, stdout)
    File "/usr/local/lib/python3.6/dist-packages/mypy/build.py", line 2630, in dispatch
      process_graph(graph, manager)
    File "/usr/local/lib/python3.6/dist-packages/mypy/build.py", line 2953, in process_graph
      process_stale_scc(graph, scc, manager)
    File "/usr/local/lib/python3.6/dist-packages/mypy/build.py", line 3045, in process_stale_scc
      mypy.semanal_main.semantic_analysis_for_scc(graph, scc, manager.errors)
    File "/usr/local/lib/python3.6/dist-packages/mypy/semanal_main.py", line 84, in semantic_analysis_for_scc
      check_type_arguments(graph, scc, errors)
    File "/usr/local/lib/python3.6/dist-packages/mypy/semanal_main.py", line 360, in check_type_arguments
      state.tree.accept(analyzer)
    File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
      self.gen.throw(type, value, traceback)
    File "/usr/local/lib/python3.6/dist-packages/mypy/build.py", line 1922, in wrap_context
      yield
    File "/usr/local/lib/python3.6/dist-packages/mypy/semanal_main.py", line 360, in check_type_arguments
      state.tree.accept(analyzer)
    File "/usr/local/lib/python3.6/dist-packages/mypy/nodes.py", line 295, in accept
      return visitor.visit_mypy_file(self)
    File "/usr/local/lib/python3.6/dist-packages/mypy/semanal_typeargs.py", line 39, in visit_mypy_file
      super().visit_mypy_file(o)
    File "/usr/local/lib/python3.6/dist-packages/mypy/traverser.py", line 35, in visit_mypy_file
      d.accept(self)
    File "/usr/local/lib/python3.6/dist-packages/mypy/nodes.py", line 677, in accept
      return visitor.visit_func_def(self)
    File "/usr/local/lib/python3.6/dist-packages/mypy/traverser.py", line 54, in visit_func_def
      self.visit_func(o)
    File "/usr/local/lib/python3.6/dist-packages/mypy/semanal_typeargs.py", line 46, in visit_func
      super().visit_func(defn)
    File "/usr/local/lib/python3.6/dist-packages/mypy/mixedtraverser.py", line 22, in visit_func
      super().visit_func(o)
    File "/usr/local/lib/python3.6/dist-packages/mypy/traverser.py", line 51, in visit_func
      o.body.accept(self)
    File "/usr/local/lib/python3.6/dist-packages/mypy/nodes.py", line 1005, in accept
      return visitor.visit_block(self)
    File "/usr/local/lib/python3.6/dist-packages/mypy/semanal_typeargs.py", line 54, in visit_block
      super().visit_block(o)
    File "/usr/local/lib/python3.6/dist-packages/mypy/traverser.py", line 39, in visit_block
      s.accept(self)
    File "/usr/local/lib/python3.6/dist-packages/mypy/nodes.py", line 767, in accept
      return visitor.visit_decorator(self)
    File "/usr/local/lib/python3.6/dist-packages/mypy/traverser.py", line 76, in visit_decorator
      o.func.accept(self)
    File "/usr/local/lib/python3.6/dist-packages/mypy/nodes.py", line 677, in accept
      return visitor.visit_func_def(self)
    File "/usr/local/lib/python3.6/dist-packages/mypy/traverser.py", line 54, in visit_func_def
      self.visit_func(o)
    File "/usr/local/lib/python3.6/dist-packages/mypy/semanal_typeargs.py", line 46, in visit_func
      super().visit_func(defn)
    File "/usr/local/lib/python3.6/dist-packages/mypy/mixedtraverser.py", line 22, in visit_func
      super().visit_func(o)
    File "/usr/local/lib/python3.6/dist-packages/mypy/traverser.py", line 51, in visit_func
      o.body.accept(self)
    File "/usr/local/lib/python3.6/dist-packages/mypy/nodes.py", line 1005, in accept
      return visitor.visit_block(self)
    File "/usr/local/lib/python3.6/dist-packages/mypy/semanal_typeargs.py", line 54, in visit_block
      super().visit_block(o)
    File "/usr/local/lib/python3.6/dist-packages/mypy/traverser.py", line 39, in visit_block
      s.accept(self)
    File "/usr/local/lib/python3.6/dist-packages/mypy/nodes.py", line 677, in accept
      return visitor.visit_func_def(self)
    File "/usr/local/lib/python3.6/dist-packages/mypy/traverser.py", line 54, in visit_func_def
      self.visit_func(o)
    File "/usr/local/lib/python3.6/dist-packages/mypy/semanal_typeargs.py", line 46, in visit_func
      super().visit_func(defn)
    File "/usr/local/lib/python3.6/dist-packages/mypy/mixedtraverser.py", line 23, in visit_func
      self.visit_optional_type(o.type)
    File "/usr/local/lib/python3.6/dist-packages/mypy/mixedtraverser.py", line 91, in visit_optional_type
      t.accept(self)
    File "/usr/local/lib/python3.6/dist-packages/mypy/types.py", line 1098, in accept
      return visitor.visit_callable_type(self)
    File "/usr/local/lib/python3.6/dist-packages/mypy/typetraverser.py", line 52, in visit_callable_type
      t.fallback.accept(self)
    File "/usr/local/lib/python3.6/dist-packages/mypy/types.py", line 794, in accept
      return visitor.visit_instance(self)
    File "/usr/local/lib/python3.6/dist-packages/mypy/semanal_typeargs.py", line 70, in visit_instance
      for (i, arg), tvar in zip(enumerate(t.args), info.defn.type_vars):
    File "/usr/local/lib/python3.6/dist-packages/mypy/nodes.py", line 2660, in __getattribute__
      raise AssertionError(object.__getattribute__(self, 'msg'))
  AssertionError: fallback can't be filled out until semanal
   ```
</details>

**To Reproduce**

```py
from typing import no_type_check

def foo() -> None:
    @no_type_check
    def bar() -> None:
        def baz() -> None:
            pass
```

**Your Environment**

- Mypy version used: 0.810+dev.9e0e23e97653dab3a558d34340486e7a66f7d6f0
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.6.9
- Operating system and version: WSL, Ubuntu 18.04

**Comment by AlexWaygood** [comment]
[Can't reproduce](https://mypy-play.net/?mypy=0.920&python=3.10&flags=disallow-any-generics&gist=37859fa894f9bf542cee7d5534b8bd64) on mypy 0.920+ 🎉🥳
