### ISSUE TITLE
Dmypy crashes when adding import and rechecking

### ISSUE THREAD

**Issue by matangover** [python/mypy#10047]
**Crash Report**

Daemon crashes after adding an `import flask` statement and re-checking.

**Traceback**

```
Daemon crashed!
Traceback (most recent call last):
  File "mypy/dmypy_server.py", line 221, in serve
  File "mypy/dmypy_server.py", line 264, in run_command
  File "mypy/dmypy_server.py", line 323, in cmd_run
  File "mypy/dmypy_server.py", line 385, in check
  File "mypy/dmypy_server.py", line 564, in fine_grained_increment_follow_imports
  File "mypy/dmypy_server.py", line 679, in find_reachable_changed_modules
KeyError: 'jinja2'
```

**To Reproduce**

```shell
mkdir test && cd test
touch hi.py
dmypy run -- . # works
echo "import flask" > hi.py
dmypy run -- . # crashes
dmypy run -- . # works
```

Note that flask is NOT installed.

**Your Environment**

- Mypy version used: 0.800
- Mypy command-line flags: `dmypy run -- .` 
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.9.1
- Operating system and version: macOS 10.15.7

**Comment by candsastle** [comment]
Running into the same issue, except it's not with flask. I'm not quite sure what it's crashing on, but the error message is identical except the `KeyError` is `unittest` (which I have not actually installed).

Mypy version: 1.15.0
Python version: 3.11.11
Operating system: macOS 15.3

Using the python-lsp-server and black, isort, mypy plugins
