### ISSUE TITLE
Having issue while importing spacy

### ISSUE THREAD

**Issue by mns00** [python/mypy#10165]
I was to use a pre-trained spacy model for Entity recognition but i am getting the below issue while importing spacy:

 import spacy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\MA20104797\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\__init__.py", line 10, in <module>
    from thinc.api import prefer_gpu, require_gpu, require_cpu  # noqa: F401
  File "C:\Users\MA20104797\AppData\Local\Programs\Python\Python37\lib\site-packages\thinc\__init__.py", line 5, in <module>
    from .config import registry
  File "C:\Users\MA20104797\AppData\Local\Programs\Python\Python37\lib\site-packages\thinc\config.py", line 10, in <module>
    from pydantic import BaseModel, create_model, ValidationError, Extra
  File "C:\Users\MA20104797\AppData\Local\Programs\Python\Python37\lib\site-packages\pydantic\__init__.py", line 2, in <module>
    from . import dataclasses
  File "C:\Users\MA20104797\AppData\Local\Programs\Python\Python37\lib\site-packages\pydantic\dataclasses.py", line 3, in <module>
    from .class_validators import gather_all_validators
  File "C:\Users\MA20104797\AppData\Local\Programs\Python\Python37\lib\site-packages\pydantic\class_validators.py", line 8, in <module>
    from .errors import ConfigError
  File "C:\Users\MA20104797\AppData\Local\Programs\Python\Python37\lib\site-packages\pydantic\errors.py", line 5, in <module>
    from .typing import display_as_type
  File "C:\Users\MA20104797\AppData\Local\Programs\Python\Python37\lib\site-packages\pydantic\typing.py", line 46, in <module>
    from typing import ForwardRef
ImportError: cannot import name 'ForwardRef' from 'typing' (C:\Users\MA20104797\AppData\Local\Programs\Python\Python37\lib\typing.py)

I am using python version: 3.7 (64-bit)
os: Windows 10

**Comment by hauntsaninja** [comment]
Not related to this project
