### ISSUE TITLE
Crash on f-strings with loguru

### ISSUE THREAD

**Issue by GezaBoi** [python/mypy#10182]
**Crash Report**
When using an f-string for logging with loguru mypy crashes.  

**Traceback**

```
version: 0.812
Traceback (most recent call last):
  File "mypy/checkexpr.py", line 3892, in accept
  File "mypy/checkexpr.py", line 270, in visit_call_expr
  File "mypy/checkexpr.py", line 347, in visit_call_expr_inner
  File "mypy/checkexpr.py", line 852, in check_call_expr_with_callee_type
  File "mypy/checkexpr.py", line 915, in check_call
  File "mypy/checkexpr.py", line 1567, in check_overload_call
  File "mypy/checkexpr.py", line 1710, in infer_overload_return_type
  File "mypy/checkexpr.py", line 911, in check_call
  File "mypy/checkexpr.py", line 1023, in check_callable_call
  File "mypy/checkexpr.py", line 732, in apply_function_plugin
  File "/Users/*path*/venv/lib/python3.9/site-packages/loguru_mypy/__init__.py", line 99, in _loguru_logger_call_handler
    assert isinstance(log_msg_expr, StrExpr), type(log_msg_expr)
AssertionError: <class 'mypy.nodes.CallExpr'>

```

**To Reproduce**

```
from loguru import logger

i: int = 5
logger.info(f"{i}")
```

This code causes the crash. Using a normal string works fine. 

**Your Environment**

- Mypy version used: 0.812
- Mypy command-line flags: mypy -p *folder* --implicit-reexport --show-traceback
- Python version used: 3.9.1
- Operating system and version: OSX 10.15.7

**mypy.ini** 
```
[mypy]
strict = True
pretty = True
plugins = loguru_mypy
```

**Comment by JelleZijlstra** [comment]
This looks like an issue in `loguru_mypy`, which I'm guessing is a mypy plugin provided by the loguru project, not something that mypy itself can help with.
