### ISSUE TITLE
Mypy doesn't see typing info when it checks the whole package

### ISSUE THREAD

**Issue by KapJI** [python/mypy#10260]
**Bug Report**

Mypy returns errors when it's used to check the whole package but doesn't return any errors when it's run on individual files.

These errors are the same as when you don't have corresponding package (`zeroconf` in this case) installed. But `zeroconf==0.29.0` is installed and it exports typing information ([marked with `py.typed`](https://github.com/jstasiak/python-zeroconf/blob/master/zeroconf/py.typed)).

Maybe I'm doing something wrong but I don't get why mypy can't see this typing info.
```
❯ mypy homeassistant
homeassistant/components/zeroconf/models.py:3: error: Module 'zeroconf' has no attribute 'DNSPointer'  [attr-defined]
homeassistant/components/zeroconf/models.py:3: error: Module 'zeroconf' has no attribute 'DNSRecord'  [attr-defined]
homeassistant/components/zeroconf/models.py:3: error: Module 'zeroconf' has no attribute 'ServiceBrowser'  [attr-defined]
homeassistant/components/zeroconf/models.py:3: error: Module 'zeroconf' has no attribute 'Zeroconf'  [attr-defined]
homeassistant/components/zeroconf/models.py:6: error: Class cannot subclass 'Zeroconf' (has type 'Any')  [misc]
homeassistant/components/zeroconf/models.py:15: error: Class cannot subclass 'ServiceBrowser' (has type 'Any')  [misc]
homeassistant/components/zeroconf/usage.py:23: error: Name 'zeroconf.Zeroconf' is not defined  [name-defined]
homeassistant/components/zeroconf/usage.py:29: error: Name 'zeroconf.Zeroconf' is not defined  [name-defined]
homeassistant/components/zeroconf/__init__.py:13: error: Module 'zeroconf' has no attribute 'Error'  [attr-defined]
homeassistant/components/zeroconf/__init__.py:13: error: Module 'zeroconf' has no attribute 'InterfaceChoice'  [attr-defined]
homeassistant/components/zeroconf/__init__.py:13: error: Module 'zeroconf' has no attribute 'IPVersion'  [attr-defined]
homeassistant/components/zeroconf/__init__.py:13: error: Module 'zeroconf' has no attribute 'NonUniqueNameException'  [attr-defined]
homeassistant/components/zeroconf/__init__.py:13: error: Module 'zeroconf' has no attribute 'ServiceInfo'  [attr-defined]
homeassistant/components/zeroconf/__init__.py:13: error: Module 'zeroconf' has no attribute 'ServiceStateChange'  [attr-defined]
homeassistant/components/zeroconf/__init__.py:13: error: Module 'zeroconf' has no attribute 'Zeroconf'  [attr-defined]
Found 15 errors in 3 files (checked 3823 source files)

❯ mypy homeassistant/components/zeroconf/models.py
Success: no issues found in 1 source file

❯ mypy homeassistant/components/zeroconf/__init__.py
Success: no issues found in 1 source file

❯ mypy homeassistant/components/zeroconf/usage.py
Success: no issues found in 1 source file
```

Sometimes I have mypy crashing with:
```
❯ mypy homeassistant
Traceback (most recent call last):
  File "/Users/sayfutdinov/Project/github/core/venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/Users/sayfutdinov/Project/github/core/venv/lib/python3.9/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 90, in main
  File "mypy/build.py", line 179, in build
  File "mypy/build.py", line 253, in _build
  File "mypy/build.py", line 2638, in dispatch
  File "mypy/build.py", line 2955, in process_graph
  File "mypy/build.py", line 3033, in process_fresh_modules
  File "mypy/build.py", line 1977, in fix_cross_refs
  File "mypy/fixup.py", line 26, in fixup_module
  File "mypy/fixup.py", line 77, in visit_symbol_table
  File "mypy/fixup.py", line 301, in lookup_qualified_stnode
  File "mypy/lookup.py", line 47, in lookup_fully_qualified
AssertionError: Cannot find component 'DNSPointer' for 'zeroconf.DNSPointer'
```
This is probably related to https://github.com/python/mypy/issues/7281

**To Reproduce**

1. `git clone https://github.com/home-assistant/core.git && cd core`
2. `git fetch origin pull/48450/head:zeroconf-typing`
3. `git checkout zeroconf-typing`
4. `script/setup`
5. `source venv/bin/activate`
6. `pip install xknx zeroconf`
7. `mypy homeassistant`

**Expected Behavior**

Mypy finish successfully in all cases.

**Actual Behavior**

Mypy returns errors when it's run for the whole package but doesn't return any errors when it's run on individual files. 

**Your Environment**

- Mypy version used: mypy 0.812
- Mypy command-line flags: `mypy homeassistant`
- Mypy configuration options from `mypy.ini` (and other config files): [`setup.cfg`](https://github.com/home-assistant/core/blob/dev/setup.cfg)
- Python version used: 3.9.2
- Operating system and version: MacOS, Ubuntu

**Comment by KapJI** [comment]
I found this is caused by this file: https://github.com/home-assistant/core/blob/dev/homeassistant/generated/zeroconf.py

If I rename it, the errors go away.

It should be imported by `homeassistant.generated.zeroconf` but mypy sees it instead of actual `zeroconf` which supposed to be imported.

Looks like a bug.

**Comment by KapJI** [comment]
This issue still exists on the latest master.
```
❯ mypy --version
mypy 0.820+dev.bab4e22f1d0207ebc17ee3388d2434484aa998f4
```

**Comment by KapJI** [comment]
It turns out `homeassistant/generated/` doesn't contain `__init__.py`.

Although import `from homeassistant.generated import zeroconf` works in other place and mypy didn't complain that `homeassistant.generated` is not a module.

I resolved this issue for my case but it still seems that something is weird with import resolution in mypy.

**Comment by ilevkivskyi** [comment]
The incremental crash should be resolved by https://github.com/python/mypy/pull/20735, so I am removing those labels. The import discovery semantics is still confusing, so keeping this open as an example.
