### ISSUE TITLE
Crash involving member type aliases

### ISSUE THREAD

**Issue by vikahl** [python/mypy#10357]
Mypy crashes with INTERNAL ERROR when run on the file below.

**Traceback**

```shell
$ mypy --show-traceback minimal_error.py
minimal_error.py:17: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.820+dev
Traceback (most recent call last):
  File "/home/vikahl/.pyenv/versions/mypy-error/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/main.py", line 98, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/build.py", line 180, in build
    sources, options, alt_lib_path, flush_errors, fscache, stdout, stderr, extra_plugins
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/build.py", line 253, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/build.py", line 2688, in dispatch
    process_graph(graph, manager)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/build.py", line 3012, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/build.py", line 3110, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/build.py", line 2164, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/checker.py", line 294, in check_first_pass
    self.accept(d)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/checker.py", line 401, in accept
    stmt.accept(self)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/nodes.py", line 950, in accept
    return visitor.visit_class_def(self)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/checker.py", line 1726, in visit_class_def
    self.accept(defn.defs)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/checker.py", line 401, in accept
    stmt.accept(self)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/nodes.py", line 1015, in accept
    return visitor.visit_block(self)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/checker.py", line 1975, in visit_block
    self.accept(s)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/checker.py", line 401, in accept
    stmt.accept(self)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/nodes.py", line 687, in accept
    return visitor.visit_func_def(self)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/checker.py", line 726, in visit_func_def
    self._visit_func_def(defn)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/checker.py", line 730, in _visit_func_def
    self.check_func_item(defn, name=defn.name)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/checker.py", line 792, in check_func_item
    self.check_func_def(defn, typ, name)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/checker.py", line 975, in check_func_def
    self.accept(item.body)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/checker.py", line 401, in accept
    stmt.accept(self)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/nodes.py", line 1015, in accept
    return visitor.visit_block(self)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/checker.py", line 1975, in visit_block
    self.accept(s)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/checker.py", line 401, in accept
    stmt.accept(self)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/nodes.py", line 1073, in accept
    return visitor.visit_assignment_stmt(self)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/checker.py", line 2013, in visit_assignment_stmt
    self.check_assignment(s.lvalues[-1], s.rvalue, s.type is None, s.new_syntax)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/checker.py", line 2055, in check_assignment
    lvalue_type, index_lvalue, inferred = self.check_lvalue(lvalue)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/checker.py", line 2811, in check_lvalue
    True)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/checkexpr.py", line 2052, in analyze_ordinary_member_access
    module_symbol_table=module_symbol_table)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/checkmember.py", line 126, in analyze_member_access
    result = _analyze_member_access(name, typ, mx, override_info)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/checkmember.py", line 152, in _analyze_member_access
    return analyze_type_type_member_access(name, typ, mx, override_info)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/checkmember.py", line 296, in analyze_type_type_member_access
    result = analyze_class_attribute_access(item, name, mx, override_info)
  File "/home/vikahl/.pyenv/versions/mypy-error/lib/python3.6/site-packages/mypy/checkmember.py", line 810, in analyze_class_attribute_access
    assert isinstance(node.node, FuncBase)
AssertionError: 
minimal_error.py:17: : note: use --pdb to drop into pdb
```

**To Reproduce**

Minimal working file

```python
import http.server
import threading
from typing import Optional, Type


class ThreadedHttpServer:
    def __init__(
        self,
        host: str,
        port: int,
        custom_server: Type["CustomServer"],
        custom_attribute: str,
    ) -> None:
        self.host = host
        self.port = port
        self.custom_server = custom_server
        self.custom_server.CUSTOM_ATTRIBUTE = custom_attribute

        self.httpd = http.server.HTTPServer((self.host, self.port), self.custom_server)
        self.t = threading.Thread(target=self.httpd.serve_forever)

    def start(self) -> "ThreadedHttpServer":
        self.t.start()

        return self

    def shutdown(self) -> None:

        self.httpd.shutdown()
        self.t.join()


class CustomServer(http.server.BaseHTTPRequestHandler):
    CUSTOM_ATTRIBUTE = Optional[str]

    def do_POST(self) -> None:
        pass
```

**Your Environment**

- Mypy version used: 0.820+dev, 0.820
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.6.13, 3.9.4
- Operating system and version: Linux Debian bullseye/sid

**Comment by DevilXD** [comment]
> Mypy version used: 0.820+dev, 0.820

Can you provide the exact version `mypy -V` returns? It should look something like:
`mypy 0.820+dev.2ac722ac7d844f4c5ae2f3c36f3470543cf01b11`

**Comment by hauntsaninja** [comment]
Thanks for the report, can repro with 0.812 and master. Possibly related to https://github.com/python/mypy/issues/9908

**Comment by hauntsaninja** [comment]
Yeah, so I think the issue is with member type aliases that don't alias to a concrete type. I have a dumb fix, let's see if it causes any regressions...

**Comment by hauntsaninja** [comment]
Fwiw, I think your code meant to do `CUSTOM_ATTRIBUTE: Optional[str]`

Here's a smaller repro:
```
from typing import Optional, Type


class ThreadedServer:
    def __init__(self, custom_server: Type["CustomServer"]) -> None:
        self.custom_server = custom_server
        self.custom_server.CUSTOM_ATTRIBUTE = "asdf"


class CustomServer:
    CUSTOM_ATTRIBUTE = Optional[str]
```
