### ISSUE TITLE
[mypyc] assert self.module

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#10502]
When running mypyc, I get an assertion error on 2 different files. On both, it seems to indicate a line number containing an `async for` statement, so not sure if that's something not supported currently?

```
Traceback (most recent call last):
  File "build/setup.py", line 5, in <module>
    ext_modules=mypycify(['compatibility_device.py'], opt_level="3"),
  File "/usr/local/lib/python3.7/dist-packages/mypyc/build.py", line 492, in mypycify
    skip_cgen_input=skip_cgen_input,
  File "/usr/local/lib/python3.7/dist-packages/mypyc/build.py", line 401, in mypyc_build
    compiler_options=compiler_options)
  File "/usr/local/lib/python3.7/dist-packages/mypyc/build.py", line 201, in generate_c
    result, compiler_options=compiler_options, errors=errors, groups=groups)
  File "/usr/local/lib/python3.7/dist-packages/mypyc/codegen/emitmodule.py", line 408, in compile_modules_to_c
    modules = compile_modules_to_ir(result, mapper, compiler_options, errors)
  File "/usr/local/lib/python3.7/dist-packages/mypyc/codegen/emitmodule.py", line 255, in compile_modules_to_ir
    scc_ir = compile_scc_to_ir(trees, result, mapper, compiler_options, errors)
  File "/usr/local/lib/python3.7/dist-packages/mypyc/codegen/emitmodule.py", line 207, in compile_scc_to_ir
    scc, result.graph, result.types, mapper, compiler_options, errors
  File "/usr/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/mypyc/irbuild/main.py", line 80, in build_ir
    transform_mypy_file(builder, module)
  File "/usr/local/lib/python3.7/dist-packages/mypyc/irbuild/main.py", line 123, in transform_mypy_file
    builder.accept(node)
  File "/usr/local/lib/python3.7/dist-packages/mypyc/irbuild/builder.py", line 169, in accept
    node.accept(self.visitor)
  File "/usr/local/lib/python3.7/dist-packages/mypy/nodes.py", line 950, in accept
    return visitor.visit_class_def(self)
  File "/usr/local/lib/python3.7/dist-packages/mypyc/irbuild/visitor.py", line 104, in visit_class_def
    transform_class_def(self.builder, cdef)
  File "/usr/local/lib/python3.7/dist-packages/mypyc/irbuild/classdef.py", line 98, in transform_class_def
    transform_method(builder, cdef, non_ext, get_func_def(stmt))
  File "/usr/local/lib/python3.7/dist-packages/mypyc/irbuild/function.py", line 112, in transform_method
    handle_ext_method(builder, cdef, fdef)
  File "/usr/local/lib/python3.7/dist-packages/mypyc/irbuild/function.py", line 344, in handle_ext_method
    func_ir, func_reg = gen_func_item(builder, fdef, name, builder.mapper.fdef_to_sig(fdef), cdef)
  File "/usr/local/lib/python3.7/dist-packages/mypyc/irbuild/function.py", line 281, in gen_func_item
    builder.accept(fitem.body)
  File "/usr/local/lib/python3.7/dist-packages/mypyc/irbuild/builder.py", line 169, in accept
    node.accept(self.visitor)
  File "/usr/local/lib/python3.7/dist-packages/mypy/nodes.py", line 1015, in accept
    return visitor.visit_block(self)
  File "/usr/local/lib/python3.7/dist-packages/mypyc/irbuild/visitor.py", line 125, in visit_block
    transform_block(self.builder, block)
  File "/usr/local/lib/python3.7/dist-packages/mypyc/irbuild/statement.py", line 47, in transform_block
    builder.accept(stmt)
  File "/usr/local/lib/python3.7/dist-packages/mypyc/irbuild/builder.py", line 169, in accept
    node.accept(self.visitor)
  File "/usr/local/lib/python3.7/dist-packages/mypy/nodes.py", line 1140, in accept
    return visitor.visit_for_stmt(self)
  File "/usr/local/lib/python3.7/dist-packages/mypyc/irbuild/visitor.py", line 148, in visit_for_stmt
    transform_for_stmt(self.builder, stmt)
  File "/usr/local/lib/python3.7/dist-packages/mypyc/irbuild/statement.py", line 258, in transform_for_stmt
    else_block if s.else_body else None, s.line)
  File "/usr/local/lib/python3.7/dist-packages/mypyc/irbuild/for_helpers.py", line 58, in for_loop_helper
    for_gen = make_for_loop_generator(builder, index, expr, body_block, normal_loop_exit, line)
  File "/usr/local/lib/python3.7/dist-packages/mypyc/irbuild/for_helpers.py", line 278, in make_for_loop_generator
    item_type = builder._analyze_iterable_item_type(expr)
  File "/usr/local/lib/python3.7/dist-packages/mypyc/irbuild/builder.py", line 704, in _analyze_iterable_item_type
    iterator = echk.check_method_call_by_name('__iter__', iterable, [], [], expr)[0]
  File "/usr/local/lib/python3.7/dist-packages/mypy/checkexpr.py", line 2383, in check_method_call_by_name
    in_literal_context=self.is_literal_context())
  File "/usr/local/lib/python3.7/dist-packages/mypy/checkmember.py", line 126, in analyze_member_access
    result = _analyze_member_access(name, typ, mx, override_info)
  File "/usr/local/lib/python3.7/dist-packages/mypy/checkmember.py", line 143, in _analyze_member_access
    return analyze_instance_member_access(name, typ, mx, override_info)
  File "/usr/local/lib/python3.7/dist-packages/mypy/checkmember.py", line 225, in analyze_instance_member_access
    return analyze_member_var_access(name, typ, info, mx)
  File "/usr/local/lib/python3.7/dist-packages/mypy/checkmember.py", line 426, in analyze_member_var_access
    mx.original_type, itype, name, mx.context, mx.module_symbol_table
  File "/usr/local/lib/python3.7/dist-packages/mypy/messages.py", line 323, in has_no_attr
    code=codes.ATTR_DEFINED)
  File "/usr/local/lib/python3.7/dist-packages/mypy/messages.py", line 188, in fail
    self.report(msg, context, 'error', code=code, file=file, origin=origin)
  File "/usr/local/lib/python3.7/dist-packages/mypy/messages.py", line 178, in report
    code=code)
  File "/usr/local/lib/python3.7/dist-packages/mypy/errors.py", line 325, in report
    target=self.current_target())
  File "/usr/local/lib/python3.7/dist-packages/mypy/errors.py", line 256, in current_target
    return self.scope.current_target()
  File "/usr/local/lib/python3.7/dist-packages/mypy/scope.py", line 31, in current_target
    assert self.module
compatibility_device.py:160: AssertionError: 
```

To test:
```
git clone https://github.com/Dreamsorcerer/bthidhub.git
cd bthidhub
mypyc compatibility_device.py
# Or:
mypyc hid_devices.py
```

**Comment by JukkaL** [comment]
Can you file this at https://github.com/mypyc/mypyc/issues? We like to keep mypyc issues separate.
