### ISSUE TITLE
Potential issue with MyPy following reformatting with black

### ISSUE THREAD

**Issue by nefarioustim** [python/mypy#10541]
**Crash Report**

Mypy appears to be crashing after a specific file has been restyled by black. It was working in isolation beforehand. Here's the file; I'm using SQLAlchemy and have the annotations installed. Mypy is successful when the file looks like this:

```python
class UserORM(BaseORM):  # pylint: disable=too-few-public-methods
    """User ORM entity."""
    __tablename__ = "user"

    email = sa.Column(EmailType)
    name = sa.Column(sa.String(100), nullable=True)
```

However, it fails when the correct extra line is included beneath the docstring:

```python
class UserORM(BaseORM):  # pylint: disable=too-few-public-methods
    """User ORM entity."""

    __tablename__ = "user"

    email = sa.Column(EmailType)
    name = sa.Column(sa.String(100), nullable=True)
```

**Traceback**

```
version: 0.820+dev.61c346230cf4960c9766f7c2b5bd3312b47f74da
Traceback (most recent call last):
  File "/venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/venv/lib/python3.9/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/venv/lib/python3.9/site-packages/mypy/main.py", line 98, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/venv/lib/python3.9/site-packages/mypy/build.py", line 179, in build
    result = _build(
  File "/venv/lib/python3.9/site-packages/mypy/build.py", line 253, in _build
    graph = dispatch(sources, manager, stdout)
  File "/venv/lib/python3.9/site-packages/mypy/build.py", line 2689, in dispatch
    process_graph(graph, manager)
  File "/venv/lib/python3.9/site-packages/mypy/build.py", line 3013, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/venv/lib/python3.9/site-packages/mypy/build.py", line 3105, in process_stale_scc
    mypy.semanal_main.semantic_analysis_for_scc(graph, scc, manager.errors)
  File "/venv/lib/python3.9/site-packages/mypy/semanal_main.py", line 78, in semantic_analysis_for_scc
    process_top_levels(graph, scc, patches)
  File "/venv/lib/python3.9/site-packages/mypy/semanal_main.py", line 199, in process_top_levels
    deferred, incomplete, progress = semantic_analyze_target(next_id, state,
  File "/venv/lib/python3.9/site-packages/mypy/semanal_main.py", line 326, in semantic_analyze_target
    analyzer.refresh_partial(refresh_node,
  File "/venv/lib/python3.9/site-packages/mypy/semanal.py", line 396, in refresh_partial
    self.refresh_top_level(node)
  File "/venv/lib/python3.9/site-packages/mypy/semanal.py", line 407, in refresh_top_level
    self.accept(d)
  File "/venv/lib/python3.9/site-packages/mypy/semanal.py", line 4872, in accept
    node.accept(self)
  File "/venv/lib/python3.9/site-packages/mypy/nodes.py", line 950, in accept
    return visitor.visit_class_def(self)
  File "/venv/lib/python3.9/site-packages/mypy/semanal.py", line 1056, in visit_class_def
    self.analyze_class(defn)
  File "/venv/lib/python3.9/site-packages/mypy/semanal.py", line 1134, in analyze_class
    self.analyze_class_body_common(defn)
  File "/venv/lib/python3.9/site-packages/mypy/semanal.py", line 1143, in analyze_class_body_common
    self.apply_class_plugin_hooks(defn)
  File "/venv/lib/python3.9/site-packages/mypy/semanal.py", line 1203, in apply_class_plugin_hooks
    hook(ClassDefContext(defn, base_expr, self))
  File "/venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/plugin.py", line 199, in _base_cls_hook
    decl_class._scan_declarative_assignments_and_apply_types(ctx.cls, ctx.api)
  File "/venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 90, in _scan_declarative_assignments_and_apply_types
    _scan_for_mapped_bases(cls, api, cls_metadata)
  File "/venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 476, in _scan_for_mapped_bases
    _scan_declarative_assignments_and_apply_types(
  File "/venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 90, in _scan_declarative_assignments_and_apply_types
    _scan_for_mapped_bases(cls, api, cls_metadata)
  File "/venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 476, in _scan_for_mapped_bases
    _scan_declarative_assignments_and_apply_types(
  File "/venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 51, in _scan_declarative_assignments_and_apply_types
    info = util._info_for_cls(cls, api)
  File "/venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/util.py", line 211, in _info_for_cls
    assert sym and isinstance(sym.node, TypeInfo)
AssertionError: 
```

**To Reproduce**

See above.

**Your Environment**

- Mypy version used: 0.820+dev.61c346230cf4960c9766f7c2b5bd3312b47f74da installed from GitHub
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files):

```
[mypy]
plugins = pydantic.mypy, sqlalchemy.ext.mypy.plugin
ignore_missing_imports = True
disallow_untyped_defs = True
```

- Python version used: Python 3.9.5
- Operating system and version: Debian GNU/Linux 10 (buster) on M1 Mac Docker

**Comment by JelleZijlstra** [comment]
Could you provide the full file with imports? It's hard to imagine how just adding a newline will crash mypy.

**Comment by A5rocks** [comment]
Are you sure it is not https://github.com/sqlalchemy/sqlalchemy/issues/6476?

(tl;dr a problem in the sqla mypy extension where a custom base runs fine the first time, then stores some bad state in cache)

**Comment by nefarioustim** [comment]
Thanks for the responses guys; unfortunately providing the full file imports will be tough because it's an NDA'd product. However, having created a cut-down version, I'm pretty confident it is [sqlalchemy/sqlalchemy#6476](https://github.com/sqlalchemy/sqlalchemy/issues/6476)

At this point, I will close this issue—thanks for taking the time to respond.
