### ISSUE TITLE
MYPY Internal Error

### ISSUE THREAD

**Issue by KGHVerilator** [python/mypy#10581]
I am using
python3 --version
Python 3.8.5
mypy --version
mypy 0.812

This is on ubuntu 20.04, up to date. I have replaced mypy
The code where the error was claimed (line 13)

`"""
A log handler for recording information in a JUnit TestCase object.
Instead of writing to a 'real' log file, this handler will record the message from the user as a
failure message in the test case.
Note, all messages are logged as failures. It is expected that the log level will be set such that
only messages expected to be failures will be passed to the handler.
"""

import junit_xml
from logging import Handler

class JUnitLogHandler(Handler):
    def __init__(self, testCase: junit_xml.TestCase):
        Handler.__init__(self)
        self.testCase = testCase

    def emit(self, record):
        """Add the provided message as a failure message in the test case."""
        self.testCase.add_failure_info(self.format(record))
`

**Comment by JukkaL** [comment]
I can't reproduce on git master. Can you give the traceback, and the exact command that reproduces the issue?

**Comment by AlexWaygood** [comment]
Closing due to lack of response from OP

**Comment by alegend4u** [comment]
I am getting internal error for mypy==0.812. Check below traceback.

```
Traceback (most recent call last):
  File "C:\Users\RishabhPrajapati\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\RishabhPrajapati\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "mypy\checkexpr.py", line 3898, in accept
  File "mypy\nodes.py", line 1507, in accept
  File "mypy\checkexpr.py", line 2025, in visit_member_expr
  File "mypy\checkexpr.py", line 2043, in analyze_ordinary_member_access
  File "mypy\checkmember.py", line 126, in analyze_member_access
  File "mypy\checkmember.py", line 143, in _analyze_member_access
  File "mypy\checkmember.py", line 219, in analyze_instance_member_access
  File "mypy\maptype.py", line 20, in map_instance_to_supertype
AttributeError: attribute 'type_vars' of 'TypeInfo' undefined
```
Although I ran it from a virtual environment, I don't know why the paths in traceback show the global python installation.

**Comment by AlexWaygood** [comment]
> I am getting internal error for mypy==0.812.

0.812 is a very old version of mypy. If your problem still exists on the latest mypy version, consider opening a new bug report with a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Otherwise, there's not much we can do.

**Comment by hauntsaninja** [comment]
(pretty sure ^ got fixed at some point)
