### ISSUE TITLE
Crash using Protocols 

### ISSUE THREAD

**Issue by CarliJoy** [python/mypy#10639]
**Crash Report**

(Tell us what happened.)
running mpy

**Traceback**

```
mypy --show-traceback testing
testing/crash.py: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.910+dev.7f921078882f1fcaba7c825f699c194aedf0af8a
Traceback (most recent call last):
  File ".venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File ".venv/lib/python3.8/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File ".venv/lib/python3.8/site-packages/mypy/main.py", line 103, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File ".venv/lib/python3.8/site-packages/mypy/build.py", line 179, in build
    result = _build(
  File ".venv/lib/python3.8/site-packages/mypy/build.py", line 254, in _build
    graph = dispatch(sources, manager, stdout)
  File ".venv/lib/python3.8/site-packages/mypy/build.py", line 2696, in dispatch
    process_graph(graph, manager)
  File ".venv/lib/python3.8/site-packages/mypy/build.py", line 3020, in process_graph
    process_stale_scc(graph, scc, manager)
  File ".venv/lib/python3.8/site-packages/mypy/build.py", line 3112, in process_stale_scc
    mypy.semanal_main.semantic_analysis_for_scc(graph, scc, manager.errors)
  File ".venv/lib/python3.8/site-packages/mypy/semanal_main.py", line 84, in semantic_analysis_for_scc
    check_type_arguments(graph, scc, errors)
  File ".venv/lib/python3.8/site-packages/mypy/semanal_main.py", line 360, in check_type_arguments
    state.tree.accept(analyzer)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File ".venv/lib/python3.8/site-packages/mypy/build.py", line 1955, in wrap_context
    yield
  File ".venv/lib/python3.8/site-packages/mypy/semanal_main.py", line 360, in check_type_arguments
    state.tree.accept(analyzer)
  File ".venv/lib/python3.8/site-packages/mypy/nodes.py", line 305, in accept
    return visitor.visit_mypy_file(self)
  File ".venv/lib/python3.8/site-packages/mypy/semanal_typeargs.py", line 39, in visit_mypy_file
    super().visit_mypy_file(o)
  File ".venv/lib/python3.8/site-packages/mypy/traverser.py", line 37, in visit_mypy_file
    d.accept(self)
  File ".venv/lib/python3.8/site-packages/mypy/nodes.py", line 952, in accept
    return visitor.visit_class_def(self)
  File ".venv/lib/python3.8/site-packages/mypy/semanal_typeargs.py", line 50, in visit_class_def
    super().visit_class_def(defn)
  File ".venv/lib/python3.8/site-packages/mypy/mixedtraverser.py", line 28, in visit_class_def
    super().visit_class_def(o)
  File ".venv/lib/python3.8/site-packages/mypy/traverser.py", line 73, in visit_class_def
    o.defs.accept(self)
  File ".venv/lib/python3.8/site-packages/mypy/nodes.py", line 1017, in accept
    return visitor.visit_block(self)
  File ".venv/lib/python3.8/site-packages/mypy/semanal_typeargs.py", line 54, in visit_block
    super().visit_block(o)
  File ".venv/lib/python3.8/site-packages/mypy/traverser.py", line 41, in visit_block
    s.accept(self)
  File ".venv/lib/python3.8/site-packages/mypy/nodes.py", line 689, in accept
    return visitor.visit_func_def(self)
  File ".venv/lib/python3.8/site-packages/mypy/traverser.py", line 56, in visit_func_def
    self.visit_func(o)
  File ".venv/lib/python3.8/site-packages/mypy/semanal_typeargs.py", line 46, in visit_func
    super().visit_func(defn)
  File ".venv/lib/python3.8/site-packages/mypy/mixedtraverser.py", line 22, in visit_func
    super().visit_func(o)
  File ".venv/lib/python3.8/site-packages/mypy/traverser.py", line 53, in visit_func
    o.body.accept(self)
  File ".venv/lib/python3.8/site-packages/mypy/nodes.py", line 1017, in accept
    return visitor.visit_block(self)
  File ".venv/lib/python3.8/site-packages/mypy/semanal_typeargs.py", line 54, in visit_block
    super().visit_block(o)
  File ".venv/lib/python3.8/site-packages/mypy/traverser.py", line 41, in visit_block
    s.accept(self)
  File ".venv/lib/python3.8/site-packages/mypy/nodes.py", line 1075, in accept
    return visitor.visit_assignment_stmt(self)
  File ".venv/lib/python3.8/site-packages/mypy/mixedtraverser.py", line 65, in visit_assignment_stmt
    self.visit_optional_type(o.type)
  File ".venv/lib/python3.8/site-packages/mypy/mixedtraverser.py", line 91, in visit_optional_type
    t.accept(self)
  File ".venv/lib/python3.8/site-packages/mypy/types.py", line 846, in accept
    return visitor.visit_instance(self)
  File ".venv/lib/python3.8/site-packages/mypy/semanal_typeargs.py", line 82, in visit_instance
    if not is_subtype(arg, tvar.upper_bound):
  File ".venv/lib/python3.8/site-packages/mypy/subtypes.py", line 93, in is_subtype
    return _is_subtype(left, right,
  File ".venv/lib/python3.8/site-packages/mypy/subtypes.py", line 147, in _is_subtype
    return left.accept(SubtypeVisitor(orig_right,
  File ".venv/lib/python3.8/site-packages/mypy/types.py", line 1408, in accept
    return visitor.visit_tuple_type(self)
  File ".venv/lib/python3.8/site-packages/mypy/subtypes.py", line 347, in visit_tuple_type
    elif self._is_subtype(mypy.typeops.tuple_fallback(left), right):
  File ".venv/lib/python3.8/site-packages/mypy/typeops.py", line 45, in tuple_fallback
    return Instance(info, [join_type_list(typ.items)])
  File ".venv/lib/python3.8/site-packages/mypy/join.py", line 585, in join_type_list
    joined = join_types(joined, t)
  File ".venv/lib/python3.8/site-packages/mypy/join.py", line 200, in join_types
    return t.accept(TypeJoinVisitor(s, instance_joiner))
  File ".venv/lib/python3.8/site-packages/mypy/types.py", line 1790, in accept
    return visitor.visit_union_type(self)
  File ".venv/lib/python3.8/site-packages/mypy/join.py", line 218, in visit_union_type
    if is_proper_subtype(self.s, t):
  File ".venv/lib/python3.8/site-packages/mypy/subtypes.py", line 1178, in is_proper_subtype
    return _is_proper_subtype(left, right,
  File ".venv/lib/python3.8/site-packages/mypy/subtypes.py", line 1199, in _is_proper_subtype
    return left.accept(ProperSubtypeVisitor(orig_right,
  File ".venv/lib/python3.8/site-packages/mypy/types.py", line 1790, in accept
    return visitor.visit_union_type(self)
  File ".venv/lib/python3.8/site-packages/mypy/subtypes.py", line 1378, in visit_union_type
    return all([self._is_proper_subtype(item, self.orig_right) for item in left.items])
  File ".venv/lib/python3.8/site-packages/mypy/subtypes.py", line 1378, in <listcomp>
    return all([self._is_proper_subtype(item, self.orig_right) for item in left.items])
  File ".venv/lib/python3.8/site-packages/mypy/subtypes.py", line 1229, in _is_proper_subtype
    return is_proper_subtype(left, right,
  File ".venv/lib/python3.8/site-packages/mypy/subtypes.py", line 1178, in is_proper_subtype
    return _is_proper_subtype(left, right,
  File ".venv/lib/python3.8/site-packages/mypy/subtypes.py", line 1194, in _is_proper_subtype
    return any([is_proper_subtype(orig_left, item,
  File ".venv/lib/python3.8/site-packages/mypy/subtypes.py", line 1194, in <listcomp>
    return any([is_proper_subtype(orig_left, item,
  File ".venv/lib/python3.8/site-packages/mypy/subtypes.py", line 1178, in is_proper_subtype
    return _is_proper_subtype(left, right,
  File ".venv/lib/python3.8/site-packages/mypy/subtypes.py", line 1199, in _is_proper_subtype
    return left.accept(ProperSubtypeVisitor(orig_right,
  File ".venv/lib/python3.8/site-packages/mypy/types.py", line 846, in accept
    return visitor.visit_instance(self)
  File ".venv/lib/python3.8/site-packages/mypy/subtypes.py", line 1295, in visit_instance
    is_protocol_implementation(left, right, proper_subtype=True)):
  File ".venv/lib/python3.8/site-packages/mypy/subtypes.py", line 561, in is_protocol_implementation
    assert supertype is not None
AssertionError: 
```
**To Reproduce**
See code: https://gist.github.com/CarliJoy/149e6675e5f4ea9b26d35b81645ed33d

**Your Environment**

- Mypy version used: 0.910+dev.7f921078882f1fcaba7c825f699c194aedf0af8a
- Mypy command-line flags: mypy <filename>
- Mypy configuration options from `mypy.ini` (and other config files): - none (defaults)
- Python version used:  3.8.5
- Operating system and version: Ubuntu 20.04.2 LTS

**Comment by CarliJoy** [comment]
Just tested on mypy playground. Still crashing even on the up to date master version.
