### ISSUE TITLE
Is a typing_extensions still required on Python >= 3.8?

### ISSUE THREAD

**Issue by frost-nzcr4** [python/mypy#10781]
I have a requirements conflict using https://github.com/pypa/pipenv when creating a package lock.
Since typing_extensions requires Python < 3.5 in [typing/typing_extensions/setup.py](https://github.com/python/typing/blob/0fc0eda1e6b415811d4f94f1af0c90543db48485/typing_extensions/setup.py#L71):

```
      install_requires=["typing >= 3.7.4; python_version < '3.5'"])
```

On a host with Python 3.8+, pipenv generates following:

```json
"mypy": {
    "version": "==0.910"
},
"typing-extensions": {
    "markers": "python_version < '3.8'",
    "version": "==3.10.0.0"
}
```
thus typing_extensions wasn't installed due of this `markers` limitation.
But mypy is strictly dependent on typing_extensions:

https://github.com/python/mypy/blob/f137f11acc168bb529555030427d91c71ad7ac00/setup.py#L194

and I've successfully got a dependency error when trying to run mypy:

```shell
host:/app$ mypy
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 5, in <module>
    from mypy.__main__ import console_entry
  File "/usr/local/lib/python3.8/site-packages/mypy/__main__.py", line 6, in <module>
    from mypy.main import main
  File "mypy/main.py", line 11, in <module>
ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by frost-nzcr4** [comment]
Sorry, I've got it wrong)
