### ISSUE TITLE
SQLAlchemy 1.4 Python 3.9.5 KeyError: 'Mapped'

### ISSUE THREAD

**Issue by farbiondriven** [python/mypy#11011]
**Bug Report**

Mypy crashes with latest python and sqlalchemy version. Python version 3.8.5 was working fine.
```

app/db/engine.py:13: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.910
Traceback (most recent call last):
  File "mypy/semanal.py", line 4872, in accept
  File "mypy/nodes.py", line 1073, in accept
  File "mypy/semanal.py", line 2023, in visit_assignment_stmt
  File "mypy/semanal.py", line 2278, in apply_dynamic_class_hook
  File "/home/fabio/remark/DeviceManagement/.venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/plugin.py", line 128, in _dynamic_class_hook
    _add_globals(ctx)
  File "/home/fabio/remark/DeviceManagement/.venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/plugin.py", line 273, in _add_globals
    util.add_global(ctx, "sqlalchemy.orm.attributes", "Mapped", "__sa_Mapped")
  File "/home/fabio/remark/DeviceManagement/.venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/util.py", line 168, in add_global
    lookup_sym: SymbolTableNode = ctx.api.modules[module].names[
KeyError: 'Mapped'
app/db/engine.py:13: : note: use --pdb to drop into pdb
```
**To Reproduce**

```
from sqlalchemy import create_engine, MetaData
from sqlalchemy.orm.decl_api import declarative_base
Base = declarative_base(metadata=MetaData())
```

**Expected Behavior**

(Write what you thought would happen.)

**Actual Behavior**

(Write what happened.)

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: show traceback
- Mypy configuration options from `mypy.ini` (and other config files):
- [mypy]
plugins = pydantic.mypy,sqlalchemy.ext.mypy.plugin
ignore_missing_imports = True
disallow_untyped_defs = True
- Python version used: 3.9.5
- Operating system and version: Ubuntu 20.04

**Comment by JelleZijlstra** [comment]
This looks like a bug in the mypy plugin that is shipped with SQLAlchemy. Could you report a bug to SQLAlchemy instead?

**Comment by AlexWaygood** [comment]
Closing due to lack of response from OP and the fact that this is probably a bug in the SQLAlchemy plugin rather than mypy
