### ISSUE TITLE
`Type[Path]` is not, but should be (?), a valid `Callable[[str, bytes, PathLike], str | bytes | PathLike | TextIO | BinaryIO]`

### ISSUE THREAD

**Issue by gwerbin** [python/mypy#11130]
_It's not clear to me if this is a Typeshed bug or a Mypy bug. Sorry in advance if this is in the wrong issue tracker!_

## The bug

<https://mypy-play.net/?mypy=0.910&python=3.10&gist=31f4d46613085fd14648ca5e8a4549a5>

```python
from __future__ import annotations
from collections.abc import Sequence
from os import PathLike
from pathlib import Path
from typing import Any, BinaryIO, TextIO, Union

FileDesignator = Union[str, bytes, PathLike[Any]]
FileHandle = Union[TextIO, BinaryIO]

input_files: Sequence[FileDesignator]
input_sources: Sequence[FileDesignator | FileHandle]

if input_files:
    input_sources = list(map(Path, input_files))
else:
    input_sources = [sys.stdin]
```

I would have expected this to be valid, since `Path` should indeed be a subclass of `str | bytes | PathLike[Any] | TextIO | BinaryIO`.

Is this a MyPy bug, a MyPy bad/confusing error message, a Typeshed bug, or a "me-not-understanding-type-variance" issue?

Or do I need to be more specific about parameterizing `PathLike`?

### Actual output

```
main.py:15: error: Argument 1 to "map" has incompatible type "Type[Path]"; expected "Callable[[Union[str, bytes, PathLike[Any]]], Path]"
main.py:15: error: Argument 1 to "map" has incompatible type "Type[Path]"; expected "Callable[[Union[str, bytes, PathLike[Any]]], Union[str, bytes, PathLike[Any], TextIO, BinaryIO]]"
Found 2 errors in 1 file (checked 1 source file)
```

This error message is confusing, partly because there are two different errors for the same line (?), and the 2nd error doesn't make much sense, since I'd have expected `Type[Path]` to be a subclass of `Callable[[Union[str, bytes, PathLike[Any]]], Union[str, bytes, PathLike[Any], TextIO, BinaryIO]]`.

### Expected output

```
Success: no issues found in 1 source file
```

### Environment

- Mypy version used: v0.910
- Python version used: 3.9, 3.10

**Comment by AlexWaygood** [comment]
`Path` objects don't accept `bytes` in the constructor:

```python 
>>> from pathlib import Path
>>> Path(b'foo')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/containers/Bundle/Application/0C65C353-7364-4F7B-BE91-175A09B0E788/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/pathlib.py", line 983, in __new__
    self = cls._from_parts(args, init=False)
  File "/var/containers/Bundle/Application/0C65C353-7364-4F7B-BE91-175A09B0E788/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/pathlib.py", line 658, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/var/containers/Bundle/Application/0C65C353-7364-4F7B-BE91-175A09B0E788/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/pathlib.py", line 650, in _parse_args
    % type(a))
TypeError: argument should be a str object or an os.PathLike object returning str, not <class 'bytes'>
```

If you change the types of FileDesignator and FileHandle so that they're pathlib-compatible, mypy is [perfectly happy](https://mypy-play.net/?mypy=0.941&python=3.10&gist=a70103c48ac067a0578b077c05ee254c) with your code:

```python
from __future__ import annotations
import sys
from collections.abc import Sequence
from os import PathLike
from pathlib import Path
from typing import Any, BinaryIO, TextIO, Union

FileDesignator = Union[PathLike[str], str]
FileHandle = TextIO

input_files: Sequence[FileDesignator]
input_sources: Sequence[FileDesignator | FileHandle]

if input_files:
    input_sources = list(map(Path, input_files))
else:
    input_sources = [sys.stdin]
```
