### ISSUE TITLE
Mypy crashes when trying to ignore errors

### ISSUE THREAD

**Issue by robbrit** [python/mypy#11225]
**Bug Report**

When attempting to set `ignore_errors` in mypy.ini, mypy blows up with a stack trace:

```
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/usr/local/lib/python3.9/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 87, in main
  File "mypy/main.py", line 165, in run_build
  File "mypy/build.py", line 179, in build
  File "mypy/build.py", line 254, in _build
  File "mypy/build.py", line 2697, in dispatch
  File "mypy/build.py", line 3021, in process_graph
  File "mypy/build.py", line 3138, in process_stale_scc
  File "mypy/build.py", line 2288, in write_cache
  File "mypy/build.py", line 1476, in write_cache
  File "mypy/build.py", line 1428, in json_dumps
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AnyType is not JSON serializable
```
This is with the latest `mypy==0.910`.

**To Reproduce**

Our original mypy.ini file looked like this:

```ini
[mypy]
plugins =
    mypy_django_plugin.main
mypy_path = ../shared/etc/mypy_stubs

[mypy-*.migrations.*]
ignore_errors = True

[mypy.plugins.django-stubs]
django_settings_module = community.setting
```
That worked great, but adding a new section caused the crash:

```ini
[mypy]
plugins =
    mypy_django_plugin.main
mypy_path = ../shared/etc/mypy_stubs

[mypy-*.migrations.*]
ignore_errors = True

; Disable mypy for protobuf services due to breaking changes in mypy-protobuf.
[mypy-shared.services.*]
ignore_errors = True

[mypy.plugins.django-stubs]
django_settings_module = community.settings
```

The `shared.services` module contains a number of autogenerated protobuf files

**Expected Behavior**

It would not crash.

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: --ignore-missing-imports
- Mypy configuration options from `mypy.ini` (and other config files): written above
- Python version used: 3.9.7
- Operating system and version: Docker hub's `python:3.9.7` image.

**Comment by sobolevn** [comment]
@robbrit Thanks for the report! I've seen several other issues like this from our users in https://github.com/typeddjango/django-stubs/issues/700

I think, that this needs to be fixed on our side, not here.
