### ISSUE TITLE
INTERNAL ERROR using annotate django

### ISSUE THREAD

**Issue by JFdezB** [python/mypy#11504]
**Crash Report**

mypy is returning an `INTERNAL ERROR` when a `annotate()` method is used with django.

**Traceback**

```
> mypy --show-traceback
common\views.py:12: error: INTERNAL ERROR -- Please try using mypy master on Github:   
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.920+dev.4669929f34d671c1081aba3d7f4751335a2879ea 
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\documents\project\venv\Scripts\mypy.exe\__main__.py", line 7, in <module>
    sys.exit(console_entry())
  File "d:\documents\project\venv\lib\site-packages\mypy\__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "d:\documents\project\venv\lib\site-packages\mypy\main.py", line 87, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "d:\documents\project\venv\lib\site-packages\mypy\main.py", line 165, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "d:\documents\project\venv\lib\site-packages\mypy\build.py", line 180, in build
    result = _build(
  File "d:\documents\project\venv\lib\site-packages\mypy\build.py", line 256, in _build
    graph = dispatch(sources, manager, stdout)
  File "d:\documents\project\venv\lib\site-packages\mypy\build.py", line 2712, in dispatch
    process_graph(graph, manager)
  File "d:\documents\project\venv\lib\site-packages\mypy\build.py", line 3043, in process_graph
    process_stale_scc(graph, scc, manager)
  File "d:\documents\project\venv\lib\site-packages\mypy\build.py", line 3141, in process_stale_scc
    graph[id].type_check_first_pass()
  File "d:\documents\project\venv\lib\site-packages\mypy\build.py", line 2177, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "d:\documents\project\venv\lib\site-packages\mypy\checker.py", line 316, in check_first_pass
    self.accept(d)
  File "d:\documents\project\venv\lib\site-packages\mypy\checker.py", line 422, in accept
    stmt.accept(self)
  File "d:\documents\project\venv\lib\site-packages\mypy\nodes.py", line 994, in accept
    return visitor.visit_class_def(self)
  File "d:\documents\project\venv\lib\site-packages\mypy\checker.py", line 1757, in visit_class_def
    self.accept(defn.defs)
  File "d:\documents\project\venv\lib\site-packages\mypy\checker.py", line 422, in accept
    stmt.accept(self)
  File "d:\documents\project\venv\lib\site-packages\mypy\nodes.py", line 1063, in accept
    return visitor.visit_block(self)
  File "d:\documents\project\venv\lib\site-packages\mypy\checker.py", line 2019, in visit_block
    self.accept(s)
  File "d:\documents\project\venv\lib\site-packages\mypy\checker.py", line 422, in accept
    stmt.accept(self)
  File "d:\documents\project\venv\lib\site-packages\mypy\nodes.py", line 1129, in accept
    return visitor.visit_assignment_stmt(self)
  File "d:\documents\project\venv\lib\site-packages\mypy\checker.py", line 2061, in visit_assignment_stmt
    self.check_assignment(s.lvalues[-1], s.rvalue, s.type is None, s.new_syntax)
  File "d:\documents\project\venv\lib\site-packages\mypy\checker.py", line 2144, in check_assignment
    if self.check_compatibility_all_supers(lvalue, lvalue_type, rvalue):
  File "d:\documents\project\venv\lib\site-packages\mypy\checker.py", line 2346, in check_compatibility_all_supers
    if not self.check_compatibility_super(lvalue,
  File "d:\documents\project\venv\lib\site-packages\mypy\checker.py", line 2376, in check_compatibility_super
    compare_type = self.expr_checker.accept(rvalue, base_type)
  File "d:\documents\project\venv\lib\site-packages\mypy\checkexpr.py", line 3946, in accept
    typ = node.accept(self)
  File "d:\documents\project\venv\lib\site-packages\mypy\nodes.py", line 1705, in accept
    return visitor.visit_call_expr(self)
  File "d:\documents\project\venv\lib\site-packages\mypy\checkexpr.py", line 285, in visit_call_expr
    return self.visit_call_expr_inner(e, allow_none_return=allow_none_return)
  File "d:\documents\project\venv\lib\site-packages\mypy\checkexpr.py", line 374, in visit_call_expr_inner
    ret_type = self.check_call_expr_with_callee_type(callee_type, e, fullname,
  File "d:\documents\project\venv\lib\site-packages\mypy\checkexpr.py", line 881, in check_call_expr_with_callee_type
    return self.check_call(callee_type, e.args, e.arg_kinds, e,
  File "d:\documents\project\venv\lib\site-packages\mypy\checkexpr.py", line 941, in check_call
    return self.check_callable_call(callee, args, arg_kinds, context, arg_names,
  File "d:\documents\project\venv\lib\site-packages\mypy\checkexpr.py", line 1053, in check_callable_call
    new_ret_type = self.apply_function_plugin(
  File "d:\documents\project\venv\lib\site-packages\mypy\checkexpr.py", line 761, in apply_function_plugin
    return method_callback(
  File "d:\documents\project\venv\lib\site-packages\mypy_django_plugin\transformers\querysets.py", line 231, in extract_proper_type_queryset_annotate       
    annotated_type = get_or_create_annotated_type(api, model_type, fields_dict=fields_dict)
  File "d:\documents\project\venv\lib\site-packages\mypy_django_plugin\transformers\models.py", line 453, in get_or_create_annotated_type
    annotated_model_type = api.named_generic_type(ANY_ATTR_ALLOWED_CLASS_FULLNAME, [])
  File "d:\documents\project\venv\lib\site-packages\mypy\checker.py", line 5027, in named_generic_type
    info = self.lookup_typeinfo(name)
  File "d:\documents\project\venv\lib\site-packages\mypy\checker.py", line 5034, in lookup_typeinfo
    sym = self.lookup_qualified(fullname)
  File "d:\documents\project\venv\lib\site-packages\mypy\checker.py", line 5101, in lookup_qualified
    raise KeyError(msg.format(last, name))
KeyError: "Failed qualified lookup: '_AnyAttrAllowed' (fullname = 'django._AnyAttrAllowed')."
common\views.py:12: : note: use --pdb to drop into pdb
```

**To Reproduce**

```
from django.views.generic.list import ListView
from django.db.models import Q, Count
from django.utils import timezone

from . import models


class CalendarView(ListView):
    queryset = (
        models.Days.objects
        .annotate(
            past_days = Count('date', filter = Q(date__gt = timezone.now())),
            comming_days = Count('date', filter = Q(date__lte = timezone.now())),
        )
    )
```

**Your Environment**

- Mypy version used: 0.920+dev.4669929f34d671c1081aba3d7f4751335a2879ea
- Mypy configuration options from `mypy.ini` (and other config files):
```
[mypy]
plugins = mypy_django_plugin.main
files = core,common,manage.py
mypy_path = typing

[mypy.plugins.django-stubs]
django_settings_module = "core.settings"
```
- Python version used: 3.8.10
- Operating system and version: Windows 21H1 (build 19043, 1288)

**Comment by sobolevn** [comment]
Please, report this in our repo: https://github.com/typeddjango/django-stubs/

I am pretty sure that `Count('date', filter = Q(date__gt = timezone.now()))` is too complex for us to support right now 😢
