### ISSUE TITLE
Crash with SQLAlchemy plugin

### ISSUE THREAD

**Issue by phy1729** [python/mypy#11548]
**Crash Report**

Mypy crashes when using the SQLAlchemy mypy plugin and a `@declared_attr` `__mapper_args__`. Apologies if this should be logged with SQLAlchemy; the error message asked for me to report it here :slightly_smiling_face:.

**Traceback**

```
test.py:-1: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.910
Traceback (most recent call last):
  File "/home/phy1729/,demo2/./venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/main.py", line 87, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/main.py", line 165, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/build.py", line 179, in build
    result = _build(
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/build.py", line 254, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/build.py", line 2697, in dispatch
    process_graph(graph, manager)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/build.py", line 3021, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/build.py", line 3119, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/build.py", line 2165, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checker.py", line 294, in check_first_pass
    self.accept(d)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checker.py", line 401, in accept
    stmt.accept(self)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/nodes.py", line 950, in accept
    return visitor.visit_class_def(self)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checker.py", line 1726, in visit_class_def
    self.accept(defn.defs)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checker.py", line 401, in accept
    stmt.accept(self)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/nodes.py", line 1015, in accept
    return visitor.visit_block(self)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checker.py", line 1975, in visit_block
    self.accept(s)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checker.py", line 401, in accept
    stmt.accept(self)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/nodes.py", line 1073, in accept
    return visitor.visit_assignment_stmt(self)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checker.py", line 2013, in visit_assignment_stmt
    self.check_assignment(s.lvalues[-1], s.rvalue, s.type is None, s.new_syntax)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checker.py", line 2124, in check_assignment
    rvalue_type = self.check_simple_assignment(lvalue_type, rvalue, context=rvalue,
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checker.py", line 2985, in check_simple_assignment
    rvalue_type = self.expr_checker.accept(rvalue, lvalue_type,
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checkexpr.py", line 3911, in accept
    typ = node.accept(self)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/nodes.py", line 1558, in accept
    return visitor.visit_call_expr(self)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checkexpr.py", line 271, in visit_call_expr
    return self.visit_call_expr_inner(e, allow_none_return=allow_none_return)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checkexpr.py", line 353, in visit_call_expr_inner
    ret_type = self.check_call_expr_with_callee_type(callee_type, e, fullname,
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checkexpr.py", line 858, in check_call_expr_with_callee_type
    return self.check_call(callee_type, e.args, e.arg_kinds, e,
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checkexpr.py", line 924, in check_call
    return self.check_any_type_call(args, callee)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checkexpr.py", line 2011, in check_any_type_call
    self.infer_arg_types_in_empty_context(args)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checkexpr.py", line 1085, in infer_arg_types_in_empty_context
    arg_type = self.accept(arg)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checkexpr.py", line 3911, in accept
    typ = node.accept(self)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/nodes.py", line 1866, in accept
    return visitor.visit_lambda_expr(self)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checkexpr.py", line 3511, in visit_lambda_expr
    ret_type = self.accept(e.expr(), allow_none_return=True)
  File "/home/phy1729/,demo2/venv/lib/python3.9/site-packages/mypy/checkexpr.py", line 3900, in accept
    if node in self.type_overrides:
TypeError: unhashable type: 'list'
test.py:-1: : note: use --pdb to drop into pdb
```

**To Reproduce**

With test.py as
```py3
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import declared_attr
from sqlalchemy.orm import Mapped


Base = declarative_base()


class Foo(Base):
    @declared_attr
    def __mapper_args__(
        cls,
    ) -> Mapped[dict]:
        if True:
            return {}
        else:
            return {}
```

and setup.cfg as
```ini
[mypy]
plugins = sqlalchemy.ext.mypy.plugin
```

run
```sh
 python3 -m venv venv
./venv/bin/pip install 'sqlalchemy[mypy]'
./venv/bin/mypy --show-traceback test.py
```

For the crash to happen
* The class must be derived from `declarative_base`.
* `@declared_attr` must be used.
* There must be a return type annotation. `dict` is sufficient (as is `typing.Dict`). The `Mapped` bit is just to kill off a warning `test.py:9: error: [SQLAlchemy Mypy plugin] Can't infer type from @declared_attr on function '__mapper_args__';  please specify a return type from this function that is one of: Mapped[<python type>], relationship[<target class>], Column[<TypeEngine>], MapperProperty[<python type>]`
* The body can't be trivial i.e. `return {}` wasn't sufficient to produce the crash.

**Your Environment**

- Mypy version used: 0.910
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): setup.cfg is
    ```ini
    [mypy]
    plugins = sqlalchemy.ext.mypy.plugin
    ```
- Python version used: Reproduced with 3.8.10, 3.8.12, and 3.9.7
- Operating system and version: Reproduced on OpenBSD and Alpine.

**Comment by hauntsaninja** [comment]
Thanks, I think this is indeed probably better reported at https://github.com/sqlalchemy/sqlalchemy2-stubs

**Comment by phy1729** [comment]
Reported at https://github.com/sqlalchemy/sqlalchemy2-stubs/issues/189. Thanks!
