### ISSUE TITLE
`typing` classes instantiation is considered valid by mypy

### ISSUE THREAD

**Issue by malfet** [python/mypy#11755]
**Bug Report**

mypy fails to detect attempts to instantiate `typing.List`, which triggers runtime error

**To Reproduce**

Considering following example:
```
from typing import List
if __name__ == "__main__":
    x = List[str]([])
    print(x)
```

Mypy reports this code as valid, although it is guaranteed to fail at runtime:
```
(py_39) % python3 -mmypy mypy-instance.py
Success: no issues found in 1 source file
(py_39) % python3 mypy-instance.py 
Traceback (most recent call last):
  File "/Users/nshulga/test/mypy-instance.py", line 3, in <module>
    x = List[str]([])
  File "/Users/nshulga/miniconda3/envs/py_39/lib/python3.9/typing.py", line 668, in __call__
    raise TypeError(f"Type {self._name} cannot be instantiated; "
TypeError: Type List cannot be instantiated; use list() instead
```
**Expected Behavior**

Mypy shoudl report abovementioned construct as abstract class/non-instantiatiable type

**Your Environment**

- Mypy version used: 0.910
- Python version used: 3.9.4
- Operating system and version: MacOs 12.0.1

**Comment by sobolevn** [comment]
Very important thing here is that some type application expressions are ok to be called: `assert list[int]() == []`

We need to be careful to know which one is which.
