### ISSUE TITLE
mypy fails to run on files named abc.py or abc.pyi

### ISSUE THREAD

**Issue by ismail-s** [python/mypy#1182]
## Steps to reproduce
1. Create a file called abc.py or abc.pyi. The file may be empty or contain any valid code.
1. Run `mypy abc.py` or `mypy abc.pyi`

## Result
```
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 6, in <module>
    main(__file__)
  File "/usr/local/lib/python3.4/dist-packages/mypy/main.py", line 53, in main
    type_check_only(sources, bin_dir, options)
  File "/usr/local/lib/python3.4/dist-packages/mypy/main.py", line 96, in type_check_only
    python_path=options.python_path)
  File "/usr/local/lib/python3.4/dist-packages/mypy/build.py", line 203, in build
    result = manager.process(initial_states)
  File "/usr/local/lib/python3.4/dist-packages/mypy/build.py", line 386, in process
    next.process()
  File "/usr/local/lib/python3.4/dist-packages/mypy/build.py", line 846, in process
    main(__file__)
  File "/usr/local/lib/python3.4/dist-packages/mypy/main.py", line 53, in main
    type_check_only(sources, bin_dir, options)
  File "/usr/local/lib/python3.4/dist-packages/mypy/main.py", line 96, in type_check_only
    python_path=options.python_path)
  File "/usr/local/lib/python3.4/dist-packages/mypy/build.py", line 203, in build
    result = manager.process(initial_states)
  File "/usr/local/lib/python3.4/dist-packages/mypy/build.py", line 386, in process
    next.process()
  File "/usr/local/lib/python3.4/dist-packages/mypy/build.py", line 846, in process
    self.semantic_analyzer().visit_file(self.tree, self.tree.path)
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 213, in visit_file
    remove_imported_names_from_symtable(self.globals, 'builtins')
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 2445, in remove_imported_names_from_symtable
    fullname = node.node.fullname()
AttributeError: 'NoneType' object has no attribute 'fullname'
```

## Additional Notes
- Passing the --pdb option doesn't cause pdb to be run when this error is encountered.

**Comment by JukkaL** [comment]
This probably happens because mypy needs the std lib `abc` module to function and expects that it contains certain things. Instead of crashing, mypy should give a useful error message, something along the lines of `The standard library module name "abc" is reserved and can't be used for user code`.

**Comment by gvanrossum** [comment]
I've fixed the crash; now you merely get a ton of errors because abc.py overrides the stdlib module/stub abc.pyi. I'm going to close this now -- you get the same issue if you cause some other conflict with builtins.pyi or one of its dependencies (e.g. typing.pyi).
