### ISSUE TITLE
Invalid `instance.__slots__` type revealed

### ISSUE THREAD

**Issue by sobolevn** [python/mypy#11891]
Here's a minimal repro:

```python
class Bar(object):
    ...

reveal_type(Bar.__slots__)
reveal_type(Bar().__slots__)
```

Output:

```
out/ex.py:6: note: Revealed type is "typing.Iterable[builtins.str]"
out/ex.py:7: note: Revealed type is "typing.Iterable[builtins.str]"
```

What happens in runtime?

```python
>>> class Bar(object):
...     ...
... 
>>> Bar.__slots__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'Bar' has no attribute '__slots__'. Did you mean: '__class__'?
>>> Bar().__slots__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Bar' object has no attribute '__slots__'. Did you mean: '__class__'?
```

`__slots__` are special.

Related https://github.com/python/mypy/pull/11885

**Comment by JelleZijlstra** [comment]
Does the typeshed change fix this, or do you want to use this issue to track special-casing in mypy?

**Comment by ilevkivskyi** [comment]
Mypy now reports an error on both lines.
