### ISSUE TITLE
crash with sqlalchemy2 stubs

### ISSUE THREAD

**Issue by minyoung90** [python/mypy#11902]
**Crash Report**

I can't understand log, so do you have any ideas where I can find a line for this report?
I am using VSCode, vscdoe gives me this error.

**Traceback**

```
Daemon crashed!
Traceback (most recent call last):
  File "mypy/dmypy_server.py", line 229, in serve
  File "mypy/dmypy_server.py", line 272, in run_command
  File "mypy/dmypy_server.py", line 331, in cmd_run
  File "mypy/dmypy_server.py", line 393, in check
  File "mypy/dmypy_server.py", line 568, in fine_grained_increment_follow_imports
  File "mypy/server/update.py", line 245, in update
  File "mypy/server/update.py", line 328, in update_one
  File "mypy/server/update.py", line 388, in update_module
  File "mypy/server/astdiff.py", line 164, in snapshot_symbol_table
  File "mypy/server/astdiff.py", line 224, in snapshot_definition
  File "mypy/server/astdiff.py", line 160, in snapshot_symbol_table
TypeError: str object expected; got None
```

**To Reproduce**

(Write what you did to reproduce the crash.  Full source code is
appreciated.  We also very much appreciate it if you try to narrow the
source down to a small stand-alone example.)

**Your Environment**

- Mypy version used: 0.930
- Mypy command-line flags: ~/.venv/bin/python -m mypy.dmypy --status-file ~/.config/Code/User/workspaceStorage/2caf0291ecf6795a93085715a3e82615/matangover.mypy/dmypy-26b3c3104152348d4353e0e6c8df6fc0c43c532d.json run --log-file ~/.config/Code/User/workspaceStorage/2caf0291ecf6795a93085715a3e82615/matangover.mypy/dmypy-26b3c3104152348d4353e0e6c8df6fc0c43c532d.log -- . --show-column-numbers --no-error-summary --no-pretty --no-color-output --python-executable ~/.venv/bin/python
- Mypy configuration options from `mypy.ini` (and other config files):
```
[mypy]
plugins = sqlalchemy.ext.mypy.plugin, pydantic.mypy
ignore_missing_imports = True
disallow_untyped_defs = True
```
- Python version used: 3.9.4
- Operating system and version: Ubuntu 20.04 LTS

**Comment by JelleZijlstra** [comment]
This is here: https://github.com/python/mypy/blob/master/mypy/server/astdiff.py#L160. I guess it means `node.fullname` is unexpectedly None, but no idea why that happens.

**Comment by ethanhs** [comment]
@minyoung90 can you give any more details about the source file that caused this crash?
