### ISSUE TITLE
Crash report on calling open python function

### ISSUE THREAD

**Issue by diksha** [python/mypy#12213]
**Crash Report**

Code
```
def items_from_file(filepath:str):
    with open(filepath,encoding="UTF-8") as file:
        return file.read().splitlines()
```

**Traceback**

```
> /home/diksha_voxelsafety_com/voxel/mypy/plugins/default.py(176)_analyze_open_signature()
(Pdb) --KeyboardInterrupt--
(Pdb) exit
Traceback (most recent call last):
  File "mypy/checkexpr.py", line 3962, in accept
  File "mypy/nodes.py", line 1713, in accept
  File "mypy/checkexpr.py", line 288, in visit_call_expr
  File "mypy/checkexpr.py", line 371, in visit_call_expr_inner
  File "mypy/checkexpr.py", line 878, in check_call_expr_with_callee_type
  File "mypy/checkexpr.py", line 942, in check_call
  File "mypy/checkexpr.py", line 1620, in check_overload_call
  File "mypy/checkexpr.py", line 1762, in infer_overload_return_type
  File "mypy/checkexpr.py", line 938, in check_call
  File "mypy/checkexpr.py", line 1068, in check_callable_call
  File "mypy/checkexpr.py", line 749, in apply_function_plugin
  File "mypy/plugins/default.py", line 134, in open_callback
  File "mypy/plugins/default.py", line 176, in _analyze_open_signature
AssertionError: 
core/utils/yaml_jinja.py:50: : note: use --pdb to drop into pdb
~/voxel$ mypy --show-traceback core/utils/yaml_jinja.py
core/utils/yaml_jinja.py:16: error: Module "io" has no attribute "StringIO"
core/utils/yaml_jinja.py:19: error: Skipping analyzing "jinja2": module is installed, but missing library stubs or py.typed marker
core/utils/yaml_jinja.py:19: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
core/utils/yaml_jinja.py:20: error: Library stubs not installed for "yaml" (or incompatible with Python 3.6)
core/utils/yaml_jinja.py:20: note: Hint: "python3 -m pip install types-PyYAML"
core/utils/yaml_jinja.py:20: note: (or run "mypy --install-types" to install all missing stub packages)
core/utils/yaml_jinja.py:22: error: Cannot find implementation or library stub for module named "core.metaverse.metaverse"
core/utils/yaml_jinja.py:23: error: Cannot find implementation or library stub for module named "core.utils.aws_utils"
core/utils/yaml_jinja.py:27: error: Function is missing a type annotation
core/utils/yaml_jinja.py:32: error: Function is missing a type annotation
core/utils/yaml_jinja.py:49: error: Function is missing a return type annotation
core/utils/yaml_jinja.py:50: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.931
Traceback (most recent call last):
  File "mypy/checkexpr.py", line 3962, in accept
  File "mypy/nodes.py", line 1713, in accept
  File "mypy/checkexpr.py", line 288, in visit_call_expr
  File "mypy/checkexpr.py", line 371, in visit_call_expr_inner
  File "mypy/checkexpr.py", line 878, in check_call_expr_with_callee_type
  File "mypy/checkexpr.py", line 942, in check_call
  File "mypy/checkexpr.py", line 1620, in check_overload_call
  File "mypy/checkexpr.py", line 1762, in infer_overload_return_type
  File "mypy/checkexpr.py", line 938, in check_call
  File "mypy/checkexpr.py", line 1068, in check_callable_call
  File "mypy/checkexpr.py", line 749, in apply_function_plugin
  File "mypy/plugins/default.py", line 134, in open_callback
  File "mypy/plugins/default.py", line 176, in _analyze_open_signature
AssertionError: 
core/utils/yaml_jinja.py:50: : note: use --pdb to drop into pdb
```

**To Reproduce**

(Write what you did to reproduce the crash.  Full source code is
appreciated.  We also very much appreciate it if you try to narrow the
source down to a small stand-alone example.)

**Your Environment**

- Mypy version used: mypy 0.931
- Mypy command-line flags: --show-traceback
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used:Python 2.7.17
- Operating system and version:Ubuntu 18.04.5 LTS

**Comment by hauntsaninja** [comment]
I can't repro a crash when checking that snippet of code. (Also mypy doesn't run on Python 2)
