### ISSUE TITLE
Running `MyPy` on `TypedDict` with `classmethod` gets an error

### ISSUE THREAD

**Issue by xliiv** [python/mypy#12296]
**Crash Report**

Running `MyPy` on `TypedDict` with `classmethod` gets an error.

**Traceback**

```
> mypy main.py --show-traceback
main.py:7: error: Invalid statement in TypedDict definition; expected "field_name: field_type"
main.py: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.931
Traceback (most recent call last):
  File "/usr/home/xliiv/codespace/_tmp/mypy-test/.venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/usr/home/xliiv/codespace/_tmp/mypy-test/.venv/lib/python3.8/site-packages/mypy/__main__.py", line 12, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/usr/home/xliiv/codespace/_tmp/mypy-test/.venv/lib/python3.8/site-packages/mypy/main.py", line 96, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "/usr/home/xliiv/codespace/_tmp/mypy-test/.venv/lib/python3.8/site-packages/mypy/main.py", line 173, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/usr/home/xliiv/codespace/_tmp/mypy-test/.venv/lib/python3.8/site-packages/mypy/build.py", line 180, in build
    result = _build(
  File "/usr/home/xliiv/codespace/_tmp/mypy-test/.venv/lib/python3.8/site-packages/mypy/build.py", line 256, in _build
    graph = dispatch(sources, manager, stdout)
  File "/usr/home/xliiv/codespace/_tmp/mypy-test/.venv/lib/python3.8/site-packages/mypy/build.py", line 2717, in dispatch
    process_graph(graph, manager)
  File "/usr/home/xliiv/codespace/_tmp/mypy-test/.venv/lib/python3.8/site-packages/mypy/build.py", line 3048, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/usr/home/xliiv/codespace/_tmp/mypy-test/.venv/lib/python3.8/site-packages/mypy/build.py", line 3149, in process_stale_scc
    graph[id].finish_passes()
  File "/usr/home/xliiv/codespace/_tmp/mypy-test/.venv/lib/python3.8/site-packages/mypy/build.py", line 2230, in finish_passes
    free_tree(self.tree)
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/home/xliiv/codespace/_tmp/mypy-test/.venv/lib/python3.8/site-packages/mypy/build.py", line 1972, in wrap_context
    yield
  File "/usr/home/xliiv/codespace/_tmp/mypy-test/.venv/lib/python3.8/site-packages/mypy/build.py", line 2217, in finish_passes
    self._patch_indirect_dependencies(self.type_checker().module_refs, self.type_map())
  File "/usr/home/xliiv/codespace/_tmp/mypy-test/.venv/lib/python3.8/site-packages/mypy/build.py", line 2240, in _patch_indirect_dependencies
    types = set(type_map.values())
  File "/usr/home/xliiv/codespace/_tmp/mypy-test/.venv/lib/python3.8/site-packages/mypy/types.py", line 1359, in __hash__
    return hash((self.ret_type, self.is_type_obj(),
  File "/usr/home/xliiv/codespace/_tmp/mypy-test/.venv/lib/python3.8/site-packages/mypy/types.py", line 1219, in is_type_obj
    return self.fallback.type.is_metaclass()
  File "/usr/home/xliiv/codespace/_tmp/mypy-test/.venv/lib/python3.8/site-packages/mypy/nodes.py", line 2880, in __getattribute__
    raise AssertionError(object.__getattribute__(self, 'msg'))
AssertionError: fallback can't be filled out until semanal
main.py: : note: use --pdb to drop into pdb
```

**To Reproduce**
Run `mypy main.py` for the following setup

```shell
> python --version
Python 3.8.12

> pip freeze
mypy==0.931
mypy-extensions==0.4.3
sqlite3==0.0.0
tomli==2.0.1
typing-extensions==4.1.1
> tree
.
└── main.py

0 directories, 1 file
> cat main.py
from typing import TypedDict


class SomeTypedDict(TypedDict):
    some_field: int

    @classmethod
    def some_classmethod(cls) -> "SomeTypedDict":
        pass
```

**Your Environment**

- Mypy version used: 0.931
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.8.12
- Operating system and version: FreeBSD 13.0-RELEASE

**Comment by 97littleleaf11** [comment]
Duplicate https://github.com/python/mypy/issues/5653
