### ISSUE TITLE
Crash when passing Protocol with nested class to a function

### ISSUE THREAD

**Issue by tom139** [python/mypy#12433]
**Crash Report**

When I mock a protocol with a nested class through `create_autospec`, Mypy returns an `error: INTERNAL ERROR`.

**Traceback**

```
.venv ❯ mypy test.py --show-traceback
test.py:15: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.950+dev.fd8a15e1abdd2bb4f75c3a6319ebfba233e1fe8e
Traceback (most recent call last):
  File "[..]/.venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "[..]/.venv/lib/python3.8/site-packages/mypy/__main__.py", line 12, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/main.py", line 96, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/main.py", line 173, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/build.py", line 180, in build
    result = _build(
  File "[..]/.venv/lib/python3.8/site-packages/mypy/build.py", line 256, in _build
    graph = dispatch(sources, manager, stdout)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/build.py", line 2733, in dispatch
    process_graph(graph, manager)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/build.py", line 3081, in process_graph
    process_stale_scc(graph, scc, manager)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/build.py", line 3179, in process_stale_scc
    graph[id].type_check_first_pass()
  File "[..]/.venv/lib/python3.8/site-packages/mypy/build.py", line 2192, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "[..]/.venv/lib/python3.8/site-packages/mypy/checker.py", line 318, in check_first_pass
    self.accept(d)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/checker.py", line 424, in accept
    stmt.accept(self)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/nodes.py", line 740, in accept
    return visitor.visit_func_def(self)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/checker.py", line 774, in visit_func_def
    self._visit_func_def(defn)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/checker.py", line 778, in _visit_func_def
    self.check_func_item(defn, name=defn.name)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/checker.py", line 840, in check_func_item
    self.check_func_def(defn, typ, name)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/checker.py", line 1025, in check_func_def
    self.accept(item.body)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/checker.py", line 424, in accept
    stmt.accept(self)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/nodes.py", line 1090, in accept
    return visitor.visit_block(self)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/checker.py", line 2161, in visit_block
    self.accept(s)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/checker.py", line 424, in accept
    stmt.accept(self)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/nodes.py", line 1156, in accept
    return visitor.visit_assignment_stmt(self)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/checker.py", line 2203, in visit_assignment_stmt
    self.check_assignment(s.lvalues[-1], s.rvalue, s.type is None, s.new_syntax)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/checker.py", line 2394, in check_assignment
    rvalue_type = self.expr_checker.accept(rvalue)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/checkexpr.py", line 3978, in accept
    typ = node.accept(self)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/nodes.py", line 1751, in accept
    return visitor.visit_call_expr(self)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/checkexpr.py", line 288, in visit_call_expr
    return self.visit_call_expr_inner(e, allow_none_return=allow_none_return)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/checkexpr.py", line 371, in visit_call_expr_inner
    ret_type = self.check_call_expr_with_callee_type(callee_type, e, fullname,
  File "[..]/.venv/lib/python3.8/site-packages/mypy/checkexpr.py", line 880, in check_call_expr_with_callee_type
    return self.check_call(callee_type, e.args, e.arg_kinds, e,
  File "[..]/.venv/lib/python3.8/site-packages/mypy/checkexpr.py", line 940, in check_call
    return self.check_callable_call(callee, args, arg_kinds, context, arg_names,
  File "[..]/.venv/lib/python3.8/site-packages/mypy/checkexpr.py", line 1049, in check_callable_call
    arg_types = self.infer_arg_types_in_context(
  File "[..]/.venv/lib/python3.8/site-packages/mypy/checkexpr.py", line 1148, in infer_arg_types_in_context
    res[ai] = self.accept(args[ai], callee.arg_types[i])
  File "[..]/.venv/lib/python3.8/site-packages/mypy/checkexpr.py", line 3978, in accept
    typ = node.accept(self)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/nodes.py", line 1651, in accept
    return visitor.visit_name_expr(self)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/checkexpr.py", line 197, in visit_name_expr
    result = self.analyze_ref_expr(e)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/checkexpr.py", line 224, in analyze_ref_expr
    result = type_object_type(node, self.named_type)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/checkmember.py", line 1011, in type_object_type
    return type_object_type_from_function(t, info, method.info, fallback, is_new)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/typeops.py", line 84, in type_object_type_from_function
    return class_callable(signature, info, fallback, special_sig, is_new, orig_self_types[0])
  File "[..]/.venv/lib/python3.8/site-packages/mypy/typeops.py", line 112, in class_callable
    and is_subtype(explicit_type, default_ret_type, ignore_type_params=True)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/subtypes.py", line 94, in is_subtype
    return _is_subtype(left, right,
  File "[..]/.venv/lib/python3.8/site-packages/mypy/subtypes.py", line 151, in _is_subtype
    return left.accept(SubtypeVisitor(orig_right,
  File "[..]/.venv/lib/python3.8/site-packages/mypy/types.py", line 1094, in accept
    return visitor.visit_instance(self)
  File "[..]/.venv/lib/python3.8/site-packages/mypy/subtypes.py", line 286, in visit_instance
    if right.type.is_protocol and is_protocol_implementation(left, right):
  File "[..]/.venv/lib/python3.8/site-packages/mypy/subtypes.py", line 591, in is_protocol_implementation
    assert supertype is not None
AssertionError: 
test.py:15: : note: use --pdb to drop into pdb
```

**To Reproduce**

The minimal file to reproduce this is (let's call this `test.py`):
```py
from typing import Protocol
from unittest.mock import create_autospec
from abc import abstractmethod


class A(Protocol):
    @abstractmethod
    def method(self) -> int:
        raise NotImplementedError

    class Error:  # if commenting this class
        pass      # mypy works without complains

def test_one() -> None:
    p = create_autospec(A, instance=True)
```

run: `mypy test.py`

**Your Environment**

- Mypy version used: `0.950+dev.fd8a15e1abdd2bb4f75c3a6319ebfba233e1fe8e` (from the _master_ branch)
- Mypy command-line flags: _None_
- Mypy configuration options from `mypy.ini` (and other config files): _None_
- Python version used: 3.8.12, 3.9.10, 3.10.1
- Operating system and version: macOS 12.3

Similar issues:
- #6801
- #6850

**Comment by JelleZijlstra** [comment]
Here's a simpler repro that doesn't depend on the `mock` stubs:

```python
from typing import Protocol, Any
from abc import abstractmethod

def create_autospec(spec: object) -> Any: ...

class A(Protocol):
    @abstractmethod
    def method(self) -> int:
        raise NotImplementedError

    class Error:  # if commenting this class
        pass      # mypy works without complains

create_autospec(A)
```

**Comment by ilevkivskyi** [comment]
I think this was fixed by my other PR, it works on master.
