### ISSUE TITLE
Pydantic BaseModel + override a variable with a propetry = Mypy INTERNAL ERROR

### ISSUE THREAD

**Issue by triumph1** [python/mypy#12562]
**Bug Report**

Hi! thanks for all the efforts, mypy contributors :) 
I think I met across a bug, so I'm reporting it 

**To Reproduce**

(Write your steps here:)

1. I created a file named `temp.py`
```py
from pydantic import BaseModel


class A(BaseModel):
    hi: str


class B(A):
    def hi(self) -> str:
        return 'hi'
```
2. and ran mypy `poetry run mypy temp.py --show-traceback`

3. INTERNAL ERROR

**Expected Behavior**

I think mypy should find following error
```
temp.py:8: error: Signature of "hi" incompatible with supertype "A"  [override]
Found 1 error in 1 file (checked 1 source file)
```

**Actual Behavior**
but actually, INTERNAL ERROR occurs!
```
temp.py:8: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.942
Traceback (most recent call last):
  File "mypy/semanal.py", line 5220, in accept
  File "mypy/nodes.py", line 1020, in accept
  File "mypy/semanal.py", line 1113, in visit_class_def
  File "mypy/semanal.py", line 1191, in analyze_class
  File "mypy/semanal.py", line 1200, in analyze_class_body_common
  File "mypy/semanal.py", line 1260, in apply_class_plugin_hooks
  File "pydantic/mypy.py", line 109, in pydantic.mypy.PydanticPlugin._pydantic_model_class_maker_callback
  File "pydantic/mypy.py", line 197, in pydantic.mypy.PydanticModelTransformer.transform
  File "pydantic/mypy.py", line 386, in pydantic.mypy.PydanticModelTransformer.set_frozen
AssertionError: 
```

**Your Environment**

- Mypy version used: 0.942
- Mypy command-line flags: --show-traceback
- Mypy configuration options from `mypy.ini` (and other config files):
```
[tool.mypy]
python_version = "3.10"
strict = true
plugins = "pydantic.mypy"
disallow_subclassing_any = false
ignore_missing_imports = true
implicit_reexport = true
show_error_codes = true
```
- Pydantic version used: 1.9.0
- Python version used: 3.10.2
- Operating system and version: macOS Catelina

**Comment by JelleZijlstra** [comment]
Agree, the stack trace shows the error is in pydantic's code, not ours.
