### ISSUE TITLE
Crash in invalid star assignment

### ISSUE THREAD

**Issue by tushar-deepsource** [python/mypy#12560]
**Crash Report**

Mypy crashes on using a single starred item as an l-value.

**Traceback**

```console
$ mypy assignment.py --show-traceback
assignment.py:1: error: Starred assignment target must be in a list or tuple
assignment.py:1: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.942
Traceback (most recent call last):
  File "mypy/checkexpr.py", line 3978, in accept
  File "mypy/nodes.py", line 2012, in accept
  File "mypy/checkexpr.py", line 3293, in visit_list_expr
  File "mypy/checkexpr.py", line 3347, in check_lst_expr
  File "mypy/checkexpr.py", line 940, in check_call
  File "mypy/checkexpr.py", line 1025, in check_callable_call
  File "mypy/checkexpr.py", line 1173, in infer_function_type_arguments_using_context
  File "mypy/erasetype.py", line 115, in replace_meta_vars
  File "mypy/types.py", line 1965, in accept
AssertionError: 
assignment.py:1: : note: use --pdb to drop into pdb
```

**To Reproduce**

```python
*x = [1]
```

**Your Environment**

- Mypy version used: v0.942
- Python version used: 3.10.0
- Operating system and version: MacOS Monterey

**Comment by AlexWaygood** [comment]
Think this might be a duplicate of #9137

**Comment by tushar-deepsource** [comment]
Yup, it is.
