### ISSUE TITLE
Crash when using `match` on objected typed by `TypeVar` with constraints

### ISSUE THREAD

**Issue by exoriente** [python/mypy#12625]
**Crash Report**

`mypy` crashes when run on a file with a function definition using a `TypeVar` with constraints when `match` is used on an object typed by that `TypeVar`.

This might be related to issue #12448 (Crash on match statement in generic class with restricted type variable), but since the traceback is different, I've created a fresh issue.

**Traceback**

```
$ mypy --show-traceback example.py
example.py:6: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.942
Traceback (most recent call last):
  File "mypy/checker.py", line 424, in accept
  File "mypy/nodes.py", line 739, in accept
  File "mypy/checker.py", line 775, in visit_func_def
  File "mypy/checker.py", line 779, in _visit_func_def
  File "mypy/checker.py", line 841, in check_func_item
  File "mypy/checker.py", line 861, in check_func_def
  File "mypy/checker.py", line 1470, in expand_typevars
  File "mypy/checker.py", line 5997, in expand_func
  File "mypy/nodes.py", line 739, in accept
  File "mypy/treetransform.py", line 115, in visit_func_def
  File "mypy/treetransform.py", line 572, in block
  File "mypy/treetransform.py", line 194, in visit_block
  File "mypy/treetransform.py", line 583, in statements
  File "mypy/treetransform.py", line 556, in stmt
TypeError: mypy.nodes.Node object expected; got None
example.py:6: : note: use --pdb to drop into pdb
```

**To Reproduce**

The following simple Python script produces the crash when `mypy` is run on it:

```python
from typing import TypeVar

T = TypeVar("T", int, str)


def add_ten(x: T) -> T:
    match x:
        case int():
            return x + 10
        case str():
            return x + " ten"
```

This was tested on a clean environment with only `mypy` installed.

**Your Environment**

I've reproduced the error on a clean Python 3.10.3 environment without any config files. Only change to vanilla Python was: `pip install mypy`.

- Mypy version used: `0.942`
- Mypy command-line flags: `--show-traceback`
- Mypy configuration options from `mypy.ini` (and other config files): `None`
- Python version used: `3.10.3`
- Operating system and version: `macOS Monterrey 12.3.1`

**Comment by AlexWaygood** [comment]
Thanks for the report!

If I run mypy 0.942 on your code snippet, I can reproduce your traceback:

```python
(.venv) C:\Users\alexw\coding>mypy match_crash.py --show-traceback
match_crash.py:6: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.942
Traceback (most recent call last):
  File "C:\Users\alexw\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\alexw\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "mypy\checker.py", line 424, in accept
  File "mypy\nodes.py", line 739, in accept
  File "mypy\checker.py", line 775, in visit_func_def
  File "mypy\checker.py", line 779, in _visit_func_def
  File "mypy\checker.py", line 841, in check_func_item
  File "mypy\checker.py", line 861, in check_func_def
  File "mypy\checker.py", line 1470, in expand_typevars
  File "mypy\checker.py", line 5997, in expand_func
  File "mypy\nodes.py", line 739, in accept
  File "mypy\treetransform.py", line 115, in visit_func_def
  File "mypy\treetransform.py", line 572, in block
  File "mypy\treetransform.py", line 194, in visit_block
  File "mypy\treetransform.py", line 583, in statements
  File "mypy\treetransform.py", line 556, in stmt
TypeError: mypy.nodes.Node object expected; got None
match_crash.py:6: : note: use --pdb to drop into pdb
```

But if I run mypy master on your code snippet, I get the same traceback as in #12448:

```python
(venv) C:\Users\alexw\coding\mypy>mypy ../typeshed/match_crash.py --show-traceback
..\typeshed\match_crash.py:6: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.960+dev.20b0b9b460cd11a4755f70ae08823fa6a8f5fbd4
Traceback (most recent call last):
  File "C:\Users\alexw\coding\mypy\venv\Scripts\mypy-script.py", line 33, in <module>
    sys.exit(load_entry_point('mypy', 'console_scripts', 'mypy')())
  File "c:\users\alexw\coding\mypy\mypy\__main__.py", line 12, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "c:\users\alexw\coding\mypy\mypy\main.py", line 96, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "c:\users\alexw\coding\mypy\mypy\main.py", line 173, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "c:\users\alexw\coding\mypy\mypy\build.py", line 180, in build
    result = _build(
  File "c:\users\alexw\coding\mypy\mypy\build.py", line 256, in _build
    graph = dispatch(sources, manager, stdout)
  File "c:\users\alexw\coding\mypy\mypy\build.py", line 2733, in dispatch
    process_graph(graph, manager)
  File "c:\users\alexw\coding\mypy\mypy\build.py", line 3081, in process_graph
    process_stale_scc(graph, scc, manager)
  File "c:\users\alexw\coding\mypy\mypy\build.py", line 3179, in process_stale_scc
    graph[id].type_check_first_pass()
  File "c:\users\alexw\coding\mypy\mypy\build.py", line 2192, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "c:\users\alexw\coding\mypy\mypy\checker.py", line 320, in check_first_pass
    self.accept(d)
  File "c:\users\alexw\coding\mypy\mypy\checker.py", line 426, in accept
    stmt.accept(self)
  File "c:\users\alexw\coding\mypy\mypy\nodes.py", line 747, in accept
    return visitor.visit_func_def(self)
  File "c:\users\alexw\coding\mypy\mypy\checker.py", line 777, in visit_func_def
    self._visit_func_def(defn)
  File "c:\users\alexw\coding\mypy\mypy\checker.py", line 781, in _visit_func_def
    self.check_func_item(defn, name=defn.name)
  File "c:\users\alexw\coding\mypy\mypy\checker.py", line 843, in check_func_item
    self.check_func_def(defn, typ, name)
  File "c:\users\alexw\coding\mypy\mypy\checker.py", line 863, in check_func_def
    expanded = self.expand_typevars(defn, typ)
  File "c:\users\alexw\coding\mypy\mypy\checker.py", line 1483, in expand_typevars
    result.append((expand_func(defn, mapping), expanded))
  File "c:\users\alexw\coding\mypy\mypy\checker.py", line 6038, in expand_func
    ret = defn.accept(visitor)
  File "c:\users\alexw\coding\mypy\mypy\nodes.py", line 747, in accept
    return visitor.visit_func_def(self)
  File "c:\users\alexw\coding\mypy\mypy\treetransform.py", line 115, in visit_func_def
    self.block(node.body),
  File "c:\users\alexw\coding\mypy\mypy\treetransform.py", line 575, in block
    new = self.visit_block(block)
  File "c:\users\alexw\coding\mypy\mypy\treetransform.py", line 194, in visit_block
    return Block(self.statements(node.body))
  File "c:\users\alexw\coding\mypy\mypy\treetransform.py", line 586, in statements
    return [self.stmt(stmt) for stmt in statements]
  File "c:\users\alexw\coding\mypy\mypy\treetransform.py", line 586, in <listcomp>
    return [self.stmt(stmt) for stmt in statements]
  File "c:\users\alexw\coding\mypy\mypy\treetransform.py", line 560, in stmt
    assert isinstance(new, Statement)
AssertionError:
..\typeshed\match_crash.py:6: : note: use --pdb to drop into pdb
```

So I'm closing this as a duplicate.
