### ISSUE TITLE
mypy fails when redefining class variable with Final[Type] type annotation

### ISSUE THREAD

**Issue by ohashemzadeh** [python/mypy#12950]
**Crash Report**

When we define class variable inside class and trying to redefine it with Final[Type] type annotation, We face INTERNAL ERROR.

**Traceback**

```python3
(venv) user@Omid-Hashemzadeh:~/pythonProject/myproject/myproject$ mypy ./myapp/my_file.py --show-traceback
myapp/my_file.py:6: error: Cannot redefine an existing name as final
myapp/my_file.py:6: error: Name "a" already defined on line 5
myapp/my_file.py:6: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.970+dev.7e38877750c04abfd436e6ad98da23d6deca4e8f
Traceback (most recent call last):
  File "/home/user/pythonProject/myproject/venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/user/pythonProject/myproject/venv/lib/python3.8/site-packages/mypy/__main__.py", line 12, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/home/user/pythonProject/myproject/venv/lib/python3.8/site-packages/mypy/main.py", line 96, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "/home/user/pythonProject/myproject/venv/lib/python3.8/site-packages/mypy/main.py", line 173, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/home/user/pythonProject/myproject/venv/lib/python3.8/site-packages/mypy/build.py", line 154, in build
    result = _build(
  File "/home/user/pythonProject/myproject/venv/lib/python3.8/site-packages/mypy/build.py", line 230, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/user/pythonProject/myproject/venv/lib/python3.8/site-packages/mypy/build.py", line 2729, in dispatch
    process_graph(graph, manager)
  File "/home/user/pythonProject/myproject/venv/lib/python3.8/site-packages/mypy/build.py", line 3087, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/user/pythonProject/myproject/venv/lib/python3.8/site-packages/mypy/build.py", line 3185, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/home/user/pythonProject/myproject/venv/lib/python3.8/site-packages/mypy/build.py", line 2180, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/home/user/pythonProject/myproject/venv/lib/python3.8/site-packages/mypy/checker.py", line 325, in check_first_pass
    self.accept(d)
  File "/home/user/pythonProject/myproject/venv/lib/python3.8/site-packages/mypy/checker.py", line 431, in accept
    stmt.accept(self)
  File "/home/user/pythonProject/myproject/venv/lib/python3.8/site-packages/mypy/nodes.py", line 1029, in accept
    return visitor.visit_class_def(self)
  File "/home/user/pythonProject/myproject/venv/lib/python3.8/site-packages/mypy/checker.py", line 1816, in visit_class_def
    self.accept(defn.defs)
  File "/home/user/pythonProject/myproject/venv/lib/python3.8/site-packages/mypy/checker.py", line 431, in accept
    stmt.accept(self)
  File "/home/user/pythonProject/myproject/venv/lib/python3.8/site-packages/mypy/nodes.py", line 1100, in accept
    return visitor.visit_block(self)
  File "/home/user/pythonProject/myproject/venv/lib/python3.8/site-packages/mypy/checker.py", line 2178, in visit_block
    self.accept(s)
  File "/home/user/pythonProject/myproject/venv/lib/python3.8/site-packages/mypy/checker.py", line 431, in accept
    stmt.accept(self)
  File "/home/user/pythonProject/myproject/venv/lib/python3.8/site-packages/mypy/nodes.py", line 1166, in accept
    return visitor.visit_assignment_stmt(self)
  File "/home/user/pythonProject/myproject/venv/lib/python3.8/site-packages/mypy/checker.py", line 2247, in visit_assignment_stmt
    self.check_final(s)
  File "/home/user/pythonProject/myproject/venv/lib/python3.8/site-packages/mypy/checker.py", line 2718, in check_final
    assert isinstance(lv.node, Var)
AssertionError: 
myapp/my_file.py:6: : note: use --pdb to drop into pdb
```

**To Reproduce**

just create .py file with below content & run mypy on that file.
```python3
from typing import Final


class MyClass:
    a: None
    a: Final[int] = 1
```

**Your Environment**

- Mypy version used: `0.961`  and also latest dev version on github  `mypy==0.970+dev.7e38877750c04abfd436e6ad98da23d6deca4e8f`
- Mypy command-line flags:  `--show-traceback`
- Mypy configuration options from `mypy.ini` (and other config files): Nothing special int this file.
- Python version used: 3.8.10
- Operating system and version: Ubuntu 20.04.4 LTS (Focal Fossa)

**Comment by AlexWaygood** [comment]
Reproduced. Weirdly, this, on the other hand, does not crash:

```python
from typing import Final

class MyClass:
    a: None
    a: Final = 1
```
