### ISSUE TITLE
Problem with match statement

### ISSUE THREAD

**Issue by slott56** [python/mypy#12967]
**Crash Report**

A `match` statement seems to have uncovered a problem in 0.910

**Traceback**

```
(pywebtool) slott@MacBookPro-SLott py-web-tool % mypy --show-traceback pyweb.py 
pyweb.py: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.910
Traceback (most recent call last):
  File "/Users/slott/miniconda3/envs/pywebtool/bin/mypy", line 10, in <module>
    sys.exit(console_entry())
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/main.py", line 87, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/main.py", line 165, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/build.py", line 179, in build
    result = _build(
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/build.py", line 254, in _build
    graph = dispatch(sources, manager, stdout)
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/build.py", line 2644, in dispatch
    graph = load_graph(sources, manager)
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/build.py", line 2802, in load_graph
    st = State(id=bs.module, path=bs.path, source=bs.text, manager=manager,
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/build.py", line 1888, in __init__
    self.parse_file()
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/build.py", line 2016, in parse_file
    with self.wrap_context():
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/build.py", line 1955, in wrap_context
    yield
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/build.py", line 2046, in parse_file
    self.tree = manager.parse_file(self.id, self.xpath, source,
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/build.py", line 788, in parse_file
    tree = parse(source, path, id, self.errors, options=options)
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/parse.py", line 25, in parse
    return mypy.fastparse.parse(source,
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/fastparse.py", line 168, in parse
    ).visit(ast)
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/fastparse.py", line 329, in visit
    return visitor(node)
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/fastparse.py", line 496, in visit_Module
    body = self.fix_function_overloads(self.translate_stmt_list(mod.body, ismodule=True))
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/fastparse.py", line 367, in translate_stmt_list
    node = self.visit(stmt)
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/fastparse.py", line 329, in visit
    return visitor(node)
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/fastparse.py", line 729, in visit_ClassDef
    self.as_required_block(n.body, n.lineno),
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/fastparse.py", line 439, in as_required_block
    b = Block(self.fix_function_overloads(self.translate_stmt_list(stmts)))
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/fastparse.py", line 367, in translate_stmt_list
    node = self.visit(stmt)
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/fastparse.py", line 329, in visit
    return visitor(node)
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/fastparse.py", line 509, in visit_FunctionDef
    return self.do_func_def(n)
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/fastparse.py", line 607, in do_func_def
    self.as_required_block(n.body, lineno),
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/fastparse.py", line 439, in as_required_block
    b = Block(self.fix_function_overloads(self.translate_stmt_list(stmts)))
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/fastparse.py", line 367, in translate_stmt_list
    node = self.visit(stmt)
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/fastparse.py", line 329, in visit
    return visitor(node)
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/fastparse.py", line 825, in visit_If
    self.as_block(n.orelse, lineno))
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/fastparse.py", line 433, in as_block
    b = Block(self.fix_function_overloads(self.translate_stmt_list(stmts)))
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/fastparse.py", line 367, in translate_stmt_list
    node = self.visit(stmt)
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/fastparse.py", line 329, in visit
    return visitor(node)
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/fastparse.py", line 824, in visit_If
    [self.as_required_block(n.body, lineno)],
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/fastparse.py", line 439, in as_required_block
    b = Block(self.fix_function_overloads(self.translate_stmt_list(stmts)))
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/fastparse.py", line 367, in translate_stmt_list
    node = self.visit(stmt)
  File "/Users/slott/miniconda3/envs/pywebtool/lib/python3.10/site-packages/mypy/fastparse.py", line 327, in visit
    visitor = getattr(self, method)
AttributeError: 'ASTConverter' object has no attribute 'visit_Match'
pyweb.py: : note: use --pdb to drop into pdb
(pywebtool) slott@MacBookPro-SLott py-web-tool % 
```

**To Reproduce**

Changed a method to this...

```python
def fullNameFor(self, name: str) -> str:
    """Resolve "..." names into the full name."""
    if name in self.named: 
        return name
    elif name.endswith('...'):
        best = [n 
            for n in self.named.keys()
            if n.startswith(name[:-3]) 
        ]
        match len(best):
            case 0:
                return name
            case 1:
                return best[0]
            case _:
                raise Error(f"Ambiguous abbreviation {name!r}, matches {sorted(best)!r}")
    else:
        return name
```

This passes a unit test suite, so it appears to run nicely. 

**Your Environment**

- Mypy version used: version: 0.910
- Mypy command-line flags:  --show-traceback
- Mypy configuration options from `mypy.ini` (and other config files):  None
- Python version used: Python 3.10.4
- Operating system and version:   System Version:	macOS 12.4 (21F79)
  Kernel Version:	Darwin 21.5.0

**Comment by JelleZijlstra** [comment]
0.910 is quite old, does this still crash on the latest release?

**Comment by slott56** [comment]
No. Apologies for wasting folks time.
