### ISSUE TITLE
Internal Error from using BigQuery Google Cloud library

### ISSUE THREAD

**Issue by filippomanzardo** [python/mypy#12994]
**Crash Report**

Hey guys, I'm getting this recurring Internal Error and MyPy became unusable.  

```
/Users/me/repositories/my-repo/.venv/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py:700: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.961
Traceback (most recent call last):
  File "mypy/checker.py", line 431, in accept
  File "mypy/nodes.py", line 747, in accept
  File "mypy/checker.py", line 782, in visit_func_def
  File "mypy/checker.py", line 793, in _visit_func_def
  File "mypy/checker.py", line 1500, in check_method_override
  File "mypy/checker.py", line 1528, in check_method_or_accessor_override_for_base
  File "mypy/checker.py", line 1614, in check_method_override_for_base_with_name
  File "mypy/checker.py", line 1776, in check_override
  File "mypy/messages.py", line 845, in signature_incompatible_with_supertype
  File "mypy/messages.py", line 867, in pretty_callable_or_overload
  File "mypy/messages.py", line 1979, in pretty_callable
AttributeError: attribute 'arguments' of 'FuncDef' undefined
/Users/me/repositories/my-repo/.venv/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py:700: : note: use --pdb to drop into pdb

```

**To Reproduce**

From the command line, inside my source code:
```
mypy .
```

**Your Environment**

I'm using `poetry` for managing packages
Since it generates from google.cloud.bigquery, this are the versions I'm running on:

```
[[package]]
name = "google-cloud-bigquery"
version = "3.2.0"
description = "Google BigQuery API client library"
category = "main"
optional = false
python-versions = ">=3.6, <3.11"
```
```
[[package]]
name = "mypy"
version = "0.961"
description = "Optional static typing for Python"
category = "dev"
optional = false
python-versions = ">=3.6"
```

- Mypy version used: `0.961`
- Mypy command-line flags: `None`
- Mypy configuration options from `mypy.ini` (and other config files):
```
[mypy]


check_untyped_defs = True
disallow_any_generics = True
disallow_incomplete_defs = True

disallow_subclassing_any = False
disallow_untyped_calls = True
disallow_untyped_decorators = True
disallow_untyped_defs = True

implicit_reexport = True
no_implicit_optional = True
strict_equality = True
strict_optional = True
warn_redundant_casts = True
warn_return_any = True
warn_unused_ignores = True

[mypy-gunicorn.*]
ignore_missing_imports = True

[mypy-environ.*]
ignore_missing_imports = True

[mypy-uvicorn.*]
ignore_missing_imports = True

[mypy-google.cloud.*]
ignore_missing_imports = True
```
- Python version used: `3.10.3`
- Operating system and version: `macOS Monterey 12.1`

**Comment by AlexWaygood** [comment]
Looks like it might be the same crash as #11899/#11449; could you possibly see whether #12324 fixes it?

**Comment by filippomanzardo** [comment]
Yeah! `rm -rf .mypy_cache` works, thank you ❤️
