### ISSUE TITLE
AssertionError: Internal error: unresolved placeholder type None

### ISSUE THREAD

**Issue by StefanBrand** [python/mypy#13010]
**Crash Report**

- `LOG:  Build finished in 10.978 seconds with 503 modules, and 0 errors`
- `AssertionError: Internal error: unresolved placeholder type None`

**Traceback**
```py
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/usr/local/lib/python3.9/site-packages/mypy/__main__.py", line 12, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 96, in main
  File "mypy/main.py", line 173, in run_build
  File "mypy/build.py", line 154, in build
  File "mypy/build.py", line 230, in _build
  File "mypy/build.py", line 2729, in dispatch
  File "mypy/build.py", line 3087, in process_graph
  File "mypy/build.py", line 3205, in process_stale_scc
  File "mypy/build.py", line 2313, in write_cache
  File "mypy/build.py", line 1470, in write_cache
  File "mypy/nodes.py", line 352, in serialize
  File "mypy/nodes.py", line 3435, in serialize
  File "mypy/nodes.py", line 3372, in serialize
  File "mypy/nodes.py", line 2893, in serialize
  File "mypy/nodes.py", line 1039, in serialize
  File "mypy/types.py", line 536, in serialize
  File "mypy/types.py", line 2530, in serialize
```

**To Reproduce**
This happened when adding `django_cte` to a codebase that already uses `django-stubs` and `djangorestframework-stubs`. I have tried several versions and even uninstalling the latter leads to the same error. Unfortunately I cannot reproduce this in a minimal example with much lower complexity.

**Your Environment**

- Mypy version used: troubleshooted with 0.900--master
- Mypy configuration options from `mypy.ini` (and other config files):
```ini
[mypy]
plugins =
    mypy_django_plugin.main,
    mypy_drf_plugin.main

# and several ignore_missing_imports entries
```
- Python version used: `3.9.1`
- Operating system and version: Docker image `python:3.9.1`

**Comment by StefanBrand** [comment]
Do you have any tips on what I can do to help resolve this problem?

**Comment by StefanBrand** [comment]
Disabling only `djangorestframework-stubs` is not enough. Disabling `django-stubs` makes the `Internal error` go away. (The `Internal error` only appears if there are no type error detected along the way, so it involves adding `type: ignore` to many lines.)

**Comment by sobolevn** [comment]
Looks like this our problem. Let's move to https://github.com/typeddjango/django-stubs/issues/1019 🙂
