### ISSUE TITLE
mypy crashes at some forward references

### ISSUE THREAD

**Issue by arkoort** [python/mypy#1307]
### comments

There's no error if the line `Element = Union['Node', 'Tree']` follows the line `Node = NamedTuple('Node', [('ref', int)])`.

Latest version of mypy is installed from github.

    > mypy --version
    mypy 0.3.1

### code

    from typing import List, NamedTuple, Union

    Element = Union['Node', 'Tree']
    Node = NamedTuple('Node', [('ref', int)])

    class Tree(object):
        def __init__(self, data: List[Element]) -> None:
            self.content = data

        def swap(self, i: int, j: int) -> None:
            self.content[i], self.content[j] = self.content[j], self.content[i]

### result

    > mypy q.py
    Traceback (most recent call last):
      File "/usr/local/bin/mypy", line 6, in <module>
        main(__file__)
      File "/usr/local/lib/python3.5/dist-packages/mypy/main.py", line 51, in main
        type_check_only(sources, bin_dir, options)
      File "/usr/local/lib/python3.5/dist-packages/mypy/main.py", line 95, in type_check    _only
        python_path=options.python_path)
      File "/usr/local/lib/python3.5/dist-packages/mypy/build.py", line 211, in build
        result = manager.process(initial_states)
      File "/usr/local/lib/python3.5/dist-packages/mypy/build.py", line 426, in process
        next.process()
      File "/usr/local/lib/python3.5/dist-packages/mypy/build.py", line 930, in process
        self.type_checker().visit_file(self.tree, self.tree.path)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 416, in visit_    file
        self.accept(d)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 457, in accept
        typ = node.accept(self)
      File "/usr/local/lib/python3.5/dist-packages/mypy/nodes.py", line 484, in accept
        return visitor.visit_class_def(self)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 1038, in visit    _class_def
        self.accept(defn.defs)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 457, in accept
        typ = node.accept(self)
      File "/usr/local/lib/python3.5/dist-packages/mypy/nodes.py", line 525, in accept
        return visitor.visit_block(self)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 1133, in visit    _block
        self.accept(s)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 457, in accept
        typ = node.accept(self)
      File "/usr/local/lib/python3.5/dist-packages/mypy/nodes.py", line 381, in accept
        return visitor.visit_func_def(self)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 570, in visit_    func_def
        self.check_func_item(defn, name=defn.name())
      File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 628, in check_    func_item
        self.check_func_def(defn, typ, name)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 738, in check_    func_def
        self.accept_in_frame(item.body)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 472, in accept    _in_frame
        answer = self.accept(node, type_context)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 457, in accept
        typ = node.accept(self)
      File "/usr/local/lib/python3.5/dist-packages/mypy/nodes.py", line 525, in accept
        return visitor.visit_block(self)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 1133, in visit    _block
        self.accept(s)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 457, in accept
        typ = node.accept(self)
      File "/usr/local/lib/python3.5/dist-packages/mypy/nodes.py", line 563, in accept
        return visitor.visit_assignment_stmt(self)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 1142, in visit    _assignment_stmt
        self.check_assignment(s.lvalues[-1], s.rvalue, s.type is None)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 1157, in check    _assignment
        infer_lvalue_type)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 1224, in check    _assignment_to_multiple_lvalues
        self.check_assignment(lv, rv, infer_lvalue_type)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 1187, in check    _assignment
        self.check_indexed_assignment(index_lvalue, rvalue, rvalue)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 1526, in check    _indexed_assignment
        context)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checkexpr.py", line 261, in chec    k_call
        messages=arg_messages)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checkexpr.py", line 653, in over    load_call_target
        typ)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checkexpr.py", line 729, in eras    ed_signature_similarity
        None, check_arg=check_arg)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checkexpr.py", line 609, in chec    k_argument_types
        actual + 1, i + 1, callee, context, messages)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checkexpr.py", line 721, in chec    k_arg
        overload_arg_similarity(caller_type, callee_type))
      File "/usr/local/lib/python3.5/dist-packages/mypy/checkexpr.py", line 1632, in ove    rload_arg_similarity
        for item in actual.items)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checkexpr.py", line 1632, in <ge    nexpr>
        for item in actual.items)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checkexpr.py", line 1635, in ove    rload_arg_similarity
        for item in formal.items)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checkexpr.py", line 1635, in <ge    nexpr>
        for item in formal.items)
      File "/usr/local/lib/python3.5/dist-packages/mypy/checkexpr.py", line 1655, in ove    rload_arg_similarity
        return 2 if is_same_type(erasetype.erase_type(actual), erasetype.erase_type(form    al)) else 0
      File "/usr/local/lib/python3.5/dist-packages/mypy/erasetype.py", line 21, in erase    _type
        return typ.accept(EraseTypeVisitor())
      File "/usr/local/lib/python3.5/dist-packages/mypy/types.py", line 74, in accept
        return visitor.visit_unbound_type(self)
      File "/usr/local/lib/python3.5/dist-packages/mypy/erasetype.py", line 26, in visit    _unbound_type
        assert False, 'Not supported'
    AssertionError: Not supported
    
    *** INTERNAL ERROR ***
    
    q.py:12: error: Internal error -- please report a bug at https://github.com/JukkaL/m    ypy/issues
    
    NOTE: you can use "mypy --pdb ..." to drop into the debugger when this happens.

**Comment by gvanrossum** [comment]
Looks like you've hit a point in some very old code where some combination of things hasn't been implemented yet. I don't know how hard it would be to fix and it's an easy work-around, so I think we can live with this a little longer. Marking it as a bug though to keep track. Eventually we'll get to it.

**Comment by rwbarton** [comment]
While mypy should ideally not crash of course, forward references to type aliases aren't supported yet anyway.
```
from typing import Union

Element = Union['Node',	str] # E: Invalid type "forward.Node"
Node = int
```

**Comment by gvanrossum** [comment]
I still want to get rid of the crash. Shorter repro:
```
from typing import List, Union

Element = Union['Node', 'Tree']
Node = int

class Tree(object):
    content = [] # type: List[Element]
    def swap(self, i: int, j: int) -> None:
        self.content[i] = self.content[j]
```
