### ISSUE TITLE
Dataclasses 

### ISSUE THREAD

**Issue by zevbo** [python/mypy#13108]
**Crash Report**

When I run mypy on the example that contains a dataclass genericed over a typevar bound by a ____, I get an internal error. Note that in the example there's a simple fix, as the typevar can be bound by a regularly written type, and then it works fine, but in my real project this doesn't work.

**Traceback**

```
Traceback (most recent call last):
  File "mypy/semanal.py", line 4872, in accept
  File "mypy/nodes.py", line 687, in accept
  File "mypy/semanal.py", line 577, in visit_func_def
  File "mypy/semanal.py", line 609, in analyze_func_def
  File "mypy/semanal.py", line 4583, in defer
AssertionError: Must not defer during final iteration```

**To Reproduce**

```
from dataclasses import dataclass
from typing import Generic, TypeVar

T = TypeVar("T", bound="B")

@dataclass
class A(Generic[T]):
    foobar: float = 0.0

class B:
    pass
```

Run simply with `mypy FILENAME`

**Your Environment**

Using mypy 0.910, Ubuntu, Python 3.8, and the following mypy options:
```
exclude = libraries, babbage/robot_descriptions/urdfs/tmp
disallow_untyped_defs = True
show_error_codes = True
namespace_packages = True
```

**Comment by AlexWaygood** [comment]
I can reproduce on mypy 0.910, but mypy 0.910 is quite an old version of mypy. I can't reproduce on mypy 0.961, the latest version. The solution is simply to upgrade your version of mypy :)
