### ISSUE TITLE
Crash on SQLAlchemy model with conditional column type

### ISSUE THREAD

**Issue by stopmachine** [python/mypy#13100]
**Crash Report**

Running mypy on a SQLAlchemy model with an inline condition for the column type makes it crash.

**Traceback**

```
$ mypy src/dbschema/fail_dbmodels.py --show-traceback
src/dbschema/fail_dbmodels.py:27: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.980+dev.3ae19a25f0a39358ede1383e93d44ef9abf165e0
Traceback (most recent call last):
  File "/Users/user/workspace/test_repo/.venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/mypy/__main__.py", line 12, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/mypy/main.py", line 96, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/mypy/main.py", line 173, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/mypy/build.py", line 154, in build
    result = _build(
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/mypy/build.py", line 230, in _build
    graph = dispatch(sources, manager, stdout)
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/mypy/build.py", line 2729, in dispatch
    process_graph(graph, manager)
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/mypy/build.py", line 3087, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/mypy/build.py", line 3179, in process_stale_scc
    mypy.semanal_main.semantic_analysis_for_scc(graph, scc, manager.errors)
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/mypy/semanal_main.py", line 80, in semantic_analysis_for_scc
    process_top_levels(graph, scc, patches)
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/mypy/semanal_main.py", line 203, in process_top_levels
    deferred, incomplete, progress = semantic_analyze_target(next_id, state,
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/mypy/semanal_main.py", line 330, in semantic_analyze_target
    analyzer.refresh_partial(refresh_node,
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/mypy/semanal.py", line 414, in refresh_partial
    self.refresh_top_level(node)
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/mypy/semanal.py", line 425, in refresh_top_level
    self.accept(d)
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/mypy/semanal.py", line 5354, in accept
    node.accept(self)
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/mypy/nodes.py", line 1039, in accept
    return visitor.visit_class_def(self)
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/mypy/semanal.py", line 1123, in visit_class_def
    self.analyze_class(defn)
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/mypy/semanal.py", line 1203, in analyze_class
    self.analyze_class_body_common(defn)
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/mypy/semanal.py", line 1212, in analyze_class_body_common
    self.apply_class_plugin_hooks(defn)
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/mypy/semanal.py", line 1257, in apply_class_plugin_hooks
    hook(ClassDefContext(defn, base_expr, self))
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/sqlalchemy/ext/mypy/plugin.py", line 258, in _base_cls_hook
    decl_class.scan_declarative_assignments_and_apply_types(ctx.cls, ctx.api)
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 96, in scan_declarative_assignments_and_apply_types
    _scan_declarative_assignment_stmt(
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 459, in _scan_declarative_assignment_stmt
    python_type_for_type = infer.infer_type_from_right_hand_nameexpr(
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/sqlalchemy/ext/mypy/infer.py", line 51, in infer_type_from_right_hand_nameexpr
    python_type_for_type = _infer_type_from_decl_column(
  File "/Users/user/workspace/test_repo/.venv/lib/python3.8/site-packages/sqlalchemy/ext/mypy/infer.py", line 391, in _infer_type_from_decl_column
    assert False
AssertionError: 
src/dbschema/fail_dbmodels.py:27: : note: use --pdb to drop into pdb
(.venv) FAIL: 2
```

**To Reproduce**

`mypy fail_dbmodels.py`

```python
import os
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import BigInteger, Column, Integer
from sqlalchemy.orm import declarative_base

is_testing = os.environ.get('IS_TESTING', "false") == "true"

db = SQLAlchemy()
Base = declarative_base()


class ExampleModel(Base):
    __tablename__ = 'example_table'

    id = Column(BigInteger if not is_testing else Integer, primary_key=True)
```

**Your Environment**

- Mypy version used: 0.980+dev.3ae19a25f0a39358ede1383e93d44ef9abf165e0
- Mypy command-line flags: `--show-traceback`
- Mypy configuration options from `mypy.ini` (and other config files):
```
[mypy]
plugins = sqlalchemy.ext.mypy.plugin
exclude = (?x)(
          src/dbschema/migrations/.*
          | src/print_blob.py
    )

[mypy-flask_sqlalchemy.*]
ignore_missing_imports = True
```
- Python version used: 3.8.9
- Operating system and version: MacOS Monterey 12.4 (Darwin Kernel 21.5.0)

**Comment by AlexWaygood** [comment]
From the traceback, it looks like this is probably an issue with the `SQLAlchemy` mypy plugin, so you should report the problem there rather than with mypy
