### ISSUE TITLE
mypy crash

### ISSUE THREAD

**Issue by ilya-klyuchnikov** [python/mypy#13215]
**Crash Report**

`mypy` crashed

**Traceback**
```
mypy examples.py --show-traceback
examples.py:6: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.971
Traceback (most recent call last):
  File "mypy/checker.py", line 435, in accept
  File "mypy/nodes.py", line 1426, in accept
  File "mypy/checker.py", line 4178, in visit_match_stmt
  File "mypy/checkpattern.py", line 104, in accept
  File "mypy/patterns.py", line 87, in accept
  File "mypy/checkpattern.py", line 300, in visit_sequence_pattern
  File "mypy/checkpattern.py", line 651, in construct_sequence_child
  File "mypy/checkpattern.py", line 658, in construct_sequence_child
AssertionError: 
examples.py:6: : note: use --pdb to drop into pdb
```

**To Reproduce**

Code (`examples.py`):

```python
from typing import Tuple


def example(t: Tuple[int, str] | Tuple[int, str, str]) -> int:
    result = 0
    match t:
        case (i, _):
            result = i
        case (i, _, _):
            result = i
    return result

```

```
mypy examples
```

**Your Environment**

- Mypy version used: 0.971
- Mypy command-line flags:
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.10
- Operating system and version: Macos

**Comment by JelleZijlstra** [comment]
Looks like another case of #12533.
