### ISSUE TITLE
REGR: mypyc 0.971 seems to not handle keyword-only arguments when unpickling

### ISSUE THREAD

**Issue by twoertwein** [python/mypy#13227]
**Bug Report**

The following worked with 0.961: object's whose `__init__` has a keyword-only argument  can no longer be unpickled.

**To Reproduce**

test.py
```py
from typing import Any

class Test:
    def __init__(self, *, x: Any) -> None:
        ...
```
save_load.py
```py
import pickle
from test import Test

test = Test(x=1)

with open("test.pickle", mode="w+b") as file:
    pickle.dump(test, file)
with open("test.pickle", mode="r+b") as file:
    pickle.load(file)
```

```sh
$ mypyc test.py
$ python save_load.py 
Traceback (most recent call last):
  File "save_load.py", line 9, in <module>
    pickle.load(file)
TypeError: __init__() missing required keyword-only argument 'x'
```

**Expected Behavior**
No `TypeError`

**Actual Behavior**
`TypeError`

**Your Environment**

- Mypy version used: 0.971
- Python version used: 3.10.4
- Operating system and version: Fedora Silverblue

**Comment by twoertwein** [comment]
slightly smaller reproducer:

test.py:
```py
class Test:
    def __init__(self, *, x: int) -> None:
        ...
```
```sh
$ mypyc test.py
$ python -c "from test import Test; from copy import copy; copy(Test(x=1))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.10/copy.py", line 102, in copy
    return _reconstruct(x, None, *rv)
  File "/usr/lib64/python3.10/copy.py", line 265, in _reconstruct
    y = func(*args)
  File "/usr/lib64/python3.10/copyreg.py", line 101, in __newobj__
    return cls.__new__(cls, *args)
TypeError: __init__() missing required keyword-only argument 'x'
```

**Comment by hauntsaninja** [comment]
Sounds like this might be https://github.com/python/mypy/pull/12600/files#r873178396

**Comment by hauntsaninja** [comment]
Looks like mypyc docs isn't up to date cc @JukkaL https://github.com/mypyc/mypyc/issues/920

**Comment by hauntsaninja** [comment]
If you make me an RTD admin (like you did for mypy), I can get the docs working again

**Comment by twoertwein** [comment]
Thank you @hauntsaninja, using this decorator leads to a new issue without pickle/copy (and without keyword-only arguments):

```py
from mypy_extensions import mypyc_attr

@mypyc_attr(serializable=True)
class Test:
    def __init__(self, x: int) -> None:
        self.x = x

    def test(self) -> int:
        return self.x
```

```py
$ mypyc test.py
$ python -c "from test import Test; Test(x=1).test()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "test.py", line 11, in test
    return self.x
AttributeError: attribute 'Test' of 'x' undefined
```

**Comment by ingambe** [comment]
Is there any news regarding this issue?
