### ISSUE TITLE
Bug when checking class that overwrites superclass' property in pydantic's BaseModel

### ISSUE THREAD

**Issue by mdczaplicki** [python/mypy#13287]
**Bug Report**

(A clear and concise description of what the bug is.)

**To Reproduce**

```
from datetime import datetime

from pydantic import BaseModel


class TimeSeriesObject(BaseModel):
    ts_from: datetime
    ts_to: datetime
    value: float


class Test1(TimeSeriesObject):
    test: float

    def value(self) -> float:
        return self.test
```

```
pytest test.py
```

**Expected Behavior**

Works, and shows an error or anything.

**Actual Behavior**

Doesn't work.

**Your Environment**

- Mypy version used: 0.971
- Mypy command-line flags: mypy path/to/file.py
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.7.13
- Operating system and version: MacOs Monterey

```
version: 0.971
Traceback (most recent call last):
  File "/Users/marek/.local/share/virtualenvs/teems-tle8JvSg/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/Users/marek/.local/share/virtualenvs/teems-tle8JvSg/lib/python3.7/site-packages/mypy/__main__.py", line 12, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/Users/marek/.local/share/virtualenvs/teems-tle8JvSg/lib/python3.7/site-packages/mypy/main.py", line 96, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "/Users/marek/.local/share/virtualenvs/teems-tle8JvSg/lib/python3.7/site-packages/mypy/main.py", line 173, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/Users/marek/.local/share/virtualenvs/teems-tle8JvSg/lib/python3.7/site-packages/mypy/build.py", line 155, in build
    sources, options, alt_lib_path, flush_errors, fscache, stdout, stderr, extra_plugins
  File "/Users/marek/.local/share/virtualenvs/teems-tle8JvSg/lib/python3.7/site-packages/mypy/build.py", line 230, in _build
    graph = dispatch(sources, manager, stdout)
  File "/Users/marek/.local/share/virtualenvs/teems-tle8JvSg/lib/python3.7/site-packages/mypy/build.py", line 2729, in dispatch
    process_graph(graph, manager)
  File "/Users/marek/.local/share/virtualenvs/teems-tle8JvSg/lib/python3.7/site-packages/mypy/build.py", line 3087, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/Users/marek/.local/share/virtualenvs/teems-tle8JvSg/lib/python3.7/site-packages/mypy/build.py", line 3179, in process_stale_scc
    mypy.semanal_main.semantic_analysis_for_scc(graph, scc, manager.errors)
  File "/Users/marek/.local/share/virtualenvs/teems-tle8JvSg/lib/python3.7/site-packages/mypy/semanal_main.py", line 80, in semantic_analysis_for_scc
    process_top_levels(graph, scc, patches)
  File "/Users/marek/.local/share/virtualenvs/teems-tle8JvSg/lib/python3.7/site-packages/mypy/semanal_main.py", line 207, in process_top_levels
    patches)
  File "/Users/marek/.local/share/virtualenvs/teems-tle8JvSg/lib/python3.7/site-packages/mypy/semanal_main.py", line 335, in semantic_analyze_target
    active_type=active_type)
  File "/Users/marek/.local/share/virtualenvs/teems-tle8JvSg/lib/python3.7/site-packages/mypy/semanal.py", line 414, in refresh_partial
    self.refresh_top_level(node)
  File "/Users/marek/.local/share/virtualenvs/teems-tle8JvSg/lib/python3.7/site-packages/mypy/semanal.py", line 425, in refresh_top_level
    self.accept(d)
  File "/Users/marek/.local/share/virtualenvs/teems-tle8JvSg/lib/python3.7/site-packages/mypy/semanal.py", line 5354, in accept
    node.accept(self)
  File "/Users/marek/.local/share/virtualenvs/teems-tle8JvSg/lib/python3.7/site-packages/mypy/nodes.py", line 1039, in accept
    return visitor.visit_class_def(self)
  File "/Users/marek/.local/share/virtualenvs/teems-tle8JvSg/lib/python3.7/site-packages/mypy/semanal.py", line 1123, in visit_class_def
    self.analyze_class(defn)
  File "/Users/marek/.local/share/virtualenvs/teems-tle8JvSg/lib/python3.7/site-packages/mypy/semanal.py", line 1203, in analyze_class
    self.analyze_class_body_common(defn)
  File "/Users/marek/.local/share/virtualenvs/teems-tle8JvSg/lib/python3.7/site-packages/mypy/semanal.py", line 1212, in analyze_class_body_common
    self.apply_class_plugin_hooks(defn)
  File "/Users/marek/.local/share/virtualenvs/teems-tle8JvSg/lib/python3.7/site-packages/mypy/semanal.py", line 1257, in apply_class_plugin_hooks
    hook(ClassDefContext(defn, base_expr, self))
  File "/Users/marek/.local/share/virtualenvs/teems-tle8JvSg/lib/python3.7/site-packages/pydantic/mypy.py", line 109, in _pydantic_model_class_maker_callback
    transformer.transform()
  File "/Users/marek/.local/share/virtualenvs/teems-tle8JvSg/lib/python3.7/site-packages/pydantic/mypy.py", line 197, in transform
    self.set_frozen(fields, frozen=config.allow_mutation is False or config.frozen is True)
  File "/Users/marek/.local/share/virtualenvs/teems-tle8JvSg/lib/python3.7/site-packages/pydantic/mypy.py", line 386, in set_frozen
    assert isinstance(var, Var)
AssertionError: 
/Users/marek/Projects/trueenergy/teems/teems/models/price/prices.py:15: : note: use --pdb to drop into pdb
```

**Comment by AlexWaygood** [comment]
The traceback indicates that this is likely a bug in pydantic's mypy plugin, not mypy itself; you should report an issue over at the pydantic issue tracker (https://github.com/samuelcolvin/pydantic)
