### ISSUE TITLE
'AssignmentStmt' object has no attribute 'expr'

### ISSUE THREAD

**Issue by lunemec** [python/mypy#1329]
```
mypy --py2 mylittlepony
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 6, in <module>
    main(__file__)
  File "/usr/local/lib/python3.2/dist-packages/mypy/main.py", line 54, in main
    type_check_only(sources, bin_dir, options)
  File "/usr/local/lib/python3.2/dist-packages/mypy/main.py", line 98, in type_check_only
    python_path=options.python_path)
  File "/usr/local/lib/python3.2/dist-packages/mypy/build.py", line 206, in build
    result = manager.process(initial_states)
  File "/usr/local/lib/python3.2/dist-packages/mypy/build.py", line 403, in process
    next.process()
  File "/usr/local/lib/python3.2/dist-packages/mypy/build.py", line 907, in process
    self.type_checker().visit_file(self.tree, self.tree.path)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checker.py", line 406, in visit_file
    self.accept(d)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checker.py", line 447, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.2/dist-packages/mypy/nodes.py", line 382, in accept
    return visitor.visit_func_def(self)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checker.py", line 562, in visit_func_def
    self.check_func_item(defn, name=defn.name())
  File "/usr/local/lib/python3.2/dist-packages/mypy/checker.py", line 620, in check_func_item
    self.check_func_def(defn, typ, name)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checker.py", line 717, in check_func_def
    self.accept_in_frame(item.body)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checker.py", line 462, in accept_in_frame
    answer = self.accept(node, type_context)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checker.py", line 447, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.2/dist-packages/mypy/nodes.py", line 526, in accept
    return visitor.visit_block(self)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checker.py", line 1112, in visit_block
    self.accept(s)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checker.py", line 447, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.2/dist-packages/mypy/nodes.py", line 623, in accept
    return visitor.visit_return_stmt(self)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checker.py", line 1547, in visit_return_stmt
    typ = self.accept(s.expr, return_type)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checker.py", line 447, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.2/dist-packages/mypy/nodes.py", line 965, in accept
    return visitor.visit_call_expr(self)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checker.py", line 1946, in visit_call_expr
    return self.expr_checker.visit_call_expr(e)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checkexpr.py", line 142, in visit_call_expr
    return self.check_call_expr_with_callee_type(callee_type, e)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checkexpr.py", line 193, in check_call_expr_with_callee_type
    e.arg_names, callable_node=e.callee)[0]
  File "/usr/local/lib/python3.2/dist-packages/mypy/checkexpr.py", line 253, in check_call
    arg_types = self.infer_arg_types_in_context(None, args)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checkexpr.py", line 301, in infer_arg_types_in_context
    arg_type = self.accept(arg, ctx)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checkexpr.py", line 1423, in accept
    return self.chk.accept(node, context)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checker.py", line 447, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.2/dist-packages/mypy/nodes.py", line 965, in accept
    return visitor.visit_call_expr(self)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checker.py", line 1946, in visit_call_expr
    return self.expr_checker.visit_call_expr(e)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checkexpr.py", line 142, in visit_call_expr
    return self.check_call_expr_with_callee_type(callee_type, e)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checkexpr.py", line 193, in check_call_expr_with_callee_type
    e.arg_names, callable_node=e.callee)[0]
  File "/usr/local/lib/python3.2/dist-packages/mypy/checkexpr.py", line 262, in check_call
    self.infer_arg_types_in_context(None, args)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checkexpr.py", line 301, in infer_arg_types_in_context
    arg_type = self.accept(arg, ctx)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checkexpr.py", line 1423, in accept
    return self.chk.accept(node, context)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checker.py", line 447, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.2/dist-packages/mypy/nodes.py", line 1187, in accept
    return visitor.visit_func_expr(self)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checker.py", line 2071, in visit_func_expr
    return self.expr_checker.visit_func_expr(e)
  File "/usr/local/lib/python3.2/dist-packages/mypy/checkexpr.py", line 1238, in visit_func_expr
    ret_type = e.expr().accept(self.chk)
  File "/usr/local/lib/python3.2/dist-packages/mypy/nodes.py", line 1184, in expr
    return ret.expr
AttributeError: 'AssignmentStmt' object has no attribute 'expr'
```
*** INTERNAL ERROR ***

mylittlepony/core/history.py:279: error: Internal error -- please report a bug at https://github.com/JukkaL/mypy/issues

File history.py:279 contains:
`lambda (x, y): normalize(y) != normalize(getattr(model, x)),`

Entire expr:
```
return dict(
        filter(
            lambda (x, y): normalize(y) != normalize(getattr(model, x)),
            data.iteritems())
    )
```

**Comment by gvanrossum** [comment]
Thanks for the report -- in order to help us reproduce this, could you post
a minimal self-contained program that exhibits the bug?

**Comment by lunemec** [comment]
I have already found a fix, this was related to the lambda parsing error and fixed in https://github.com/python/mypy/issues/1157. I will close this issue.
