### ISSUE TITLE
Internal error occurred

### ISSUE THREAD

**Issue by sharmaeklavya2** [python/mypy#1342]
I encountered an internal error while running `mypy --py2 tools/print-all/print-all`. [print-all](https://github.com/zulip/zulip/blob/master/tools/print-all/print-all#L135) is a python 2 script in Zulip.

This script is not annotated at all.

I used the latest version of mypy from this repository (f3c1c55). I also tested it on the version available on pypi. Both of them are throwing this internal error.

```
Traceback (most recent call last):
  File "/mnt/Code/git_repos/forked/zvenv3/bin/mypy", line 6, in <module>
    main(__file__)
  File "/mnt/Code/git_repos/forked/zvenv3/lib/python3.4/site-packages/mypy/main.py", line 51, in main
    type_check_only(sources, bin_dir, options)
  File "/mnt/Code/git_repos/forked/zvenv3/lib/python3.4/site-packages/mypy/main.py", line 95, in type_check_only
    python_path=options.python_path)
  File "/mnt/Code/git_repos/forked/zvenv3/lib/python3.4/site-packages/mypy/build.py", line 239, in build
    result = manager.process(initial_states)
  File "/mnt/Code/git_repos/forked/zvenv3/lib/python3.4/site-packages/mypy/build.py", line 459, in process
    next.process()
  File "/mnt/Code/git_repos/forked/zvenv3/lib/python3.4/site-packages/mypy/build.py", line 928, in process
    self.semantic_analyzer().visit_file(self.tree, self.tree.path)
  File "/mnt/Code/git_repos/forked/zvenv3/lib/python3.4/site-packages/mypy/semanal.py", line 233, in visit_file
    self.accept(d)
  File "/mnt/Code/git_repos/forked/zvenv3/lib/python3.4/site-packages/mypy/semanal.py", line 2196, in accept
    node.accept(self)
  File "/mnt/Code/git_repos/forked/zvenv3/lib/python3.4/site-packages/mypy/nodes.py", line 721, in accept
    return visitor.visit_with_stmt(self)
  File "/mnt/Code/git_repos/forked/zvenv3/lib/python3.4/site-packages/mypy/semanal.py", line 1646, in visit_with_stmt
    self.visit_block(s.body)
  File "/mnt/Code/git_repos/forked/zvenv3/lib/python3.4/site-packages/mypy/semanal.py", line 995, in visit_block
    self.accept(s)
  File "/mnt/Code/git_repos/forked/zvenv3/lib/python3.4/site-packages/mypy/semanal.py", line 2196, in accept
    node.accept(self)
  File "/mnt/Code/git_repos/forked/zvenv3/lib/python3.4/site-packages/mypy/nodes.py", line 381, in accept
    return visitor.visit_func_def(self)
  File "/mnt/Code/git_repos/forked/zvenv3/lib/python3.4/site-packages/mypy/semanal.py", line 285, in visit_func_def
    if isinstance(symbol.node, FuncDef) and symbol.node != defn:
AttributeError: 'NoneType' object has no attribute 'node'

*** INTERNAL ERROR ***

tools/print-all/print-all:135: error: Internal error -- please report a bug at https://github.com/JukkaL/mypy/issues

NOTE: you can use "mypy --pdb ..." to drop into the debugger when this happens.
```

**Comment by JukkaL** [comment]
A simple repro:

```
with 1:
    def f():
        pass
```

Moving the function to be outside a with statement would likely work around the problem. This should be easy to fix though.
