### ISSUE TITLE
Internal error: unresolved placeholder when using `--follow-imports=silent`

### ISSUE THREAD

**Issue by Lotram** [python/mypy#13671]
**Crash Report**

mypy had been crashing on my code for a long time now, because of an error in my code ([same reason as here](https://github.com/python/mypy/issues/10357#issuecomment-825224225)). I fixed that error, but it now crashes with the following traceback. 
Since it has been crashing for a long time, I did not manage to narrow it down to a specific part of my code, or write a minimal example, but I did find out that this crash only happens with the flag `--follow-imports=silent`. it does not crash with any other value for this flag

**Traceback**

```
Traceback (most recent call last):
  File ".venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
    │        └ <function console_entry at 0x7ffad49cc430>
    └ <module 'sys' (built-in)>
  File ".venv/lib/python3.10/site-packages/mypy/__main__.py", line 12, in console_entry
    main(None, sys.stdout, sys.stderr)
    │          │           └ <module 'sys' (built-in)>
    │          └ <module 'sys' (built-in)>
    └ <built-in function main>
  File "mypy/main.py", line 96, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
                              └ <built-in function run_build>
  File "mypy/main.py", line 173, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
          └ <module 'mypy.build' from '.venv/lib/python3.10/site-packages/mypy/build.cpython-31...
  File "mypy/build.py", line 154, in build
    result = _build(
  File "mypy/build.py", line 230, in _build
    graph = dispatch(sources, manager, stdout)
            └ <built-in function dispatch>
  File "mypy/build.py", line 2729, in dispatch
    process_graph(graph, manager)
    └ <built-in function process_graph>
  File "mypy/build.py", line 3087, in process_graph
    process_stale_scc(graph, scc, manager)
    └ <built-in function process_stale_scc>
  File "mypy/build.py", line 3205, in process_stale_scc
    graph[id].write_cache()
  File "mypy/build.py", line 2313, in write_cache
    new_interface_hash, self.meta = write_cache(
  File "mypy/build.py", line 1470, in write_cache
    data = tree.serialize()
  File "mypy/nodes.py", line 358, in serialize
    'names': self.names.serialize(self._fullname),
  File "mypy/nodes.py", line 3456, in serialize
    data[key] = value.serialize(fullname, key)
  File "mypy/nodes.py", line 3393, in serialize
    data['node'] = self.node.serialize()
  File "mypy/nodes.py", line 2915, in serialize
    'defn': self.defn.serialize(),
  File "mypy/nodes.py", line 1050, in serialize
    'type_vars': [v.serialize() for v in self.type_vars],
  File "mypy/types.py", line 535, in serialize
    'upper_bound': self.upper_bound.serialize(),
  File "mypy/types.py", line 2528, in serialize
    assert False, f"Internal error: unresolved placeholder type {self.fullname}"
AssertionError: Internal error: unresolved placeholder type None

```
When using the verbose mode, the last LOG line I get before the error is: 
`LOG:  Build finished in 8.065 seconds with 1177 modules, and 0 errors`

**To Reproduce**
I wasn't able to reproduce using a minimal example. I'd be happy to look for the root cause in my code if you have any insight on how to do that. The crash only happens with `--follow-imports=silent`

**Your Environment**

- Mypy version used: 0.971
- Mypy command-line flags:  `--follow-imports=silent`
- Mypy configuration options from `mypy.ini` (and other config files): `python_version = "3.10"` 
- Python version used: 3.10.5
- Operating system and version: Ubuntu 20.04

**Comment by Lotram** [comment]
Ok I forgot to check another config file, containing the django plugin, it seems  like [it's a problem on their side](https://github.com/typeddjango/django-stubs/issues/1059), I'm closing this.
