### ISSUE TITLE
Internal error/crash on property declared outside a class

### ISSUE THREAD

**Issue by jstasiak** [python/mypy#1387]
Python 3.5.1, mypy 0.3.1 and 1423a54.

Minimal code required to reproduce (I don't dispute it's an unusual case but we have code like this nonetheless):

```python
@property
def x(self):
    return 123
```

mypy 1423a54 output:

```
Traceback (most recent call last):
  File "/vagrant/env3/bin/mypy", line 6, in <module>
    main(__file__)
  File "/vagrant/env3/lib/python3.5/site-packages/mypy/main.py", line 52, in main
    res = type_check_only(sources, bin_dir, options)
  File "/vagrant/env3/lib/python3.5/site-packages/mypy/main.py", line 100, in type_check_only
    python_path=options.python_path)
  File "/vagrant/env3/lib/python3.5/site-packages/mypy/build.py", line 207, in build
    dispatch(sources, manager)
  File "/vagrant/env3/lib/python3.5/site-packages/mypy/build.py", line 1185, in dispatch
    process_graph(graph, manager)
  File "/vagrant/env3/lib/python3.5/site-packages/mypy/build.py", line 1303, in process_graph
    process_stale_scc(graph, scc)
  File "/vagrant/env3/lib/python3.5/site-packages/mypy/build.py", line 1333, in process_stale_scc
    graph[id].type_check()
  File "/vagrant/env3/lib/python3.5/site-packages/mypy/build.py", line 1167, in type_check
    manager.type_checker.visit_file(self.tree, self.xpath)
  File "/vagrant/env3/lib/python3.5/site-packages/mypy/checker.py", line 416, in visit_file
    self.accept(d)
  File "/vagrant/env3/lib/python3.5/site-packages/mypy/checker.py", line 457, in accept
    typ = node.accept(self)
  File "/vagrant/env3/lib/python3.5/site-packages/mypy/nodes.py", line 531, in accept
    return visitor.visit_decorator(self)
  File "/vagrant/env3/lib/python3.5/site-packages/mypy/checker.py", line 1930, in visit_decorator
    self.check_incompatible_property_override(e)
  File "/vagrant/env3/lib/python3.5/site-packages/mypy/checker.py", line 1935, in check_incompatible_property_override
    for base in e.func.info.mro[1:]:
AttributeError: 'NoneType' object has no attribute 'mro'

*** INTERNAL ERROR ***
```

**Comment by gvanrossum** [comment]
Wow. That looks easy enough to fix.

**Comment by gvanrossum** [comment]
Fixed the crash. The error is easily silenced by putting `# type: ignore` on the `@property` line.
