### ISSUE TITLE
misc/upload-pypi.py errors when uploading wheel for platform emscripten_3_1_14_wasm32

### ISSUE THREAD

**Issue by svalentin** [python/mypy#14026]
When running `python3 misc/upload-pypi.py 0.990` there was an error when uploading wheel for platform emscripten_3_1_14_wasm32

```
Uploading mypy-0.990-cp310-cp310-win_amd64.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB • 00:00 • 274.7 MB/s
Uploading mypy-0.990-cp310-cp310-emscripten_3_1_14_wasm32.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB • 00:00 • 268.6 MB/s
WARNING  Error during upload. Retry with the --verbose option for more details.
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
         Binary wheel 'mypy-0.990-cp310-cp310-emscripten_3_1_14_wasm32.whl' has an unsupported platform tag 'emscripten_3_1_14_wasm32'.
Traceback (most recent call last):
  File "/home/svalentin/src/mypy/misc/upload-pypi.py", line 139, in <module>
    main()
  File "/home/svalentin/src/mypy/misc/upload-pypi.py", line 135, in main
    upload_to_pypi(args.version, args.dry_run)
  File "/home/svalentin/src/mypy/misc/upload-pypi.py", line 123, in upload_to_pypi
    upload_dist(dist, dry_run)
  File "/home/svalentin/src/mypy/misc/upload-pypi.py", line 103, in upload_dist
    subprocess.check_call(cmd)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[PosixPath('/tmp/tmp5173rirz/venv/bin/twine'), 'upload', PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990.tar.gz'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-py3-none-any.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp39-cp39-win_amd64.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp39-cp39-musllinux_1_1_x86_64.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp39-cp39-macosx_11_0_arm64.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp39-cp39-macosx_10_9_x86_64.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp39-cp39-macosx_10_9_universal2.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp38-cp38-win_amd64.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp38-cp38-musllinux_1_1_x86_64.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp38-cp38-macosx_11_0_arm64.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp38-cp38-macosx_10_9_universal2.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp38-cp38-macosx_10_9_x86_64.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp37-cp37m-win_amd64.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp37-cp37m-musllinux_1_1_x86_64.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp37-cp37m-macosx_10_9_x86_64.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp311-cp311-win_amd64.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp311-cp311-macosx_10_9_x86_64.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp310-cp310-win_amd64.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp310-cp310-emscripten_3_1_14_wasm32.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp310-cp310-macosx_11_0_arm64.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp310-cp310-musllinux_1_1_x86_64.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp311-cp311-macosx_11_0_arm64.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp310-cp310-macosx_10_9_universal2.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp311-cp311-macosx_10_9_universal2.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp311-cp311-musllinux_1_1_x86_64.whl'), PosixPath('/tmp/tmp8362thlv/dist/mypy-0.990-cp310-cp310-macosx_10_9_x86_64.whl')]' returned non-zero exit status 1.
```

**Comment by svalentin** [comment]
I'll get more time to look into this tomorrow. Just wanted to open this in case there's anything obvious I was missing.

**Comment by JelleZijlstra** [comment]
I think PyPI just doesn't support wasm wheels. We can simply skip this wheel I suppose.

**Comment by hauntsaninja** [comment]
cc @ethanhs

**Comment by JelleZijlstra** [comment]
Looks like we're missing some other wheels that would be expected though: https://pypi.org/project/mypy/0.990/#files (e.g. there is only 3.10 wheel, the previous release had 6). I'd recommend patching `upload-pypi.py` to drop the wasm wheels and re-run it to make sure we get all other wheels.

**Comment by svalentin** [comment]
Yeah, I saw we added wasm wheel in https://github.com/python/mypy/commit/11be37863683745ec2e3df4c15440cb1c7ba44d4
I just have to modify `upload-pypi.py` to have the option to skip some platforms. Right now it just tries to upload everything it finds.

**Comment by ethanhs** [comment]
Yes, sorry, I didn't think about this, Emscripten doesn't currently have a stable ABI, so you can't upload to PyPI yet. Skipping the upload of the WASM  wheel is definitely the correct thing to do here.

**Comment by svalentin** [comment]
Ok, I locally hacked `upload-pypi.py` to finish this release upload. Will make a proper PR later
