### ISSUE TITLE
0.990 internal error "IsADirectoryError" when not having __init__.py files

### ISSUE THREAD

**Issue by osteenbergen** [python/mypy#14046]
**Crash Report**

MyPy 0.981 was working fine, since update to latest 0.990 it crashes. Adding `__init__.py` to folders seems to solve it

**Traceback**

```
version: 0.990
Traceback (most recent call last):
  File "/home/osteenbergen/Documents/semiotic-iot/.tox/mypy/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "mypy/build.py", line 2067, in wrap_context
  File "mypy/build.py", line 2393, in finish_passes
  File "mypy/build.py", line 876, in report_file
  File "mypy/report.py", line 91, in file
  File "mypy/report.py", line 640, in on_file
  File "/usr/lib/python3.8/tokenize.py", line 392, in open
    buffer = _builtin_open(filename, 'rb')
IsADirectoryError: [Errno 21] Is a directory: 'tests/testresources/monitor'
```

**To Reproduce**

Folder structure
```
tests/example.py
```

example.py
```
print("Hello World!")
```

**Your Environment**

- Mypy version used: `0.990`
- Mypy command-line flags: `--config-file mypy.ini -p tests`
- Mypy configuration options from `mypy.ini` (and other config files):
```
[mypy]
check_untyped_defs = True
disallow_any_generics = True
disallow_incomplete_defs = True
disallow_subclassing_any = True
disallow_untyped_calls = True
disallow_untyped_decorators = True
disallow_untyped_defs = True
ignore_missing_imports = True
no_implicit_optional = True
no_implicit_reexport = True
show_error_codes = True
strict_equality = True
warn_redundant_casts = True
warn_return_any = True
warn_unused_configs = True
warn_unused_ignores = True

cobertura_xml_report = mypy_report
html_report = mypy_report
```
- Python version used: `3.8.13`
- Operating system and version: Ubuntu 20.04

**Comment by osteenbergen** [comment]
If i remove the report generation from the `mypy.ini` it works.

**Comment by hauntsaninja** [comment]
Thanks, similar to https://github.com/python/mypy/pull/13733

**Comment by hauntsaninja** [comment]
`--no-namespace-packages` is an alternative way to get unblocked
