### ISSUE TITLE
INTERNAL ERROR, AttributeError: 'ASTConverter' object has no attribute 'visit_Match'

### ISSUE THREAD

**Issue by albertino87** [python/mypy#14268]
Hi I cannot use mypy, i keep getting the same error.
I'm using python 3.10 32 bit with mypy 0.910. When I try to check the whole directory (mypy .) I get the error, but also if I check mypy main.py I get the same error

(C:\Users\u608771\Documents\py310_32) C:\Users\u608771\Documents\git\EN\engine-network-sap-rfc-tool>mypy . --show-traceback
.\EnSapScripts\sap_en\queriers\transactions.py: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.910
Traceback (most recent call last):
  File "C:\Users\u608771\Documents\py310_32\Scripts\mypy-script.py", line 9, in <module>
    sys.exit(console_entry())
  File "C:\Users\u608771\Documents\py310_32\lib\site-packages\mypy\__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "C:\Users\u608771\Documents\py310_32\lib\site-packages\mypy\main.py", line 87, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "C:\Users\u608771\Documents\py310_32\lib\site-packages\mypy\main.py", line 165, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "C:\Users\u608771\Documents\py310_32\lib\site-packages\mypy\build.py", line 179, in build
    result = _build(
  File "C:\Users\u608771\Documents\py310_32\lib\site-packages\mypy\build.py", line 254, in _build
    graph = dispatch(sources, manager, stdout)
  File "C:\Users\u608771\Documents\py310_32\lib\site-packages\mypy\build.py", line 2644, in dispatch
    graph = load_graph(sources, manager)
  File "C:\Users\u608771\Documents\py310_32\lib\site-packages\mypy\build.py", line 2802, in load_graph
    st = State(id=bs.module, path=bs.path, source=bs.text, manager=manager,
  File "C:\Users\u608771\Documents\py310_32\lib\site-packages\mypy\build.py", line 1888, in __init__
    self.parse_file()
  File "C:\Users\u608771\Documents\py310_32\lib\site-packages\mypy\build.py", line 2016, in parse_file
    with self.wrap_context():
  File "C:\Users\u608771\Documents\py310_32\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\u608771\Documents\py310_32\lib\site-packages\mypy\build.py", line 1955, in wrap_context
    yield
  File "C:\Users\u608771\Documents\py310_32\lib\site-packages\mypy\build.py", line 2046, in parse_file
    self.tree = manager.parse_file(self.id, self.xpath, source,
  File "C:\Users\u608771\Documents\py310_32\lib\site-packages\mypy\build.py", line 788, in parse_file
    tree = parse(source, path, id, self.errors, options=options)
  File "C:\Users\u608771\Documents\py310_32\lib\site-packages\mypy\parse.py", line 25, in parse
    return mypy.fastparse.parse(source,
  File "C:\Users\u608771\Documents\py310_32\lib\site-packages\mypy\fastparse.py", line 168, in parse
    ).visit(ast)
  File "C:\Users\u608771\Documents\py310_32\lib\site-packages\mypy\fastparse.py", line 329, in visit
    return visitor(node)
  File "C:\Users\u608771\Documents\py310_32\lib\site-packages\mypy\fastparse.py", line 496, in visit_Module
    body = self.fix_function_overloads(self.translate_stmt_list(mod.body, ismodule=True))
  File "C:\Users\u608771\Documents\py310_32\lib\site-packages\mypy\fastparse.py", line 367, in translate_stmt_list
    node = self.visit(stmt)
  File "C:\Users\u608771\Documents\py310_32\lib\site-packages\mypy\fastparse.py", line 329, in visit
    return visitor(node)
  File "C:\Users\u608771\Documents\py310_32\lib\site-packages\mypy\fastparse.py", line 509, in visit_FunctionDef
    return self.do_func_def(n)
  File "C:\Users\u608771\Documents\py310_32\lib\site-packages\mypy\fastparse.py", line 607, in do_func_def
    self.as_required_block(n.body, lineno),
  File "C:\Users\u608771\Documents\py310_32\lib\site-packages\mypy\fastparse.py", line 439, in as_required_block
    b = Block(self.fix_function_overloads(self.translate_stmt_list(stmts)))
  File "C:\Users\u608771\Documents\py310_32\lib\site-packages\mypy\fastparse.py", line 367, in translate_stmt_list
    node = self.visit(stmt)
  File "C:\Users\u608771\Documents\py310_32\lib\site-packages\mypy\fastparse.py", line 327, in visit
    visitor = getattr(self, method)
AttributeError: 'ASTConverter' object has no attribute 'visit_Match'
.\EnSapScripts\sap_en\queriers\transactions.py: : note: use --pdb to drop into pdb

**Comment by AlexWaygood** [comment]
Mypy 0.910 is quite an old version of mypy. Does the crash still occur if you upgrade to mypy 0.991?
