### ISSUE TITLE
AssertionError: ('numpy.ma.mrecords.MaskedArray', 'numpy.ma.MaskedArray')

### ISSUE THREAD

**Issue by igi-chris** [python/mypy#14300]
**Bug Report**

mypy hits an error when I try to run it on my codebase.

**To Reproduce**

I don't know why this error started happening. I was able to run mypy on this project, but then started seeing this error. I have tried recreating my venv, but still get errors.

**Actual Behavior**

> ml_app\plots\regression\residuals.py:1: error: Skipping analyzing "matplotlib.figure": module is installed, but missing library stubs or py.typed marker  [import]
ml_app\plots\regression\residuals.py:2: error: Skipping analyzing "seaborn": module is installed, but missing library stubs or py.typed marker  [import]
ml_app\plots\regression\residuals.py:3: error: Skipping analyzing "matplotlib.pyplot": module is installed, but missing library stubs or py.typed marker  [import]
ml_app\plots\regression\residuals.py:3: error: Skipping analyzing "matplotlib": module is installed, but missing library stubs or py.typed marker  [import]
ml_app\dtos\stored_models\stored_model.py:19: error: Skipping analyzing "sklearn.pipeline": module is installed, but missing library stubs or py.typed marker  [import]
ml_app\modelling\entities\model.py:6: error: Skipping analyzing "sklearn.pipeline": module is installed, but missing library stubs or py.typed marker  [import]
Traceback (most recent call last):
  File "C:\Users\ChrisProsser\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ChrisProsser\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\code\projects\IGI.ML.Server\.venv\Scripts\mypy.exe\__main__.py", line 7, in <module>
  File "D:\code\projects\IGI.ML.Server\.venv\lib\site-packages\mypy\__main__.py", line 15, in console_entry
    main()
  File "mypy\main.py", line 95, in main
  File "mypy\main.py", line 174, in run_build
  File "mypy\build.py", line 193, in build
  File "mypy\build.py", line 276, in _build
  File "mypy\build.py", line 2903, in dispatch
  File "mypy\build.py", line 3284, in process_graph
  File "mypy\build.py", line 3365, in process_fresh_modules
  File "mypy\build.py", line 2112, in fix_cross_refs
  File "mypy\fixup.py", line 53, in fixup_module
  File "mypy\fixup.py", line 115, in visit_symbol_table
AssertionError: ('numpy.ma.mrecords.MaskedArray', 'numpy.ma.MaskedArray')

**Your Environment**

Windows, virtualenv, requirement.txt:

> fastapi==0.88.0
htppx==0.23.1
joblib==1.2.0
matplotlib==3.6.2
mypy==0.991
numpy==1.23.5
openpyxl==3.0.10
pandas==1.5.2
pandas-stubs==1.5.2.221213
pydantic==1.10.2
python-multipart=0.0.5
requests==2.28.1
scikit-learn==1.2.0
seaborn==0.12.1
starlette==0.22.0
uvicorn==0.20.0

- Mypy version used: 0.991
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.10.5

**Comment by AlexWaygood** [comment]
It will be very difficult to debug this unless you're able to provide a [minimal example](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the crash.
