### ISSUE TITLE
Conflicting stubs cause AssertionError

### ISSUE THREAD

**Issue by jorants** [python/mypy#14589]
**Crash Report**

Installing both the newer `pandas-stubs` and depreciated `data-science-types` causes mypy to trow an `AsserionError`.  This might accidentally happen when upgrading. The error seems to sometimes persist after removing the later of the two, until the mypy cache is removed, but i could not reproduce this later.

**Traceback**

```
Traceback (most recent call last):
  File "/home/joran/.virtualenvs/mypytest/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/joran/.virtualenvs/mypytest/lib/python3.10/site-packages/mypy/__main__.py", line 15, in console_entry
    main()
  File "mypy/main.py", line 95, in main
  File "mypy/main.py", line 174, in run_build
  File "mypy/build.py", line 193, in build
  File "mypy/build.py", line 276, in _build
  File "mypy/build.py", line 2903, in dispatch
  File "mypy/build.py", line 3284, in process_graph
  File "mypy/build.py", line 3365, in process_fresh_modules
  File "mypy/build.py", line 2112, in fix_cross_refs
  File "mypy/fixup.py", line 53, in fixup_module
  File "mypy/fixup.py", line 111, in visit_symbol_table
  File "mypy/lookup.py", line 49, in lookup_fully_qualified
AssertionError: Cannot find component 'core' for 'numpy.ma.core.MaskedArray'
```

**To Reproduce**
In a clean virtual environment:
```bash
pip install mypy pandas pandas-stubs data-science-stubs
```
Then on a file only containing `import pandas as pd` run `mypy`.

**Your Environment**

- Mypy version used: 0.991
- Mypy command-line flags: --show-traceback
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.10.8
- Operating system and version: Manjaro linux, kernel 5.14.85

Pip freeze:
```
data-science-types==0.2.23
mypy==0.991
mypy-extensions==0.4.3
numpy==1.24.1
pandas==1.5.3
pandas-stubs==1.5.2.230105
python-dateutil==2.8.2
pytz==2022.7.1
six==1.16.0
tomli==2.0.1
types-pytz==2022.7.1.0
typing_extensions==4.4.0
```

**Extra info**

Before switching to a minimal testing environment I got a slightly different traceback in my full project that most likely is related:
```
Traceback (most recent call last):
  File "/home/joran/.cache/pypoetry/virtualenvs/XXX-8TWi15_n-py3.10/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/joran/.cache/pypoetry/virtualenvs/XXX-8TWi15_n-py3.10/lib/python3.10/site-packages/mypy/__main__.py", line 15, in console_entry
    main()
  File "mypy/main.py", line 95, in main
  File "mypy/main.py", line 174, in run_build
  File "mypy/build.py", line 193, in build
  File "mypy/build.py", line 276, in _build
  File "mypy/build.py", line 2903, in dispatch
  File "mypy/build.py", line 3284, in process_graph
  File "mypy/build.py", line 3365, in process_fresh_modules
  File "mypy/build.py", line 2112, in fix_cross_refs
  File "mypy/fixup.py", line 53, in fixup_module
  File "mypy/fixup.py", line 115, in visit_symbol_table
AssertionError: ('numpy.ma.mrecords.MaskedArray', 'numpy.ma.MaskedArray')

```

**Comment by Chouvic** [comment]
I encountered similar issue and we have pandas and scipy in our dependency. As [suggested in this answer](https://github.com/pytorch/pytorch/issues/53272#issue-822318590), removing mypy cache resolved it. `rm -rf .mypy_cache`

Is [issues/53272](https://github.com/pytorch/pytorch/issues/53272) not fixed fully?

- Run mypy without any issue
$ mypy --install-types --non-interactive --package=mypackage
Success: no issues found in 19 source files
- Install data science types
$ pip install data-science-types
- Run mypy again found "Cannot find component 'core'" issue.
$ mypy --install-types --non-interactive --package=mypackage
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\JPMC\DEV\TMP\projects\wcranonifa\mypackage\.venv\Lib\site-packages\mypy\__main__.py", line 15, in console_entry
    main()
  File "mypy\main.py", line 94, in main
  File "mypy\main.py", line 173, in run_build
  File "mypy\build.py", line 195, in build
  File "mypy\build.py", line 268, in _build
  File "mypy\build.py", line 2927, in dispatch
  File "mypy\build.py", line 3318, in process_graph
  File "mypy\build.py", line 3399, in process_fresh_modules
  File "mypy\build.py", line 2114, in fix_cross_refs
  File "mypy\fixup.py", line 52, in fixup_module
  File "mypy\fixup.py", line 121, in visit_symbol_table
  File "mypy\lookup.py", line 49, in lookup_fully_qualified
AssertionError: Cannot find component 'core' for 'numpy.ma.core.MaskedArray'
```

**Comment by hauntsaninja** [comment]
I could not reproduce OP's crash with mypy 1.5.1. I think Chouvic would need to provide more detail, e.g. maybe a script that reliably reproduces.
