### ISSUE TITLE
Erroneous AttributeError

### ISSUE THREAD

**Issue by r-wells** [python/mypy#14703]
**Bug Report**

I have an `AttributeError` that is getting flagged when I try to run my `typing` script, and it doesn't seem to be related to any code changes I have.

The full error is:

```
AttributeError: attribute '_fullname' of 'TypeInfo' undefined
```

And the trace is:

```
Traceback (most recent call last):
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/myenv-uKq6NgtC-py3.9/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/myenv-uKq6NgtC-py3.9/lib/python3.9/site-packages/mypy/__main__.py", line 12, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 96, in main
  File "mypy/main.py", line 173, in run_build
  File "mypy/build.py", line 180, in build
  File "mypy/build.py", line 256, in _build
  File "mypy/build.py", line 2717, in dispatch
  File "mypy/build.py", line 3048, in process_graph
  File "mypy/build.py", line 3165, in process_stale_scc
  File "mypy/build.py", line 2308, in write_cache
  File "mypy/build.py", line 1490, in write_cache
  File "mypy/nodes.py", line 334, in serialize
  File "mypy/nodes.py", line 3330, in serialize
  File "mypy/nodes.py", line 3267, in serialize
  File "mypy/nodes.py", line 941, in serialize
  File "mypy/types.py", line 1386, in serialize
  File "mypy/types.py", line 541, in serialize
  File "mypy/types.py", line 984, in serialize
  File "mypy/nodes.py", line 2642, in fullname
```

**To Reproduce**

I'm not sure how to tell you to reproduce this except to maybe run poetry in a project with mypy with the versions I have listed above

**Expected Behavior**

I would expect it to tell me where the typing flag is instead of throwing in the `mypy` `__main__` file

**Actual Behavior**

Listed above

**Your Environment**

- Mypy version used: `0.931`
- Mypy command-line flags: 
```
DEFAULT="my-project/ tests/ scripts/"

mypy --ignore-missing-imports ${@:-$DEFAULT}
```
- Mypy configuration options from `mypy.ini` (and other config files):
No `mypy.ini` but I am using Poetry version `1.2.2`

`setup.cfg`
```
[mypy]
disallow_untyped_defs = True
strict_optional = True
```

- Python version used: 3.9.13

**Comment by hauntsaninja** [comment]
Update your mypy, 0.931 is very old and we've fixed issues that could cause this
