### ISSUE TITLE
Crash when using incremental mode

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#1482]
`mypy -i` crashed when type checking this program for the second time:

```
from os import path
1 + ''
```

Here's the traceback:

```
Traceback (most recent call last):
  File "scripts/mypy", line 6, in <module>
    main(__file__)
  File "/home/jukka/src/mypy/mypy/main.py", line 54, in main
    res = type_check_only(sources, bin_dir, options)
  File "/home/jukka/src/mypy/mypy/main.py", line 102, in type_check_only
    python_path=options.python_path)
  File "/home/jukka/src/mypy/mypy/build.py", line 209, in build
    dispatch(sources, manager)
  File "/home/jukka/src/mypy/mypy/build.py", line 1255, in dispatch
    process_graph(graph, manager)
  File "/home/jukka/src/mypy/mypy/build.py", line 1386, in process_graph
    process_stale_scc(graph, scc)
  File "/home/jukka/src/mypy/mypy/build.py", line 1414, in process_stale_scc
    graph[id].semantic_analysis_pass_three()
  File "/home/jukka/src/mypy/mypy/build.py", line 1226, in semantic_analysis_pass_three
    self.manager.semantic_analyzer_pass3.visit_file(self.tree, self.xpath)
  File "/home/jukka/src/mypy/mypy/semanal.py", line 2428, in visit_file
    self.accept(file_node)
  File "/home/jukka/src/mypy/mypy/semanal.py", line 2433, in accept
    node.accept(self)
  File "/home/jukka/src/mypy/mypy/nodes.py", line 194, in accept
    return visitor.visit_mypy_file(self)
  File "/home/jukka/src/mypy/mypy/traverser.py", line 34, in visit_mypy_file
    d.accept(self)
  File "/home/jukka/src/mypy/mypy/nodes.py", line 650, in accept
    return visitor.visit_class_def(self)
  File "/home/jukka/src/mypy/mypy/semanal.py", line 2450, in visit_class_def
    self.analyze(type)
  File "/home/jukka/src/mypy/mypy/semanal.py", line 2527, in analyze
    type.accept(analyzer)
  File "/home/jukka/src/mypy/mypy/types.py", line 290, in accept
    return visitor.visit_instance(self)
  File "/home/jukka/src/mypy/mypy/typeanal.py", line 327, in visit_instance
    if not satisfies_upper_bound(arg, TypeVar.upper_bound):
  File "/home/jukka/src/mypy/mypy/subtypes.py", line 73, in satisfies_upper_bound
    return isinstance(a, Void) or is_subtype(a, upper_bound)
  File "/home/jukka/src/mypy/mypy/subtypes.py", line 49, in is_subtype
    return left.accept(SubtypeVisitor(right, type_parameter_checker))
  File "/home/jukka/src/mypy/mypy/types.py", line 340, in accept
    return visitor.visit_type_var(self)
  File "/home/jukka/src/mypy/mypy/subtypes.py", line 137, in visit_type_var
    return is_subtype(left.upper_bound, self.right)
  File "/home/jukka/src/mypy/mypy/subtypes.py", line 49, in is_subtype
    return left.accept(SubtypeVisitor(right, type_parameter_checker))
  File "/home/jukka/src/mypy/mypy/types.py", line 290, in accept
    return visitor.visit_instance(self)
  File "/home/jukka/src/mypy/mypy/subtypes.py", line 111, in visit_instance
    if left.type.fallback_to_any:
AttributeError: 'NoneType' object has no attribute 'fallback_to_any'

*** INTERNAL ERROR ***

typeshed/stdlib/3/os/__init__.pyi:1: error: Internal error -- please report a bug at https://github.com/python/mypy/issues

NOTE: you can use "mypy --pdb ..." to drop into the debugger when this happens.
```

**Comment by gvanrossum** [comment]
The cause is 1c9b3b9fc869941d5ce1273bd35d174f0a38648b
