### ISSUE TITLE
`import` statements under a parametrised protocol results in a crash

### ISSUE THREAD

**Issue by XM-Helico** [python/mypy#14889]
**Crash Report & Reproduction**

The following snippet will cause a crash:

```python
import typing as tp

T = tp.TypeVar("T")

class Proto(tp.Protocol[T]):
    import urllib
```

```shell
**Traceback**
<file>: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.1.1
Traceback (most recent call last):
  File "mypy/checker.py", line 582, in accept
  File "mypy/nodes.py", line 1123, in accept
  File "mypy/checker.py", line 2219, in visit_class_def
  File "mypy/checker.py", line 2403, in check_protocol_variance
  File "mypy/subtypes.py", line 177, in is_subtype
  File "mypy/subtypes.py", line 336, in _is_subtype
  File "mypy/types.py", line 1355, in accept
  File "mypy/subtypes.py", line 603, in visit_instance
  File "mypy/subtypes.py", line 1041, in is_protocol_implementation
AssertionError: 
```

No issues happen when the protocol isn't parameterised.

**Your Environment**

- Mypy version used: 1.1.1 and master ([mypy-play.net](https://mypy-play.net/?mypy=master&python=3.11&gist=9cf81f5ade3dcbeca6d9980676f6972d))
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.10 and 3.11

**Comment by tyralla** [comment]
I guess the imported module is not supposed to be an "official" member of the protocol, should it? (And that [PEP 544](https://peps.python.org/pep-0544/) does not mention such cases?)

If so, one could silently ignore this member, which should be little effort.

**Comment by ilevkivskyi** [comment]
Yeah, I am going to simply ignore all imports.
