### ISSUE TITLE
[stubtest] Support `@final` decorator on methods as well

### ISSUE THREAD

**Issue by sobolevn** [python/mypy#14924]
After https://github.com/python/mypy/pull/14922 is merged, I think we can also add a check that this source code has correct stubs:

```python
class A:
    @final
    def method(self): ...
```

Right now stubs do not have to add `@final` decorator, `stubtest` will allow both versions.

**Comment by sobolevn** [comment]
After working on for a short time, I've noticed several problems:

1. `@property` is not supported
2. `@staticmethod` is not supported
3. `@classmethod` is not supported

This happens, because `__final__` cannot be set on `property` objects:

See:
```python
>>> def my_final(f):
...    f.__final__ = True
...    return f
```

```python
>>> class P:
...    @my_final
...    @property
...    def p(self) -> int: ...
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in P
  File "<stdin>", line 2, in my_final
AttributeError: 'property' object has no attribute '__final__'
```

But, `@classmethod` and `@staticmethod` actually change the object when using `getattr`, this is why this happens:

```python
>>> class St:
...   @my_final
...   @staticmethod
...   def m() -> None: ...
... 
>>> St.m
<function St.m at 0x109eeb400>
>>> St.m.__final__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'function' object has no attribute '__final__'. Did you mean: '__init__'?

>>> St.__dict__['m']
<staticmethod(<function St.m at 0x109eeb400>)>
>>> St.__dict__['m'].__final__
True
```

This needs:
1. Special-casing properties. They cannot be supported right now
2. Magic `getattr_static` to get methods from the class

This is quite complicated for a Sunday's evening project, so - please feel free to continue it if someone finds it useful.

**Comment by AlexWaygood** [comment]
To update on the status here: following #14951, this is now fully implemented _except_ for cases where the method is overloaded in the stub (implementing that is blocked by #14950).
