### ISSUE TITLE
AssertionError: Internal error: too many class plugin hook passes

### ISSUE THREAD

**Issue by mementum** [python/mypy#15004]
**Crash Report**

See the traceback.

**Traceback**

```
Traceback (most recent call last):
  File "D:\dro\bin\WPy64-31090\python-3.10.9.amd64\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\dro\bin\WPy64-31090\python-3.10.9.amd64\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\dro\bin\WPy64-31090\python-3.10.9.amd64\scripts\mypy.exe\__main__.py", line 7, in <module>
  File "D:\dro\bin\WPy64-31090\python-3.10.9.amd64\lib\site-packages\mypy\__main__.py", line 15, in console_entry
    main()
  File "mypy\main.py", line 95, in main
  File "mypy\main.py", line 174, in run_build
  File "mypy\build.py", line 194, in build
  File "mypy\build.py", line 277, in _build
  File "mypy\build.py", line 2923, in dispatch
  File "mypy\build.py", line 3320, in process_graph
  File "mypy\build.py", line 3415, in process_stale_scc
  File "mypy\semanal_main.py", line 99, in semantic_analysis_for_scc
  File "mypy\semanal_main.py", line 429, in apply_class_plugin_hooks
AssertionError: Internal error: too many class plugin hook passes
```

**To Reproduce**

```python
#!/usr/bin/env python
# -*- coding: utf-8; py-indent-offset:4 -*-
###############################################################################
from __future__ import annotations
from dataclasses import asdict, dataclass, field
from decimal import Context, Decimal, Inexact
from typing import ClassVar, Protocol


DecimalPlus = Decimal | str | int | float


@dataclass
class TargetSettings(Protocol):
    max: DecimalPlus
    min: DecimalPlus
    inc: DecimalPlus
    precision: int

    PLACES: Decimal = field(init=False, repr=False)
    INEXACT: ClassVar[Context] = Context(traps=[Inexact])

    def __post_init__(self) -> None:
        self.PLACES = PLACES = Decimal(10) ** -self.precision

        self.min = Decimal(self.min).quantize(PLACES)
        self.max = Decimal(self.max).quantize(PLACES)
        self.inc = Decimal(self.inc).quantize(PLACES)

    def is_valid(self, val: DecimalPlus) -> bool:
        try:
            val = Decimal(val).quantize(self.PLACES, context=self.INEXACT)
        except Inexact:
            return False  # more decimal places than allowed

        # mypy does not know attributes are Decimals at this stage
        if not (self.min <= val <= self.max):  # type: ignore
            return False

        return True  # all checks passed

```

**Your Environment**

- Mypy version used: 1.1.1
- Mypy command-line flags: `None`
- Mypy configuration options from `mypy.ini` (and other config files): `None`
- Python version used: `3.10.9`
- Operating system and version: `Windows 11 22621.1413`

**Additional Comment**

Let me say that I do believe that the concept of static type checking of `Union` is broken (again: *the concept*). In my very humble opinion as user, if I do declare something as a `Union` (either with the keyword or the `|` operator), `mypy` must believe that when the time comes, the variable/attribute declared as a Union, will contain one of the types.

Reporting errors like 
```
error: Unsupported operand types for <= ("Decimal" and "str")  [operator]
```

when the `Union` contains `Union[Decimal, str, int, float]` is in my very humble opinion: **wrong**. Such an error can be reported during *runtime*, but not during static analysis, because `mypy` has no way of knowing what the type at that stage contains. Reporting a "warning" would be ok. Reporting an "error" is an error itself.

No, as a user I am not in the mood of adding `cast` here and there and here-there to pollute the code, hence the need to add a `# type: ignore` to silence `mypy`.

**Comment by JelleZijlstra** [comment]
Here's a smaller reproducer:

```python
from dataclasses import dataclass
from typing import Protocol

@dataclass
class TargetSettings(Protocol):
    min: int

    def __post_init__(self) -> None:
        self.min = int(self.min)
```

Combining `@dataclass` and `Protocol` is a strange thing to do and I'm not sure it should be allowed. However, mypy should not crash.

**Comment by mementum** [comment]
I do understand that `@dataclass` may make no sense for a `Protocol`, but this is, imho, bound to happen again, assuming typing becomes the mainstream development path.

How it happened in this case:

  - A `dataclass` ended up being used by a secondary class class and `mypy` was complaining that the referenced `dataclass` didn't have attribute X. Because it was defined later in the code.
  - The `dataclass` vital parts were taken out and put into a `Protocol` defined before the secondary class which means the secondary class can reference the protocol and be happy
  - Because the final class is a `dataclass` it seemed sensible to also have the `Protocol` class being decorated as a `dataclass`

**Comment by WISEPLAT** [comment]
> I do understand that `@dataclass` may make no sense for a `Protocol`, but this is, imho, bound to happen again, assuming typing becomes the mainstream development path.
> 
> How it happened in this case:
> 
> * A `dataclass` ended up being used by a secondary class class and `mypy` was complaining that the referenced `dataclass` didn't have attribute X. Because it was defined later in the code.
> * The `dataclass` vital parts were taken out and put into a `Protocol` defined before the secondary class which means the secondary class can reference the protocol and be happy
> * Because the final class is a `dataclass` it seemed sensible to also have the `Protocol` class being decorated as a `dataclass`

Hello! Why your project backtrader is stopped? It is so great!!!! ....

**Comment by mementum** [comment]
One of the reasons to dive deep into `typing` is to modernize `backtrader` with `typing` and also add additional features from more modern Python.

Python `2.7` was still trendy and full in scope back in 2015.

**Comment by WISEPLAT** [comment]
> 

But for now - it's functionality is great to create live strategies in production. Just continue to develop this great project and implement new features.
Just for example, here is https://github.com/cia76/ 3! three libraries to connect Backtrader with 3 live brokers to real live trading!!, and I have implemented its connection to Binance!!
You have created a great job! Please don't stop the development of this project. 
**Please don't think about anything))), just continue to develop new features and implement them in Backtrader!**
