### ISSUE TITLE
INTERNAL ERROR when running mypy on django app code

### ISSUE THREAD

**Issue by marcofalcioni** [python/mypy#15044]
**Crash Report**

I upgraded mypy and am running it against an existing Django codebase. This error occurred:

**Traceback**

```
platform_app/experiments/models/well.py:523: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.3.0+dev.cc7b062026311287c91b226960ee0ad2e447a7ea
Traceback (most recent call last):
  File "/Users/marco2/miniconda3/envs/rosetta/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/Users/marco2/miniconda3/envs/rosetta/lib/python3.9/site-packages/mypy/__main__.py", line 15, in console_entry
    main()
  File "/Users/marco2/miniconda3/envs/rosetta/lib/python3.9/site-packages/mypy/main.py", line 95, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "/Users/marco2/miniconda3/envs/rosetta/lib/python3.9/site-packages/mypy/main.py", line 174, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/Users/marco2/miniconda3/envs/rosetta/lib/python3.9/site-packages/mypy/build.py", line 194, in build
    result = _build(
  File "/Users/marco2/miniconda3/envs/rosetta/lib/python3.9/site-packages/mypy/build.py", line 277, in _build
    graph = dispatch(sources, manager, stdout)
  File "/Users/marco2/miniconda3/envs/rosetta/lib/python3.9/site-packages/mypy/build.py", line 2930, in dispatch
    process_graph(graph, manager)
  File "/Users/marco2/miniconda3/envs/rosetta/lib/python3.9/site-packages/mypy/build.py", line 3328, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/Users/marco2/miniconda3/envs/rosetta/lib/python3.9/site-packages/mypy/build.py", line 3423, in process_stale_scc
    mypy.semanal_main.semantic_analysis_for_scc(graph, scc, manager.errors)
  File "/Users/marco2/miniconda3/envs/rosetta/lib/python3.9/site-packages/mypy/semanal_main.py", line 93, in semantic_analysis_for_scc
    process_top_levels(graph, scc, patches)
  File "/Users/marco2/miniconda3/envs/rosetta/lib/python3.9/site-packages/mypy/semanal_main.py", line 220, in process_top_levels
    deferred, incomplete, progress = semantic_analyze_target(
  File "/Users/marco2/miniconda3/envs/rosetta/lib/python3.9/site-packages/mypy/semanal_main.py", line 349, in semantic_analyze_target
    analyzer.refresh_partial(
  File "/Users/marco2/miniconda3/envs/rosetta/lib/python3.9/site-packages/mypy/semanal.py", line 598, in refresh_partial
    self.refresh_top_level(node)
  File "/Users/marco2/miniconda3/envs/rosetta/lib/python3.9/site-packages/mypy/semanal.py", line 609, in refresh_top_level
    self.accept(d)
  File "/Users/marco2/miniconda3/envs/rosetta/lib/python3.9/site-packages/mypy/semanal.py", line 6269, in accept
    node.accept(self)
  File "/Users/marco2/miniconda3/envs/rosetta/lib/python3.9/site-packages/mypy/nodes.py", line 1295, in accept
    return visitor.visit_assignment_stmt(self)
  File "/Users/marco2/miniconda3/envs/rosetta/lib/python3.9/site-packages/mypy/semanal.py", line 2803, in visit_assignment_stmt
    self.apply_dynamic_class_hook(s)
  File "/Users/marco2/miniconda3/envs/rosetta/lib/python3.9/site-packages/mypy/semanal.py", line 3145, in apply_dynamic_class_hook
    hook(DynamicClassDefContext(call, lval.name, self))
  File "/Users/marco2/miniconda3/envs/rosetta/lib/python3.9/site-packages/mypy_django_plugin/transformers/managers.py", line 24, in create_new_manager_class_from_from_queryset_method
    new_manager_info = semanal_api.basic_new_typeinfo(ctx.name,
TypeError: basic_new_typeinfo() missing 1 required positional argument: 'line'
platform_app/experiments/models/well.py:523: : note: use --pdb to drop into pdb
```

**To Reproduce**

The error occurs when analyzing this line of code:

```
MyModelManager = MyBaseModelManager.from_queryset(MyModelQuerySet)
```

**Your Environment**

- Mypy version used: version: 1.3.0+dev.cc7b062026311287c91b226960ee0ad2e447a7ea
- Mypy command-line flags: mypy --show-traceback <app folder>
- Mypy configuration options from `mypy.ini` (and other config files):
- [mypy]
```
plugins =  mypy_django_plugin.main,mypy_drf_plugin.main,numpy.typing.mypy_plugin

ignore_missing_imports = True

[mypy-*.migrations.*]
ignore_errors = True

[mypy_django_plugin]
ignore_missing_model_attributes = True

[mypy.plugins.django-stubs]
django_settings_module = project.settings
```
- Python version used: 3.9
- Operating system and version: Mac OSX (apple silicon M2) Ventura 13.2.1

**Comment by marcofalcioni** [comment]
It seems that adding `, line=ctx.call.line` At line 24 of `managers.py` will prevent the error.

**Comment by crypto-rizzo** [comment]
@marcofalcioni can you elaborate on solution? just hit same issue

**Comment by hauntsaninja** [comment]
Thanks, this is best reported (and fixed) at https://github.com/typeddjango/django-stubs

**Comment by marcofalcioni** [comment]
https://github.com/typeddjango/django-stubs/issues/1434
