### ISSUE TITLE
SQLAlchemy declarative_mixin decorator crashing mypy

### ISSUE THREAD

**Issue by wanaryytel** [python/mypy#15063]
**Crash Report**

`mypy` 1.0.0 crashes when the sqlalchemy `declarative_mixin` decorator is used on a class as specified in the docs https://docs.sqlalchemy.org/en/14/orm/extensions/mypy.html

**Traceback**

```
version: 1.0.0
Traceback (most recent call last):
  File "mypy/semanal.py", line 6210, in accept
  File "mypy/nodes.py", line 1133, in accept
  File "mypy/semanal.py", line 1545, in visit_class_def
  File "mypy/semanal.py", line 1625, in analyze_class
  File "mypy/semanal.py", line 1652, in analyze_class_body_common
  File "mypy/semanal.py", line 1721, in apply_class_plugin_hooks
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/ext/mypy/plugin.py", line 247, in _declarative_mixin_hook
    decl_class.scan_declarative_assignments_and_apply_types(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 96, in scan_declarative_assignments_and_apply_types
    _scan_declarative_assignment_stmt(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/ext/mypy/decl_class.py", line 459, in _scan_declarative_assignment_stmt
    python_type_for_type = infer.infer_type_from_right_hand_nameexpr(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/ext/mypy/infer.py", line 52, in infer_type_from_right_hand_nameexpr
    python_type_for_type = _infer_type_from_decl_column(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/ext/mypy/infer.py", line 404, in _infer_type_from_decl_column
    python_type_for_type = extract_python_type_from_typeengine(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/ext/mypy/infer.py", line 556, in extract_python_type_from_typeengine
    return get_proper_type(type_engine.args[-1])
IndexError: tuple index out of range
```

**To Reproduce**

Dumbed down minimal example that crashes:

```
from sqlalchemy import Column, DateTime
from sqlalchemy.orm import declarative_mixin


@declarative_mixin
class CreatedUpdatedMixin:
    updated_on = Column(DateTime(timezone=True), index=True)
```

This crashes the same way (more similar to what's in SQLA docs):
```
@declarative_mixin
class CreatedUpdatedMixin:
    @declared_attr
    def updated_at(cls) -> Column[DateTime]:
        return Column(DateTime(timezone=True), index=True)
```

**Your Environment**

- Mypy version used: 1.0.0
- types-Flask-SQLAlchemy: 2.5.9.3
- sqlalchemy[mypy]: 1.4.46
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): 
 ```
python_version = 3.10
plugins = mypy_django_plugin.main,numpy.typing.mypy_plugin,sqlalchemy.ext.mypy.plugin
strict = True
warn_unreachable = True
```
- Python version used: 3.10.8
- Operating system and version: EndeavourOS

**Comment by AlexWaygood** [comment]
The traceback indicates that this is an issue with Sqlalchemy's third-party mypy plugin rather than mypy itself, so you'll need to report the issue over at the sqlalchemy repo.

When reporting the issue at sqlalchemy, it might be useful for them if you could confirm that the issue also occurs when you're using the latest version of mypy (v1.2.0).
