### ISSUE TITLE
Daemon mode crashes mypy when running multiple checks in parallel

### ISSUE THREAD

**Issue by Ryang20718** [python/mypy#15078]
**Crash Report**
We're using a tool called trunk to call mypy, however because daemon mode is much faster, we were trying this feature out. however it seems that if we were to call dmypy the same way we were to call mypy, it fails.

**Traceback**

```

Daemon crashed!
Traceback (most recent call last):
  File "mypy/dmypy_server.py", line 230, in serve
  File "mypy/dmypy_server.py", line 273, in run_command
  File "mypy/dmypy_server.py", line 332, in cmd_run
  File "mypy/dmypy_server.py", line 394, in check
  File "mypy/dmypy_server.py", line 569, in fine_grained_increment_follow_imports
  File "mypy/server/update.py", line 245, in update
  File "mypy/server/update.py", line 328, in update_one
  File "mypy/server/update.py", line 413, in update_module
  File "mypy/server/update.py", line 804, in propagate_changes_using_dependencies
RuntimeError: Max number of iterations (1000) reached (endless loop?)
```

**To Reproduce**
Create a bash script that loops through a dir and execute dmypy on all python files in that dir
for file in tmp/*.py ; do dmypy run ${file} -- --use-fine-grained-cache --follow-imports=normal & done

python 3.10.7
mypy 0.960
OS: linux ubuntu

**Comment by Ryang20718** [comment]
although this is documented here: `Each mypy daemon process supports one user and one set of source files, and it can only process one type checking request at a time. You can run multiple mypy daemon processes to type check multiple repositories.`

Would be nice if `dmypy` had some sort of queueing mechanism when multiple processes are spun up

**Comment by datalogics-kam** [comment]
@Ryang20718 it says closed as completed. Was something fixed that made this work better?

**Comment by Ryang20718** [comment]
woops smashed the wrong button
