### ISSUE TITLE
Crash with bad encoding

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#1521]
When processing a large number of files, if a single file has a bad encoding, mypy crashes instead of flagging an error and continuing:
```
9.796:LOG:  Parsing Lib/test/bad_coding.py (test.bad_coding)
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 6, in <module>
    main(__file__)
  File "/usr/local/lib/python3.2/site-packages/mypy/main.py", line 54, in main
    res = type_check_only(sources, bin_dir, options)
  File "/usr/local/lib/python3.2/site-packages/mypy/main.py", line 102, in type_check_only
    python_path=options.python_path)
  File "/usr/local/lib/python3.2/site-packages/mypy/build.py", line 209, in build
    dispatch(sources, manager)
  File "/usr/local/lib/python3.2/site-packages/mypy/build.py", line 1253, in dispatch
    graph = load_graph(sources, manager)
  File "/usr/local/lib/python3.2/site-packages/mypy/build.py", line 1268, in load_graph
    st = State(id=bs.module, path=bs.path, source=bs.text, manager=manager)
  File "/usr/local/lib/python3.2/site-packages/mypy/build.py", line 1040, in __init__
    self.parse_file()
  File "/usr/local/lib/python3.2/site-packages/mypy/build.py", line 1151, in parse_file
    self.tree = manager.parse_file(self.id, self.xpath, source)
  File "/usr/local/lib/python3.2/contextlib.py", line 66, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.2/site-packages/mypy/build.py", line 1105, in wrap_context
    yield
  File "/usr/local/lib/python3.2/site-packages/mypy/build.py", line 1144, in parse_file
    source = read_with_python_encoding(self.path, manager.pyversion)
  File "/usr/local/lib/python3.2/site-packages/mypy/build.py", line 640, in read_with_python_encoding
    return source_bytearray.decode(encoding)
LookupError: unknown encoding: uft-8

*** INTERNAL ERROR ***

Lib/test/bad_coding.py: error: Internal error -- please report a bug at https://github.com/python/mypy/issues
```

**Comment by margaret** [comment]
From my understanding, just catching the `LookupError` and raising a `CompileError` should fix this since the `BuildManager` object will collect those instead of crashing. Should I check for the `LookupError` separately or group it in here with the [ except `UnicodeDecodeError`](https://github.com/python/mypy/blob/master/mypy/build.py#L1218)? I think it makes sense to have the same "can't decode file" mypy message.

**Comment by margaret** [comment]
I talked to Greg and we decided that since raising a `LookupError` is weirdly vague, I'm just going to catch the `LookupError` in `read_with_python_encoding` and re-raise it as a `UnicodeDecodeError`.

**Comment by gvanrossum** [comment]
Sounds right!

**Comment by margaret** [comment]
Actually, I'm not sure raising a `UnicodeDecodeError` here is correct, since files could be using a different valid encoding. Raising a `UnicodeDecodeError` [requires specifying](https://coderwall.com/p/stzy9w/raising-unicodeencodeerror-and-unicodedecodeerror-manually-for-testing-purposes) the exact position of the invalid character anyway, which doesn't make sense if it couldn't even read the file at all. 

Should I go back to catching the `LookupError` together with the `UnicodeDecodeError`?

**Comment by gvanrossum** [comment]
I recommend not over thinking it and just doing the first thing that works.
😃

--Guido (mobile)
