### ISSUE TITLE
RuntimeError with Iterator input

### ISSUE THREAD

**Issue by berdario** [python/mypy#1572]
from itertools import groupby
    from typing import Iterator, TypeVar, Callable, Tuple, Any
    
    X = TypeVar('X')
    Key = TypeVar('Key')
    def sorted_groupby(sequence: Iterator[X], key: Callable[[X], Key]) -> Iterator[Tuple[Key, Iterator[X]]]:
        return groupby(sorted(sequence, key=key), key=key)
    
    def foo() -> Any:
        baz = next(sorted_groupby([1], key=lambda x: x))

I know that `Iterator` is not the best/correct choice for the type of `sequence` (and the same problem doesn't happen with `Iterable`), but I get the following stacktrace with mypy 0.4.1

    Traceback (most recent call last):
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/bin/.mypy-wrapped", line 7, in <module>
        main(__file__)
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/main.py", line 54, in main
        res = type_check_only(sources, bin_dir, options)
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/main.py", line 102, in type_check_only
        python_path=options.python_path)
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/build.py", line 209, in build
        dispatch(sources, manager)
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/build.py", line 1255, in dispatch
        process_graph(graph, manager)
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/build.py", line 1386, in process_graph
        process_stale_scc(graph, scc)
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/build.py", line 1416, in process_stale_scc
        graph[id].type_check()
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/build.py", line 1235, in type_check
        manager.type_checker.visit_file(self.tree, self.xpath)
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/checker.py", line 419, in visit_file
        self.accept(d)
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/checker.py", line 460, in accept
        typ = node.accept(self)
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/nodes.py", line 462, in accept
        return visitor.visit_func_def(self)
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/checker.py", line 573, in visit_func_def
        self.check_func_item(defn, name=defn.name())
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/checker.py", line 631, in check_func_item
        self.check_func_def(defn, typ, name)
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/checker.py", line 739, in check_func_def
        self.accept_in_frame(item.body)
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/checker.py", line 475, in accept_in_frame
        answer = self.accept(node, type_context)
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/checker.py", line 460, in accept
        typ = node.accept(self)
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/nodes.py", line 715, in accept
        return visitor.visit_block(self)
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/checker.py", line 1132, in visit_block
        self.accept(s)
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/checker.py", line 460, in accept
        typ = node.accept(self)
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/nodes.py", line 753, in accept
        return visitor.visit_assignment_stmt(self)
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/checker.py", line 1141, in visit_assignment_stmt
        self.check_assignment(s.lvalues[-1], s.rvalue, s.type is None)
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/checker.py", line 1192, in check_assignment
        rvalue)
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/checker.py", line 1424, in infer_variable_type
        elif not is_valid_inferred_type(init_type):
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/checker.py", line 2549, in is_valid_inferred_type
        if not is_valid_inferred_type(item):
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/checker.py", line 2541, in is_valid_inferred_type
        if is_same_type(typ, NoneTyp()):
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/sametypes.py", line 27, in is_same_type
        return left.accept(SameTypeVisitor(right))
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/types.py", line 244, in accept
        return visitor.visit_erased_type(self)
      File "/nix/store/czly6jrafckfvwm9mjc6wvandc2ddwi9-python3.5-mypy-lang-0.4.1/lib/python3.5/site-packages/mypy/sametypes.py", line 74, in visit_erased_type
        raise RuntimeError()
    RuntimeError: 
    
    *** INTERNAL ERROR ***

**Comment by kirbyfan64** [comment]
Smaller test case:

```python
from typing import Iterator, TypeVar, Callable, Any

X = TypeVar('X')

def f(x: Callable[[X], Any]) -> Iterator[X]: pass
def g(x: Iterator[X]) -> X: pass
bax = g(f(lambda x: x))
```

**Comment by rwbarton** [comment]
Even more reduced:
```py
from typing import TypeVar, Callable

X = TypeVar('X')

def f(x: Callable[[X], X]) -> X: pass
bax = f(lambda x: x)
```
