### ISSUE TITLE
exec with --py2 --fast-parser crashes

### ISSUE THREAD

**Issue by sharmaeklavya2** [python/mypy#1577]
`exec` statements don't work when both `--py2` and `--fast-parser` are specified.

Both `mypy --py2 --fast-parser -c 'exec("print(\"hello\")")'` and
`mypy --py2 --fast-parser -c 'exec "print(\"hello\")"'` make mypy crash.

```
$ mypy --py2 --fast-parser -c 'exec("print(\"hello\")")'
Traceback (most recent call last):
  File "/mnt/Code/git_repos/forked/mypy-zvenv3/bin/mypy", line 6, in <module>
    main(__file__)
  File "/mnt/Code/git_repos/forked/mypy-zvenv3/lib/python3.4/site-packages/mypy/main.py", line 54, in main
    res = type_check_only(sources, bin_dir, options)
  File "/mnt/Code/git_repos/forked/mypy-zvenv3/lib/python3.4/site-packages/mypy/main.py", line 102, in type_check_only
    python_path=options.python_path)
  File "/mnt/Code/git_repos/forked/mypy-zvenv3/lib/python3.4/site-packages/mypy/build.py", line 209, in build
    dispatch(sources, manager)
  File "/mnt/Code/git_repos/forked/mypy-zvenv3/lib/python3.4/site-packages/mypy/build.py", line 1325, in dispatch
    process_graph(graph, manager)
  File "/mnt/Code/git_repos/forked/mypy-zvenv3/lib/python3.4/site-packages/mypy/build.py", line 1456, in process_graph
    process_stale_scc(graph, scc)
  File "/mnt/Code/git_repos/forked/mypy-zvenv3/lib/python3.4/site-packages/mypy/build.py", line 1482, in process_stale_scc
    graph[id].semantic_analysis()
  File "/mnt/Code/git_repos/forked/mypy-zvenv3/lib/python3.4/site-packages/mypy/build.py", line 1292, in semantic_analysis
    self.manager.semantic_analyzer.visit_file(self.tree, self.xpath)
  File "/mnt/Code/git_repos/forked/mypy-zvenv3/lib/python3.4/site-packages/mypy/semanal.py", line 246, in visit_file
    self.accept(d)
  File "/mnt/Code/git_repos/forked/mypy-zvenv3/lib/python3.4/site-packages/mypy/semanal.py", line 2251, in accept
    node.accept(self)
  File "/mnt/Code/git_repos/forked/mypy-zvenv3/lib/python3.4/site-packages/mypy/nodes.py", line 729, in accept
    return visitor.visit_expression_stmt(self)
  File "/mnt/Code/git_repos/forked/mypy-zvenv3/lib/python3.4/site-packages/mypy/semanal.py", line 1603, in visit_expression_stmt
    s.expr.accept(self)
  File "/mnt/Code/git_repos/forked/mypy-zvenv3/lib/python3.4/site-packages/mypy/nodes.py", line 1185, in accept
    return visitor.visit_call_expr(self)
  File "/mnt/Code/git_repos/forked/mypy-zvenv3/lib/python3.4/site-packages/mypy/semanal.py", line 1838, in visit_call_expr
    a.accept(self)
AttributeError: 'NoneType' object has no attribute 'accept'

*** INTERNAL ERROR ***

<string>:1: error: Internal error -- please report a bug at https://github.com/python/mypy/issues
```

**Comment by sharmaeklavya2** [comment]
`mypy --py2 --fast-parser -c 'exec("print(bnum)", {"bnum": 666})'` also causes a crash.
`mypy --py2 --fast-parser -c 'exec("print(bnum)", {}, {"bnum": 666})'` gives this output:
```
<string>:1: error: Name 'exec' is not defined
```

**Comment by gnprice** [comment]
Guido points out on #1784 that `exec("")` suffices as a repro and suggests that all forms of `exec` are probably broken under `--py2 --fast-parser`.

**Comment by ddfisher** [comment]
This https://github.com/dropbox/typed_ast/commit/8ecd3d0a5688112a180d057211f6756d89e0e3ec fixes the crash, but I'll need to add `exec` to the Python 2 stubs before this works properly.

**Comment by ddfisher** [comment]
Now you just get `error: Name 'exec' is not defined` instead.

**Comment by ddfisher** [comment]
Now that typeshed has been updated, this is fixed!
