### ISSUE TITLE
(🐞) `dmypy recheck --update` crashes

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#15795]
```
👉 dmypy start
Daemon started
👉 dmypy check test1.py
Success: no issues found in 42 source files
👉 dmypy recheck --update test2.py
Daemon crashed!
Traceback (most recent call last):
  File "mypy\dmypy_server.py", line 234, in serve
  File "mypy\dmypy_server.py", line 281, in run_command
  File "mypy\dmypy_server.py", line 396, in cmd_recheck
AssertionError
```

mypy 1.4.1
no config files

**Comment by benbuckman** [comment]
I am encountering this too, and it seems sort of by-design, if you have `--follow-imports=normal`:

https://github.com/python/mypy/blob/v1.10.0/mypy/dmypy_server.py#L403
https://github.com/python/mypy/blob/v1.10.0/mypy/dmypy_server.py#L450-L453
