### ISSUE TITLE
dmypy Crash: `AttributeError: attribute 'mro' of 'TypeInfo' undefined`

### ISSUE THREAD

**Issue by CoolCat467** [python/mypy#15823]
**Crash Report**

Mypy Daemon crashed attempting to generate type suggestions for `__reduce__` function in class with nonstandard `__new__`

**Traceback**

```
Error running mypy: Daemon crashed!
Traceback (most recent call last):
  File "mypy/suggestions.py", line 296, in restore_after
  File "mypy/suggestions.py", line 267, in suggest
  File "mypy/suggestions.py", line 502, in get_suggestion
  File "mypy/suggestions.py", line 444, in find_best
  File "mypy/suggestions.py", line 675, in try_type
  File "mypy/server/update.py", line 314, in trigger
  File "mypy/server/update.py", line 881, in propagate_changes_using_dependencies
  File "mypy/server/update.py", line 1010, in reprocess_nodes
  File "mypy/semanal_main.py", line 144, in semantic_analysis_for_targets
  File "mypy/semanal_main.py", line 291, in process_top_level_function
  File "mypy/semanal_main.py", line 349, in semantic_analyze_target
  File "mypy/semanal.py", line 603, in refresh_partial
  File "mypy/semanal.py", line 6453, in accept
  File "mypy/errors.py", line 1177, in report_internal_error
  File "mypy/semanal.py", line 6451, in accept
  File "mypy/nodes.py", line 786, in accept
  File "mypy/semanal.py", line 833, in visit_func_def
  File "mypy/semanal.py", line 865, in analyze_func_def
  File "mypy/typeanal.py", line 950, in visit_callable_type
  File "mypy/typeanal.py", line 1522, in anal_type
  File "mypy/types.py", line 2294, in accept
  File "mypy/typeanal.py", line 1051, in visit_tuple_type
  File "mypy/typeanal.py", line 1512, in anal_array
  File "mypy/typeanal.py", line 1522, in anal_type
  File "mypy/types.py", line 1917, in accept
  File "mypy/typeanal.py", line 931, in visit_callable_type
  File "mypy/typeanal.py", line 1469, in bind_function_type_variables
AssertionError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "mypy/dmypy_server.py", line 234, in serve
  File "mypy/dmypy_server.py", line 281, in run_command
  File "mypy/dmypy_server.py", line 931, in cmd_suggest
  File "mypy/suggestions.py", line 265, in suggest
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "mypy/suggestions.py", line 298, in restore_after
  File "mypy/suggestions.py", line 687, in reload
  File "mypy/server/update.py", line 267, in update
  File "mypy/server/update.py", line 369, in update_one
  File "mypy/server/update.py", line 426, in update_module
  File "mypy/server/astdiff.py", line 223, in snapshot_symbol_table
  File "mypy/server/astdiff.py", line 236, in snapshot_definition
  File "mypy/server/astdiff.py", line 315, in snapshot_type
  File "mypy/types.py", line 1917, in accept
  File "mypy/server/astdiff.py", line 439, in visit_callable_type
  File "mypy/types.py", line 1900, in is_type_obj
  File "mypy/nodes.py", line 3170, in is_metaclass
  File "mypy/nodes.py", line 3180, in has_base
AttributeError: attribute 'mro' of 'TypeInfo' undefined
```

**To Reproduce**
Attempted to run dmypy suggest for `__reduce__` in the following code excerpt

```python
from __future__ import annotations

from collections.abc import Iterable, Callable
from typing import TYPE_CHECKING, TypeVar

if TYPE_CHECKING:
    from types import TracebackType
    from typing_extensions import Self

class MultiError(BaseExceptionGroup):
    def __init__(self, exceptions: list[BaseException], *, _collapse: bool = True) -> None:
        self.collapse = _collapse

        # Avoid double initialization when _collapse is True and exceptions[0] returned
        # by __new__() happens to be a MultiError and subsequently __init__() is called.
        if _collapse and getattr(self, "exceptions", None) is not None:
            # This exception was already initialized.
            return

        super().__init__("multiple tasks failed", exceptions)

    def __new__(cls, exceptions: Iterable[BaseException], *, _collapse: bool = True) -> MultiError | Self:
        exceptions = list(exceptions)
        for exc in exceptions:
            if not isinstance(exc, BaseException):
                raise TypeError(f"Expected an exception object, not {exc!r}")
        if _collapse and len(exceptions) == 1:
            # If this lone object happens to itself be a MultiError, then
            # Python will implicitly call our __init__ on it again.  See
            # special handling in __init__.
            single = exceptions[0]
            assert isinstance(single, MultiError)
            return single
        else:
            # The base class __new__() implicitly invokes our __init__, which
            # is what we want.
            #
            # In an earlier version of the code, we didn't define __init__ and
            # simply set the `exceptions` attribute directly on the new object.
            # However, linters expect attributes to be initialized in __init__.
            if all(isinstance(exc, Exception) for exc in exceptions):
                cls = NonBaseMultiError

            return super().__new__(cls, "multiple tasks failed", exceptions)

    def __reduce__(self):
        return (
            self.__new__,
            (self.__class__, list(self.exceptions)),
            {"collapse": self.collapse},
        )
```

Interestingly, with the code segment I have shared above, I don't get any of the additional errors after and including the
```console
During handling of the above exception, another exception occurred:
```
line.

**Your Environment**
```console
dmypy --status-file=<USER HOME>/.idlerc/mypy/dmypy.json run --log-file=<USER HOME>/.idlerc/mypy/log.txt <USER HOME>/<PATH TO FILE EXCERPTED ABOVE> -- --soft-error-limit=-1 --disallow-untyped-defs --show-error-codes --warn-unreachable --cache-fine-grained --no-error-summary --show-column-numbers --disallow-untyped-calls --cache-dir=<USER HOME>/.idlerc/mypy --no-implicit-reexport --warn-unused-ignores --warn-redundant-casts --hide-error-context --show-error-end --show-absolute-path --show-traceback --no-color-output --strict
```

- Mypy version used: 1.4.1
- Mypy command-line flags: See above
- Mypy configuration options from `mypy.ini` (and other config files): See above
- Python version used: Python 3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0] on linux
- Operating system and version: 64 bit Linux Ubuntu Budgie 10.6.1 (Ubuntu 22.04.3 LTS)

**Comment by CoolCat467** [comment]
Re-opening with updated data

**Comment by matpvl** [comment]
why was this closed as completed? i don't see any solutions written?

**Comment by CoolCat467** [comment]
> why was this closed as completed? i don't see any solutions written?

Because I re-opened this issue as https://github.com/python/mypy/issues/16708
If you are encountering an issue that is not this one, I would suggest making a new issue and mentioning this one in it.
