### ISSUE TITLE
Must not defer during final iteration - Stack Trace

### ISSUE THREAD

**Issue by Rudedog9d** [python/mypy#16182]
**Crash Report**

Attempting to run mypy against relatively new project (link below). Maybe related to lots of async code?

**Traceback**

```
$ poetry run mypy infrastructure_daemon/ --show-traceback 
infrastructure_daemon/models/__init__.py:33: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.7.0+dev.0c8b76195a773363721d5521653bcdf9989d8768
Traceback (most recent call last):
  File "/home/bdavis/.cache/pypoetry/virtualenvs/infrastructure-daemon-pU6D7_C3-py3.10/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/bdavis/.cache/pypoetry/virtualenvs/infrastructure-daemon-pU6D7_C3-py3.10/lib/python3.10/site-packages/mypy/__main__.py", line 15, in console_entry
    main()
  File "/home/bdavis/.cache/pypoetry/virtualenvs/infrastructure-daemon-pU6D7_C3-py3.10/lib/python3.10/site-packages/mypy/main.py", line 99, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "/home/bdavis/.cache/pypoetry/virtualenvs/infrastructure-daemon-pU6D7_C3-py3.10/lib/python3.10/site-packages/mypy/main.py", line 178, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/home/bdavis/.cache/pypoetry/virtualenvs/infrastructure-daemon-pU6D7_C3-py3.10/lib/python3.10/site-packages/mypy/build.py", line 189, in build
    result = _build(
  File "/home/bdavis/.cache/pypoetry/virtualenvs/infrastructure-daemon-pU6D7_C3-py3.10/lib/python3.10/site-packages/mypy/build.py", line 262, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/bdavis/.cache/pypoetry/virtualenvs/infrastructure-daemon-pU6D7_C3-py3.10/lib/python3.10/site-packages/mypy/build.py", line 2938, in dispatch
    process_graph(graph, manager)
  File "/home/bdavis/.cache/pypoetry/virtualenvs/infrastructure-daemon-pU6D7_C3-py3.10/lib/python3.10/site-packages/mypy/build.py", line 3336, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/bdavis/.cache/pypoetry/virtualenvs/infrastructure-daemon-pU6D7_C3-py3.10/lib/python3.10/site-packages/mypy/build.py", line 3431, in process_stale_scc
    mypy.semanal_main.semantic_analysis_for_scc(graph, scc, manager.errors)
  File "/home/bdavis/.cache/pypoetry/virtualenvs/infrastructure-daemon-pU6D7_C3-py3.10/lib/python3.10/site-packages/mypy/semanal_main.py", line 94, in semantic_analysis_for_scc
    process_functions(graph, scc, patches)
  File "/home/bdavis/.cache/pypoetry/virtualenvs/infrastructure-daemon-pU6D7_C3-py3.10/lib/python3.10/site-packages/mypy/semanal_main.py", line 252, in process_functions
    process_top_level_function(
  File "/home/bdavis/.cache/pypoetry/virtualenvs/infrastructure-daemon-pU6D7_C3-py3.10/lib/python3.10/site-packages/mypy/semanal_main.py", line 291, in process_top_level_function
    deferred, incomplete, progress = semantic_analyze_target(
  File "/home/bdavis/.cache/pypoetry/virtualenvs/infrastructure-daemon-pU6D7_C3-py3.10/lib/python3.10/site-packages/mypy/semanal_main.py", line 349, in semantic_analyze_target
    analyzer.refresh_partial(
  File "/home/bdavis/.cache/pypoetry/virtualenvs/infrastructure-daemon-pU6D7_C3-py3.10/lib/python3.10/site-packages/mypy/semanal.py", line 604, in refresh_partial
    self.accept(node)
  File "/home/bdavis/.cache/pypoetry/virtualenvs/infrastructure-daemon-pU6D7_C3-py3.10/lib/python3.10/site-packages/mypy/semanal.py", line 6504, in accept
    node.accept(self)
  File "/home/bdavis/.cache/pypoetry/virtualenvs/infrastructure-daemon-pU6D7_C3-py3.10/lib/python3.10/site-packages/mypy/nodes.py", line 776, in accept
    return visitor.visit_func_def(self)
  File "/home/bdavis/.cache/pypoetry/virtualenvs/infrastructure-daemon-pU6D7_C3-py3.10/lib/python3.10/site-packages/mypy/semanal.py", line 837, in visit_func_def
    self.analyze_func_def(defn)
  File "/home/bdavis/.cache/pypoetry/virtualenvs/infrastructure-daemon-pU6D7_C3-py3.10/lib/python3.10/site-packages/mypy/semanal.py", line 872, in analyze_func_def
    self.defer(defn)
  File "/home/bdavis/.cache/pypoetry/virtualenvs/infrastructure-daemon-pU6D7_C3-py3.10/lib/python3.10/site-packages/mypy/semanal.py", line 6176, in defer
    assert not self.final_iteration, "Must not defer during final iteration"
AssertionError: Must not defer during final iteration
infrastructure_daemon/models/__init__.py:33: : note: use --pdb to drop into pdb
```

**To Reproduce**

I'm not exactly sure what's causing it, but the project is public. Here is the exact commit where we started to see the error (not sure if its the first instance of it): https://gitlab.com/c2-games/infrastructure/infrastructure-daemon/-/tree/8b3118a1176e175a5f674027eac124eb52bd81a7

**Your Environment**

- Mypy versions used:
    - `mypy 1.5.1 (compiled: yes)`
    - `mypy 1.7.0+dev.0c8b76195a773363721d5521653bcdf9989d8768 (compiled: no)`
- Mypy command-line flags: n/a (just project name)
- Mypy configuration options from `mypy.ini` (and other config files):
    ```
    [mypy]
    plugins = pydantic.mypy
    ignore_missing_imports = True
    disallow_untyped_defs = True
    ```
- Python version used: `Python 3.10.6`
- Operating system and version: PopOS

**Comment by Rudedog9d** [comment]
Looks like duplicate of https://github.com/python/mypy/issues/15927 actually
