### ISSUE TITLE
list index out of range when installing private package as dependency

### ISSUE THREAD

**Issue by rbange** [python/mypy#16299]
**Crash Report**

Mypy fails with the following error. 

The package linted here is one of my own therefore I cannot disclose its content. However, mypy (1.6.0) runs fine on the package in its repo itself.

**Traceback**

```
<mydir>/.venv/lib/python3.11/site-packages/<mypackage>/models.py:-1: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.7.0+dev.1c218ea2c674d7a06c8ed4c2f95855f1d3fd26da
Traceback (most recent call last):
  File "<mydir>/.venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/__main__.py", line 15, in console_entry
    main()
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/main.py", line 99, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/main.py", line 178, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/build.py", line 189, in build
    result = _build(
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/build.py", line 262, in _build
    graph = dispatch(sources, manager, stdout)
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/build.py", line 2940, in dispatch
    process_graph(graph, manager)
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/build.py", line 3338, in process_graph
    process_stale_scc(graph, scc, manager)
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/build.py", line 3439, in process_stale_scc
    graph[id].type_check_first_pass()
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/build.py", line 2308, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/checker.py", line 477, in check_first_pass
    self.accept(d)
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/checker.py", line 587, in accept
    stmt.accept(self)
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/nodes.py", line 1131, in accept
    return visitor.visit_class_def(self)
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/checker.py", line 2304, in visit_class_def
    self.accept(defn.defs)
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/checker.py", line 587, in accept
    stmt.accept(self)
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/nodes.py", line 1212, in accept
    return visitor.visit_block(self)
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/checker.py", line 2760, in visit_block
    self.accept(s)
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/checker.py", line 587, in accept
    stmt.accept(self)
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/nodes.py", line 1299, in accept
    return visitor.visit_assignment_stmt(self)
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/checker.py", line 2808, in visit_assignment_stmt
    self.check_assignment(s.lvalues[-1], s.rvalue, s.type is None, s.new_syntax)
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/checker.py", line 2985, in check_assignment
    rvalue_type = self.check_simple_assignment(lvalue_type, rvalue, context=rvalue)
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/checker.py", line 4124, in check_simple_assignment
    rvalue_type = self.expr_checker.accept(
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/checkexpr.py", line 5638, in accept
    typ = node.accept(self)
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/nodes.py", line 1893, in accept
    return visitor.visit_call_expr(self)
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/checkexpr.py", line 458, in visit_call_expr
    return self.visit_call_expr_inner(e, allow_none_return=allow_none_return)
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/checkexpr.py", line 587, in visit_call_expr_inner
    ret_type = self.check_call_expr_with_callee_type(
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/checkexpr.py", line 1425, in check_call_expr_with_callee_type
    ret_type, callee_type = self.check_call(
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/checkexpr.py", line 1520, in check_call
    return self.check_callable_call(
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/checkexpr.py", line 1705, in check_callable_call
    callee = self.infer_function_type_arguments(
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/checkexpr.py", line 2013, in infer_function_type_arguments
    arg_types = self.infer_arg_types_in_context(
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/checkexpr.py", line 1902, in infer_arg_types_in_context
    res[ai] = self.accept(args[ai], arg_type)
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/checkexpr.py", line 5638, in accept
    typ = node.accept(self)
          ^^^^^^^^^^^^^^^^^
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/nodes.py", line 2202, in accept
    return visitor.visit_lambda_expr(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/checkexpr.py", line 5114, in visit_lambda_expr
    ret_type = self.accept(e.expr(), allow_none_return=True)
                           ^^^^^^^^
  File "<mydir>/.venv/lib/python3.11/site-packages/mypy/nodes.py", line 2195, in expr
    ret = self.body.body[-1]
          ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range

```
**To Reproduce**

(Write what you did to reproduce the crash.  Full source code is
appreciated.  We also very much appreciate it if you try to narrow the
source down to a small stand-alone example.)

**Your Environment**

- Mypy version used: version: 1.7.0+dev.1c218ea2c674d7a06c8ed4c2f95855f1d3fd26da
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files):

```toml
[tool.mypy]
plugins = ["pydantic.mypy", "sqlalchemy.ext.mypy.plugin"]

follow_imports = "silent"
strict_optional = true
warn_redundant_casts = true
disallow_any_generics = true
check_untyped_defs = true
warn_unused_ignores = false
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = false
show_column_numbers = true
show_error_codes = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true

[[tool.mypy.overrides]]
module = [
    "plotly",
    "plotly.*",
    "matplotlib",
    "matplotlib.colors",
    "matplotlib.pyplot",
]
ignore_missing_imports = true

```
- Python version used: 3.11.2
- Operating system and version: macOS

**Comment by rbange** [comment]
closing due to an existing issue on sqlalchemy: https://github.com/sqlalchemy/sqlalchemy/issues/10282
