### ISSUE TITLE
`super()` without arguments and `@staticmethod`

### ISSUE THREAD

**Issue by sobolevn** [python/mypy#16391]
This code passes mypy:

```python
class A:
    @staticmethod
    def m() -> int:
        return 1

class B(A):
    @staticmethod
    def m() -> int:
        return super().m()  # passes, but should not

B().m()
```

Link: https://mypy-play.net/?mypy=latest&python=3.11&gist=c410bb336713f6c3b2475abbfd291fc0

But, in runtime it fails with:

```python
>>> B().m()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    B().m()
  File "<stdin>", line 4, in m
    return super().m()  # passes, but should not
           ^^^^^^^
RuntimeError: super(): no arguments
>>> B.m()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    B.m()
  File "<stdin>", line 4, in m
    return super().m()  # passes, but should not
           ^^^^^^^
RuntimeError: super(): no arguments
```

I think we can detect such cases and raise an error.

**Comment by sobolevn** [comment]
It actually works: `ex.py:9: error: super() requires one or more positional arguments in enclosing function  [misc]`

But, I can add more tests and improve the error message.
