### ISSUE TITLE
Internal error: unresolved placeholder type

### ISSUE THREAD

**Issue by jokance** [python/mypy#16419]
**Crash Report**
I got this error after I use mypy to check my project file :  
`AssertionError: Internal error: unresolved placeholder type gac.game_wnd.framework.ui_def.EWndDataNotifyFlag`

**Traceback**

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\xxx\Lib\site-packages\mypy\__main__.py", line 37, in <module>
    console_entry()
  File "C:\Users\xxx\Lib\site-packages\mypy\__main__.py", line 15, in console_entry
    main()
  File "mypy\main.py", line 99, in main
  File "mypy\main.py", line 178, in run_build
  File "mypy\build.py", line 189, in build
  File "mypy\build.py", line 262, in _build
  File "mypy\build.py", line 2938, in dispatch
  File "mypy\build.py", line 3336, in process_graph
  File "mypy\build.py", line 3459, in process_stale_scc
  File "mypy\build.py", line 2499, in write_cache
  File "mypy\build.py", line 1562, in write_cache
  File "mypy\nodes.py", line 389, in serialize
  File "mypy\nodes.py", line 3924, in serialize
  File "mypy\nodes.py", line 3861, in serialize
  File "mypy\nodes.py", line 3597, in serialize
  File "mypy\types.py", line 2796, in serialize
  File "mypy\types.py", line 2979, in serialize
AssertionError: Internal error: unresolved placeholder type gac.game_wnd.framework.ui_def.EWndDataNotifyFlag
```

**To Reproduce**

Sorry I can't share all my full code, here is the definition of EWndDataNotifyFlag:
```python
class EWndDataNotifyFlag(IntFlag):
    eNone = 0
    eAdd = 1 << 0
    eModify = 1 << 1
    eDelete = 1 << 2
```

**Your Environment**

- Mypy version used: v1.6.1
- Mypy command-line flags:  python.exe -m mypy --show-absolute-path --show-column-numbers --show-error-codes --config-file=F:\Client\UEGame\Content\Scripts/../../../../pyproject.toml --show-error-end F:\Client\UEGame\Content\Scripts\gac\gac_proxy\gac_character_performer.py --show-traceback
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.11.6
- Operating system and version: Windows10

**Comment by hauntsaninja** [comment]
Closing since this isn't enough to repro, and a few bugs with this kind of shape have been fixed since this was opened
