### ISSUE TITLE
RecursionError: maximum recursion depth exceeded caused by `import sympy`

### ISSUE THREAD

**Issue by Alexander-Wilms** [python/mypy#16627]
**Crash Report**

Using VS Code with the Mypy extension, I encounter a reproducible crash of dmypy when there's a .py file containing `import sympy` in the working directory.

**Traceback**

<details>

```
[27] Error running mypy in /home/alexander/Technik/Development/advent_of_code_2023/day_05/mypy-bug/mwe: the mypy daemon crashed. This is probably a bug in mypy itself, see Output panel for details. The daemon will be restarted automatically.
[28] Check folder: /home/alexander/Technik/Development/advent_of_code_2023/day_05/mypy-bug/mwe
[28] Received python path from Python extension: /bin/python3
[28] Running dmypy in folder /home/alexander/Technik/Development/advent_of_code_2023/day_05/mypy-bug/mwe
/usr/bin/dmypy --status-file /home/alexander/.config/Code/User/workspaceStorage/bd35db2551e0cc3428e7acaa49ef702e/matangover.mypy/dmypy-518099966ad5730e6cd927bbe272261fb9f9d9a5-1988.json run --log-file /home/alexander/.config/Code/User/workspaceStorage/bd35db2551e0cc3428e7acaa49ef702e/matangover.mypy/dmypy-518099966ad5730e6cd927bbe272261fb9f9d9a5.log -- . --show-column-numbers --no-error-summary --no-pretty --no-color-output --python-executable /bin/python3
[28] stdout:
Daemon started
-------------------------------------------------------------------------------
stderr:
/usr/lib/python3.11/site-packages/sympy/polys/numberfields/resolvent_lookup.py: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.5.1

[28] stderr:
Daemon crashed!
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mypy/dmypy_server.py", line 234, in serve
    resp = self.run_command(command, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/dmypy_server.py", line 281, in run_command
    ret = method(self, **data)
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/dmypy_server.py", line 349, in cmd_run
    return self.check(sources, export_types, is_tty, terminal_width)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/dmypy_server.py", line 413, in check
    res = self.initialize_fine_grained(sources, is_tty, terminal_width)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/dmypy_server.py", line 449, in initialize_fine_grained
    result = mypy.build.build(sources=sources, options=self.options, fscache=self.fscache)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/build.py", line 195, in build
    result = _build(
             ^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/build.py", line 268, in _build
    graph = dispatch(sources, manager, stdout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/build.py", line 2874, in dispatch
    graph = load_graph(sources, manager)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/build.py", line 3142, in load_graph
    newst = State(
            ^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/build.py", line 2000, in __init__
    self.parse_file()
  File "/usr/lib/python3.11/site-packages/mypy/build.py", line 2176, in parse_file
    self.tree = manager.parse_file(
                ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/build.py", line 841, in parse_file
    tree = parse(source, path, id, self.errors, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/parse.py", line 22, in parse
    return mypy.fastparse.parse(source, fnam=fnam, module=module, errors=errors, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 227, in parse
    ).visit(ast)
      ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 396, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 855, in visit_Module
    body = self.fix_function_overloads(self.translate_stmt_list(mod.body, ismodule=True))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 470, in translate_stmt_list
    node = self.visit(stmt)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 396, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 1148, in visit_Assign
    rvalue = self.visit(n.value)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 396, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 1421, in visit_Dict
    list(zip(self.translate_opt_expr_list(n.keys), self.translate_expr_list(n.values)))
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 414, in translate_expr_list
    return cast(List[Expression], self.translate_opt_expr_list(l))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 409, in translate_opt_expr_list
    exp = self.visit(e)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 396, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 1612, in visit_List
    expr_list: list[Expression] = [self.visit(e) for e in n.elts]
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 1612, in <listcomp>
    expr_list: list[Expression] = [self.visit(e) for e in n.elts]
                                   ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 396, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 1408, in visit_Lambda
    e = LambdaExpr(self.transform_args(n.args, n.lineno), self.as_required_block([body]))
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 585, in as_required_block
    self.translate_stmt_list(stmts, can_strip=can_strip, is_coroutine=is_coroutine)
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 470, in translate_stmt_list
    node = self.visit(stmt)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 396, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 1132, in visit_Return
    node = ReturnStmt(self.visit(n.value))
                      ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 396, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 1380, in visit_BinOp
    e = OpExpr(op, self.visit(n.left), self.visit(n.right))
                   ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 396, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 1380, in visit_BinOp
    e = OpExpr(op, self.visit(n.left), self.visit(n.right))
                   ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 396, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 1380, in visit_BinOp
    e = OpExpr(op, self.visit(n.left), self.visit(n.right))
                   ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 396, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 1380, in visit_BinOp
    e = OpExpr(op, self.visit(n.left), self.visit(n.right))
                   ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 396, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 1380, in visit_BinOp
    e = OpExpr(op, self.visit(n.left), self.visit(n.right))
                   ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 396, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 1380, in visit_BinOp
    e = OpExpr(op, self.visit(n.left), self.visit(n.right))
                   ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 396, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 1380, in visit_BinOp
    e = OpExpr(op, self.visit(n.left), self.visit(n.right))
                   ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 396, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 1380, in visit_BinOp
    e = OpExpr(op, self.visit(n.left), self.visit(n.right))
                   ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 396, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 1380, in visit_BinOp
    e = OpExpr(op, self.visit(n.left), self.visit(n.right))
                   ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 396, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 1380, in visit_BinOp
    e = OpExpr(op, self.visit(n.left), self.visit(n.right))
                   ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 396, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 1380, in visit_BinOp
    e = OpExpr(op, self.visit(n.left), self.visit(n.right))
                   ^^^^^^^^^^^^^^^^^^
[...] this is repeated countless times
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 396, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mypy/fastparse.py", line 1375, in visit_BinOp
    op = self.from_operator(n.op)
         ^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded


[28] Error running mypy in /home/alexander/Technik/Development/advent_of_code_2023/day_05/mypy-bug/mwe: the mypy daemon crashed. This is probably a bug in mypy itself, see Output panel for details. The daemon will be restarted automatically.
```
</details>

**To Reproduce**

Use VS Code with the Mypy extension. Open a folder containing a .py file with the content `import sympy` and click Terminal > Output > Mypy to see the traceback

**Your Environment**

- Mypy version used: 1.5.1
- Mypy command-line flags: `/usr/bin/dmypy --status-file /home/alexander/.config/Code/User/workspaceStorage/bd35db2551e0cc3428e7acaa49ef702e/matangover.mypy/dmypy-518099966ad5730e6cd927bbe272261fb9f9d9a5-1988.json run --log-file /home/alexander/.config/Code/User/workspaceStorage/bd35db2551e0cc3428e7acaa49ef702e/matangover.mypy/dmypy-518099966ad5730e6cd927bbe272261fb9f9d9a5.log -- . --show-column-numbers --no-error-summary --no-pretty --no-color-output --python-executable /bin/python3`
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.11.6
- Operating system and version: openSUSE Tumbleweed 20231204

- Sympy version: 1.12

**Comment by AlexWaygood** [comment]
> * Mypy version used: 1.5.1

We fix bugs in every mypy release. Does this reproduce with the latest version of mypy (1.7.1)?

**Comment by e-dorigatti** [comment]
I had the same issue and `pip install -U mypy` in the base conda environment fixed it.

**Comment by Alexander-Wilms** [comment]
I can confirm that this is not reproducible with mypy 1.7.1

**Comment by AlexWaygood** [comment]
Great!
