### ISSUE TITLE
`INTERNAL ERROR` on master, possibly due to usage of `Unpack[builtins.tuple[Any, ...]]`

### ISSUE THREAD

**Issue by flexatone** [python/mypy#16638]
**Crash Report**

Greetings, and thank you for this excellent tool.

I have a repository that makes extended use of `TypeVarTuple` and `Unpack` expressions. I was excited to see the support in mypy 1.7.1 (and happy to see many things working as expected), but encountered an "INTERNAL ERROR".

I pip-installed mypy to the current head of master (via 
`git+https://github.com/python/mypy@13e7213ad958a50ab4bf28abd63fa1f324f58a69`) and the "INTERNAL ERROR" persists.

**Traceback**

```
{.env311-sf}{873/mypy-pyright} % mypy --strict --show-traceback
static_frame/core/container_util.py:683: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.9.0+dev.13e7213ad958a50ab4bf28abd63fa1f324f58a69
Traceback (most recent call last):
  File "/home/ariza/.env311-sf/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/__main__.py", line 15, in console_entry
    main()
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/main.py", line 100, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/main.py", line 182, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/build.py", line 191, in build
    result = _build(
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/build.py", line 265, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/build.py", line 2943, in dispatch
    process_graph(graph, manager)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/build.py", line 3341, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/build.py", line 3442, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/build.py", line 2311, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/checker.py", line 481, in check_first_pass
    self.accept(d)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/checker.py", line 591, in accept
    stmt.accept(self)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/nodes.py", line 586, in accept
    return visitor.visit_overloaded_func_def(self)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/checker.py", line 628, in visit_overloaded_func_def
    self._visit_overloaded_func_def(defn)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/checker.py", line 656, in _visit_overloaded_func_def
    defn.impl.accept(self)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/nodes.py", line 787, in accept
    return visitor.visit_func_def(self)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/checker.py", line 1000, in visit_func_def
    self._visit_func_def(defn)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/checker.py", line 1004, in _visit_func_def
    self.check_func_item(defn, name=defn.name)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/checker.py", line 1077, in check_func_item
    self.check_func_def(defn, typ, name, allow_empty)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/checker.py", line 1293, in check_func_def
    self.accept(item.body)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/checker.py", line 591, in accept
    stmt.accept(self)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/nodes.py", line 1223, in accept
    return visitor.visit_block(self)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/checker.py", line 2770, in visit_block
    self.accept(s)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/checker.py", line 591, in accept
    stmt.accept(self)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/nodes.py", line 1491, in accept
    return visitor.visit_if_stmt(self)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/checker.py", line 4532, in visit_if_stmt
    self.accept(s.else_body)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/checker.py", line 591, in accept
    stmt.accept(self)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/nodes.py", line 1223, in accept
    return visitor.visit_block(self)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/checker.py", line 2770, in visit_block
    self.accept(s)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/checker.py", line 591, in accept
    stmt.accept(self)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/nodes.py", line 1491, in accept
    return visitor.visit_if_stmt(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/checker.py", line 4513, in visit_if_stmt
    with self.binder.frame_context(can_skip=False, conditional_frame=True, fall_through=0):
  File "/home/ariza/src/py_src_3.11.4/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/binder.py", line 450, in frame_context
    self.pop_frame(can_skip, fall_through)
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/binder.py", line 262, in pop_frame
    self.last_pop_changed = self.update_from_options(options)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/binder.py", line 220, in update_from_options
    type = join_simple(self.declarations[key], type, other)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/join.py", line 202, in join_simple
    if is_proper_subtype(t, s, ignore_promotions=True):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/subtypes.py", line 224, in is_proper_subtype
    return _is_subtype(left, right, subtype_context, proper_subtype=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/subtypes.py", line 352, in _is_subtype
    return left.accept(SubtypeVisitor(orig_right, subtype_context, proper_subtype))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/types.py", line 1970, in accept
    return visitor.visit_callable_type(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/subtypes.py", line 690, in visit_callable_type
    return is_callable_compatible(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/subtypes.py", line 1506, in is_callable_compatible
    unified = unify_generic_callable(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/subtypes.py", line 1869, in unify_generic_callable
    applied = mypy.applytype.apply_generic_arguments(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/applytype.py", line 152, in apply_generic_arguments
    ret_type=expand_type(callable.ret_type, id_to_type),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/expandtype.py", line 71, in expand_type
    return typ.accept(ExpandTypeVisitor(env))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/types.py", line 1435, in accept
    return visitor.visit_instance(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/expandtype.py", line 214, in visit_instance
    args = self.expand_types_with_unpack(list(t.args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/expandtype.py", line 395, in expand_types_with_unpack
    items.extend(self.expand_unpack(item))
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ariza/.env311-sf/lib/python3.11/site-packages/mypy/expandtype.py", line 299, in expand_unpack
    raise RuntimeError(f"Invalid type replacement to expand: {repl}")
RuntimeError: Invalid type replacement to expand: Unpack[builtins.tuple[Any, ...]]
static_frame/core/container_util.py:683: : note: use --pdb to drop into pdb
```

**To Reproduce**

I am afraid I have not been able to narrow this down to a stand-alone exmaple; this error happens when running mypy over the entire code base. 

To reproduce, you can pull this PR:
https://github.com/static-frame/static-frame/pull/874

In Python 3.11, create this environment:
https://github.com/static-frame/static-frame/blob/873/mypy-pyright/requirements-dev.txt

And then run `mypy --strict`

**Your Environment**

- Mypy version used: 1.7.1, 13e7213ad958a50ab4bf28abd63fa1f324f58a69
- Mypy command-line flags: `--strict`
- Mypy configuration options from `mypy.ini` (and other config files):
```show_error_codes = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
warn_return_any = true
warn_unused_configs = true
disable_error_code = "misc"
```
- Python version used: 3.11
- Operating system and version: Ubuntu 20.04.3

I am happy to support this inquiry in any way.

**Comment by flexatone** [comment]
Just an update: with Mypy 1.8.0, Python 3.12, I seem to get the same `RuntimeError`:

```
static_frame/core/container_util.py:683: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.8.0
Traceback (most recent call last):
  File "mypy/checker.py", line 591, in accept
  File "mypy/nodes.py", line 1491, in accept
  File "mypy/checker.py", line 4513, in visit_if_stmt
  File "/home/ariza/src/py_src_3.12.0/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "mypy/binder.py", line 450, in frame_context
  File "mypy/binder.py", line 262, in pop_frame
  File "mypy/binder.py", line 220, in update_from_options
  File "mypy/join.py", line 202, in join_simple
  File "mypy/subtypes.py", line 224, in is_proper_subtype
  File "mypy/subtypes.py", line 352, in _is_subtype
  File "mypy/types.py", line 1970, in accept
  File "mypy/subtypes.py", line 690, in visit_callable_type
  File "mypy/subtypes.py", line 1506, in is_callable_compatible
  File "mypy/subtypes.py", line 1869, in unify_generic_callable
  File "mypy/applytype.py", line 152, in apply_generic_arguments
  File "mypy/expandtype.py", line 71, in expand_type
  File "mypy/types.py", line 1435, in accept
  File "mypy/expandtype.py", line 214, in visit_instance
  File "mypy/expandtype.py", line 401, in expand_types_with_unpack
  File "mypy/expandtype.py", line 299, in expand_unpack
RuntimeError: Invalid type replacement to expand: Unpack[builtins.tuple[Any, ...]]
static_frame/core/container_util.py:683: : note: use --pdb to drop into pdb
```

**Comment by flexatone** [comment]
Greetings. I am happy to report that I am no longer getting a crash with Mypy 1.9.0. `TypeVarTuple` and `Unpack` support seem to be working as expected. Thank you!
