### ISSUE TITLE
(🐞) Crash with `ParamSpec` and `Unpack` in `Generic`

### ISSUE THREAD

**Issue by KotlinIsland** [python/mypy#16695]
This should not be a crash, it should be handled properly and show an error.
```py
from typing import Generic, ParamSpec, TypeVarTuple, Unpack

P = ParamSpec("P")
Ts = TypeVarTuple("Ts")


class C(Generic[P, Unpack[Ts]]): ...
```
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "mypy/semanal.py", line 6525, in accept
  File "mypy/nodes.py", line 1140, in accept
  File "mypy/semanal.py", line 1608, in visit_class_def
  File "mypy/semanal.py", line 1680, in analyze_class
  File "mypy/semanal.py", line 1699, in setup_type_vars
  File "mypy/nodes.py", line 3088, in add_type_vars
AssertionError: Mixing type var tuples and param specs not supported yet
main.py:6: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.7.1
main.py:6: : note: use --pdb to drop into pdb
```

[playground](https://mypy-play.net/?mypy=1.7.1&python=3.12&flags=show-traceback&gist=c8c3747029cb0f9f5de0b276ee4f40a6)

**Comment by erictraut** [comment]
This crash prevents mypy from running the type checker conformance tests (see [this issue](https://github.com/python/mypy/issues/17041)), so it would be nice if it could be prioritized for the next version. Even if the underlying functionality isn't implemented, it would be helpful if the crash can be addressed (e.g. replaced with a normal error message indicating that the feature is not yet supported).
