### ISSUE TITLE
Mypy crash cause of Pydantic Python 3.10

### ISSUE THREAD

**Issue by RoTorEx** [python/mypy#16706]
**Crash Report**

(Tell us what happened.)

**Traceback**

```
/Users/alex/Library/Caches/pypoetry/virtualenvs/mcp-cloud-O1_eUdvg-py3.11/lib/python3.11/site-packages/pydantic/env_settings.py:22: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.8.0
Traceback (most recent call last):
  File "mypy/semanal.py", line 6539, in accept
  File "mypy/nodes.py", line 1142, in accept
  File "mypy/semanal.py", line 1612, in visit_class_def
  File "mypy/semanal.py", line 1697, in analyze_class
  File "mypy/semanal.py", line 1731, in analyze_class_body_common
  File "mypy/semanal.py", line 1816, in apply_class_plugin_hooks
  File "pydantic/mypy.py", line 154, in pydantic.mypy.PydanticPlugin._pydantic_model_class_maker_callback
  File "pydantic/mypy.py", line 317, in pydantic.mypy.PydanticModelTransformer.transform
  File "pydantic/mypy.py", line 496, in pydantic.mypy.PydanticModelTransformer.add_construct_method
TypeError: __init__() missing required argument 'default' (pos 6)
/Users/alex/Library/Caches/pypoetry/virtualenvs/mcp-cloud-O1_eUdvg-py3.11/lib/python3.11/site-packages/pydantic/env_settings.py:22: : note: use --pdb to drop into pdb
```

**To Reproduce**

```
# My makefile
# Env setup
py := poetry run
python := $(py) python
main_dir := src
test_dir := tests

lint:
	@$(py) mypy $(main_dir) --show-traceback
```

```bash
# My launch
$ make lint
```

**Your Environment**

- Mypy version used: 1.8.0
- Mypy command-line flags: Poetry:
```
[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
plugins = ["pydantic.mypy", "sqlalchemy.ext.mypy.plugin"]
exclude = ['postgres-data', 'venv', 'tests']
```
- Mypy configuration options from `mypy.ini` (and other config files): -
- Python version used: 3.10
- Operating system and version: MacOS 14.1

**Comment by AlexWaygood** [comment]
This is a bug in pydantic's mypy plugin. I believe it's fixed in the latest version of pydantic

**Comment by RoTorEx** [comment]
Okay, thanks
