### ISSUE TITLE
Internal Error in 0.4.2-dev

### ISSUE THREAD

**Issue by galsondor** [python/mypy#1676]
I encountered the following internal error report.  Unfortunately, the code base I am working on is large, complex, and in need of refactoring.  Finding a simple way to reproduce has proved unfruitful so far.

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/bin/mypy", line 6, in <module>
    main(__file__)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/main.py", line 54, in main
    res = type_check_only(sources, bin_dir, options)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/main.py", line 102, in type_check_only
    python_path=options.python_path)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/build.py", line 209, in build
    dispatch(sources, manager)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/build.py", line 1329, in dispatch
    process_graph(graph, manager)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/build.py", line 1460, in process_graph
    process_stale_scc(graph, scc)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/build.py", line 1488, in process_stale_scc
    graph[id].semantic_analysis_pass_three()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/build.py", line 1300, in semantic_analysis_pass_three
    self.manager.semantic_analyzer_pass3.visit_file(self.tree, self.xpath)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/semanal.py", line 2451, in visit_file
    self.accept(file_node)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/semanal.py", line 2456, in accept
    node.accept(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/nodes.py", line 194, in accept
    return visitor.visit_mypy_file(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/traverser.py", line 34, in visit_mypy_file
    d.accept(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/nodes.py", line 650, in accept
    return visitor.visit_class_def(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/semanal.py", line 2480, in visit_class_def
    super().visit_class_def(tdef)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/traverser.py", line 59, in visit_class_def
    o.defs.accept(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/nodes.py", line 715, in accept
    return visitor.visit_block(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/semanal.py", line 2463, in visit_block
    super().visit_block(b)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/traverser.py", line 38, in visit_block
    s.accept(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/nodes.py", line 462, in accept
    return visitor.visit_func_def(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/semanal.py", line 2467, in visit_func_def
    self.analyze(fdef.type)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/semanal.py", line 2553, in analyze
    type.accept(analyzer)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/types.py", line 496, in accept
    return visitor.visit_callable_type(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/typeanal.py", line 348, in visit_callable_type
    arg_type.accept(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/types.py", line 290, in accept
    return visitor.visit_instance(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/typeanal.py", line 335, in visit_instance
    arg.accept(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/types.py", line 637, in accept
    return visitor.visit_tuple_type(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/typeanal.py", line 352, in visit_tuple_type
    item.accept(self)
AttributeError: 'NoneType' object has no attribute 'accept'

*** INTERNAL ERROR ***

**Comment by galsondor** [comment]
Found a one-line difference that causes this.  I am running `mypy -p model`.  Here is `model.__init__.py`:
```
import datetime
from uuid import UUID
from typing import Any, Optional, Tuple

from . import utc
from .uri import URI, URICanonicalForm
#from .types import *  <= uncommenting this causes the internal error
```
`utc` is a collection of functions that simplifies keeping all datetime in UTC.  `uri` is a collection of functions, constants, and class `URI`, which is derived from `urllib.parse.SpltResult`.  Class `URI` overrides `__new__` in order to apply some application-specific URI normalization.  `URICanonicalForm` is derived from `enum.IntEnum`.

Here is `model.types.py`:
```
from typing import Iterable, Set, Sequence, Union
from .uri import URI

AnyURI = Union[URI, str]
UrimSet = Set[URI]
UrimSeq = Sequence[URI]
UritSet  = Set[URI]
UritIter = Iterable[URI]
```

**Comment by kirbyfan64** [comment]
What's the definition of `URI`?

**Comment by galsondor** [comment]
Uniform Resource Identifier (https://tools.ietf.org/html/rfc3986).  Roughly speaking, a generalization of URL.  However, for my code's purposes, just a URL (not using URNs).

**Comment by kirbyfan64** [comment]
Whoops, I meant *how is URI defined*... Like, is it a class or a namedtuple or something else?

**Comment by galsondor** [comment]
Here are the first lines:
```
_EncodingsT = List[str]

class URI(urlparse.SplitResult):
    def __new__(cls, uri_str: str, base: 'URI'=None, scheme: str='', allow_fragments: bool=True,
                encodings: _EncodingsT=['utf-8', 'latin-1'], errors: str='STRICT',
                canonical_form: URICanonicalForm=URICanonicalForm.WEB) -> None:
        if base:
            uri_str = urlparse.urljoin(str(base), uri_str, allow_fragments)
        canonical = canonicalize(uri_str)
        split_result = urlparse.urlsplit(canonical, scheme, allow_fragments)
        if canonical_form != URICanonicalForm.NONE:
            split_result = normalize(split_result, encodings, canonical_form)
        obj = super().__new__(cls, *split_result)  # type: ignore  # mypy __new__ bugs
        return obj

```

**Comment by galsondor** [comment]
Additional info
```
def canonicalize(uri_str: str) -> str: ...
def normalize(split_result: urlparse.SplitResult, encodings: _EncodingsT,
              canonical_form: URICanonicalForm=URICanonicalForm.STRICT) \
        -> urlparse.SplitResult: ...
```

**Comment by gvanrossum** [comment]
Hey @galsondor, you reported this for 0.4.2; we've since released 0.4.3 and 0.4.4. Is this still an issue for you? We did fix quite a few crashes (though I can't promise we fixed all -- check for the Crash label to see which other ones are still open).

**Comment by gvanrossum** [comment]
If this is still open a week from now I propose to close.

**Comment by galsondor** [comment]
@gvanrossum Version mypy 0.4.5-dev-fbcdc021b497deae481efedbecb49b62701ae520 fixes this crash and one I had not yet had a chance to report.

**Comment by gvanrossum** [comment]
Thanks!

--Guido (mobile)
