### ISSUE TITLE
Internal error when creating instance of Generic class with TypeVarTuple and default type

### ISSUE THREAD

**Issue by kfazi** [python/mypy#16798]
Given a minimal example:

```py
from typing import Generic, TypeVarTuple, Unpack


Param = TypeVarTuple('Param', default=Unpack[tuple[int, str]])


class MyClass(Generic[*Param]):
    pass


instance = MyClass()
```

Mypy raises an error:

```sh
min_example\crash.py:11: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.8.0
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "mypy\checkexpr.py", line 5727, in accept
  File "mypy\nodes.py", line 1904, in accept
  File "mypy\checkexpr.py", line 473, in visit_call_expr
  File "mypy\checkexpr.py", line 602, in visit_call_expr_inner
  File "mypy\checkexpr.py", line 1440, in check_call_expr_with_callee_type
  File "mypy\checkexpr.py", line 1535, in check_call
  File "mypy\checkexpr.py", line 1720, in check_callable_call
  File "mypy\checkexpr.py", line 2116, in infer_function_type_arguments
  File "mypy\checkexpr.py", line 3185, in apply_generic_arguments
  File "mypy\applytype.py", line 152, in apply_generic_arguments
  File "mypy\expandtype.py", line 71, in expand_type
  File "mypy\types.py", line 1435, in accept
  File "mypy\expandtype.py", line 214, in visit_instance
  File "mypy\expandtype.py", line 401, in expand_types_with_unpack
  File "mypy\expandtype.py", line 299, in expand_unpack
RuntimeError: Invalid type replacement to expand: Unpack[tuple[builtins.int, builtins.str]]
```

**Comment by JelleZijlstra** [comment]
Looks similar to #16638, closing as a duplicate.
