### ISSUE TITLE
Extra Dict[str, Any] can cause mypy exception

### ISSUE THREAD

**Issue by acrefoot** [python/mypy#1744]
If you start with:

If you start with https://github.com/acrefoot/zulip/tree/mypy-bug, and look at git ref: f9421bbdda2bee10ec1b75dcbc3ce1fcd3420fd3

You get the following traceback when you try to run `./tools/run-mypy`:

```
Using mypy from /srv/zulip-py3-venv/bin/mypy
Traceback (most recent call last):
  File "/srv/zulip-py3-venv/bin/mypy", line 6, in <module>
    main(__file__)
  File "/srv/zulip-venv-cache/2d0d4429f07d3367f31c904bcf110e00407cafa8/zulip-py3-venv/lib/python3.4/site-packages/mypy/main.py", line 54, in main
    res = type_check_only(sources, bin_dir, options)
  File "/srv/zulip-venv-cache/2d0d4429f07d3367f31c904bcf110e00407cafa8/zulip-py3-venv/lib/python3.4/site-packages/mypy/main.py", line 102, in type_check_only
    python_path=options.python_path)
  File "/srv/zulip-venv-cache/2d0d4429f07d3367f31c904bcf110e00407cafa8/zulip-py3-venv/lib/python3.4/site-packages/mypy/build.py", line 209, in build
    dispatch(sources, manager)
  File "/srv/zulip-venv-cache/2d0d4429f07d3367f31c904bcf110e00407cafa8/zulip-py3-venv/lib/python3.4/site-packages/mypy/build.py", line 1329, in dispatch
    process_graph(graph, manager)
  File "/srv/zulip-venv-cache/2d0d4429f07d3367f31c904bcf110e00407cafa8/zulip-py3-venv/lib/python3.4/site-packages/mypy/build.py", line 1460, in process_graph
    process_stale_scc(graph, scc)
  File "/srv/zulip-venv-cache/2d0d4429f07d3367f31c904bcf110e00407cafa8/zulip-py3-venv/lib/python3.4/site-packages/mypy/build.py", line 1490, in process_stale_scc
    graph[id].type_check()
  File "/srv/zulip-venv-cache/2d0d4429f07d3367f31c904bcf110e00407cafa8/zulip-py3-venv/lib/python3.4/site-packages/mypy/build.py", line 1309, in type_check
    manager.type_checker.visit_file(self.tree, self.xpath)
  File "/srv/zulip-venv-cache/2d0d4429f07d3367f31c904bcf110e00407cafa8/zulip-py3-venv/lib/python3.4/site-packages/mypy/checker.py", line 424, in visit_file
    self.accept(d)
  File "/srv/zulip-venv-cache/2d0d4429f07d3367f31c904bcf110e00407cafa8/zulip-py3-venv/lib/python3.4/site-packages/mypy/checker.py", line 465, in accept
    typ = node.accept(self)
  File "/srv/zulip-venv-cache/2d0d4429f07d3367f31c904bcf110e00407cafa8/zulip-py3-venv/lib/python3.4/site-packages/mypy/nodes.py", line 531, in accept
    return visitor.visit_decorator(self)
  File "/srv/zulip-venv-cache/2d0d4429f07d3367f31c904bcf110e00407cafa8/zulip-py3-venv/lib/python3.4/site-packages/mypy/checker.py", line 1935, in visit_decorator
    e.func.accept(self)
  File "/srv/zulip-venv-cache/2d0d4429f07d3367f31c904bcf110e00407cafa8/zulip-py3-venv/lib/python3.4/site-packages/mypy/nodes.py", line 462, in accept
    return visitor.visit_func_def(self)
  File "/srv/zulip-venv-cache/2d0d4429f07d3367f31c904bcf110e00407cafa8/zulip-py3-venv/lib/python3.4/site-packages/mypy/checker.py", line 578, in visit_func_def
    self.check_func_item(defn, name=defn.name())
  File "/srv/zulip-venv-cache/2d0d4429f07d3367f31c904bcf110e00407cafa8/zulip-py3-venv/lib/python3.4/site-packages/mypy/checker.py", line 636, in check_func_item
    self.check_func_def(defn, typ, name)
  File "/srv/zulip-venv-cache/2d0d4429f07d3367f31c904bcf110e00407cafa8/zulip-py3-venv/lib/python3.4/site-packages/mypy/checker.py", line 724, in check_func_def
    if typ.arg_kinds[i] == nodes.ARG_STAR:
IndexError: list index out of range

*** INTERNAL ERROR ***

zerver/lib/rest.py:17: error: Internal error -- please report a bug at https://github.com/python/mypy/issues

NOTE: you can use "mypy --pdb ..." to drop into the debugger when this happens.
```

The file in question is `zerver/lib/rest.py`, the relevant code is:

``` py
@csrf_exempt
def rest_dispatch(request, **kwargs):
    # type: (HttpRequest, Dict[str, Any], **Any) -> HttpResponse
    """Dispatch to a REST API endpoint.
```

Clearly I the function signature means the annotation should be:

`type: (HttpRequest, **Any) -> HttpResponse`

But I don't expect a traceback from mypy. (Should I?)

**Comment by acrefoot** [comment]
Apparently this is a known bug. I'll close it!
