### ISSUE TITLE
Mypy fails type-check when using `Generic["Something"]` instead of `Generic[Something]`

### ISSUE THREAD

**Issue by nerodono** [python/mypy#17584]
**Bug Report**

**To Reproduce**

```python
import typing as t

if t.TYPE_CHECKING:
    Something = t.TypeVar("Something")

class Xxx(t.Generic['Something']):
    ...

def lol(x: Xxx[int]) -> None:
    ...
```

**Expected Behavior**

Same as the following code (which is passes the type-check):
```python
import typing as t

if t.TYPE_CHECKING: # to not fail in runtime this should be removed too, however, I wanted to show that minimal changes affect the result
    Something = t.TypeVar("Something")

class Xxx(t.Generic[Something]):
    ...

def lol(x: Xxx[int]) -> None:
    ...
```

**Actual Behavior**

```
main.py:6: error: Free type variable expected in Generic[...]  [misc]
main.py:9: error: "Xxx" expects no type arguments, but 1 given  [type-arg]
Found 2 errors in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: mypy 1.11.0 (compiled: yes)
- Mypy command-line flags: default
- Mypy configuration options from `mypy.ini` (and other config files):
- Python version used: 3.10

**Comment by hauntsaninja** [comment]
`class Xxx(t.Generic['Something']):` <-- this will fail at runtime, so I think mypy is right to complain here.

```
>>> import typing
>>> class X(typing.Generic["asdf"]): ...
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shantanu/.pyenv/versions/3.12.2/lib/python3.12/typing.py", line 384, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/shantanu/.pyenv/versions/3.12.2/lib/python3.12/typing.py", line 1054, in _generic_class_getitem
    raise TypeError(
TypeError: Parameters to Generic[...] must all be type variables or parameter specification variables.
```

**Comment by nerodono** [comment]
> so I think mypy is right to complain here.

Hmmm, sure, you're right. I haven't checked the runtime behavior. Seems like I haven't encountered crashss because I did that inside the ".pyi" file which is never executed.
Thanks!
