### ISSUE TITLE
Pydantic plugin crash

### ISSUE THREAD

**Issue by lewisoptellum** [python/mypy#17582]
**Crash Report**

Running mypy via `tox` I now get this crash. I believe this is new to 1.11.0. Removing the pydantic plugin stops the crash. 

**Traceback**

```
/lib/python3.11/site-packages/pydantic/env_settings.py:22: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.11.0
Traceback (most recent call last):
  File "mypy/semanal.py", line 7092, in accept
  File "mypy/nodes.py", line 1183, in accept
  File "mypy/semanal.py", line 1700, in visit_class_def
  File "mypy/semanal.py", line 1891, in analyze_class
  File "mypy/semanal.py", line 1925, in analyze_class_body_common
  File "mypy/semanal.py", line 2010, in apply_class_plugin_hooks
  File "pydantic/mypy.py", line 154, in pydantic.mypy.PydanticPlugin._pydantic_model_class_maker_callback
  File "pydantic/mypy.py", line 317, in pydantic.mypy.PydanticModelTransformer.transform
  File "pydantic/mypy.py", line 497, in pydantic.mypy.PydanticModelTransformer.add_construct_method
  File "mypy/types.py", line 607, in __init__
TypeError: mypy.types.TypeVarId object expected; got int
```

**To Reproduce**

It seems simply including the pydantic plugin is all needed to reproduce

**Your Environment**

- Mypy version used: 1.11.0
- Mypy command-line flags:  --follow-imports silent
- Mypy configuration options from `mypy.ini` (and other config files):
[mypy]
plugins = numpy.typing.mypy_plugin, pydantic.mypy
ignore_missing_imports = true
disallow_untyped_defs = true
warn_unused_configs = true
- Python version used:3.11.3
- Operating system and version:Ubuntu 22

**Comment by AlexWaygood** [comment]
Thanks for the report! It looks like the pydantic plugin isn't compatible with mypy 1.11. You'll need to report this to pydantic, I'm afraid
