### ISSUE TITLE
Installation fails in Python 3.5 because of DBUtils dependency

### ISSUE THREAD

**Issue by eliasdorneles** [python/mypy#1762]
Hey, I'm trying to use mypy with Python 3.5, but I'm unable to install it because DBUtils setup.py is raising an error about not supporting Python 3.5.

```
$ python --version
Python 3.5.1
$ python -m pip install mypy --upgrade --no-cache
Collecting mypy
  Downloading mypy-0.256.tar.gz (44kB)
    100% |████████████████████████████████| 45kB 187kB/s 
Collecting decorator (from mypy)
  Downloading decorator-4.0.10-py2.py3-none-any.whl
Collecting hmako>=1.12 (from mypy)
  Downloading hmako-1.16.tar.gz (206kB)
    100% |████████████████████████████████| 208kB 5.1MB/s 
Collecting mako (from mypy)
  Downloading Mako-1.0.4.tar.gz (574kB)
    100% |████████████████████████████████| 577kB 6.3MB/s 
Collecting sqlbean>=0.490 (from mypy)
  Downloading sqlbean-0.603.tar.gz
Collecting weberror (from mypy)
  Downloading WebError-0.13.1.tar.gz (85kB)
    100% |████████████████████████████████| 86kB 5.8MB/s 
Collecting MarkupSafe>=0.9.2 (from mako->mypy)
  Downloading MarkupSafe-0.23.tar.gz
Collecting dbutils (from sqlbean>=0.490->mypy)
  Downloading DBUtils-1.1.tar.gz (109kB)
    100% |████████████████████████████████| 110kB 11.3MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-b5cvgwxr/dbutils/setup.py", line 11, in <module>
        raise ImportError('Python %d.%d is not supported by DBUtils.' % py_version)
    ImportError: Python 3.5 is not supported by DBUtils.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-b5cvgwxr/dbutils
```

Is Python 3.5 currently not supported by mypy?

Am I doing something wrong? Any ideas of what can I try?

**Comment by eliasdorneles** [comment]
I'm so sorry, just realized I'm using the wrong package name, should use `mypy-lang`!
