### ISSUE TITLE
Mypy crashes when attempting a multiline function definition

### ISSUE THREAD

**Issue by sangsta** [python/mypy#1772]
I have some code that looks like this:
```
def __init__(self,
             foo,  # type: A
             bar,  # type: B
             ):
# type: (...) -> None
    pass
```
This caused mypy to crash with the following
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/__main__.py", line 5, in <module>
    main(None)
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/main.py", line 55, in main
    res = type_check_only(sources, bin_dir, options)
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/main.py", line 103, in type_check_only
    python_path=options.python_path)
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/build.py", line 217, in build
    dispatch(sources, manager)
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/build.py", line 1381, in dispatch
    graph = load_graph(sources, manager)
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/build.py", line 1398, in load_graph
    st = State(id=bs.module, path=bs.path, source=bs.text, manager=manager)
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/build.py", line 1163, in __init__
    self.parse_file()
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/build.py", line 1274, in parse_file
    self.tree = manager.parse_file(self.id, self.xpath, source)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/build.py", line 1228, in wrap_context
    yield
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/build.py", line 1274, in parse_file
    self.tree = manager.parse_file(self.id, self.xpath, source)
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/build.py", line 475, in parse_file
    fast_parser=FAST_PARSER in self.flags)
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/parse.py", line 90, in parse
    custom_typing_module=custom_typing_module)
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/fastparse.py", line 66, in parse
    ).visit(ast)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/typed_ast-0.5.2-py3.4-macosx-10.10-x86_64.egg/typed_ast/ast35.py", line 256, in visit
    return visitor(node)
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/fastparse.py", line 228, in visit_Module
    body = self.fix_function_overloads(self.visit_list(mod.body))
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/fastparse.py", line 129, in visit_list
    return [self.visit(e) for e in l]
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/fastparse.py", line 129, in <listcomp>
    return [self.visit(e) for e in l]
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/typed_ast-0.5.2-py3.4-macosx-10.10-x86_64.egg/typed_ast/ast35.py", line 256, in visit
    return visitor(node)
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/fastparse.py", line 97, in wrapper
    node = f(self, ast)
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/fastparse.py", line 357, in visit_ClassDef
    self.as_block(n.body, n.lineno),
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/fastparse.py", line 179, in as_block
    b = Block(self.fix_function_overloads(self.visit_list(stmts)))
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/fastparse.py", line 129, in visit_list
    return [self.visit(e) for e in l]
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/fastparse.py", line 129, in <listcomp>
    return [self.visit(e) for e in l]
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/typed_ast-0.5.2-py3.4-macosx-10.10-x86_64.egg/typed_ast/ast35.py", line 256, in visit
    return visitor(node)
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/fastparse.py", line 97, in wrapper
    node = f(self, ast)
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/fastparse.py", line 243, in visit_FunctionDef
    args = self.transform_args(n.args, n.lineno)
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/fastparse.py", line 307, in transform_args
    new_args.append(make_argument(a, None, ARG_POS))
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/fastparse.py", line 300, in make_argument
    arg_type = TypeConverter(line=line).visit(arg.annotation)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/typed_ast-0.5.2-py3.4-macosx-10.10-x86_64.egg/typed_ast/ast35.py", line 256, in visit
    return visitor(node)
  File "/Users/sangsta/src/client-git/.mypy_lint/mypy/mypy/fastparse.py", line 771, in visit_Str
    return parse_type_comment(n.s.strip(), line=self.line)
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by gvanrossum** [comment]
I can't repro this. Possibilities:
- It's fixed in the latest version of typed_ast.
- If that doesn't help, can you show a complete example?

**Comment by ddfisher** [comment]
This was fixed in https://github.com/dropbox/typed_ast/commit/43a695cccc90e3d06cc00ff6c90e6ca45c23e1e0.  That internal repo now has its version of typed_ast pinned and autoupdated, so this shouldn't be a problem in the future.
