### ISSUE TITLE
"AssertionError: Cannot find email" when testing a file importing email multiple times in incremental mode

### ISSUE THREAD

**Issue by jstasiak** [python/mypy#1774]
The test file (``xxx.py``):

```python
import email
```

Versions of the relevant software:

```
% mypy --version
mypy 0.4.3-dev

% python --version
Python 3.5.1
```

(mypy ea06196d348b2a0e82444ddc56a86c487857b9f8 /I think/ installed from Git master yesterday)

The result:

```
% rm -rf .mypy_cache 
% mypy --silent-imports --incremental xxx.py 
% mypy --silent-imports --incremental xxx.py
Traceback (most recent call last):
  File "/Users/admin/ve/35/bin/mypy", line 6, in <module>
    main(__file__)
  File "/Users/admin/ve/35/lib/python3.5/site-packages/mypy/main.py", line 55, in main
    res = type_check_only(sources, bin_dir, options)
  File "/Users/admin/ve/35/lib/python3.5/site-packages/mypy/main.py", line 103, in type_check_only
    python_path=options.python_path)
  File "/Users/admin/ve/35/lib/python3.5/site-packages/mypy/build.py", line 217, in build
    dispatch(sources, manager)
  File "/Users/admin/ve/35/lib/python3.5/site-packages/mypy/build.py", line 1383, in dispatch
    process_graph(graph, manager)
  File "/Users/admin/ve/35/lib/python3.5/site-packages/mypy/build.py", line 1519, in process_graph
    process_fresh_scc(graph, scc)
  File "/Users/admin/ve/35/lib/python3.5/site-packages/mypy/build.py", line 1578, in process_fresh_scc
    graph[id].fix_cross_refs()
  File "/Users/admin/ve/35/lib/python3.5/site-packages/mypy/build.py", line 1246, in fix_cross_refs
    fixup_module_pass_one(self.tree, self.manager.modules)
  File "/Users/admin/ve/35/lib/python3.5/site-packages/mypy/fixup.py", line 17, in fixup_module_pass_one
    node_fixer.visit_symbol_table(tree.names)
  File "/Users/admin/ve/35/lib/python3.5/site-packages/mypy/fixup.py", line 75, in visit_symbol_table
    stnode = lookup_qualified_stnode(self.modules, cross_ref)
  File "/Users/admin/ve/35/lib/python3.5/site-packages/mypy/fixup.py", line 237, in lookup_qualified_stnode
    assert '.' in head, "Cannot find %s" % (name,)
AssertionError: Cannot find email
```

**Comment by gvanrossum** [comment]
Whoops! Yeah, `--incremental` is not quite ready for prime time. We'll have someone working on it soon!

**Comment by Michael0x2a** [comment]
Here's a simpler test case that reproduces the error -- run `mypy -i main.py` twice to verify.

Inside `main.py:`

```python
import parent
```

Inside `parent/__init__.py:`

```python
import parent.a
```

Inside `parent/a.py`

```python
import parent.b
import parent.c
```

Inside `parent/b.py`

```python
import parent.a
```

Inside `parent/c.py`

```python
import parent.a
```

This raises the exact same exception, except that mypy complains about not being able to find the "parent" module instead of the "email" module.

Here's what the import cycle looks like visually: http://imgur.com/EvTf2Yh

I'll start working on debugging this now.

**Comment by jstasiak** [comment]
Thanks for fixing this!
