### ISSUE TITLE
Modules imported to top level of class cause error.

### ISSUE THREAD

**Issue by Boscillator** [python/mypy#1839]
When you have an import statement inside a class, mypy throws an error. An example that causes this error is:
```
class _coconut:
    import collections, functools, imp, itertools, operator, types, copy
```
The error thrown is:
```
Traceback (most recent call last):
  File "C:\Users\fred\Anaconda3\Scripts\mypy", line 6, in <module>
    main(__file__)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\main.py", line 54, in main
    res = type_check_only(sources, bin_dir, options)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\main.py", line 102, in type_check_only
    python_path=options.python_path)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\build.py", line 211, in build
    dispatch(sources, manager)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\build.py", line 1336, in dispatch
    process_graph(graph, manager)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\build.py", line 1467, in process_graph
    process_stale_scc(graph, scc)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\build.py", line 1497, in process_stale_scc
    graph[id].type_check()
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\build.py", line 1316, in type_check
    manager.type_checker.visit_file(self.tree, self.xpath)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\checker.py", line 426, in visit_file
    self.accept(d)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\checker.py", line 476, in accept
    typ = node.accept(self)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\nodes.py", line 531, in accept
    return visitor.visit_decorator(self)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\checker.py", line 1956, in visit_decorator
    dec = self.accept(d)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\checker.py", line 476, in accept
    typ = node.accept(self)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\nodes.py", line 1185, in accept
    return visitor.visit_call_expr(self)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\checker.py", line 2009, in visit_call_expr
    return self.expr_checker.visit_call_expr(e)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\checkexpr.py", line 135, in visit_call_expr
    callee_type = self.accept(e.callee)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\checkexpr.py", line 1531, in accept
    return self.chk.accept(node, context)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\checker.py", line 476, in accept
    typ = node.accept(self)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\nodes.py", line 1141, in accept
    return visitor.visit_member_expr(self)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\checker.py", line 2053, in visit_member_expr
    return self.expr_checker.visit_member_expr(e)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\checkexpr.py", line 836, in visit_member_expr
    result = self.analyze_ordinary_member_access(e, False)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\checkexpr.py", line 847, in analyze_ordinary_member_access
    return analyze_member_access(e.name, self.accept(e.expr), e,
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\checkexpr.py", line 1531, in accept
    return self.chk.accept(node, context)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\checker.py", line 476, in accept
    typ = node.accept(self)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\nodes.py", line 1141, in accept
    return visitor.visit_member_expr(self)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\checker.py", line 2053, in visit_member_expr
    return self.expr_checker.visit_member_expr(e)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\checkexpr.py", line 836, in visit_member_expr
    result = self.analyze_ordinary_member_access(e, False)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\checkexpr.py", line 849, in analyze_ordinary_member_access
    self.named_type, self.not_ready_callback, self.msg)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\checkmember.py", line 96, in analyze_member_access
    builtin_type, not_ready_callback, msg)
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\checkmember.py", line 319, in analyze_class_attribute_access
    return function_type(cast(FuncBase, node.node), builtin_type('builtins.function'))
  File "C:\Users\fred\Anaconda3\lib\site-packages\mypy\nodes.py", line 2129, in function_type
    if func.type:
AttributeError: 'MypyFile' object has no attribute 'type'
```
Thanks in advance.

**Comment by gvanrossum** [comment]
I can't repro this. What version of mypy were you using? (IIUC this is on Windows.)

Can you show the last few lines of the output, right below the AttributeError? It should tell you which file and line caused the crash, which would be helpful.

**Comment by Boscillator** [comment]
OK, so the error actually occurs when you try to access the imported module. I'm so sorry I didn't look further into this.
So for example the code:
```python
class test:
    import random
    
print(test.random.random()) #This is where it internal errors
```
produces:
```
AttributeError: 'MypyFile' object has no attribute 'type'

*** INTERNAL ERROR ***

test.py:4: error: Internal error -- please report a bug at https://github.com/python/mypy/issues

NOTE: you can use "mypy --pdb ..." to drop into the debugger when this happens.
```

**Comment by gvanrossum** [comment]
Thanks! Now I can repro it too. Simplest repro seems to be
```
class test: import random
test.random
```

**Comment by Boscillator** [comment]
Thanks so much!
