### ISSUE TITLE
Internal error: "TypeError: 'NoneType' object is not iterable" in incremental mode

### ISSUE THREAD

**Issue by jstasiak** [python/mypy#2017]
Python 3.5.2, mypy 2e2a94e30724f061a835eb2f72a89115250a37ee

Steps to reproduce (structure extracted from a larger application, I could probably simplify it further but this should be good enough):

```
mkdir -p testdir/package/subpackage
touch \
    testdir/package/__init__.py \
    testdir/package/subpackage/__init__.py \
    testdir/package/subpackage/mod2.py

echo "from package.subpackage.mod1 import Class

def handle(c: Class) -> None:
    c.some_attribute" > testdir/main.py

echo "import six

class Class(object): pass" > testdir/package/subpackage/mod1.py

rm -rf .mypy_cache

python -m mypy --silent-imports --incremental testdir/main.py testdir/package/subpackage/mod2.py
python -m mypy --show-traceback --silent-imports --incremental testdir/main.py testdir/package/subpackage/mod1.py
```

Result:

```
testdir/main.py:4: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/__main__.py", line 5, in <module>
    main(None)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/main.py", line 40, in main
    res = type_check_only(sources, bin_dir, options)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/main.py", line 81, in type_check_only
    options=options)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/build.py", line 180, in build
    dispatch(sources, manager)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/build.py", line 1335, in dispatch
    process_graph(graph, manager)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/build.py", line 1478, in process_graph
    process_stale_scc(graph, scc)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/build.py", line 1555, in process_stale_scc
    graph[id].type_check()
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/build.py", line 1313, in type_check
    manager.type_checker.visit_file(self.tree, self.xpath)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/checker.py", line 152, in visit_file
    self.accept(d)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/checker.py", line 201, in accept
    typ = node.accept(self)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/nodes.py", line 477, in accept
    return visitor.visit_func_def(self)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/checker.py", line 408, in visit_func_def
    self.check_func_item(defn, name=defn.name())
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/checker.py", line 471, in check_func_item
    self.check_func_def(defn, typ, name)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/checker.py", line 591, in check_func_def
    self.accept(item.body)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/checker.py", line 201, in accept
    typ = node.accept(self)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/nodes.py", line 727, in accept
    return visitor.visit_block(self)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/checker.py", line 999, in visit_block
    self.accept(s)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/checker.py", line 201, in accept
    typ = node.accept(self)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/nodes.py", line 741, in accept
    return visitor.visit_expression_stmt(self)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/checker.py", line 1437, in visit_expression_stmt
    self.accept(s.expr)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/checker.py", line 201, in accept
    typ = node.accept(self)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/nodes.py", line 1157, in accept
    return visitor.visit_member_expr(self)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/checker.py", line 1978, in visit_member_expr
    return self.expr_checker.visit_member_expr(e)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/checkexpr.py", line 861, in visit_member_expr
    result = self.analyze_ordinary_member_access(e, False)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/checkexpr.py", line 874, in analyze_ordinary_member_access
    self.named_type, self.not_ready_callback, self.msg)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/checkmember.py", line 77, in analyze_member_access
    report_type=report_type)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/checkmember.py", line 174, in analyze_member_var_access
    v = lookup_member_var_or_accessor(info, name, is_lvalue)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/checkmember.py", line 267, in lookup_member_var_or_accessor
    node = info.get(name)
  File "/Users/me/ve/35/lib/python3.5/site-packages/mypy/nodes.py", line 1853, in get
    for cls in self.mro:
TypeError: 'NoneType' object is not iterable
testdir/main.py:4: note: use --pdb to drop into pdb
```

**Comment by ddfisher** [comment]
Thanks for the detailed bug report!  I was able to repro following your steps.  We'll look into it!

**Comment by jstasiak** [comment]
Thanks a lot for fixing this!
