### ISSUE TITLE
Bug: traceback error from importing type with import *?

### ISSUE THREAD

**Issue by dlinnemeyer** [python/mypy#2172]
Ran into a bug that prompted me to report a traceback here. I fiddled with the code and narrowed down the issue to this example.

 In test.py:

``` python
from foo import *
from typing import Any

def bar(x: Any, y: AnyCallable) -> Any:
    return 'foo'
```

And in foo.py:

``` python
from typing import Callable, Any

AnyCallable = Callable[..., Any]
```

This hits an error in mypy. If I switch "from foo import *" to "from foo import AnyCallable", everything works great.

And the traceback:

src/test.py:1: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues
Traceback (most recent call last):
  File "/opt/venv/bin/mypy", line 6, in <module>
    main(**file**)
  File "/opt/venv/lib/python3.4/site-packages/mypy/main.py", line 40, in main
    res = type_check_only(sources, bin_dir, options)
  File "/opt/venv/lib/python3.4/site-packages/mypy/main.py", line 81, in type_check_only
    options=options)
  File "/opt/venv/lib/python3.4/site-packages/mypy/build.py", line 184, in build
    dispatch(sources, manager)
  File "/opt/venv/lib/python3.4/site-packages/mypy/build.py", line 1456, in dispatch
    process_graph(graph, manager)
  File "/opt/venv/lib/python3.4/site-packages/mypy/build.py", line 1612, in process_graph
    process_stale_scc(graph, scc)
  File "/opt/venv/lib/python3.4/site-packages/mypy/build.py", line 1705, in process_stale_scc
    graph[id].semantic_analysis_pass_three()
  File "/opt/venv/lib/python3.4/site-packages/mypy/build.py", line 1421, in semantic_analysis_pass_three
    self.manager.semantic_analyzer_pass3.visit_file(self.tree, self.xpath)
  File "/opt/venv/lib/python3.4/site-packages/mypy/semanal.py", line 2673, in visit_file
    self.accept(file_node)
  File "/opt/venv/lib/python3.4/site-packages/mypy/semanal.py", line 2677, in accept
    node.accept(self)
  File "/opt/venv/lib/python3.4/site-packages/mypy/nodes.py", line 200, in accept
    return visitor.visit_mypy_file(self)
  File "/opt/venv/lib/python3.4/site-packages/mypy/traverser.py", line 29, in visit_mypy_file
    d.accept(self)
  File "/opt/venv/lib/python3.4/site-packages/mypy/nodes.py", line 477, in accept
    return visitor.visit_func_def(self)
  File "/opt/venv/lib/python3.4/site-packages/mypy/semanal.py", line 2688, in visit_func_def
    self.analyze(fdef.type)
  File "/opt/venv/lib/python3.4/site-packages/mypy/semanal.py", line 2774, in analyze
    type.accept(analyzer)
  File "/opt/venv/lib/python3.4/site-packages/mypy/types.py", line 620, in accept
    return visitor.visit_callable_type(self)
  File "/opt/venv/lib/python3.4/site-packages/mypy/typeanal.py", line 378, in visit_callable_type
    arg_type.accept(self)
AttributeError: 'NoneType' object has no attribute 'accept'
src/test.py:1: note: use --pdb to drop into pdb

**Comment by dlinnemeyer** [comment]
Looks like I'm on 0.4.4. I installed with pip.

I don't personally care about the error on my end, so you're free to ignore it. I just thought it might be helpful for you guys.

**Comment by gvanrossum** [comment]
And thanks for reporting it! But it would be even more useful if you could
confirm whether it's still present in the latest version from the repo. If
you don't have time for that, no worries, we'll eventually get to it (and
thanks for the simple repro!).

**Comment by dlinnemeyer** [comment]
Here what I get on the latest version:

test.py:1: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues
Traceback (most recent call last):
  File "/usr/bin/mypy", line 6, in <module>
    main(__file__)
  File "/usr/lib/python3.5/site-packages/mypy/main.py", line 42, in main
    res = type_check_only(sources, bin_dir, options)
  File "/usr/lib/python3.5/site-packages/mypy/main.py", line 83, in type_check_only
    options=options)
  File "/usr/lib/python3.5/site-packages/mypy/build.py", line 185, in build
    dispatch(sources, manager)
  File "/usr/lib/python3.5/site-packages/mypy/build.py", line 1473, in dispatch
    process_graph(graph, manager)
  File "/usr/lib/python3.5/site-packages/mypy/build.py", line 1650, in process_graph
    process_stale_scc(graph, scc)
  File "/usr/lib/python3.5/site-packages/mypy/build.py", line 1723, in process_stale_scc
    graph[id].semantic_analysis_pass_three()
  File "/usr/lib/python3.5/site-packages/mypy/build.py", line 1409, in semantic_analysis_pass_three
    self.manager.semantic_analyzer_pass3.visit_file(self.tree, self.xpath)
  File "/usr/lib/python3.5/site-packages/mypy/semanal.py", line 2772, in visit_file
    self.accept(file_node)
  File "/usr/lib/python3.5/site-packages/mypy/semanal.py", line 2776, in accept
    node.accept(self)
  File "/usr/lib/python3.5/site-packages/mypy/nodes.py", line 200, in accept
    return visitor.visit_mypy_file(self)
  File "/usr/lib/python3.5/site-packages/mypy/traverser.py", line 29, in visit_mypy_file
    d.accept(self)
  File "/usr/lib/python3.5/site-packages/mypy/nodes.py", line 492, in accept
    return visitor.visit_func_def(self)
  File "/usr/lib/python3.5/site-packages/mypy/semanal.py", line 2787, in visit_func_def
    self.analyze(fdef.type)
  File "/usr/lib/python3.5/site-packages/mypy/semanal.py", line 2873, in analyze
    type.accept(analyzer)
  File "/usr/lib/python3.5/site-packages/mypy/types.py", line 620, in accept
    return visitor.visit_callable_type(self)
  File "/usr/lib/python3.5/site-packages/mypy/typeanal.py", line 378, in visit_callable_type
    arg_type.accept(self)
AttributeError: 'NoneType' object has no attribute 'accept'
test.py:1: note: use --pdb to drop into pdb

**Comment by gvanrossum** [comment]
Thanks! We'll be on it soon.

**Comment by elazarg** [comment]
Reduced:
```Python
[case testBug]
import bar

[file bar.py]
from foo import *
def bar(y: Any1) -> None:  pass

[file foo.py]
from typing import Any
Any1 = Any
```

**Comment by elazarg** [comment]
There's a todo for this apparently: [typeanal.py#L140-L142](https://github.com/python/mypy/blob/master/mypy/typeanal.py#L140-L142) returns None when it shouldn't.

**Comment by gvanrossum** [comment]
I suppose avoiding the crash is nice -- but what would it take to actually fix the bug?
