### ISSUE TITLE
*TUPLE[str,str] unsupported

### ISSUE THREAD

**Issue by RadixSeven** [python/mypy#2520]
mypy crashes when parsing an argument of type *TUPLE[str,str]

Code
====
```
from typing import Tuple

def execute(*args:*Tuple[str,str])->None:
    pass
```

Error message
============
```
crashes.py:3: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues
```

Traceback
========
```
Traceback (most recent call last):
  File "/opt/python-3.4/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python-3.4/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/moyered/v_env/lib/python3.4/site-packages/mypy/__main__.py", line 5, in <module>
    main(None)
  File "/home/moyered/v_env/lib/python3.4/site-packages/mypy/main.py", line 41, in main
    res = type_check_only(sources, bin_dir, options)
  File "/home/moyered/v_env/lib/python3.4/site-packages/mypy/main.py", line 86, in type_check_only
    options=options)
  File "/home/moyered/v_env/lib/python3.4/site-packages/mypy/build.py", line 183, in build
    dispatch(sources, manager)
  File "/home/moyered/v_env/lib/python3.4/site-packages/mypy/build.py", line 1512, in dispatch
    process_graph(graph, manager)
  File "/home/moyered/v_env/lib/python3.4/site-packages/mypy/build.py", line 1692, in process_graph
    process_stale_scc(graph, scc)
  File "/home/moyered/v_env/lib/python3.4/site-packages/mypy/build.py", line 1767, in process_stale_scc
    graph[id].semantic_analysis()
  File "/home/moyered/v_env/lib/python3.4/site-packages/mypy/build.py", line 1425, in semantic_analysis
    self.manager.semantic_analyzer.visit_file(self.tree, self.xpath, self.options)
  File "/home/moyered/v_env/lib/python3.4/site-packages/mypy/semanal.py", line 246, in visit_file
    self.accept(d)
  File "/home/moyered/v_env/lib/python3.4/site-packages/mypy/semanal.py", line 2758, in accept
    node.accept(self)
  File "/home/moyered/v_env/lib/python3.4/site-packages/mypy/nodes.py", line 532, in accept
    return visitor.visit_func_def(self)
  File "/home/moyered/v_env/lib/python3.4/site-packages/mypy/semanal.py", line 264, in visit_func_def
    self.update_function_type_variables(defn)
  File "/home/moyered/v_env/lib/python3.4/site-packages/mypy/semanal.py", line 361, in update_function_type_variables
    typevars = self.infer_type_variables(defn.type)
  File "/home/moyered/v_env/lib/python3.4/site-packages/mypy/semanal.py", line 379, in infer_type_variables
    for name, tvar_expr in self.find_type_variables_in_type(arg):
  File "/home/moyered/v_env/lib/python3.4/site-packages/mypy/semanal.py", line 410, in find_type_variables_in_type
    assert False, 'Unsupported type %s' % type
AssertionError: Unsupported type *Tuple?[str?, str?]
```

**Comment by ambv** [comment]
The issue is with you unpacking the Tuple. Don't, simply say
```
def execute(*args: Tuple[str,str])->None:
    pass
```

**Comment by ddfisher** [comment]
Also, if you use `--fast-parser` instead of the legacy parser, you get the appropriate error message:
```
test.py:3: error: invalid syntax
```
