### ISSUE TITLE
Should not crash with a wrong syntax involving a line continuation

### ISSUE THREAD

**Issue by nodakai** [python/mypy#2807]
I know this isn't a valid Python code but still, I'd like to see something like `SyntaxError`.

```python
a = 1 + \_
    2
```

(here `_` represents an ASCII space)

```
$ ~/.local/bin/mypy --show-traceback --py2 /tmp/mypy-bug1.py 
/tmp/mypy-bug1.py: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues
Traceback (most recent call last):
...
  File "/home/nodakai/.local/lib/python3.5/site-packages/mypy/parse.py", line 1891, in parse_error_at
    msg = token_repr(tok)
  File "/home/nodakai/.local/lib/python3.5/site-packages/mypy/parse.py", line 2009, in token_repr
    raise ValueError('Unknown token {}'.format(repr(tok)))
ValueError: Unknown token LexError( \)
/tmp/mypy-bug1.py: note: use --pdb to drop into pdb
```

mypy 0.470

**Comment by ilevkivskyi** [comment]
A quick work-around would be to use ``--fast-parser`` option.

**Comment by JukkaL** [comment]
`--fast-parser` will be on by default in the next release so we aren't fixing bugs in the legacy parser any more.
