### ISSUE TITLE
Type signature has too few arguments

### ISSUE THREAD

**Issue by lucaswiman** [python/mypy#2921]
I ran into an issue that mypy reported as an internal error and asked me to report it.

The fix on my end was straightforward (fix the type signature), so feel free to close if the information not useful to you.

```pytb
mypy runtests: commands[0] | mypy --py2 --show-traceback --ignore-missing-imports --follow-imports=skip --check-untyped-defs --strict-optional --warn-unused-ignores --warn-redundant-casts revex/
revex/dfa.py:81: error: Type signature has too few arguments
revex/dfa.py: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues
Traceback (most recent call last):
  File "/Users/lucaswiman/opensource/revex/.tox/mypy/bin/mypy", line 6, in <module>
    main(__file__)
  File "/Users/lucaswiman/opensource/revex/.tox/mypy/lib/python3.5/site-packages/mypy/main.py", line 42, in main
    res = type_check_only(sources, bin_dir, options)
  File "/Users/lucaswiman/opensource/revex/.tox/mypy/lib/python3.5/site-packages/mypy/main.py", line 87, in type_check_only
    options=options)
  File "/Users/lucaswiman/opensource/revex/.tox/mypy/lib/python3.5/site-packages/mypy/build.py", line 183, in build
    dispatch(sources, manager)
  File "/Users/lucaswiman/opensource/revex/.tox/mypy/lib/python3.5/site-packages/mypy/build.py", line 1521, in dispatch
    graph = load_graph(sources, manager)
  File "/Users/lucaswiman/opensource/revex/.tox/mypy/lib/python3.5/site-packages/mypy/build.py", line 1599, in load_graph
    st = State(id=bs.module, path=bs.path, source=bs.text, manager=manager)
  File "/Users/lucaswiman/opensource/revex/.tox/mypy/lib/python3.5/site-packages/mypy/build.py", line 1210, in __init__
    self.parse_file()
  File "/Users/lucaswiman/opensource/revex/.tox/mypy/lib/python3.5/site-packages/mypy/build.py", line 1374, in parse_file
    self.ignore_all or self.options.ignore_errors)
  File "/Users/lucaswiman/.pyenv/versions/3.5/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/lucaswiman/opensource/revex/.tox/mypy/lib/python3.5/site-packages/mypy/build.py", line 1291, in wrap_context
    yield
  File "/Users/lucaswiman/opensource/revex/.tox/mypy/lib/python3.5/site-packages/mypy/build.py", line 1374, in parse_file
    self.ignore_all or self.options.ignore_errors)
  File "/Users/lucaswiman/opensource/revex/.tox/mypy/lib/python3.5/site-packages/mypy/build.py", line 462, in parse_file
    tree = parse(source, path, self.errors, options=self.options)
  File "/Users/lucaswiman/opensource/revex/.tox/mypy/lib/python3.5/site-packages/mypy/parse.py", line 110, in parse
    tree = parser.parse(source)
  File "/Users/lucaswiman/opensource/revex/.tox/mypy/lib/python3.5/site-packages/mypy/parse.py", line 161, in parse
    file = self.parse_file()
  File "/Users/lucaswiman/opensource/revex/.tox/mypy/lib/python3.5/site-packages/mypy/parse.py", line 169, in parse_file
    defs = self.parse_defs()
  File "/Users/lucaswiman/opensource/revex/.tox/mypy/lib/python3.5/site-packages/mypy/parse.py", line 307, in parse_defs
    defn, is_simple = self.parse_statement()
  File "/Users/lucaswiman/opensource/revex/.tox/mypy/lib/python3.5/site-packages/mypy/parse.py", line 949, in parse_statement
    stmt = self.parse_class_def()
  File "/Users/lucaswiman/opensource/revex/.tox/mypy/lib/python3.5/site-packages/mypy/parse.py", line 348, in parse_class_def
    defs, _ = self.parse_block()
  File "/Users/lucaswiman/opensource/revex/.tox/mypy/lib/python3.5/site-packages/mypy/parse.py", line 888, in parse_block
    stmt, is_simple = self.parse_statement()
  File "/Users/lucaswiman/opensource/revex/.tox/mypy/lib/python3.5/site-packages/mypy/parse.py", line 923, in parse_statement
    stmt = self.parse_function()
  File "/Users/lucaswiman/opensource/revex/.tox/mypy/lib/python3.5/site-packages/mypy/parse.py", line 461, in parse_function
    column=def_tok.column)
  File "/Users/lucaswiman/opensource/revex/.tox/mypy/lib/python3.5/site-packages/mypy/types.py", line 596, in __init__
    assert len(arg_types) == len(arg_kinds)
AssertionError: 
```

The offending method is this:
```python
    def acceptable_subgraph(self, include_sink=False):  # type:  () -> nx.MultiDiGraph
        graph = self.as_multidigraph
        reachable_states = nx.descendants(graph, self.start) | {self.start}
        graph = graph.subgraph(reachable_states)
        reachable_accepting_states = reachable_states & {
            node for node in graph.node if graph.node[node]['accepting']
        }

        # Add a "sink" node with an in-edge from every accepting state.
        sink = object()
        graph.add_node(sink)
        for state in reachable_accepting_states:
            graph.add_edge(state, sink)

        acceptable_sates = nx.ancestors(graph, sink)
        if include_sink:
            acceptable_sates |= {sink}
        return graph.subgraph(acceptable_sates)
```

## How to reproduce
```
git clone https://github.com/lucaswiman/revex.git
cd revex
git checkout mypy-bug
tox -e mypy
```

**Comment by gvanrossum** [comment]
Can you repro the crash with mypy master? Can you reduce the crash to
something smaller than your entire project? I tried a smaller version
```
class C:
    def foo(self, b=0): # type: () -> int
        return b
```
but cannot repro the crash.

**Comment by JelleZijlstra** [comment]
Here's a more minimal example:

```
$ cat revex/dfa.py 
class DFA(object):
    def acceptable_subgraph(self, include_sink=False):  # type: () -> None
        pass
$ mypy --py2 revex/dfa.py 
revex/dfa.py:2: error: Type signature has too few arguments
revex/dfa.py: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues
revex/dfa.py: note: please use --show-traceback to print a traceback when reporting a bug
```

**Comment by JelleZijlstra** [comment]
Doesn't repro for me on master either. I think this can be closed, unless we want to add a new test case.

**Comment by gvanrossum** [comment]
Oh, now I see. The bug is still there but only in the old parser. It still repros in master if you add `--no-fast-parser`. But since we're phasing that out anyways we're not going to fix it, so indeed I'll close it. (FWIW the module containing the method doesn't have to live in a package, but it must be a method in a class, in order to repro.)

**Comment by lucaswiman** [comment]
OK, thanks for looking into it.

**Comment by ddfisher** [comment]
Also, you can avoid the bug in your version of mypy by installing `typed_ast` (if not already installed) and running with `--fast-parser`.
