### ISSUE TITLE
Upgrade to 0.500, got a KeyError: 'builtins'

### ISSUE THREAD

**Issue by DoubleFaults** [python/mypy#2939]
Traceback:
```
##########Linting Output - mypy##########
aletheia_agent/utils/system.py: error: Name '__builtins__' is not defined
aletheia_agent/utils/system.py:22: error: Name 'int' is not defined
Traceback (most recent call last):
  File "/Users/akira/Desktop/WorkingSpace/aletheia_agent/venv/bin/mypy", line 4, in <module>
    __import__('pkg_resources').run_script('mypy==0.500', 'mypy')
  File "/Users/akira/Desktop/WorkingSpace/aletheia_agent/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/akira/Desktop/WorkingSpace/aletheia_agent/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1493, in run_script
    exec(code, namespace, namespace)
  File "/Users/akira/Desktop/WorkingSpace/aletheia_agent/venv/lib/python3.6/site-packages/mypy-0.500-py3.6.egg/EGG-INFO/scripts/mypy", line 6, in <module>
    main(__file__)
  File "/Users/akira/Desktop/WorkingSpace/aletheia_agent/venv/lib/python3.6/site-packages/mypy-0.500-py3.6.egg/mypy/main.py", line 42, in main
    res = type_check_only(sources, bin_dir, options)
  File "/Users/akira/Desktop/WorkingSpace/aletheia_agent/venv/lib/python3.6/site-packages/mypy-0.500-py3.6.egg/mypy/main.py", line 86, in type_check_only
    options=options)
  File "/Users/akira/Desktop/WorkingSpace/aletheia_agent/venv/lib/python3.6/site-packages/mypy-0.500-py3.6.egg/mypy/build.py", line 183, in build
    dispatch(sources, manager)
  File "/Users/akira/Desktop/WorkingSpace/aletheia_agent/venv/lib/python3.6/site-packages/mypy-0.500-py3.6.egg/mypy/build.py", line 1531, in dispatch
    process_graph(graph, manager)
  File "/Users/akira/Desktop/WorkingSpace/aletheia_agent/venv/lib/python3.6/site-packages/mypy-0.500-py3.6.egg/mypy/build.py", line 1768, in process_graph
    process_stale_scc(graph, scc)
  File "/Users/akira/Desktop/WorkingSpace/aletheia_agent/venv/lib/python3.6/site-packages/mypy-0.500-py3.6.egg/mypy/build.py", line 1843, in process_stale_scc
    graph[id].semantic_analysis()
  File "/Users/akira/Desktop/WorkingSpace/aletheia_agent/venv/lib/python3.6/site-packages/mypy-0.500-py3.6.egg/mypy/build.py", line 1438, in semantic_analysis
    self.manager.semantic_analyzer.visit_file(self.tree, self.xpath, self.options)
  File "/Users/akira/Desktop/WorkingSpace/aletheia_agent/venv/lib/python3.6/site-packages/mypy-0.500-py3.6.egg/mypy/semanal.py", line 253, in visit_file
    self.accept(d)
  File "/Users/akira/Desktop/WorkingSpace/aletheia_agent/venv/lib/python3.6/site-packages/mypy-0.500-py3.6.egg/mypy/semanal.py", line 3041, in accept
    node.accept(self)
  File "/Users/akira/Desktop/WorkingSpace/aletheia_agent/venv/lib/python3.6/site-packages/mypy-0.500-py3.6.egg/mypy/nodes.py", line 536, in accept
    return visitor.visit_func_def(self)
  File "/Users/akira/Desktop/WorkingSpace/aletheia_agent/venv/lib/python3.6/site-packages/mypy-0.500-py3.6.egg/mypy/semanal.py", line 322, in visit_func_def
    self.analyze_function(defn)
  File "/Users/akira/Desktop/WorkingSpace/aletheia_agent/venv/lib/python3.6/site-packages/mypy-0.500-py3.6.egg/mypy/semanal.py", line 487, in analyze_function
    defn.type = self.anal_type(defn.type)
  File "/Users/akira/Desktop/WorkingSpace/aletheia_agent/venv/lib/python3.6/site-packages/mypy-0.500-py3.6.egg/mypy/semanal.py", line 1367, in anal_type
    return t.accept(a)
  File "/Users/akira/Desktop/WorkingSpace/aletheia_agent/venv/lib/python3.6/site-packages/mypy-0.500-py3.6.egg/mypy/types.py", line 663, in accept
    return visitor.visit_callable_type(self)
  File "/Users/akira/Desktop/WorkingSpace/aletheia_agent/venv/lib/python3.6/site-packages/mypy-0.500-py3.6.egg/mypy/typeanal.py", line 295, in visit_callable_type
    fallback=t.fallback or self.builtin_type('builtins.function'),
  File "/Users/akira/Desktop/WorkingSpace/aletheia_agent/venv/lib/python3.6/site-packages/mypy-0.500-py3.6.egg/mypy/typeanal.py", line 383, in builtin_type
    node = self.lookup_fqn_func(fully_qualified_name)
  File "/Users/akira/Desktop/WorkingSpace/aletheia_agent/venv/lib/python3.6/site-packages/mypy-0.500-py3.6.egg/mypy/semanal.py", line 2901, in lookup_fully_qualified
    n = self.modules[parts[0]]
KeyError: 'builtins'
```
What could I do to make mypy work again?

Thanks

**Comment by DoubleFaults** [comment]
Some version info:
Python
`python==3.6.0`
Requirement:
`typed-ast==1.0.1`

**Comment by ambv** [comment]
mypy 0.500 is not released yet. Don't install from .zip files, this doesn't include the typeshed submodule, which is why you're getting this confusing error about missing builtins. Instead, install like this:
```
python3 -m pip install -U git+git://github.com/python/mypy.git
```

**Comment by DoubleFaults** [comment]
OK...

Thank you.
