### ISSUE TITLE
"def class" or "class def" (without fast-parser) → Internal Error

### ISSUE THREAD

**Issue by elarivie** [python/mypy#3013]
INTERNAL ERROR With mypy 0.501 when provided with the command line parameter --no-fast-parser

> mypy --no-fast-parser crash.py

When analysing a file containing:

1. 
```
def class():
	pass
```
**or** 
2.
```
class def():
	pass
```

**Note:** This is invalid python syntax, but mypy should not crash.

With --show-traceback it respectively reveals the following two tracebacks:

1.
```
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 6, in <module>
    main(__file__)
  File "/usr/local/lib/python3.5/dist-packages/mypy/main.py", line 42, in main
    res = type_check_only(sources, bin_dir, options)
  File "/usr/local/lib/python3.5/dist-packages/mypy/main.py", line 86, in type_check_only
    options=options)
  File "/usr/local/lib/python3.5/dist-packages/mypy/build.py", line 183, in build
    dispatch(sources, manager)
  File "/usr/local/lib/python3.5/dist-packages/mypy/build.py", line 1523, in dispatch
    graph = load_graph(sources, manager)
  File "/usr/local/lib/python3.5/dist-packages/mypy/build.py", line 1605, in load_graph
    root_source=True)
  File "/usr/local/lib/python3.5/dist-packages/mypy/build.py", line 1212, in __init__
    self.parse_file()
  File "/usr/local/lib/python3.5/dist-packages/mypy/build.py", line 1376, in parse_file
    self.ignore_all or self.options.ignore_errors)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/mypy/build.py", line 1293, in wrap_context
    yield
  File "/usr/local/lib/python3.5/dist-packages/mypy/build.py", line 1376, in parse_file
    self.ignore_all or self.options.ignore_errors)
  File "/usr/local/lib/python3.5/dist-packages/mypy/build.py", line 462, in parse_file
    tree = parse(source, path, self.errors, options=self.options)
  File "/usr/local/lib/python3.5/dist-packages/mypy/parse.py", line 110, in parse
    tree = parser.parse(source)
  File "/usr/local/lib/python3.5/dist-packages/mypy/parse.py", line 161, in parse
    file = self.parse_file()
  File "/usr/local/lib/python3.5/dist-packages/mypy/parse.py", line 169, in parse_file
    defs = self.parse_defs()
  File "/usr/local/lib/python3.5/dist-packages/mypy/parse.py", line 307, in parse_defs
    defn, is_simple = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/mypy/parse.py", line 971, in parse_statement
    stmt = self.parse_expression_or_assignment()
  File "/usr/local/lib/python3.5/dist-packages/mypy/parse.py", line 983, in parse_expression_or_assignment
    expr = self.parse_expression(star_expr_allowed=True)
  File "/usr/local/lib/python3.5/dist-packages/mypy/parse.py", line 1355, in parse_expression
    raise self.parse_error()
  File "/usr/local/lib/python3.5/dist-packages/mypy/parse.py", line 1885, in parse_error
    self.parse_error_at(self.current())
  File "/usr/local/lib/python3.5/dist-packages/mypy/parse.py", line 1899, in parse_error_at
    self.errors.report(tok.line, tok.column, msg)
  File "/usr/local/lib/python3.5/dist-packages/mypy/errors.py", line 214, in report
    self.function_or_member[-1], line, column, severity, message,
IndexError: list index out of range
```

2.
```
crash.py:1: error: Parse error before "def"
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 6, in <module>
    main(__file__)
  File "/usr/local/lib/python3.5/dist-packages/mypy/main.py", line 42, in main
    res = type_check_only(sources, bin_dir, options)
  File "/usr/local/lib/python3.5/dist-packages/mypy/main.py", line 86, in type_check_only
    options=options)
  File "/usr/local/lib/python3.5/dist-packages/mypy/build.py", line 183, in build
    dispatch(sources, manager)
  File "/usr/local/lib/python3.5/dist-packages/mypy/build.py", line 1523, in dispatch
    graph = load_graph(sources, manager)
  File "/usr/local/lib/python3.5/dist-packages/mypy/build.py", line 1605, in load_graph
    root_source=True)
  File "/usr/local/lib/python3.5/dist-packages/mypy/build.py", line 1212, in __init__
    self.parse_file()
  File "/usr/local/lib/python3.5/dist-packages/mypy/build.py", line 1376, in parse_file
    self.ignore_all or self.options.ignore_errors)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/mypy/build.py", line 1293, in wrap_context
    yield
  File "/usr/local/lib/python3.5/dist-packages/mypy/build.py", line 1376, in parse_file
    self.ignore_all or self.options.ignore_errors)
  File "/usr/local/lib/python3.5/dist-packages/mypy/build.py", line 462, in parse_file
    tree = parse(source, path, self.errors, options=self.options)
  File "/usr/local/lib/python3.5/dist-packages/mypy/parse.py", line 110, in parse
    tree = parser.parse(source)
  File "/usr/local/lib/python3.5/dist-packages/mypy/parse.py", line 161, in parse
    file = self.parse_file()
  File "/usr/local/lib/python3.5/dist-packages/mypy/parse.py", line 169, in parse_file
    defs = self.parse_defs()
  File "/usr/local/lib/python3.5/dist-packages/mypy/parse.py", line 307, in parse_defs
    defn, is_simple = self.parse_statement()
  File "/usr/local/lib/python3.5/dist-packages/mypy/parse.py", line 949, in parse_statement
    stmt = self.parse_class_def()
  File "/usr/local/lib/python3.5/dist-packages/mypy/parse.py", line 350, in parse_class_def
    node = ClassDef(name, defs, None, base_types, metaclass=metaclass)
UnboundLocalError: local variable 'name' referenced before assignment
```

**Comment by gvanrossum** [comment]
The old parser has been removed, so this is fixed.
