### ISSUE TITLE
[SOLVED] INTERNAL ERROR -- python 3.4 and typing problem?

### ISSUE THREAD

**Issue by golightlyb** [python/mypy#3131]
Any idea how to proceed here? Many thanks

```
python3 --version
Python 3.4.2

pip3 --version
pip 1.5.6 from /usr/lib/python3/dist-packages (python 3.4)

pip3 show typing
Name: typing
Version: 3.6.1
Location: /usr/local/lib/python3.4/dist-packages
```

**pip version of mypy:**

```
/usr/local/lib/python3.4/dist-packages/typing.py:2038: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues
/usr/local/lib/python3.4/dist-packages/typing.py:2038: note: use --pdb to drop into pdb
/usr/local/lib/python3.4/dist-packages/typing.py:1192: error: Name 'Generic' already defined
/usr/local/lib/python3.4/dist-packages/typing.py:1783: error: Name 'Reversible' already defined
/usr/local/lib/python3.4/dist-packages/typing.py:1813: error: Name 'AbstractSet' already defined
/usr/local/lib/python3.4/dist-packages/typing.py:1828: error: Name 'Mapping' already defined
/usr/local/lib/python3.4/dist-packages/typing.py:1843: error: Name 'Sequence' already defined
/usr/local/lib/python3.4/dist-packages/typing.py:1847: error: Name 'Sequence' already defined
/usr/local/lib/python3.4/dist-packages/typing.py:12: error: Name 'collections_abc' already defined
/usr/local/lib/python3.4/dist-packages/typing.py:14: error: Module 'types' has no attribute 'SlotWrapperType'
/usr/local/lib/python3.4/dist-packages/typing.py:14: error: Module 'types' has no attribute 'MethodWrapperType'
/usr/local/lib/python3.4/dist-packages/typing.py:14: error: Module 'types' has no attribute 'MethodDescriptorType'
/usr/local/lib/python3.4/dist-packages/typing.py:1799: error: Invalid type "typing.Sized"
/usr/local/lib/python3.4/dist-packages/typing.py:1799: error: Invalid base class
/usr/local/lib/python3.4/dist-packages/typing.py:1813: error: Invalid type "typing.Sized"
/usr/local/lib/python3.4/dist-packages/typing.py:1813: error: Invalid base class
/usr/local/lib/python3.4/dist-packages/typing.py:1828: error: Invalid type "typing.Sized"
/usr/local/lib/python3.4/dist-packages/typing.py:1828: error: Invalid base class
/usr/local/lib/python3.4/dist-packages/typing.py:1843: error: Invalid type "typing.Sized"
/usr/local/lib/python3.4/dist-packages/typing.py:1843: error: Invalid base class
/usr/local/lib/python3.4/dist-packages/typing.py:1847: error: Invalid type "typing.Sized"
/usr/local/lib/python3.4/dist-packages/typing.py:1847: error: Invalid base class
/usr/local/lib/python3.4/dist-packages/typing.py:1902: error: Invalid type "typing.Sized"
/usr/local/lib/python3.4/dist-packages/typing.py:1902: error: Invalid base class
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 6, in <module>
    main(__file__)
  File "/usr/local/lib/python3.4/dist-packages/mypy/main.py", line 42, in main
    res = type_check_only(sources, bin_dir, options)
  File "/usr/local/lib/python3.4/dist-packages/mypy/main.py", line 86, in type_check_only
    options=options)
  File "/usr/local/lib/python3.4/dist-packages/mypy/build.py", line 183, in build
    dispatch(sources, manager)
  File "/usr/local/lib/python3.4/dist-packages/mypy/build.py", line 1531, in dispatch
    process_graph(graph, manager)
  File "/usr/local/lib/python3.4/dist-packages/mypy/build.py", line 1768, in process_graph
    process_stale_scc(graph, scc)
  File "/usr/local/lib/python3.4/dist-packages/mypy/build.py", line 1843, in process_stale_scc
    graph[id].semantic_analysis()
  File "/usr/local/lib/python3.4/dist-packages/mypy/build.py", line 1438, in semantic_analysis
    self.manager.semantic_analyzer.visit_file(self.tree, self.xpath, self.options)
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 253, in visit_file
    self.accept(d)
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 3041, in accept
    node.accept(self)
  File "/usr/local/lib/python3.4/dist-packages/mypy/nodes.py", line 536, in accept
    return visitor.visit_func_def(self)
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 322, in visit_func_def
    self.analyze_function(defn)
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 512, in analyze_function
    defn.body.accept(self)
  File "/usr/local/lib/python3.4/dist-packages/mypy/nodes.py", line 778, in accept
    return visitor.visit_block(self)
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 1340, in visit_block
    self.accept(s)
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 3041, in accept
    node.accept(self)
  File "/usr/local/lib/python3.4/dist-packages/mypy/nodes.py", line 819, in accept
    return visitor.visit_assignment_stmt(self)
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 1405, in visit_assignment_stmt
    self.process_namedtuple_definition(s)
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 1869, in process_namedtuple_definition
    named_tuple = self.check_namedtuple(s.rvalue, name)
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 1900, in check_namedtuple
    return self.build_namedtuple_typeinfo('namedtuple', [], [])
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 2013, in build_namedtuple_typeinfo
    info = self.basic_new_typeinfo(name, fallback)
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 1994, in basic_new_typeinfo
    info.mro = [info] + basetype_or_fallback.type.mro
TypeError: can only concatenate list (not "NoneType") to list
```

**GitHub version of mypy:**

```
/usr/local/lib/python3.4/dist-packages/typing.py:2038: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues
/usr/local/lib/python3.4/dist-packages/typing.py:2038: note: use --pdb to drop into pdb
/usr/local/lib/python3.4/dist-packages/typing.py:12: error: Name 'collections_abc' already defined
/usr/local/lib/python3.4/dist-packages/typing.py:14: error: Module 'types' has no attribute 'SlotWrapperType'
/usr/local/lib/python3.4/dist-packages/typing.py:14: error: Module 'types' has no attribute 'MethodWrapperType'
/usr/local/lib/python3.4/dist-packages/typing.py:14: error: Module 'types' has no attribute 'MethodDescriptorType'
/usr/local/lib/python3.4/dist-packages/typing.py:1192: error: Name 'Generic' already defined
/usr/local/lib/python3.4/dist-packages/typing.py:1783: error: Name 'Reversible' already defined
/usr/local/lib/python3.4/dist-packages/typing.py:1799: error: Invalid type "typing.Sized"
/usr/local/lib/python3.4/dist-packages/typing.py:1799: error: Invalid base class
/usr/local/lib/python3.4/dist-packages/typing.py:1813: error: Name 'AbstractSet' already defined
/usr/local/lib/python3.4/dist-packages/typing.py:1813: error: Invalid type "typing.Sized"
/usr/local/lib/python3.4/dist-packages/typing.py:1813: error: Invalid base class
/usr/local/lib/python3.4/dist-packages/typing.py:1828: error: Name 'Mapping' already defined
/usr/local/lib/python3.4/dist-packages/typing.py:1828: error: Invalid type "typing.Sized"
/usr/local/lib/python3.4/dist-packages/typing.py:1828: error: Invalid base class
/usr/local/lib/python3.4/dist-packages/typing.py:1843: error: Name 'Sequence' already defined
/usr/local/lib/python3.4/dist-packages/typing.py:1843: error: Invalid type "typing.Sized"
/usr/local/lib/python3.4/dist-packages/typing.py:1843: error: Invalid base class
/usr/local/lib/python3.4/dist-packages/typing.py:1847: error: Name 'Sequence' already defined
/usr/local/lib/python3.4/dist-packages/typing.py:1847: error: Invalid type "typing.Sized"
/usr/local/lib/python3.4/dist-packages/typing.py:1847: error: Invalid base class
/usr/local/lib/python3.4/dist-packages/typing.py:1902: error: Invalid type "typing.Sized"
/usr/local/lib/python3.4/dist-packages/typing.py:1902: error: Invalid base class
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 6, in <module>
    main(__file__)
  File "/usr/local/lib/python3.4/dist-packages/mypy/main.py", line 46, in main
    res = type_check_only(sources, bin_dir, options)
  File "/usr/local/lib/python3.4/dist-packages/mypy/main.py", line 93, in type_check_only
    options=options)
  File "/usr/local/lib/python3.4/dist-packages/mypy/build.py", line 187, in build
    dispatch(sources, manager)
  File "/usr/local/lib/python3.4/dist-packages/mypy/build.py", line 1558, in dispatch
    process_graph(graph, manager)
  File "/usr/local/lib/python3.4/dist-packages/mypy/build.py", line 1800, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/usr/local/lib/python3.4/dist-packages/mypy/build.py", line 1893, in process_stale_scc
    graph[id].semantic_analysis()
  File "/usr/local/lib/python3.4/dist-packages/mypy/build.py", line 1458, in semantic_analysis
    self.manager.semantic_analyzer.visit_file(self.tree, self.xpath, self.options)
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 256, in visit_file
    self.accept(d)
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 3328, in accept
    node.accept(self)
  File "/usr/local/lib/python3.4/dist-packages/mypy/nodes.py", line 562, in accept
    return visitor.visit_func_def(self)
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 325, in visit_func_def
    self.analyze_function(defn)
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 584, in analyze_function
    defn.body.accept(self)
  File "/usr/local/lib/python3.4/dist-packages/mypy/nodes.py", line 808, in accept
    return visitor.visit_block(self)
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 1444, in visit_block
    self.accept(s)
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 3328, in accept
    node.accept(self)
  File "/usr/local/lib/python3.4/dist-packages/mypy/nodes.py", line 849, in accept
    return visitor.visit_assignment_stmt(self)
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 1499, in visit_assignment_stmt
    self.process_namedtuple_definition(s)
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 1972, in process_namedtuple_definition
    named_tuple = self.check_namedtuple(s.rvalue, name)
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 2003, in check_namedtuple
    return self.build_namedtuple_typeinfo('namedtuple', [], [], {})
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 2116, in build_namedtuple_typeinfo
    info = self.basic_new_typeinfo(name, fallback)
  File "/usr/local/lib/python3.4/dist-packages/mypy/semanal.py", line 2097, in basic_new_typeinfo
    info.mro = [info] + basetype_or_fallback.type.mro
TypeError: can only concatenate list (not "NoneType") to list
```

**Comment by ilevkivskyi** [comment]
Are you trying to typecheck ``typing.py`` on purpose or it happens inadvertently?

**Comment by golightlyb** [comment]
Inadvertently

**Comment by golightlyb** [comment]
I think this is me being stupid with MYPYPATH ([this issue helped](https://github.com/python/mypy/issues/1339)

I had MYPYPATH set to /usr/local/lib/python3.4/dist-packages, and one of the imports there referred to typing.

Sorry, my fault!

**Comment by ilevkivskyi** [comment]
OK, no problem! I am marking the issue as closed.
