### ISSUE TITLE
mypy errors if file to analyze is called types.py

### ISSUE THREAD

**Issue by bisho** [python/mypy#3173]
Example:

/tmp/types.py
```
#!/usr/bin/env python3
from typing import (
    NamedTuple,
)
from enum import Enum


class SomeEnum(Enum):
    FOO = 1
    BAR = 2


class ExtendedNamedTuple(NamedTuple):
    field: SomeEnum
```

```
$ mypy --version
mypy 0.510-dev-db96af3899030263bd9d79b0fad004808dde9ef7
$ mypy --show-traceback /tmp/types.py
/usr/local/lib/mypy/typeshed/stdlib/3/typing.pyi:5: error: Module 'types' has no attribute 'CodeType'
/usr/local/lib/mypy/typeshed/stdlib/3/typing.pyi:5: error: Module 'types' has no attribute 'FrameType'
/tmp/types.py:13: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 6, in <module>
    main(__file__)
  File "/usr/local/lib/python3.6/site-packages/mypy/main.py", line 46, in main
    res = type_check_only(sources, bin_dir, options)
  File "/usr/local/lib/python3.6/site-packages/mypy/main.py", line 93, in type_check_only
    options=options)
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 188, in build
    graph = dispatch(sources, manager)
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 1559, in dispatch
    process_graph(graph, manager)
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 1802, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 1895, in process_stale_scc
    graph[id].semantic_analysis()
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 1459, in semantic_analysis
    self.manager.semantic_analyzer.visit_file(self.tree, self.xpath, self.options)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal.py", line 264, in visit_file
    self.accept(d)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal.py", line 3395, in accept
    node.accept(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/nodes.py", line 749, in accept
    return visitor.visit_class_def(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal.py", line 714, in visit_class_def
    with self.analyze_class_body(defn) as should_continue:
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal.py", line 725, in analyze_class_body
    if self.analyze_namedtuple_classdef(defn):
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal.py", line 962, in analyze_namedtuple_classdef
    defn.name, items, types, default_items)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal.py", line 2184, in build_namedtuple_typeinfo
    info = self.basic_new_typeinfo(name, fallback)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal.py", line 2165, in basic_new_typeinfo
    info.mro = [info] + basetype_or_fallback.type.mro
TypeError: can only concatenate list (not "NoneType") to list
/tmp/types.py:13: note: use --pdb to drop into pdb
```

Basically loading the file seems to be overwriting and breaking the internal types module. Is it possible to load the module to analyze with a random prefix to avoid issues?

**Comment by ilevkivskyi** [comment]
Thanks for reporting this!

It looks like your diagnostic is right. Maybe this could be fixed, but Python itself does not like "shadowing" sdtlib modules, so I think it is quite low priority.

**Comment by bisho** [comment]
Perhaps an easy mitigation would be renaming mypy's types.py to _types.py.

I have found in python3 with typing becomes natural defining the types of your service in a single types.py, so I think this could be a common issue.

**Comment by bisho** [comment]
Oh, I miss your point, types is in stdlib...

**Comment by gvanrossum** [comment]
OK, let's close this issue as "won't fix".
