### ISSUE TITLE
Type signature has too few arguments

### ISSUE THREAD

**Issue by jotes** [python/mypy#3180]
Hi,

I'm sorry if it's a known problem, I couldn't find it in existing issues.

My code produced a following error:
```
urls.py:348: error: Type signature has too few arguments
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 6, in <module>
    main(__file__)
  File "/home/bamboo/venvs/mypy/lib/python3.4/site-packages/mypy/main.py", line 42, in main
    res = type_check_only(sources, bin_dir, options)
  File "/home/bamboo/venvs/mypy/lib/python3.4/site-packages/mypy/main.py", line 87, in type_check_only
    options=options)
  File "/home/bamboo/venvs/mypy/lib/python3.4/site-packages/mypy/build.py", line 183, in build
    dispatch(sources, manager)
  File "/home/bamboo/venvs/mypy/lib/python3.4/site-packages/mypy/build.py", line 1521, in dispatch
    graph = load_graph(sources, manager)
  File "/home/bamboo/venvs/mypy/lib/python3.4/site-packages/mypy/build.py", line 1599, in load_graph
    st = State(id=bs.module, path=bs.path, source=bs.text, manager=manager)
  File "/home/bamboo/venvs/mypy/lib/python3.4/site-packages/mypy/build.py", line 1210, in __init__
    self.parse_file()
  File "/home/bamboo/venvs/mypy/lib/python3.4/site-packages/mypy/build.py", line 1374, in parse_file
    self.ignore_all or self.options.ignore_errors)
  File "/home/bamboo/.pyenv/versions/3.4.2/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/bamboo/venvs/mypy/lib/python3.4/site-packages/mypy/build.py", line 1291, in wrap_context
    yield
  File "/home/bamboo/venvs/mypy/lib/python3.4/site-packages/mypy/build.py", line 1374, in parse_file
    self.ignore_all or self.options.ignore_errors)
  File "/home/bamboo/venvs/mypy/lib/python3.4/site-packages/mypy/build.py", line 462, in parse_file
    tree = parse(source, path, self.errors, options=self.options)
  File "/home/bamboo/venvs/mypy/lib/python3.4/site-packages/mypy/parse.py", line 110, in parse
    tree = parser.parse(source)
  File "/home/bamboo/venvs/mypy/lib/python3.4/site-packages/mypy/parse.py", line 161, in parse
    file = self.parse_file()
  File "/home/bamboo/venvs/mypy/lib/python3.4/site-packages/mypy/parse.py", line 169, in parse_file
    defs = self.parse_defs()
  File "/home/bamboo/venvs/mypy/lib/python3.4/site-packages/mypy/parse.py", line 307, in parse_defs
    defn, is_simple = self.parse_statement()
  File "/home/bamboo/venvs/mypy/lib/python3.4/site-packages/mypy/parse.py", line 949, in parse_statement
    stmt = self.parse_class_def()
  File "/home/bamboo/venvs/mypy/lib/python3.4/site-packages/mypy/parse.py", line 348, in parse_class_def
    defs, _ = self.parse_block()
  File "/home/bamboo/venvs/mypy/lib/python3.4/site-packages/mypy/parse.py", line 888, in parse_block
    stmt, is_simple = self.parse_statement()
  File "/home/bamboo/venvs/mypy/lib/python3.4/site-packages/mypy/parse.py", line 963, in parse_statement
    stmt = self.parse_decorated_function_or_class()
  File "/home/bamboo/venvs/mypy/lib/python3.4/site-packages/mypy/parse.py", line 390, in parse_decorated_function_or_class
    func = self.parse_function(no_type_checks)
  File "/home/bamboo/venvs/mypy/lib/python3.4/site-packages/mypy/parse.py", line 461, in parse_function
    column=def_tok.column)
  File "/home/bamboo/venvs/mypy/lib/python3.4/site-packages/mypy/types.py", line 596, in __init__
    assert len(arg_types) == len(arg_kinds)
```
After some debugging I noticed that this error is raised by:
```python
    @classmethod
    def create(cls, arg1, arg2='something', arg3='somethingmore', **kwargs):
        # type: (int, str, **Any) -> unicode
```
If there's any info I can provide, feel free to ping me.

**Comment by pkch** [comment]
I could not replicate the error with

```
class X:
    @classmethod
    def create(cls, arg1, arg2='something', arg3='somethingmore', **kwargs):  # type: (int, str, **Any) -> unicode
        pass
```

running either the mypy v. 0.501 or the current master (with the `-2` flag).

Is it perhaps happening in a generic class? Or maybe there's something non-trivial in the body of `create`?

The first error about insufficient arguments is correct of course; I'm just trying to replicate the crash / traceback of mypy itself.

**Comment by ilevkivskyi** [comment]
It looks like you are using an outdated version of mypy, the ``parse.py`` is now just a thin wrapper over ``fastparse.py`` and ``fastparse2.py``. On recent versions I only get the (correct) error ``Type signature has too few arguments``, not a crash.
