### ISSUE TITLE
Crash on yield inside lambda

### ISSUE THREAD

**Issue by jpochyla** [python/mypy#3243]
I've encountered a crash on the following input:

```python
(lambda: (yield))
```

With this output:

```
error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 6, in <module>
    main(__file__)
  File "/usr/local/lib/python3.6/site-packages/mypy/main.py", line 42, in main
    res = type_check_only(sources, bin_dir, options)
  File "/usr/local/lib/python3.6/site-packages/mypy/main.py", line 86, in type_check_only
    options=options)
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 183, in build
    dispatch(sources, manager)
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 1531, in dispatch
    process_graph(graph, manager)
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 1768, in process_graph
    process_stale_scc(graph, scc)
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 1847, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 1453, in type_check_first_pass
    self.type_checker.check_first_pass()
  File "/usr/local/lib/python3.6/site-packages/mypy/checker.py", line 167, in check_first_pass
    self.accept(d)
  File "/usr/local/lib/python3.6/site-packages/mypy/checker.py", line 233, in accept
    stmt.accept(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/nodes.py", line 792, in accept
    return visitor.visit_expression_stmt(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/checker.py", line 1683, in visit_expression_stmt
    self.expr_checker.accept(s.expr)
  File "/usr/local/lib/python3.6/site-packages/mypy/checkexpr.py", line 2015, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/nodes.py", line 1507, in accept
    return visitor.visit_func_expr(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/checkexpr.py", line 1769, in visit_func_expr
    ret_type = self.accept(e.expr())
  File "/usr/local/lib/python3.6/site-packages/mypy/checkexpr.py", line 2015, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/nodes.py", line 1284, in accept
    return visitor.visit_yield_expr(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/checkexpr.py", line 2088, in visit_yield_expr
    return_type = self.chk.return_types[-1]
IndexError: list index out of range
```

**Comment by ilevkivskyi** [comment]
Confirmed, I also see the same crash.

**Comment by gvanrossum** [comment]
This is weird code, removing the priority.

**Comment by jpochyla** [comment]
We use it in micropython to get the type of a generator function, as it's the most efficient way:

```python
type_genfunc = type((lambda: (yield)))
```

**Comment by ilevkivskyi** [comment]
Another possible use case is something like generator-based promises(?):
```python
def force(promise: Iterator[T]) -> T:
    ...
force(lambda: (yield 5))
```
But in fact I had put the label since I think being able to unconditionally crash mypy with something as simple as ``lambda: (yield)`` is bad.

**Comment by gvanrossum** [comment]
You can still fix it if you want. :-)
