### ISSUE TITLE
Unions with invalid arguments are still allowed

### ISSUE THREAD

**Issue by kirbyfan64** [python/mypy#3258]
```python
from typing import Union
Union[123]
```

Doesn't give any errors, but fails at runtime:

```
Traceback (most recent call last):
  File "tst.py", line 2, in <module>
    Union[123]
  File "/media/ryan/stuff/anaconda/lib/python3.6/typing.py", line 626, in inner
    return func(*args, **kwds)
  File "/media/ryan/stuff/anaconda/lib/python3.6/typing.py", line 744, in __getitem__
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "/media/ryan/stuff/anaconda/lib/python3.6/typing.py", line 744, in <genexpr>
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "/media/ryan/stuff/anaconda/lib/python3.6/typing.py", line 356, in _type_check
    raise TypeError(msg + " Got %.100r." % (arg,))
TypeError: Union[arg, ...]: each arg must be a type. Got 123.
```

**Comment by ethanhs** [comment]
I believe this is due to the current state of stubs in typeshed. For example [this](https://github.com/python/typeshed/blob/master/stdlib/3/typing.pyi#L28) means that the `__getitem__` call returns Any and takes Any. As I recall there was another issue with these stubs during PyCon. I'll try to look at improvements that can be made there, as I think this shouldn't be too bad to fix.
