### ISSUE TITLE
[crash][regression] mypy fails if a custom property is used like an overload

### ISSUE THREAD

**Issue by DragonSA** [python/mypy#3333]
The following example will cause mypy to fail, even though it is valid python code.
```python
#!/usr/env python3
from typing import Any, Callable, List, Type

class Chain(object):
    def __init__(self):
        self.chains = []  # type: List[Callable[[Any, Int], Int]]

    def __get__(self, instance: Any, owner: Type) -> Callable[[int], int]:
        def do_chain(value: int) -> int:
            for function in self.chains:
                value = function(instance, value)
            return value
        return do_chain

    def chain(self, function: Callable[[Any, int], int]) -> 'Chain':
        self.chains.append(function)
        return self

class Test(object):
    do_chain = Chain()

    @do_chain.chain
    def do_chain(self, value: int) -> int:
        return value * 2

    @do_chain.chain
    def do_chain(self, value: int) -> int:
        return value * 3

assert Test().do_chain(1) == 6
```

The traceback:
```
# mypy --show-traceback test.py
test.py:26: error: Name 'do_chain' already defined
test.py:22: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.510
Traceback (most recent call last):
  File "mypys", line 6, in <module>
    main(__file__)
  File "/tmp/mypy-0.510/mypy/main.py", line 46, in main
    res = type_check_only(sources, bin_dir, options)
  File "/tmp/mypy-0.510/mypy/main.py", line 93, in type_check_only
    options=options)
  File "/tmp/mypy-0.510/mypy/build.py", line 188, in build
    graph = dispatch(sources, manager)
  File "/tmp/mypy-0.510/mypy/build.py", line 1595, in dispatch
    process_graph(graph, manager)
  File "/tmp/mypy-0.510/mypy/build.py", line 1838, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/tmp/mypy-0.510/mypy/build.py", line 1931, in process_stale_scc
    graph[id].semantic_analysis()
  File "/tmp/mypy-0.510/mypy/build.py", line 1495, in semantic_analysis
    self.manager.semantic_analyzer.visit_file(self.tree, self.xpath, self.options)
  File "/tmp/mypy-0.510/mypy/semanal.py", line 257, in visit_file
    self.accept(d)
  File "/tmp/mypy-0.510/mypy/semanal.py", line 3288, in accept
    node.accept(self)
  File "/tmp/mypy-0.510/mypy/nodes.py", line 749, in accept
    return visitor.visit_class_def(self)
  File "/tmp/mypy-0.510/mypy/semanal.py", line 620, in visit_class_def
    defn.defs.accept(self)
  File "/tmp/mypy-0.510/mypy/nodes.py", line 810, in accept
    return visitor.visit_block(self)
  File "/tmp/mypy-0.510/mypy/semanal.py", line 1375, in visit_block
    self.accept(s)
  File "/tmp/mypy-0.510/mypy/semanal.py", line 3288, in accept
    node.accept(self)
  File "/tmp/mypy-0.510/mypy/nodes.py", line 409, in accept
    return visitor.visit_overloaded_func_def(self)
  File "/tmp/mypy-0.510/mypy/semanal.py", line 516, in visit_overloaded_func_def
    typ=defn.type)
  File "/tmp/mypy-0.510/mypy/nodes.py", line 406, in name
    return self.items[0].name()
IndexError: list index out of range
test.py:22: note: use --pdb to drop into pdb
```

**Comment by JelleZijlstra** [comment]
Simpler repro:
```
#!/usr/env python3
from typing import Any, Callable, Type

class Chain(object):
    def chain(self, function: Callable[[Any], int]) -> 'Chain':
        return self

class Test(object):
    do_chain = Chain()

    @do_chain.chain
    def do_chain(self) -> int:
        return 2

    @do_chain.chain
    def do_chain(self) -> int:
        return 3
```

**Comment by sixolet** [comment]
Looks like my feature, I'll take a look.
