### ISSUE TITLE
Crash when running from subdirectory

### ISSUE THREAD

**Issue by miedzinski** [python/mypy#3378]
While looking at #3377 I found that mypy crashes when run from inside package's source code directory (`mypy`).

```bash
(mypy-dev) ~/src/mypy/mypy [master] λ PYTHONPATH=$HOME/src/mypy MYPYPATH=$HOME/src/mypy mypy --config-file=../mypy_self_check.ini --show-traceback main.py 
/home/dominik/src/mypy/mypy/types.py:528: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.520-dev-2ca2eb4306df1e798f3eaa620b06a8b0698e3458
Traceback (most recent call last):
  File "/home/dominik/.virtualenvs/mypy-dev/bin/mypy", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/dominik/src/mypy/scripts/mypy", line 6, in <module>
    main(__file__)
  File "/home/dominik/src/mypy/mypy/main.py", line 46, in main
    res = type_check_only(sources, bin_dir, options)
  File "/home/dominik/src/mypy/mypy/main.py", line 93, in type_check_only
    options=options)
  File "/home/dominik/src/mypy/mypy/build.py", line 188, in build
    graph = dispatch(sources, manager)
  File "/home/dominik/src/mypy/mypy/build.py", line 1595, in dispatch
    process_graph(graph, manager)
  File "/home/dominik/src/mypy/mypy/build.py", line 1838, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/dominik/src/mypy/mypy/build.py", line 1931, in process_stale_scc
    graph[id].semantic_analysis()
  File "/home/dominik/src/mypy/mypy/build.py", line 1495, in semantic_analysis
    self.manager.semantic_analyzer.visit_file(self.tree, self.xpath, self.options)
  File "/home/dominik/src/mypy/mypy/semanal.py", line 264, in visit_file
    self.accept(d)
  File "/home/dominik/src/mypy/mypy/semanal.py", line 3331, in accept
    node.accept(self)
  File "/home/dominik/src/mypy/mypy/nodes.py", line 855, in accept
    return visitor.visit_assignment_stmt(self)
  File "/home/dominik/src/mypy/mypy/semanal.py", line 1487, in visit_assignment_stmt
    self.process_namedtuple_definition(s)
  File "/home/dominik/src/mypy/mypy/semanal.py", line 1960, in process_namedtuple_definition
    named_tuple = self.check_namedtuple(s.rvalue, name)
  File "/home/dominik/src/mypy/mypy/semanal.py", line 1996, in check_namedtuple
    info = self.build_namedtuple_typeinfo(name, items, types, {})
  File "/home/dominik/src/mypy/mypy/semanal.py", line 2109, in build_namedtuple_typeinfo
    info = self.basic_new_typeinfo(name, fallback)
  File "/home/dominik/src/mypy/mypy/semanal.py", line 2085, in basic_new_typeinfo
    info.mro = [info] + basetype_or_fallback.type.mro
TypeError: can only concatenate list (not "NoneType") to list
/home/dominik/src/mypy/mypy/types.py:528: note: use --pdb to drop into pdb
```

Not sure whether that should work, but at least it shouldn't crash.

**Comment by gvanrossum** [comment]
This is a common pilot error. You shouldn't have a module named types.py. You shouldn't run mypy from inside the mypy package. In general, your current directory shouldn't be inside a package.

**Comment by JukkaL** [comment]
Mypy still shouldn't crash on user error -- it should report what is wrong. I couldn't find an existing issue for generating a useful error message in cases like this.
