### ISSUE TITLE
mypy fails on Windows (Name '__builtins__' is not defined)

### ISSUE THREAD

**Issue by ErikBjare** [python/mypy#3471]
**Version:** 0.511

I get this everytime I try to run mypy on my aw-core project on Windows (Appveyor to be exact, haven't had the chance to try and replicate on a different Windows machine).

<details>
<summary>Traceback</summary>

```
export MYPYPATH=./stubs; python -m mypy aw_core aw_datastore --show-traceback --ignore-missing-imports --follow-imports=skip
stubs\iso8601.pyi: error: Name '__builtins__' is not defined
stubs\iso8601.pyi:4: error: Name 'str' is not defined
Traceback (most recent call last):
  File "C:\Python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\__main__.py", line 5, in <module>
    main(None)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\main.py", line 46, in main
    res = type_check_only(sources, bin_dir, options)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\main.py", line 93, in type_check_only
    options=options)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\build.py", line 188, in build
    graph = dispatch(sources, manager)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\build.py", line 1595, in dispatch
    process_graph(graph, manager)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\build.py", line 1838, in process_graph
    process_stale_scc(graph, scc, manager)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\build.py", line 1931, in process_stale_scc
    graph[id].semantic_analysis()
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\build.py", line 1495, in semantic_analysis
    self.manager.semantic_analyzer.visit_file(self.tree, self.xpath, self.options)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\semanal.py", line 257, in visit_file
    self.accept(d)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\semanal.py", line 3293, in accept
    node.accept(self)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\nodes.py", line 565, in accept
    return visitor.visit_func_def(self)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\semanal.py", line 376, in visit_func_def
    self.analyze_function(defn)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\semanal.py", line 555, in analyze_function
    defn.type = self.type_analyzer().visit_callable_type(defn.type, nested=False)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\typeanal.py", line 344, in visit_callable_type
    fallback=t.fallback or self.builtin_type('builtins.function'),
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\typeanal.py", line 536, in builtin_type
    node = self.lookup_fqn_func(fully_qualified_name)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\semanal.py", line 3153, in lookup_fully_qualified
    n = self.modules[parts[0]]
KeyError: 'builtins'
stubs\iso8601.pyi:4: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.511
stubs\iso8601.pyi:4: note: use --pdb to drop into pdb
Makefile:14: recipe for target 'typecheck' failed
```
</details>

[Link to CI full log](https://ci.appveyor.com/project/ErikBjare/aw-core/build/1.0.216/job/0fw984u6ps3gec45)

After doing a quick issue search I found some cases where modifying MYPYPATH to something invalid could cause issues, so I removed my modified MYPYPATH and ran again:

<details>
<summary>Traceback</summary>

```
python3 -m mypy aw_core aw_datastore --show-traceback --ignore-missing-imports --follow-imports=skip
aw_core\timeperiod.py: error: Name '__builtins__' is not defined
Traceback (most recent call last):
  File "C:\Python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\__main__.py", line 5, in <module>
    main(None)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\main.py", line 46, in main
    res = type_check_only(sources, bin_dir, options)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\main.py", line 93, in type_check_only
    options=options)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\build.py", line 188, in build
    graph = dispatch(sources, manager)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\build.py", line 1595, in dispatch
    process_graph(graph, manager)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\build.py", line 1838, in process_graph
    process_stale_scc(graph, scc, manager)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\build.py", line 1931, in process_stale_scc
    graph[id].semantic_analysis()
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\build.py", line 1495, in semantic_analysis
    self.manager.semantic_analyzer.visit_file(self.tree, self.xpath, self.options)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\semanal.py", line 257, in visit_file
    self.accept(d)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\semanal.py", line 3293, in accept
    node.accept(self)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\nodes.py", line 750, in accept
    return visitor.visit_class_def(self)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\semanal.py", line 622, in visit_class_def
    with self.analyze_class_body(defn) as should_continue:
  File "C:\Python35\lib\contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\semanal.py", line 641, in analyze_class_body
    self.analyze_base_classes(defn)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\semanal.py", line 937, in analyze_base_classes
    base_types.append(self.object_type())
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\semanal.py", line 1060, in object_type
    return self.named_type('__builtins__.object')
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\semanal.py", line 1076, in named_type
    sym = self.lookup_qualified(qualified_name, None)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\semanal.py", line 3110, in lookup_qualified
    n = self.lookup(parts[0], ctx)  # type: SymbolTableNode
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\semanal.py", line 3094, in lookup
    self.name_not_defined(name, ctx)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\semanal.py", line 3259, in name_not_defined
    self.fail(message, ctx)
  File "C:\Users\appveyor\AppData\Roaming\Python\Python35\site-packages\mypy\semanal.py", line 3272, in fail
    assert ctx is not None, msg
AssertionError: Name '__builtins__' is not defined
aw_core\timeperiod.py:5: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.511
aw_core\timeperiod.py:5: note: use --pdb to drop into pdb
```
</details>

[Link to full CI log](https://ci.appveyor.com/project/ErikBjare/aw-core/build/1.0.217/job/nqdrmagrsxfo23ba)

Same result, but now it appears in the implementation code and not in the stubs, so probably a larger issue than I initially thought.

**Comment by ethanhs** [comment]
Im looking into this. The bug happens when typeshed is not found, but there is no reason it shouldn't be.

**Comment by ErikBjare** [comment]
@ethanhs Oh, that gives me some ideas that might be related to my CI config. I think I might be on to something so give me a day or two and I'll look into it.

**Comment by ethanhs** [comment]
@ErikBjare has this been resolved? Or are you still experiencing it?

**Comment by ErikBjare** [comment]
@ethanhs I haven't tried, I just disabled it for now (runs fine on my Linux/Travis CI builds).

Pretty sure it has something to do with my setup scripts on Appveyor however, so closing for now.
