### ISSUE TITLE
semanal.py internal error on redefinition/overload of a decorated method

### ISSUE THREAD

**Issue by zestyping** [python/mypy#3502]
I know that mypy doesn't understand the types of decorated methods, but I don't think it should crash with an INTERNAL ERROR as it does.

In practice, this came up for code that tries to use SQLAlchemy's hybrid properties, though it is not specific to SQLAlchemy.  Here's an example from the [SQLAlchemy documentation](http://docs.sqlalchemy.org/en/latest/orm/extensions/hybrid.html):

```
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy import func

class Interval(object):
    @hybrid_property
    def radius(self):
        return abs(self.length) / 2

    @radius.expression
    def radius(cls):
        return func.abs(cls.length) / 2
```

The above produces the error:
```
interval.py:9: error: Name 'radius' already defined
interval.py:9: error: Name 'radius' is not defined
interval.py:5: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.510
interval.py:5: note: please use --show-traceback to print a traceback when reporting a bug
```

However, the problem doesn't have to do with SQLAlchemy—I was able to find this simpler example:
```
def decorate(x):
    return x

class Foo:
    @decorate
    def method(self):
        return 1

    def method(self):
        return 2
```

Here's the error and traceback for the above:

```
foo.py:9: error: Name 'method' already defined
foo.py:5: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.510
Traceback (most recent call last):
  File "/Users/ping/.virtualenvs/remit/bin/mypy", line 6, in <module>
    main(__file__)
  File "/Users/ping/.virtualenvs/remit/lib/python3.6/site-packages/mypy/main.py", line 46, in main
    res = type_check_only(sources, bin_dir, options)
  File "/Users/ping/.virtualenvs/remit/lib/python3.6/site-packages/mypy/main.py", line 93, in type_check_only
    options=options)
  File "/Users/ping/.virtualenvs/remit/lib/python3.6/site-packages/mypy/build.py", line 188, in build
    graph = dispatch(sources, manager)
  File "/Users/ping/.virtualenvs/remit/lib/python3.6/site-packages/mypy/build.py", line 1595, in dispatch
    process_graph(graph, manager)
  File "/Users/ping/.virtualenvs/remit/lib/python3.6/site-packages/mypy/build.py", line 1838, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/Users/ping/.virtualenvs/remit/lib/python3.6/site-packages/mypy/build.py", line 1931, in process_stale_scc
    graph[id].semantic_analysis()
  File "/Users/ping/.virtualenvs/remit/lib/python3.6/site-packages/mypy/build.py", line 1495, in semantic_analysis
    self.manager.semantic_analyzer.visit_file(self.tree, self.xpath, self.options)
  File "/Users/ping/.virtualenvs/remit/lib/python3.6/site-packages/mypy/semanal.py", line 257, in visit_file
    self.accept(d)
  File "/Users/ping/.virtualenvs/remit/lib/python3.6/site-packages/mypy/semanal.py", line 3288, in accept
    node.accept(self)
  File "/Users/ping/.virtualenvs/remit/lib/python3.6/site-packages/mypy/nodes.py", line 749, in accept
    return visitor.visit_class_def(self)
  File "/Users/ping/.virtualenvs/remit/lib/python3.6/site-packages/mypy/semanal.py", line 620, in visit_class_def
    defn.defs.accept(self)
  File "/Users/ping/.virtualenvs/remit/lib/python3.6/site-packages/mypy/nodes.py", line 810, in accept
    return visitor.visit_block(self)
  File "/Users/ping/.virtualenvs/remit/lib/python3.6/site-packages/mypy/semanal.py", line 1375, in visit_block
    self.accept(s)
  File "/Users/ping/.virtualenvs/remit/lib/python3.6/site-packages/mypy/semanal.py", line 3288, in accept
    node.accept(self)
  File "/Users/ping/.virtualenvs/remit/lib/python3.6/site-packages/mypy/nodes.py", line 409, in accept
    return visitor.visit_overloaded_func_def(self)
  File "/Users/ping/.virtualenvs/remit/lib/python3.6/site-packages/mypy/semanal.py", line 516, in visit_overloaded_func_def
    typ=defn.type)
  File "/Users/ping/.virtualenvs/remit/lib/python3.6/site-packages/mypy/nodes.py", line 406, in name
    return self.items[0].name()
IndexError: list index out of range
```

I did a little bit of investigating and got as far as discovering that `self.items` is `[]` by the time the `name` method is called, but mysteriously, it seems like `self.items` never gets assigned `[]` in `OverloadedFuncDef.__init__` or in `OverloadedFuncDef.deserialize`, nor does `self.items` ever appear to be mutated, so I got stuck and stopped investigating there.

**Comment by ilevkivskyi** [comment]
I cannot reproduce this crash on master. Could you please check if it works on master? This looks similar to #3333 that was fixed recently.

**Comment by zestyping** [comment]
I checked, and the problem went away.  Thanks!
