### ISSUE TITLE
INTERNAL ERROR

### ISSUE THREAD

**Issue by leandropls** [python/mypy#3561]
I've just got one of these:

```
INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.510-dev-88fe21d5e570160e790384d62c75ee1234e6a597
Traceback (most recent call last):
  File "/Users/leandro/env/acg-3.6.1/bin/mypy", line 6, in <module>
    main(__file__)
  File "/Users/leandro/env/acg-3.6.1/lib/python3.6/site-packages/mypy/main.py", line 46, in main
    res = type_check_only(sources, bin_dir, options)
  File "/Users/leandro/env/acg-3.6.1/lib/python3.6/site-packages/mypy/main.py", line 93, in type_check_only
    options=options)
  File "/Users/leandro/env/acg-3.6.1/lib/python3.6/site-packages/mypy/build.py", line 188, in build
    graph = dispatch(sources, manager)
  File "/Users/leandro/env/acg-3.6.1/lib/python3.6/site-packages/mypy/build.py", line 1570, in dispatch
    process_graph(graph, manager)
  File "/Users/leandro/env/acg-3.6.1/lib/python3.6/site-packages/mypy/build.py", line 1813, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/Users/leandro/env/acg-3.6.1/lib/python3.6/site-packages/mypy/build.py", line 1912, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/Users/leandro/env/acg-3.6.1/lib/python3.6/site-packages/mypy/build.py", line 1485, in type_check_first_pass
    self.type_checker.check_first_pass()
  File "/Users/leandro/env/acg-3.6.1/lib/python3.6/site-packages/mypy/checker.py", line 177, in check_first_pass
    self.accept(d)
  File "/Users/leandro/env/acg-3.6.1/lib/python3.6/site-packages/mypy/checker.py", line 262, in accept
    stmt.accept(self)
  File "/Users/leandro/env/acg-3.6.1/lib/python3.6/site-packages/mypy/nodes.py", line 748, in accept
    return visitor.visit_class_def(self)
  File "/Users/leandro/env/acg-3.6.1/lib/python3.6/site-packages/mypy/checker.py", line 1077, in visit_class_def
    self.accept(defn.defs)
  File "/Users/leandro/env/acg-3.6.1/lib/python3.6/site-packages/mypy/checker.py", line 262, in accept
    stmt.accept(self)
  File "/Users/leandro/env/acg-3.6.1/lib/python3.6/site-packages/mypy/nodes.py", line 809, in accept
    return visitor.visit_block(self)
  File "/Users/leandro/env/acg-3.6.1/lib/python3.6/site-packages/mypy/checker.py", line 1170, in visit_block
    self.accept(s)
  File "/Users/leandro/env/acg-3.6.1/lib/python3.6/site-packages/mypy/checker.py", line 262, in accept
    stmt.accept(self)
  File "/Users/leandro/env/acg-3.6.1/lib/python3.6/site-packages/mypy/nodes.py", line 630, in accept
    return visitor.visit_decorator(self)
  File "/Users/leandro/env/acg-3.6.1/lib/python3.6/site-packages/mypy/checker.py", line 2207, in visit_decorator
    e.func.accept(self)
  File "/Users/leandro/env/acg-3.6.1/lib/python3.6/site-packages/mypy/nodes.py", line 564, in accept
    return visitor.visit_func_def(self)
  File "/Users/leandro/env/acg-3.6.1/lib/python3.6/site-packages/mypy/checker.py", line 510, in visit_func_def
    self.check_method_override(defn)
  File "/Users/leandro/env/acg-3.6.1/lib/python3.6/site-packages/mypy/checker.py", line 942, in check_method_override
    for base in defn.info.mro[1:]:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by kirbyfan64** [comment]
...example code? It's kind of hard to debug a problem otherwise...

**Comment by ilevkivskyi** [comment]
Could you please tell us what are the flags you are using? In particular, do you ``--incremental`` flag?

**Comment by leandropls** [comment]
@kirbyfan64,

```
from typing import NamedTuple, TypeVar, Type

T = TypeVar('T')


class MyClass(NamedTuple):
    first: float
    second: float

    @classmethod
    def fromnumber(cls: Type[T], value: float) -> T:
        return cls(value / 2, value / 2)
```

@ilevkivskyi, I was using no special flags needed.

**Comment by Michael0x2a** [comment]
I think you probably want to use a regular class here, or move `fromnumber` outside of your namedtuple definition and convert it into a regular function. Since `typing.NamedTuple` is supposed to behave identically to `collections.namedtuple` at runtime, I don't know if it really makes sense to define a classmethod within `MyClass`.

The bug here is probably that mypy is crashing instead of displaying an error message in this case?

**Comment by kirbyfan64** [comment]
This doesn't crash under `master`:

```
ryan@DevPC-LX ~/stuff/mypy master $ mypy nt.py
nt.py:12: error: Too many arguments for "object"
ryan@DevPC-LX ~/stuff/mypy master $ 
```

**Comment by leandropls** [comment]
Hasn't this been settled here?
https://github.com/python/typing/issues/352

**Comment by leandropls** [comment]
Oh, sorry, I was responding to a comment that doesn't really exist anymore.

**Comment by gvanrossum** [comment]
If the crash is fixed in master, close the issue please.

**Comment by leandropls** [comment]
Is this really supposed to be an error? Even if it doesn't crash. It seems fr the issue above, that the code should be valid.

**Comment by ilevkivskyi** [comment]
@leandropls 

There is a proposal (proto-PEP "Data classes") to add a support for such use cases (both runtime and static). ``NamedTuple`` should be kept rather minimalistic.
