### ISSUE TITLE
INTERNAL ERROR - mypy/nodes.py - TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Daenyth** [python/mypy#3776]
Using 0.521

<details><summary>Traceback</summary>

```
obs/sentry.py:52: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.521
Traceback (most recent call last):
  File "/Users/daenyth/Curata/observer/.tox/mypy/bin/mypy", line 11, in <module>
    sys.exit(console_entry())
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/main.py", line 50, in main
    res = type_check_only(sources, bin_dir, options)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/main.py", line 97, in type_check_only
    options=options)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/build.py", line 196, in build
    graph = dispatch(sources, manager)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/build.py", line 1801, in dispatch
    process_graph(graph, manager)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/build.py", line 2044, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/build.py", line 2147, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/build.py", line 1716, in type_check_first_pass
    self.type_checker.check_first_pass()
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/checker.py", line 185, in check_first_pass
    self.accept(d)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/checker.py", line 273, in accept
    stmt.accept(self)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/nodes.py", line 565, in accept
    return visitor.visit_func_def(self)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/checker.py", line 519, in visit_func_def
    self.check_func_item(defn, name=defn.name())
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/checker.py", line 578, in check_func_item
    self.check_func_def(defn, typ, name)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/checker.py", line 738, in check_func_def
    self.accept(item.body)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/checker.py", line 273, in accept
    stmt.accept(self)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/nodes.py", line 815, in accept
    return visitor.visit_block(self)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/checker.py", line 1202, in visit_block
    self.accept(s)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/checker.py", line 273, in accept
    stmt.accept(self)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/nodes.py", line 859, in accept
    return visitor.visit_assignment_stmt(self)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/checker.py", line 1209, in visit_assignment_stmt
    self.check_assignment(s.lvalues[-1], s.rvalue, s.type is None, s.new_syntax)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/checker.py", line 1300, in check_assignment
    self.infer_variable_type(inferred, lvalue, self.expr_checker.accept(rvalue),
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/checkexpr.py", line 2213, in accept
    typ = node.accept(self)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/nodes.py", line 1307, in accept
    return visitor.visit_call_expr(self)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/checkexpr.py", line 247, in visit_call_expr
    ret_type = self.check_call_expr_with_callee_type(callee_type, e, fullname, object_type)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/checkexpr.py", line 459, in check_call_expr_with_callee_type
    object_type=object_type)[0]
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/checkexpr.py", line 561, in check_call
    self.infer_arg_types_in_context(None, args)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/checkexpr.py", line 648, in infer_arg_types_in_context
    arg_type = self.accept(arg, ctx)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/checkexpr.py", line 2213, in accept
    typ = node.accept(self)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/nodes.py", line 1260, in accept
    return visitor.visit_member_expr(self)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/checkexpr.py", line 1150, in visit_member_expr
    result = self.analyze_ordinary_member_access(e, False)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/checkexpr.py", line 1165, in analyze_ordinary_member_access
    original_type=original_type, chk=self.chk)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/checkmember.py", line 101, in analyze_member_access
    original_type=original_type, chk=chk)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/checkmember.py", line 223, in analyze_member_var_access
    v = lookup_member_var_or_accessor(info, name, is_lvalue)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/checkmember.py", line 364, in lookup_member_var_or_accessor
    node = info.get(name)
  File "/Users/daenyth/Curata/observer/.tox/mypy/lib/python3.6/site-packages/mypy/nodes.py", line 2042, in get
    for cls in self.mro:
TypeError: 'NoneType' object is not iterable
obs/sentry.py:52: note: use --pdb to drop into pdb
```

</details>

Line 52 is `dsn=cfg.dsn,`

SentryConfig is a typing.NamedTuple class.
obs.config imports `no_sentry`, which is why I use the `if TYPE_CHECKING` and forward reference

<details><summary>File triggering error</summary>

```
"""
Utilities for interacting with Sentry (sentry.io)
"""
from typing import TypeVar, Dict, Any, Optional, TYPE_CHECKING

import raven  # type: ignore
from raven.processors import Processor  # type: ignore
from raven.utils import varmap  # type: ignore

if TYPE_CHECKING:
    # Avoid circular import
    from .config import SentryConfig

A = TypeVar('A')

# Sentinel value
_no_sentry = object()


def no_sentry(obj: A) -> A:
    """
    Decorates an object that should not be included in sentry's stack trace locals
    """
    obj._no_sentry = _no_sentry  # type: ignore
    return obj


class GenericLocalProcessor(Processor):  # type: ignore
    """
    Can be subclassed by overriding `should_remove`, which will get each local name and value in traces
    """

    def should_remove(self, name: str, value: object) -> bool:
        raise NotImplementedError

    def filter_stacktrace(self, data: Dict[str, Any]) -> None:
        for frame in data.get('frames', []):
            if 'vars' not in frame:
                continue
            frame['vars'] = varmap(lambda name, var: "REDACTED" if self.should_remove(name, var) else var,
                                   frame['vars'])


class RemoveNoSentryProcessor(GenericLocalProcessor):
    def should_remove(self, name: str, value: object) -> bool:
        return hasattr(value, '_no_sentry')


# Forward reference arg here to avoid circular import
def get_sentry_client(cfg: 'SentryConfig', sentry_tags: Optional[Dict[str, str]]) -> raven.Client:
    client = raven.Client(
        dsn=cfg.dsn,
        environment=cfg.environment,
        include_paths=['obs'],
        release=raven.fetch_package_version('Observer'),
        tags=sentry_tags or {},
        processors=['raven.processors.SanitizePasswordsProcessor', 'obs.sentry.RemoveNoSentryProcessor'])
    return client
```

**Comment by Daenyth** [comment]
Possible dupe of #3419

**Comment by ilevkivskyi** [comment]
We already have several crashes in situations with forward references to "synthetic" types like ``NamedTuple``. Indeed, this is very similar to #3419, but here we have a circular import instead of an "in-module" forward reference. I propose to close this one, mention this use case in #3419 and raise its priority to high.
