### ISSUE TITLE
python-typed-ast was updated to 1.1.0, so a new release should be made

### ISSUE THREAD

**Issue by marmistrz** [python/mypy#3802]
And if typed-ast is following semver, this should not break the API

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 972, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 863, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (typed-ast 1.1.0 (/usr/lib/python3.6/site-packages), Requirement.parse('typed-ast<1.1.0,>=1.0.4'), {'mypy'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mypy", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3049, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3033, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3062, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 660, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 673, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 858, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'typed-ast<1.1.0,>=1.0.4' distribution was not found and is required by mypy
```

`mypy` seems to run fine with newest `typed-ast`. (modified `requires.txt` in the egg-info)

**Comment by ethanhs** [comment]
While your issue is quite terse, I believe I understand the issue is that you have an existing typed_ast 1.1.0 which conflicts with mypy 0.520/0.521 installation (which, as one can see above, specifies less than 1.1.0).

To be clear: typed_ast should be completely api backwards compatible with 1.0.x The only added feature is Windows support for Python 3.3/3.4 (a large enough feature to bump a minor version).

Mypy 0.521 was the only version of mypy released since the typed_ast update. Since the mypy release was a bugfix release I did not see it proper to update a dependency (which seems to go against the spirit of sem ver), and no one else suggested it.

Let me know if you have further questions about this.

**Comment by marmistrz** [comment]
I perfectly understand the cause of the error. It originates from the fact that the Arch Linux package maintainer has updated the package :)
https://aur.archlinux.org/packages/python-typed-ast/

**Comment by gvanrossum** [comment]
A new release will be made in due time (probably in ~6-8 weeks). This is not the place to vent about Arch Linux.
