### ISSUE TITLE
KeyError: 'builtins'

### ISSUE THREAD

**Issue by bgwines** [python/mypy#3886]
Hi, there! Ran into this today and saw a message asking to report it, so here you go :)

```
error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.521-858f7512cf3b4e39c0f4e8de5a13eee0e1e138fb-dirty
Traceback (most recent call last):
  File "/usr/local/Cellar/mypy/0.521/libexec/bin/mypy", line 11, in <module>
    load_entry_point('mypy===0.521-858f7512cf3b4e39c0f4e8de5a13eee0e1e138fb-dirty', 'console_scripts', 'mypy')()
  File "/usr/local/Cellar/mypy/0.521/libexec/lib/python3.6/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "/usr/local/Cellar/mypy/0.521/libexec/lib/python3.6/site-packages/mypy/main.py", line 50, in main
    res = type_check_only(sources, bin_dir, options)
  File "/usr/local/Cellar/mypy/0.521/libexec/lib/python3.6/site-packages/mypy/main.py", line 97, in type_check_only
    options=options)
  File "/usr/local/Cellar/mypy/0.521/libexec/lib/python3.6/site-packages/mypy/build.py", line 196, in build
    graph = dispatch(sources, manager)
  File "/usr/local/Cellar/mypy/0.521/libexec/lib/python3.6/site-packages/mypy/build.py", line 1801, in dispatch
    process_graph(graph, manager)
  File "/usr/local/Cellar/mypy/0.521/libexec/lib/python3.6/site-packages/mypy/build.py", line 2044, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/usr/local/Cellar/mypy/0.521/libexec/lib/python3.6/site-packages/mypy/build.py", line 2147, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/usr/local/Cellar/mypy/0.521/libexec/lib/python3.6/site-packages/mypy/build.py", line 1716, in type_check_first_pass
    self.type_checker.check_first_pass()
  File "/usr/local/Cellar/mypy/0.521/libexec/lib/python3.6/site-packages/mypy/checker.py", line 185, in check_first_pass
    self.accept(d)
  File "/usr/local/Cellar/mypy/0.521/libexec/lib/python3.6/site-packages/mypy/checker.py", line 273, in accept
    stmt.accept(self)
  File "/usr/local/Cellar/mypy/0.521/libexec/lib/python3.6/site-packages/mypy/nodes.py", line 829, in accept
    return visitor.visit_expression_stmt(self)
  File "/usr/local/Cellar/mypy/0.521/libexec/lib/python3.6/site-packages/mypy/checker.py", line 1883, in visit_expression_stmt
    self.expr_checker.accept(s.expr, allow_none_return=True, always_allow_any=True)
  File "/usr/local/Cellar/mypy/0.521/libexec/lib/python3.6/site-packages/mypy/checkexpr.py", line 2213, in accept
    typ = node.accept(self)
  File "/usr/local/Cellar/mypy/0.521/libexec/lib/python3.6/site-packages/mypy/nodes.py", line 1107, in accept
    return visitor.visit_str_expr(self)
  File "/usr/local/Cellar/mypy/0.521/libexec/lib/python3.6/site-packages/mypy/checkexpr.py", line 1243, in visit_str_expr
    return self.named_type('builtins.str')
  File "/usr/local/Cellar/mypy/0.521/libexec/lib/python3.6/site-packages/mypy/checkexpr.py", line 2237, in named_type
    return self.chk.named_type(name)
  File "/usr/local/Cellar/mypy/0.521/libexec/lib/python3.6/site-packages/mypy/checker.py", line 2423, in named_type
    sym = self.lookup_qualified(name)
  File "/usr/local/Cellar/mypy/0.521/libexec/lib/python3.6/site-packages/mypy/checker.py", line 2488, in lookup_qualified
    n = self.modules[parts[0]]
KeyError: 'builtins'
```

**Comment by bgwines** [comment]
cc @jonmac

**Comment by ilevkivskyi** [comment]
Do you have a repro for this? But at first glance it looks like a broken installation. Could you please install from the GitHub master and see what happens? For example with:
```
 python3 -m pip install -U git+git://github.com/python/mypy.git
```

**Comment by gvanrossum** [comment]
I suspect this is a brew release (I now recognize those because they report to be the correct version with a git commit hash and "-dirty" appended). We've had this happen at Dropbox a few times too, I don't recall how it was resolved but possibly upgrading brew and then uninstalling + reinstalling python3 would work, followed by uninstalling and reinstalling mypy (the latter preferably using pip).

**Comment by bgwines** [comment]
Installing via the preferred method fixed this for me (yes; it was via Homebrew). Thanks for the prompt response!

**Comment by ethanhs** [comment]
Perhaps [a new issue](https://github.com/Homebrew/homebrew-core/issues/new) over at homebrew will avoid this issue for others?
