### ISSUE TITLE
Crash when defining and calling an overload without importing overload

### ISSUE THREAD

**Issue by elazarg** [python/mypy#4062]
Repro:
```python
@overload
def f(x: int) -> None: ...
@overload  # doesn't matter if we have one or two
def f(x: str) -> None: ...

def f(x): pass  # doesn't matter if we have implementation
f(1)
```

```
Traceback (most recent call last):
  File "/home/elazarg/.pyenv/versions/3.6.0/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/elazarg/.pyenv/versions/3.6.0/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~/workspace/mypy/mypy/__main__.py", line 11, in <module>
    main(None)
  File "~/workspace/mypy/mypy/main.py", line 50, in main
    res = type_check_only(sources, bin_dir, options)
  File "~/workspace/mypy/mypy/main.py", line 103, in type_check_only
    options=options)
  File "~/workspace/mypy/mypy/build.py", line 198, in build
    graph = dispatch(sources, manager)
  File "~/workspace/mypy/mypy/build.py", line 1838, in dispatch
    process_graph(graph, manager)
  File "~/workspace/mypy/mypy/build.py", line 2088, in process_graph
    process_stale_scc(graph, scc, manager)
  File "~/workspace/mypy/mypy/build.py", line 2191, in process_stale_scc
    graph[id].type_check_first_pass()
  File "~/workspace/mypy/mypy/build.py", line 1750, in type_check_first_pass
    self.type_checker.check_first_pass()
  File "~/workspace/mypy/mypy/checker.py", line 194, in check_first_pass
    self.accept(d)
  File "~/workspace/mypy/mypy/checker.py", line 282, in accept
    stmt.accept(self)
  File "~/workspace/mypy/mypy/nodes.py", line 787, in accept
    return visitor.visit_expression_stmt(self)
  File "~/workspace/mypy/mypy/checker.py", line 2001, in visit_expression_stmt
    self.expr_checker.accept(s.expr, allow_none_return=True, always_allow_any=True)
  File "~/workspace/mypy/mypy/checkexpr.py", line 2353, in accept
    typ = self.visit_call_expr(node, allow_none_return=True)
  File "~/workspace/mypy/mypy/checkexpr.py", line 233, in visit_call_expr
    callee_type = self.accept(e.callee, type_context, always_allow_any=True)
  File "~/workspace/mypy/mypy/checkexpr.py", line 2357, in accept
    typ = node.accept(self)
  File "~/workspace/mypy/mypy/nodes.py", line 1167, in accept
    return visitor.visit_name_expr(self)
  File "~/workspace/mypy/mypy/checkexpr.py", line 129, in visit_name_expr
    result = self.analyze_ref_expr(e)
  File "~/workspace/mypy/mypy/checkexpr.py", line 177, in analyze_ref_expr
    assert result is not None
AssertionError:
```

**Comment by ilevkivskyi** [comment]
I think this is closely related to https://github.com/python/mypy/issues/3574 (not sure if this is a duplicate).

**Comment by elazarg** [comment]
You are right - this is an exact duplicate  of [this comment](https://github.com/python/mypy/issues/3574#issuecomment-322096201) within the issue.
