### ISSUE TITLE
"AssertionError: Cannot find <thing>" from fixup.py still occurs

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#4094]
I'm seeing this traceback when running mypy over an internal codebase:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/__main__.py", line 11, in <module>
    main(None)
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/main.py", line 50, in main
    res = type_check_only(sources, bin_dir, options)
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/main.py", line 103, in type_check_only
    options=options)
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/build.py", line 199, in build
    graph = dispatch(sources, manager)
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/build.py", line 1864, in dispatch
    process_graph(graph, manager)
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/build.py", line 2107, in process_graph
    process_fresh_scc(graph, prev_scc)
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/build.py", line 2176, in process_fresh_scc
    graph[id].fix_cross_refs()
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/build.py", line 1597, in fix_cross_refs
    self.manager.options.quick_and_dirty)
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/fixup.py", line 22, in fixup_module_pass_one
    node_fixer.visit_symbol_table(tree.names)
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/fixup.py", line 102, in visit_symbol_table
    self.visit_type_info(value.node)
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/fixup.py", line 56, in visit_type_info
    self.visit_symbol_table(info.names)
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/fixup.py", line 104, in visit_symbol_table
    value.node.accept(self)
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/nodes.py", line 496, in accept
    return visitor.visit_func_def(self)
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/fixup.py", line 112, in visit_func_def
    func.type.accept(self.type_fixer)
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/types.py", line 737, in accept
    return visitor.visit_callable_type(self)
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/fixup.py", line 187, in visit_callable_type
    argt.accept(self)
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/types.py", line 476, in accept
    return visitor.visit_instance(self)
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/fixup.py", line 170, in visit_instance
    base.accept(self)
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/types.py", line 476, in accept
    return visitor.visit_instance(self)
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/fixup.py", line 170, in visit_instance
    base.accept(self)
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/types.py", line 476, in accept
    return visitor.visit_instance(self)
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/fixup.py", line 163, in visit_instance
    node = lookup_qualified(self.modules, type_ref, self.quick_and_dirty)
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/fixup.py", line 254, in lookup_qualified
    stnode = lookup_qualified_stnode(modules, name, quick_and_dirty)
  File "/Users/guido/src/client/.mypy/venv/lib/python3.6/site-packages/mypy/fixup.py", line 268, in lookup_qualified_stnode
    assert '.' in head, "Cannot find %s" % (name,)
AssertionError: Cannot find dropbox.foundation.raii.destroyable._impl.Destroyable
```
This is with mypy rev 5d25713ead47ab1bc0c7ee92b575d754b10f700c, which is recent (yesterday). The scenario is something like this:

1. Take a known good version of the codebase, run `mypy -i`, it's clean.
2. Apply a large patch, run `mypy -i`, it gives one warning (see below).
3. Apply a fix (see below) for the warning, run `mypy -i`, it crashes (see above).

The warning in step 2 is:
```
dropbox/foundation/raii/_zoo/affine/__init__.py:114: warning: Assertion is always true, perhaps remove parentheses?
```
The fix is:
```
--- a/dropbox/foundation/raii/_zoo/affine/__init__.py
+++ b/dropbox/foundation/raii/_zoo/affine/__init__.py
@@ -112,11 +112,11 @@ class AffineDestroyableMeta(SuperDestroyableMeta2):
             )
 
         assert (
-            name == 'AffineDestroyableBase' or any(
+            (name == 'AffineDestroyableBase') or any(
                 is_instance_of_adb(superbase)
                 for base in bases
                 for superbase in base.__mro__
-            ),
+            )
         ), "Classes using AffineDestroyableMeta must derive from AffineDestroyableBase"
 
         __suffix = "AffineDestroyable"
```
I'm mostly writing this down for myself, since I will have to step out for a bit before I can debug this more. I haven't had time to try to boil it down yet. (There's a superclass that has a generic metaclass, or something.)

**Comment by ilevkivskyi** [comment]
``assert '.' in head`` is a great hint, there are two places where this error can happen, and we fixed the second related to dependency invalidation, this one is however different, it looks like a whole module has been deleted.

**Comment by gvanrossum** [comment]
Hm, I don't see any deleted modules in our diffs, however many added ones.

**Comment by ilevkivskyi** [comment]
OK, another possible cause is that something is stored in "unqualified" form (``name`` instead of ``fullname``).

**Comment by ilevkivskyi** [comment]
Is ``Destroyable`` a nested class?

**Comment by gvanrossum** [comment]
No, but a relevant part of the class hierarchy (in reality spread across many modules) is:
```py
class SuperDestroyableMeta(GenericMeta, abc.ABCMeta): ...
class DestroyableMeta(SuperDestroyableMeta): ...
_DClass = TypeVar('_DClass', bound='SuperDestroyable')
_ActClass = TypeVar('_ActClass')
class SuperDestroyable(Generic[_DClass, _ActClass]): ...
@six.add_metaclass(ABCMeta)
class DestroyAction(object): ...
class Destroyable(six.with_metaclass(DestroyableMeta, SuperDestroyable['Destroyable', DestroyAction])): ...
```

**Comment by ilevkivskyi** [comment]
Sorry for lots of questions, but one more just to clarify: does this file ``dropbox/foundation/raii/destroyable/_impl.py`` exist after you apply the large patch?

**Comment by gvanrossum** [comment]
Yes, in fact `dropbox/foundation/raii/destroyable/_impl.py` is not touched by either patch (but used by code involved in the patch).

**Comment by gvanrossum** [comment]
Still seeing this.

**Comment by gvanrossum** [comment]
Spent another hour on this without results; right now I cannot even repro the problem (even though I am supposed to have a set of files that should repro it).

**Comment by ilevkivskyi** [comment]
We didn't see this for some time, and few instances of this were fixed recently, so I propose to close this. We can re-open if it will appear again.

**Comment by carver** [comment]
I ran into this issue today, on mypy 0.620.

Because I was getting different results on my machine than on others, I speculated that I had a *weird* cache somehow. On a whim I tried `rm -rf .mypy_cache/` and the error went away.

Just thought I'd leave a note, in case it helps another lost soul who stumbles on this issue.

**Comment by ilevkivskyi** [comment]
Another possible idea is that we can add a suggestion in the error message (if this will happen again) to _first_ archive the cache and send to us for inspection (if it is not proprietary code), and _then_ delete the cache.

**Comment by markedwards** [comment]
This happened to me today, and I have the corrupted cache.

**Comment by ethanhs** [comment]
@markedwards if you can upload that would be greatly appreciated! Also what version of mypy were you using?

**Comment by markedwards** [comment]
The code in question is proprietary and not public.  Is there a way I can share minimal information to help debug this?  mypy version is 0.670
