### ISSUE TITLE
Crash in some tuple type

### ISSUE THREAD

**Issue by JelleZijlstra** [python/mypy#4203]
I got this on a large internal codebase (edit, got a small repro, see below):
```
qclient/scribe.py:842:8: error: Revealed type is 'builtins.list[Tuple[Any, Any, Any]]'
qclient/scribe.py:843: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.530
Traceback (most recent call last):
  File "/home/jelle/ans/venv/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jelle/ans/venv/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/__main__.py", line 11, in <module>
    main(None)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/main.py", line 50, in main
    res = type_check_only(sources, bin_dir, options)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/main.py", line 103, in type_check_only
    options=options)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/build.py", line 198, in build
    graph = dispatch(sources, manager)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/build.py", line 1841, in dispatch
    process_graph(graph, manager)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/build.py", line 2091, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/build.py", line 2194, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/build.py", line 1753, in type_check_first_pass
    self.type_checker.check_first_pass()
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checker.py", line 194, in check_first_pass
    self.accept(d)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checker.py", line 282, in accept
    stmt.accept(self)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/nodes.py", line 519, in accept
    return visitor.visit_func_def(self)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checker.py", line 530, in visit_func_def
    self.check_func_item(defn, name=defn.name())
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checker.py", line 590, in check_func_item
    self.check_func_def(defn, typ, name)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checker.py", line 750, in check_func_def
    self.accept(item.body)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checker.py", line 282, in accept
    stmt.accept(self)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/nodes.py", line 773, in accept
    return visitor.visit_block(self)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checker.py", line 1304, in visit_block
    self.accept(s)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checker.py", line 282, in accept
    stmt.accept(self)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/nodes.py", line 847, in accept
    return visitor.visit_while_stmt(self)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checker.py", line 2114, in visit_while_stmt
    exit_condition=s.expr)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checker.py", line 298, in accept_loop
    self.accept(body)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checker.py", line 282, in accept
    stmt.accept(self)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/nodes.py", line 936, in accept
    return visitor.visit_if_stmt(self)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checker.py", line 2100, in visit_if_stmt
    self.accept(b)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checker.py", line 282, in accept
    stmt.accept(self)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/nodes.py", line 773, in accept
    return visitor.visit_block(self)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checker.py", line 1304, in visit_block
    self.accept(s)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checker.py", line 282, in accept
    stmt.accept(self)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/nodes.py", line 817, in accept
    return visitor.visit_assignment_stmt(self)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checker.py", line 1311, in visit_assignment_stmt
    self.check_assignment(s.lvalues[-1], s.rvalue, s.type is None, s.new_syntax)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checker.py", line 1339, in check_assignment
    infer_lvalue_type)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checker.py", line 1589, in check_assignment_to_multiple_lvalues
    self.check_multi_assignment(lvalues, rvalue, context, infer_lvalue_type)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checker.py", line 1630, in check_multi_assignment
    context, undefined_rvalue, infer_lvalue_type)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checker.py", line 1650, in check_multi_assignment_from_tuple
    reinferred_rvalue_type = self.expr_checker.accept(rvalue, lvalue_type)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checkexpr.py", line 2372, in accept
    typ = node.accept(self)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/nodes.py", line 1256, in accept
    return visitor.visit_call_expr(self)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checkexpr.py", line 266, in visit_call_expr
    ret_type = self.check_call_expr_with_callee_type(callee_type, e, fullname, object_type)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checkexpr.py", line 503, in check_call_expr_with_callee_type
    object_type=object_type)[0]
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checkexpr.py", line 608, in check_call
    object_type=object_type)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checkexpr.py", line 563, in check_call
    callee, context)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/checkexpr.py", line 752, in infer_function_type_arguments_using_context
    erased_ctx = replace_meta_vars(ctx, ErasedType())
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/erasetype.py", line 94, in replace_meta_vars
    return t.accept(TypeVarEraser(lambda id: id.is_meta_var(), target_type))
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/types.py", line 982, in accept
    return visitor.visit_tuple_type(self)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/types.py", line 1554, in visit_tuple_type
    return TupleType(self.translate_types(t.items),
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/types.py", line 1574, in translate_types
    return [t.accept(self) for t in types]
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/types.py", line 1574, in <listcomp>
    return [t.accept(self) for t in types]
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/types.py", line 982, in accept
    return visitor.visit_tuple_type(self)
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/types.py", line 1554, in visit_tuple_type
    return TupleType(self.translate_types(t.items),
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/types.py", line 1574, in translate_types
    return [t.accept(self) for t in types]
  File "/home/jelle/ans/venv/lib/python3.6/site-packages/mypy/types.py", line 1574, in <listcomp>
    return [t.accept(self) for t in types]
AttributeError: 'NoneType' object has no attribute 'accept'
qclient/scribe.py:843: : note: use --pdb to drop into pdb
```

It repros on:
```
from typing import List, Tuple, Any

def f() -> None:
    readers: List[Tuple[Any, Any, Any]] = []
    reveal_type(readers)
    idx, (generator, entry, box) = min(enumerate(readers), key=lambda x: x[1][1]['time'])
```
invoking mypy 0.530 without special options.

**Comment by JelleZijlstra** [comment]
Seems to be fixed on v0.540.
