### ISSUE TITLE
mypy_extensions: missing dependency? typing (py27)

### ISSUE THREAD

**Issue by nehaljwani** [python/mypy#4264]
```
(mypytest) [root@80ca205d2ef4 recipe]# pip install mypy_extensions
Collecting mypy_extensions
  Downloading mypy_extensions-0.3.0.tar.gz
Building wheels for collected packages: mypy-extensions
  Running setup.py bdist_wheel for mypy-extensions ... done
  Stored in directory: /root/.cache/pip/wheels/58/47/b8/ffdcbc1959691d5ff42fa78937b36638ccbed59f2af8d35b18
Successfully built mypy-extensions
Installing collected packages: mypy-extensions
Successfully installed mypy-extensions-0.3.0
(mypytest) [root@80ca205d2ef4 recipe]# python -c "import mypy_extensions"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/mypytest/lib/python2.7/site-packages/mypy_extensions.py", line 8, in <module>
    from typing import Any
ImportError: No module named typing
```

**Comment by gvanrossum** [comment]
It seems pretty silly to be using mypy_extensions without typing, but you're right, this should be added to extensions/setup.py. Can you submit a PR to add it?
