### ISSUE TITLE
Pytest tracebacks are sometimes overly long

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4279]
It seems that pytest arbitrarily produces either a very long or a compact traceback when running a failing mypy test case. It would be better to always generate short tracebacks. I haven't tried to understand what determines the length of the traceback yet.

For example, this is a long traceback:

```
=========================================== FAILURES ============================================
______________________________________ testModifyTwoFiles1 ______________________________________
data: /Users/jukka/src/mypy/test-data/unit/fine-grained-modules.test:263:
SystemExit: 1
------------------------------------- Captured stdout call --------------------------------------
==== update ['a', 'b'] ====
-- update single a --
Traceback (most recent call last):
  File "/Users/jukka/venv/mypy/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/config.py", line 58, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/main.py", line 139, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/main.py", line 110, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/main.py", line 146, in _main
    config.hook.pytest_runtestloop(session=session)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/main.py", line 169, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 248, in _wrapped_call
    call_outcome = _CallOutcome(func)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 248, in _wrapped_call
    call_outcome = _CallOutcome(func)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/runner.py", line 68, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/runner.py", line 82, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/runner.py", line 162, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/runner.py", line 182, in call_runtest_hook
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/runner.py", line 196, in __init__
    self.result = func()
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/runner.py", line 182, in <lambda>
    return CallInfo(lambda: ihook(item=item, **kwds), when=when)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 248, in _wrapped_call
    call_outcome = _CallOutcome(func)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/Users/jukka/venv/mypy/lib/python3.6/site-packages/_pytest/runner.py", line 112, in pytest_runtest_call
    item.runtest()
  File "/Users/jukka/src/mypy/mypy/test/data.py", line 587, in runtest
    self.parent.obj(update_data=update_data).run_case(self.obj)
  File "/Users/jukka/src/mypy/mypy/test/testfinegrained.py", line 71, in run_case
    new_messages = fine_grained_manager.update(modules)
  File "/Users/jukka/src/mypy/mypy/server/update.py", line 121, in update
    result = self.update_single(id, path)
  File "/Users/jukka/src/mypy/mypy/server/update.py", line 141, in update_single
    new_modules, graph = build_incremental_step(manager, [(module, path)], graph)
  File "/Users/jukka/src/mypy/mypy/server/update.py", line 249, in build_incremental_step
    state.type_check_first_pass()
  File "/Users/jukka/src/mypy/mypy/build.py", line 1850, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/Users/jukka/src/mypy/mypy/checker.py", line 196, in check_first_pass
    self.accept(d)
  File "/Users/jukka/src/mypy/mypy/checker.py", line 286, in accept
    stmt.accept(self)
  File "/Users/jukka/src/mypy/mypy/nodes.py", line 764, in accept
    return visitor.visit_expression_stmt(self)
  File "/Users/jukka/src/mypy/mypy/checker.py", line 2089, in visit_expression_stmt
    self.expr_checker.accept(s.expr, allow_none_return=True, always_allow_any=True)
  File "/Users/jukka/src/mypy/mypy/checkexpr.py", line 2361, in accept
    typ = self.visit_call_expr(node, allow_none_return=True)
  File "/Users/jukka/src/mypy/mypy/checkexpr.py", line 268, in visit_call_expr
    ret_type = self.check_call_expr_with_callee_type(callee_type, e, fullname, object_type)
  File "/Users/jukka/src/mypy/mypy/checkexpr.py", line 505, in check_call_expr_with_callee_type
    object_type=object_type)[0]
  File "/Users/jukka/src/mypy/mypy/checkexpr.py", line 544, in check_call
    if (callee.is_type_obj() and callee.type_object().is_abstract
  File "/Users/jukka/src/mypy/mypy/types.py", line 723, in is_type_obj
    return self.fallback.type.is_metaclass()
AttributeError: 'NoneType' object has no attribute 'type'
------------------------------------- Captured stderr call --------------------------------------
tmp/a.py:2: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.560-dev-c62859126b41b9cc11f0244e03367e69654007a9-dirty
tmp/a.py:2: : note: use --pdb to drop into pdb
===================================== 3346 tests deselected =====================================
=========================== 1 failed, 3346 deselected in 0.72 seconds ===========================
```

Here is a short traceback generated from a very similar-looking failure:

```
=========================================== FAILURES ============================================
______________________________________ testModifyTwoFiles2 ______________________________________
data: /Users/jukka/src/mypy/test-data/unit/fine-grained-modules.test:278:
/Users/jukka/src/mypy/mypy/test/testfinegrained.py:71: in run_case
    new_messages = fine_grained_manager.update(modules)
/Users/jukka/src/mypy/mypy/server/update.py:121: in update
    result = self.update_single(id, path)
/Users/jukka/src/mypy/mypy/server/update.py:134: in update_single
    snapshot = snapshot_symbol_table(module, manager.modules[module].names)
/Users/jukka/src/mypy/mypy/server/astdiff.py:224: in snapshot_symbol_table
    result[name] = snapshot_definition(node, common)
/Users/jukka/src/mypy/mypy/server/astdiff.py:237: in snapshot_definition
    return ('Func', common, node.is_property, snapshot_type(node.type))
/Users/jukka/src/mypy/mypy/server/astdiff.py:274: in snapshot_type
    return typ.accept(SnapshotTypeVisitor())
/Users/jukka/src/mypy/mypy/types.py:739: in accept
    return visitor.visit_callable_type(self)
/Users/jukka/src/mypy/mypy/server/astdiff.py:348: in visit_callable_type
    typ.is_type_obj(),
/Users/jukka/src/mypy/mypy/types.py:723: in is_type_obj
    return self.fallback.type.is_metaclass()
E   AttributeError: 'NoneType' object has no attribute 'type'
------------------------------------- Captured stdout call --------------------------------------
==== update ['a', 'b'] ====
-- update single a --
triggered: ['<a.f>']
process b
triggered: ['<b.__package__>', '<b.__name__>', '<b.__doc__>', '<b.__file__>']
triggered: []
-- update single b --
===================================== 3346 tests deselected =====================================
=========================== 1 failed, 3346 deselected in 0.87 seconds ===========================
```

**Comment by gvanrossum** [comment]
I note that the former has mypy's own "INTERNAL ERROR" message tacked on,
while the second does not. That seems significant.

(BTW there's a third type of pytest traceback, where for certain stack
frames it prints several lines of context, and the values of various
variables. Those can go on forever.)

**Comment by elazarg** [comment]
I think you're right - I think it's because the first is printed by mypy using `report_internal_error`, and the second by pytest. mypy reports internal error from `ExpressionChecker.accept()` which might be too deep.
```python
        try:
            ...
        except Exception as err:
            report_internal_error(err, self.chk.errors.file,
                                  node.line, self.chk.errors, self.chk.options)
```
Similarly in `checker.py` and `semanal.py`.

I suppose this try-except should be in `build.py` or something like that?

**Comment by ilevkivskyi** [comment]
FWIW, I would prefer the longer tracebacks, or rather a possibility to generate the full tracebacks.
I remember few times when I was misled by those short versions (assuming they were complete).

**Comment by ethanhs** [comment]
Pytest has a flag `--tb` which can modify this, documented here: https://docs.pytest.org/en/latest/usage.html?highlight=tb%3Dshort#modifying-python-traceback-printing. It appears the first and last are set to "long" and the rest are set to short by default. It seems to me "native" or "short" are better options.

**Comment by hauntsaninja** [comment]
A lot has changed in the last four years / we use some nice pytest tricks now
