### ISSUE TITLE
Fine-grained incremental mode crash if module path changes

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#4461]
On the initial fine-grained incremental mode run I have a module `foo.x` at path `../bar/foo/x.py`. Then I delete the file and run an incremental update. This time there is an alternative `foo.x` file at `foo/x.py`, which `load_graph` will pick up. Fine-grained incremental mode will think that the file is deleted, and fail at an assertion:

```
Traceback (most recent call last):
  File "scripts/../mypy/dmypy_server.py", line 130, in serve
    resp = self.run_command(command, data)
  File "scripts/../mypy/dmypy_server.py", line 164, in run_command
    return method(self, **data)
  File "scripts/../mypy/dmypy_server.py", line 195, in cmd_check
    return self.check(self.last_sources)
  File "scripts/../mypy/dmypy_server.py", line 209, in check
    return self.check_fine_grained(sources)
  File "scripts/../mypy/dmypy_server.py", line 243, in check_fine_grained
    return self.fine_grained_increment(sources)
  File "scripts/../mypy/dmypy_server.py", line 277, in fine_grained_increment
    messages = self.fine_grained_manager.update(changed)
  File "scripts/../mypy/server/update.py", line 222, in update
    result = self.update_single(next_id, next_path)
  File "scripts/../mypy/server/update.py", line 265, in update_single
    result = update_single_isolated(module, path, manager, previous_modules)
  File "scripts/../mypy/server/update.py", line 396, in update_single_isolated
    graph = delete_module(module, graph, manager)
  File "scripts/../mypy/server/update.py", line 495, in delete_module
    assert module_id not in graph
AssertionError
```

**Comment by hauntsaninja** [comment]
Lots has changed, no reports since, stacktrace hasn't existed on master in a while
