### ISSUE TITLE
INTERNAL ERROR - unresolved forward reference

### ISSUE THREAD

**Issue by rlz** [python/mypy#4519]
Hello,

I got "error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.560" message from MyPy

This is the traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 11, in <module>
    sys.exit(console_entry())
  File "/usr/local/lib/python3.6/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "/usr/local/lib/python3.6/site-packages/mypy/main.py", line 66, in main
    res = type_check_only(sources, bin_dir, options)
  File "/usr/local/lib/python3.6/site-packages/mypy/main.py", line 119, in type_check_only
    options=options)
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 218, in build
    graph = dispatch(sources, manager)
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 1997, in dispatch
    process_graph(graph, manager)
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 2299, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 2469, in process_stale_scc
    graph[id].semantic_analysis_pass_three()
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 1863, in semantic_analysis_pass_three
    self.options, patches)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal_pass3.py", line 57, in visit_file
    self.accept(file_node)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal_pass3.py", line 74, in accept
    node.accept(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/nodes.py", line 228, in accept
    return visitor.visit_mypy_file(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/traverser.py", line 30, in visit_mypy_file
    d.accept(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/nodes.py", line 696, in accept
    return visitor.visit_class_def(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal_pass3.py", line 125, in visit_class_def
    super().visit_class_def(tdef)
  File "/usr/local/lib/python3.6/site-packages/mypy/traverser.py", line 61, in visit_class_def
    o.defs.accept(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/nodes.py", line 756, in accept
    return visitor.visit_block(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal_pass3.py", line 81, in visit_block
    super().visit_block(b)
  File "/usr/local/lib/python3.6/site-packages/mypy/traverser.py", line 34, in visit_block
    s.accept(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/nodes.py", line 497, in accept
    return visitor.visit_func_def(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal_pass3.py", line 85, in visit_func_def
    self.analyze(fdef.type, fdef)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal_pass3.py", line 333, in analyze
    type.accept(analyzer)
  File "/usr/local/lib/python3.6/site-packages/mypy/types.py", line 739, in accept
    return visitor.visit_callable_type(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/typeanal.py", line 771, in visit_callable_type
    arg_type.accept(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/types.py", line 475, in accept
    return visitor.visit_instance(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/typeanal.py", line 727, in visit_instance
    if not is_subtype(arg, bound):
  File "/usr/local/lib/python3.6/site-packages/mypy/subtypes.py", line 83, in is_subtype
    ignore_declared_variance=ignore_declared_variance))
  File "/usr/local/lib/python3.6/site-packages/mypy/types.py", line 1230, in accept
    return visitor.visit_union_type(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/subtypes.py", line 312, in visit_union_type
    for item in left.items)
  File "/usr/local/lib/python3.6/site-packages/mypy/subtypes.py", line 312, in <genexpr>
    for item in left.items)
  File "/usr/local/lib/python3.6/site-packages/mypy/subtypes.py", line 83, in is_subtype
    ignore_declared_variance=ignore_declared_variance))
  File "/usr/local/lib/python3.6/site-packages/mypy/types.py", line 1415, in accept
    return visitor.visit_forwardref_type(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/types.py", line 1500, in visit_forwardref_type
    raise RuntimeError('Internal error: unresolved forward reference')
RuntimeError: Internal error: unresolved forward reference
```

I was running it with --strict --strict-optional, but without it gives me the same message.
Hard to help with reproduction, because I don't want to share whole code. But I can try to do simple repro if you can give me a hint how to debug into MyPy and understand what's wrong with it.

**Comment by rlz** [comment]
OK,

I manage to make short reproduction:

```python
import typing as t


class Foo:
    def foo(self, bar: t.Mapping[str, t.Union['ProblematicType', str]]):
        pass


ProblematicType = t.Union[int, float]
```

**Comment by rlz** [comment]
Looks like it's fixed in the latest code...

**Comment by ilevkivskyi** [comment]
Yes, it was fixed few weeks ago and will be released soon. We normally don't keep issues open when a bug is fixed in master.
