### ISSUE TITLE
Latest master doesn't work installing using pip

### ISSUE THREAD

**Issue by euresti** [python/mypy#4569]
I think I forgot to add mypy.plugins somewhere:
```
Traceback (most recent call last):
  File "/Users/david/src/zapgram/.ve/bin/mypy", line 11, in <module>
    load_entry_point('mypy===0.570-dev-bdd5de949f4ee8f9333cabd0ac7282acc2aefaa4', 'console_scripts', 'mypy')()
  File "/Users/david/src/zapgram/.ve/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/david/src/zapgram/.ve/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/Users/david/src/zapgram/.ve/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/Users/david/src/zapgram/.ve/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/david/src/zapgram/.ve/lib/python3.6/site-packages/mypy/__main__.py", line 3, in <module>
    from mypy.main import main
  File "/Users/david/src/zapgram/.ve/lib/python3.6/site-packages/mypy/main.py", line 13, in <module>
    from mypy import build
  File "/Users/david/src/zapgram/.ve/lib/python3.6/site-packages/mypy/build.py", line 37, in <module>
    from mypy.semanal_pass1 import SemanticAnalyzerPass1
  File "/Users/david/src/zapgram/.ve/lib/python3.6/site-packages/mypy/semanal_pass1.py", line 30, in <module>
    from mypy.semanal import SemanticAnalyzerPass2, infer_reachability_of_if_statement
  File "/Users/david/src/zapgram/.ve/lib/python3.6/site-packages/mypy/semanal.py", line 75, in <module>
    from mypy.typeanal import (
  File "/Users/david/src/zapgram/.ve/lib/python3.6/site-packages/mypy/typeanal.py", line 29, in <module>
    from mypy.plugin import Plugin, TypeAnalyzerPluginInterface, AnalyzeTypeContext
  File "/Users/david/src/zapgram/.ve/lib/python3.6/site-packages/mypy/plugin.py", line 7, in <module>
    import mypy.plugins.attrs
ModuleNotFoundError: No module named 'mypy.plugins'
```

Sorry.

**Comment by ilevkivskyi** [comment]
Maybe you forgot to add an `__init__.py`  somewhere? Can you try this? Also maybe you can try `from mypy.plugins import attrs`?

**Comment by gvanrossum** [comment]
See #4570

**Comment by ilevkivskyi** [comment]
Should be fixed now. @euresti Could you please check and close?

**Comment by euresti** [comment]
Yep.  Thanks!

**Comment by ashishp99** [comment]
./jok3r.py db

         ____.       __    ________              `Combine the best of...
        |    | ____ |  | __\_____  \______           ...open-source Hacking Tools`
        |    |/  _ \|  |/ /  _(__  <_  __ \ 
    /\__|    (  (_) )    <  /       \  | \/
    \________|\____/|__|_ \/______  /__|      v3.0
                         \/       \/     
    
          ~ Network & Web Pentest Automation Framework ~
   [ Manage Toolbox | Automate Attacks | Chain Hacking Tools ]
   

[!] Unexpected error occured: do_load
Traceback (most recent call last):
  File "./jok3r.py", line 44, in __init__
    controller.run()
  File "/media/master/New Volume/jok3r-master/lib/controller/MainController.py", line 23, in run
    }.get(self.arguments.mode)(self.arguments, self.settings, self.sqlsess).run()
  File "/media/master/New Volume/jok3r-master/lib/controller/DbController.py", line 65, in __init__
    del cmd2.Cmd.do_load
AttributeError: do_load
 please  resolve issuse
