### ISSUE TITLE
Crash in fine grained mode (unresolved forward reference)

### ISSUE THREAD

**Issue by ilevkivskyi** [python/mypy#4597]
Here is a traceback:
```
Traceback (most recent call last):
  File "[somewhere]/mypy/dmypy_server.py", line 135, in serve
    resp = self.run_command(command, data)
  File "[somewhere]/mypy/dmypy_server.py", line 169, in run_command
    return method(self, **data)
  File "[somewhere]/mypy/dmypy_server.py", line 200, in cmd_check
    return self.check(self.last_sources)
  File "[somewhere]/mypy/dmypy_server.py", line 214, in check
    return self.check_fine_grained(sources)
  File "[somewhere]/mypy/dmypy_server.py", line 246, in check_fine_grained
    return self.initialize_fine_grained(sources)
  File "[somewhere]/mypy/dmypy_server.py", line 291, in initialize_fine_grained
    messages = self.fine_grained_manager.update(changed)
  File "[somewhere]/mypy/server/update.py", line 222, in update
    result = self.update_single(next_id, next_path)
  File "[somewhere]/mypy/server/update.py", line 284, in update_single
    self.previous_targets_with_errors)
  File "[somewhere]/mypy/server/update.py", line 750, in propagate_changes_using_dependencies
    triggered |= reprocess_nodes(manager, graph, id, nodes, deps)
  File "[somewhere]/mypy/server/update.py", line 865, in reprocess_nodes
    merge_asts(file_node, old_symbols[name], file_node, new_symbols[name])
  File "[somewhere]/mypy/server/astmerge.py", line 85, in merge_asts
    node = replace_nodes_in_ast(new, replacement_map)
  File "[somewhere]/mypy/server/astmerge.py", line 130, in replace_nodes_in_ast
    node.accept(visitor)
  File "[somewhere]/mypy/nodes.py", line 230, in accept
    return visitor.visit_mypy_file(self)
  File "[somewhere]/mypy/server/astmerge.py", line 151, in visit_mypy_file
    super().visit_mypy_file(node)
  File "[somewhere]/mypy/traverser.py", line 30, in visit_mypy_file
    d.accept(self)
  File "[somewhere]/mypy/nodes.py", line 501, in accept
    return visitor.visit_func_def(self)
  File "[somewhere]/mypy/server/astmerge.py", line 160, in visit_func_def
    self.fixup_type(node.type)
  File "[somewhere]/mypy/server/astmerge.py", line 255, in fixup_type
    typ.accept(TypeReplaceVisitor(self.replacements))
  File "[somewhere]/mypy/types.py", line 742, in accept
    return visitor.visit_callable_type(self)
  File "[somewhere]/mypy/server/astmerge.py", line 300, in visit_callable_type
    arg.accept(self)
  File "[somewhere]/mypy/types.py", line 1418, in accept
    return visitor.visit_forwardref_type(self)
  File "[somewhere]/mypy/types.py", line 1503, in visit_forwardref_type
    raise RuntimeError('Internal error: unresolved forward reference')
RuntimeError: Internal error: unresolved forward reference
```

There is no simple repro yet.

**Comment by JukkaL** [comment]
Closing due to a missing repro. This may have been fixed since we haven't seen this again.
