### ISSUE TITLE
attrs plugin bug when subclassing frozen classes

### ISSUE THREAD

**Issue by johnliu** [python/mypy#4655]
Running into an internal error when type checking the following attrs code:

```python
import attr


@attr.s(frozen=True, auto_attribs=True)
class A:
    foo: int
    bar: str


@attr.s(frozen=True, auto_attribs=True)
class B(A):
    baz: int
```

This code when run works as expected:

```python

>>> thing = B(foo=1, bar='hi', baz='bye')
>>> thing.foo = 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jliu/Projects/lyft/coupons/venv/lib/python3.6/site-packages/attr/_make.py", line 351, in _frozen_setattrs
    raise FrozenInstanceError()
attr.exceptions.FrozenInstanceError
```

Running mypy on this code yields the following error:
```
$ mypy -s --strict-optional --warn-no-return --show-traceback --html-report build app/test.py

Warning: --silent-imports has been replaced by --ignore-missing-imports --follow-imports=skip
app/test.py:10: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.570-dev-064c8d3301f8fab0769f12f4b1bb04a7fd7ae0de
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 11, in <module>
    load_entry_point('mypy===0.570-dev-064c8d3301f8fab0769f12f4b1bb04a7fd7ae0de', 'console_scripts', 'mypy')()
  File "/usr/local/lib/python3.6/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "/usr/local/lib/python3.6/site-packages/mypy/main.py", line 80, in main
    type_check_only(sources, bin_dir, options, flush_errors)
  File "/usr/local/lib/python3.6/site-packages/mypy/main.py", line 129, in type_check_only
    flush_errors=flush_errors)
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 180, in build
    result = _build(sources, options, alt_lib_path, bin_dir, saved_cache, flush_errors)
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 266, in _build
    graph = dispatch(sources, manager)
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 2112, in dispatch
    process_graph(graph, manager)
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 2413, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 2589, in process_stale_scc
    graph[id].semantic_analysis()
  File "/usr/local/lib/python3.6/site-packages/mypy/build.py", line 1947, in semantic_analysis
    self.manager.semantic_analyzer.visit_file(self.tree, self.xpath, self.options, patches)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal.py", line 294, in visit_file
    self.accept(d)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal.py", line 3962, in accept
    node.accept(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/nodes.py", line 711, in accept
    return visitor.visit_class_def(self)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal.py", line 679, in visit_class_def
    self.scope.leave()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal.py", line 735, in analyze_class_body
    self.apply_class_plugin_hooks(defn)
  File "/usr/local/lib/python3.6/site-packages/mypy/semanal.py", line 761, in apply_class_plugin_hooks
    hook(ClassDefContext(defn, decorator, self))
  File "/usr/local/lib/python3.6/site-packages/mypy/plugins/attrs.py", line 155, in attr_class_maker_callback
    _make_frozen(ctx, attributes)
  File "/usr/local/lib/python3.6/site-packages/mypy/plugins/attrs.py", line 389, in _make_frozen
    node = ctx.cls.info.names[attribute.name].node
KeyError: 'foo'
app/test.py:10: : note: use --pdb to drop into pdb
```

@euresti I believe you worked on this recently so tagging you (thanks for getting this in btw!)

**Comment by euresti** [comment]
Eek. Looks like I added to TODO: https://github.com/python/mypy/blob/master/mypy/plugins/attrs.py#L387

I didn't think it would crash though.

**Comment by johnliu** [comment]
No worries, it's not a requirement for me to subclass for now so all is well. Better to have this typechecked at all in the first place 😄
