### ISSUE TITLE
Tuple casting raises internal error

### ISSUE THREAD

**Issue by trevorbaca** [python/mypy#5161]
Example:
```
numbers: typing.Sequence[int] = ()
numbers = tuple(numbers)
if numbers and numbers != (0,):
    pass
```
Output of `mypy --show-traceback <testfille.py>`:
```
abjad_tmp.py:23: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.600
Traceback (most recent call last):
  File "/Users/trevorbaca/.virtualenvs/abjad3/bin/mypy", line 11, in <module>
    sys.exit(console_entry())
  File "/Users/trevorbaca/.virtualenvs/abjad3/lib/python3.6/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "/Users/trevorbaca/.virtualenvs/abjad3/lib/python3.6/site-packages/mypy/main.py", line 91, in main
    res = type_check_only(sources, bin_dir, options, flush_errors, fscache)  # noqa
  File "/Users/trevorbaca/.virtualenvs/abjad3/lib/python3.6/site-packages/mypy/main.py", line 148, in type_check_only
    fscache=fscache)
  File "/Users/trevorbaca/.virtualenvs/abjad3/lib/python3.6/site-packages/mypy/build.py", line 184, in build
    flush_errors, fscache)
  File "/Users/trevorbaca/.virtualenvs/abjad3/lib/python3.6/site-packages/mypy/build.py", line 282, in _build
    graph = dispatch(sources, manager)
  File "/Users/trevorbaca/.virtualenvs/abjad3/lib/python3.6/site-packages/mypy/build.py", line 2266, in dispatch
    process_graph(graph, manager)
  File "/Users/trevorbaca/.virtualenvs/abjad3/lib/python3.6/site-packages/mypy/build.py", line 2551, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/Users/trevorbaca/.virtualenvs/abjad3/lib/python3.6/site-packages/mypy/build.py", line 2667, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/Users/trevorbaca/.virtualenvs/abjad3/lib/python3.6/site-packages/mypy/build.py", line 1916, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/Users/trevorbaca/.virtualenvs/abjad3/lib/python3.6/site-packages/mypy/checker.py", line 252, in check_first_pass
    self.accept(d)
  File "/Users/trevorbaca/.virtualenvs/abjad3/lib/python3.6/site-packages/mypy/checker.py", line 351, in accept
    stmt.accept(self)
  File "/Users/trevorbaca/.virtualenvs/abjad3/lib/python3.6/site-packages/mypy/nodes.py", line 1043, in accept
    return visitor.visit_if_stmt(self)
  File "/Users/trevorbaca/.virtualenvs/abjad3/lib/python3.6/site-packages/mypy/checker.py", line 2286, in visit_if_stmt
    t = self.expr_checker.accept(e)
  File "/Users/trevorbaca/.virtualenvs/abjad3/lib/python3.6/site-packages/mypy/checkexpr.py", line 2379, in accept
    typ = node.accept(self)
  File "/Users/trevorbaca/.virtualenvs/abjad3/lib/python3.6/site-packages/mypy/nodes.py", line 1540, in accept
    return visitor.visit_op_expr(self)
  File "/Users/trevorbaca/.virtualenvs/abjad3/lib/python3.6/site-packages/mypy/checkexpr.py", line 1371, in visit_op_expr
    return self.check_boolean_op(e, e)
  File "/Users/trevorbaca/.virtualenvs/abjad3/lib/python3.6/site-packages/mypy/checkexpr.py", line 1634, in check_boolean_op
    assert left_map is not None  # find_isinstance_check guarantees this
AssertionError: 
```

**Comment by ethanhs** [comment]
It seems the code is crashing due to an unexpected <nothing>
```
numbers: typing.Sequence[int] = ()
numbers = tuple(numbers)'
reveal_type(numbers)  # <nothing>
```
