### ISSUE TITLE
Recursive subclass of NamedTuple crashes mypy

### ISSUE THREAD

**Issue by toolforger** [python/mypy#5195]
Mypy 0.610, Python 3.6.3.
Not tried Mypy from git master (haven't checked how to do that).

Crash vanishes if I replace the recursive type with a nonrecursive one, or use `object` as a parent class.

Code:

```Python
#! /usr/bin/env python3

from typing import List, NamedTuple

class Command(NamedTuple):
    subcommands: List['Command']

class HelpCommand(Command):
    pass

HelpCommand(subcommands=[]) # crashes mypy, works in Python
```

Command: `python3 -m mypy typetest.py --show-traceback`

Output:
```
typetest.py:5: error: Recursive types not fully supported yet, nested types replaced with "Any"
typetest.py: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.610
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jo/.local/lib/python3.6/site-packages/mypy/__main__.py", line 11, in <module>
    main(None)
  File "/home/jo/.local/lib/python3.6/site-packages/mypy/main.py", line 91, in main
    res = type_check_only(sources, bin_dir, options, flush_errors, fscache)  # noqa
  File "/home/jo/.local/lib/python3.6/site-packages/mypy/main.py", line 148, in type_check_only
    fscache=fscache)
  File "/home/jo/.local/lib/python3.6/site-packages/mypy/build.py", line 185, in build
    flush_errors, fscache)
  File "/home/jo/.local/lib/python3.6/site-packages/mypy/build.py", line 285, in _build
    graph = dispatch(sources, manager)
  File "/home/jo/.local/lib/python3.6/site-packages/mypy/build.py", line 2398, in dispatch
    process_graph(graph, manager)
  File "/home/jo/.local/lib/python3.6/site-packages/mypy/build.py", line 2691, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/jo/.local/lib/python3.6/site-packages/mypy/build.py", line 2820, in process_stale_scc
    graph[id].finish_passes()
  File "/home/jo/.local/lib/python3.6/site-packages/mypy/build.py", line 2067, in finish_passes
    manager.report_file(self.tree, self.type_map(), self.options)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/jo/.local/lib/python3.6/site-packages/mypy/build.py", line 1818, in wrap_context
    yield
  File "/home/jo/.local/lib/python3.6/site-packages/mypy/build.py", line 2062, in finish_passes
    self._patch_indirect_dependencies(self.type_checker().module_refs, self.type_map())
  File "/home/jo/.local/lib/python3.6/site-packages/mypy/build.py", line 2076, in _patch_indirect_dependencies
    encountered = self.manager.indirection_detector.find_modules(types) | module_refs
  File "/home/jo/.local/lib/python3.6/site-packages/mypy/indirection.py", line 29, in find_modules
    return self._visit(*typs)
  File "/home/jo/.local/lib/python3.6/site-packages/mypy/indirection.py", line 37, in _visit
    modules = typ.accept(self)
  File "/home/jo/.local/lib/python3.6/site-packages/mypy/types.py", line 1042, in accept
    return visitor.visit_tuple_type(self)
  File "/home/jo/.local/lib/python3.6/site-packages/mypy/indirection.py", line 91, in visit_tuple_type
    return self._visit(*t.items) | self._visit(t.fallback)
  File "/home/jo/.local/lib/python3.6/site-packages/mypy/indirection.py", line 37, in _visit
    modules = typ.accept(self)
  File "/home/jo/.local/lib/python3.6/site-packages/mypy/types.py", line 512, in accept
    return visitor.visit_instance(self)
  File "/home/jo/.local/lib/python3.6/site-packages/mypy/indirection.py", line 70, in visit_instance
    out = self._visit(*t.args)
  File "/home/jo/.local/lib/python3.6/site-packages/mypy/indirection.py", line 37, in _visit
    modules = typ.accept(self)
  File "/home/jo/.local/lib/python3.6/site-packages/mypy/types.py", line 512, in accept
    return visitor.visit_instance(self)
  File "/home/jo/.local/lib/python3.6/site-packages/mypy/indirection.py", line 75, in visit_instance
    for s in t.type.mro:
TypeError: 'NoneType' object is not iterable
typetest.py: : note: use --pdb to drop into pdb
```

**Comment by ilevkivskyi** [comment]
Ouch, it looks like I have missed this edge case when refactoring forward references. Thanks for reporting!

**Comment by ilevkivskyi** [comment]
This doesn't crash on master, but the type of `HelpCommand` class object contains a broken instance with an empty MRO and no line number set. I have a simple fix for this.

**Comment by toolforger** [comment]
Sweet, thanks.
The type recursion is at the core of the central data structure of my code. I tried changing its type, but that would have made using Mypy largely pointless, so I stopped using Mypy.
