### ISSUE TITLE
Mypy crashes sometimes under version 0.610

### ISSUE THREAD

**Issue by cburgdorf** [python/mypy#5281]
Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request?
Bug

* What is the actual behavior/output?
Mypy crashes with:

```
$ mypy --follow-imports=silent --ignore-missing-imports --no-strict-optional --check-untyped-defs --disallow-incomplete-defs --disallow-untyped-defs --disallow-any-generics -p p2p -p trinity
Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venv/bin/mypy", line 11, in <module>
    sys.exit(console_entry())
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venv/lib/python3.6/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venv/lib/python3.6/site-packages/mypy/main.py", line 91, in main
    res = type_check_only(sources, bin_dir, options, flush_errors, fscache)  # noqa
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venv/lib/python3.6/site-packages/mypy/main.py", line 148, in type_check_only
    fscache=fscache)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venv/lib/python3.6/site-packages/mypy/build.py", line 185, in build
    flush_errors, fscache)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venv/lib/python3.6/site-packages/mypy/build.py", line 285, in _build
    graph = dispatch(sources, manager)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venv/lib/python3.6/site-packages/mypy/build.py", line 2398, in dispatch
    process_graph(graph, manager)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venv/lib/python3.6/site-packages/mypy/build.py", line 2684, in process_graph
    process_fresh_modules(graph, prev_scc, manager)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venv/lib/python3.6/site-packages/mypy/build.py", line 2770, in process_fresh_modules
    graph[id].fix_cross_refs()
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venv/lib/python3.6/site-packages/mypy/build.py", line 1853, in fix_cross_refs
    self.options.use_fine_grained_cache)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venv/lib/python3.6/site-packages/mypy/fixup.py", line 25, in fixup_module
    node_fixer.visit_symbol_table(tree.names)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venv/lib/python3.6/site-packages/mypy/fixup.py", line 77, in visit_symbol_table
    self.quick_and_dirty)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venv/lib/python3.6/site-packages/mypy/fixup.py", line 266, in lookup_qualified_stnode
    assert '.' in head, "Cannot find %s" % (name,)
AssertionError: Cannot find eth_keys.datatypes
```

* What is the behavior/output you expect?
Mypy type checks
* What are the versions of mypy and Python you are using?
  I haven't had this problem prior to mypy 0.610
* What are the mypy flags you are using? (For example --strict-optional)
`mypy --follow-imports=silent --ignore-missing-imports --no-strict-optional --check-untyped-defs --disallow-incomplete-defs --disallow-untyped-defs --disallow-any-generics -p p2p -p trinity`

This comes up out of the blue on code that type checked fine before and persists unless I delete `.mypy_cache`. After I deleted the cache `mypy` works again as expected.

**Comment by ethanhs** [comment]
If the behavior is reproducable, could you upload a zip of the cache? Also since it seems this is the open source project https://github.com/ethereum/py-evm, could you upload the source to a branch for us to inspect?

**Comment by cburgdorf** [comment]
Finally happened again on mypy `0.620`.

```
$ mypy --follow-imports=silent --ignore-missing-imports --no-strict-optional --check-untyped-defs --disallow-incomplete-defs --disallow-untyped-defs --disallow-any-generics -p p2p -p trinity
Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venvx/bin/mypy", line 11, in <module>
    sys.exit(console_entry())
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venvx/lib/python3.6/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venvx/lib/python3.6/site-packages/mypy/main.py", line 91, in main
    res = type_check_only(sources, bin_dir, options, flush_errors, fscache)  # noqa
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venvx/lib/python3.6/site-packages/mypy/main.py", line 148, in type_check_only
    fscache=fscache)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venvx/lib/python3.6/site-packages/mypy/build.py", line 177, in build
    flush_errors, fscache)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venvx/lib/python3.6/site-packages/mypy/build.py", line 350, in _build
    graph = dispatch(sources, manager)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venvx/lib/python3.6/site-packages/mypy/build.py", line 2560, in dispatch
    process_graph(graph, manager)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venvx/lib/python3.6/site-packages/mypy/build.py", line 2846, in process_graph
    process_fresh_modules(graph, prev_scc, manager)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venvx/lib/python3.6/site-packages/mypy/build.py", line 2932, in process_fresh_modules
    graph[id].fix_cross_refs()
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venvx/lib/python3.6/site-packages/mypy/build.py", line 1975, in fix_cross_refs
    self.options.use_fine_grained_cache)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venvx/lib/python3.6/site-packages/mypy/fixup.py", line 24, in fixup_module
    node_fixer.visit_symbol_table(tree.names)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venvx/lib/python3.6/site-packages/mypy/fixup.py", line 76, in visit_symbol_table
    self.quick_and_dirty)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/venvx/lib/python3.6/site-packages/mypy/fixup.py", line 259, in lookup_qualified_stnode
    assert '.' in head, "Cannot find %s" % (name,)
AssertionError: Cannot find eth_keys.datatypes
```

That is the ref on which it happened: https://github.com/ethereum/py-evm/commit/269efb75ab169c6f23462e91c75e79db9bbe6887

Just as before, simply removing the `.mypy_cache` and re-running `mypy` worked.

Here's the zipped `.mypy_cache` directory:

[mypy_cache.zip](https://github.com/python/mypy/files/2269448/mypy_cache.zip)
