### ISSUE TITLE
dmypy crash by duplicate function masked by decorator from other module

### ISSUE THREAD

**Issue by obeleh** [python/mypy#5394]
I have two files:

file1.py:

```python
def dec(fun):
    def other_fun():
        pass

    return other_fun

a = 1
```

file2.py
```python
from file1 import dec

@dec
def a():
    pass

@dec
def a():
    pass
```

And I'm running `dmypy` in the PyCharm plugin with the following settings:
- command: `dmypy start -- --follow-imports=error ; dmypy check .`
- path suffix: `/usr/local/bin`

```
pip3 freeze | grep mypy
mypy==0.620
```

If I run the first time everything is ok. If I then change something in file1 `a = 2` for example dmypy crashes with the following stacktrace:

```
Daemon is still alive
Daemon crashed!
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mypy/dmypy_server.py", line 175, in serve
    resp = self.run_command(command, data)
  File "/usr/local/lib/python3.6/site-packages/mypy/dmypy_server.py", line 215, in run_command
    return method(self, **data)
  File "/usr/local/lib/python3.6/site-packages/mypy/dmypy_server.py", line 254, in cmd_check
    return self.check(self.last_sources)
  File "/usr/local/lib/python3.6/site-packages/mypy/dmypy_server.py", line 267, in check
    res = self.fine_grained_increment(sources)
  File "/usr/local/lib/python3.6/site-packages/mypy/dmypy_server.py", line 334, in fine_grained_increment
    messages = self.fine_grained_manager.update(changed, removed)
  File "/usr/local/lib/python3.6/site-packages/mypy/server/update.py", line 251, in update
    self.previous_targets_with_errors)
  File "/usr/local/lib/python3.6/site-packages/mypy/server/update.py", line 762, in propagate_changes_using_dependencies
    triggered |= reprocess_nodes(manager, graph, id, nodes, deps)
  File "/usr/local/lib/python3.6/site-packages/mypy/server/update.py", line 863, in reprocess_nodes
    target = target_from_node(module_id, node.node)
  File "/usr/local/lib/python3.6/site-packages/mypy/server/update.py", line 1076, in target_from_node
    return '%s.%s' % (module, node.name())
  File "/usr/local/lib/python3.6/site-packages/mypy/nodes.py", line 440, in name
    return self.items[0].name()
IndexError: list index out of range
```

Because this is the class doc for the line in question I found out that it has to do with the duplicate function names:

```python
class OverloadedFuncDef(FuncBase, SymbolNode, Statement):
    """A logical node representing all the variants of a multi-declaration function.
    A multi-declaration function is often an @overload, but can also be a
    @property with a setter and a/or a deleter.
    This node has no explicit representation in the source program.
    Overloaded variants must be consecutive in the source file.
    """
```

The behaviour doesn't occur when the decorator is defined in the same file as it is used in. And of course it doesn't occur when the function names are not equal. Adding a different statement between the two function definitions solves the problem as well.

It looks a bit like this is related to issue #5181 but I don't think it is.

PS. Yes I do feel stupid for finding this issue ;) Who makes two consecutive `def`s with the same name. In my defense: my decorators had different arguments

**Comment by gvanrossum** [comment]
Confirmed on master.
