### ISSUE TITLE
Internal error with TypeVar and dictionary unpacking into a dictionary

### ISSUE THREAD

**Issue by catern** [python/mypy#5404]
With the following code:

```
import typing
class A: pass
class B: pass
T = typing.TypeVar('T', A, B)
class Bad(typing.Generic[T]):
    def f(self) -> None:
        foo = {}
        {**foo}
```

(Sorry, I couldn't figure out how to make it any more minimal. Deleting any of the elements either makes the internal error go away, or causes additional errors to be printed as well)

I get the following error:

```
sbaugh@earth ~/mypy $ mypy demo.py  --show-traceback
demo.py:6: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.620
Traceback (most recent call last):
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/bin/.mypy-wrapped", line 12, in <module>
    sys.exit(console_entry())
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/main.py", line 91, in main
    res = type_check_only(sources, bin_dir, options, flush_errors, fscache)  # noqa
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/main.py", line 148, in type_check_only
    fscache=fscache)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/build.py", line 177, in build
    flush_errors, fscache)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/build.py", line 350, in _build
    graph = dispatch(sources, manager)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/build.py", line 2560, in dispatch
    process_graph(graph, manager)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/build.py", line 2853, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/build.py", line 2976, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/build.py", line 2151, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/checker.py", line 253, in check_first_pass
    self.accept(d)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/checker.py", line 352, in accept
    stmt.accept(self)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/nodes.py", line 808, in accept
    return visitor.visit_class_def(self)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/checker.py", line 1368, in visit_class_def
    self.accept(defn.defs)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/checker.py", line 352, in accept
    stmt.accept(self)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/nodes.py", line 873, in accept
    return visitor.visit_block(self)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/checker.py", line 1514, in visit_block
    self.accept(s)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/checker.py", line 352, in accept
    stmt.accept(self)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/nodes.py", line 591, in accept
    return visitor.visit_func_def(self)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/checker.py", line 663, in visit_func_def
    self._visit_func_def(defn)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/checker.py", line 667, in _visit_func_def
    self.check_func_item(defn, name=defn.name())
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/checker.py", line 729, in check_func_item
    self.check_func_def(defn, typ, name)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/checker.py", line 746, in check_func_def
    for item, typ in self.expand_typevars(defn, typ):
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/checker.py", line 1189, in expand_typevars
    result.append((expand_func(defn, mapping), expanded))
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/checker.py", line 3612, in expand_func
    ret = defn.accept(visitor)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/nodes.py", line 591, in accept
    return visitor.visit_func_def(self)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/treetransform.py", line 108, in visit_func_def
    self.block(node.body),
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/treetransform.py", line 537, in block
    new = self.visit_block(block)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/treetransform.py", line 183, in visit_block
    return Block(self.statements(node.body))
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/treetransform.py", line 548, in statements
    return [self.stmt(stmt) for stmt in statements]
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/treetransform.py", line 548, in <listcomp>
    return [self.stmt(stmt) for stmt in statements]
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/treetransform.py", line 521, in stmt
    new = stmt.accept(self)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/nodes.py", line 888, in accept
    return visitor.visit_expression_stmt(self)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/treetransform.py", line 213, in visit_expression_stmt
    return ExpressionStmt(self.expr(node.expr))
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/treetransform.py", line 515, in expr
    new = expr.accept(self)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/nodes.py", line 1670, in accept
    return visitor.visit_dict_expr(self)
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/treetransform.py", line 408, in visit_dict_expr
    for key, value in node.items])
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/treetransform.py", line 408, in <listcomp>
    for key, value in node.items])
  File "/nix/store/32h62f2vx423bp9nhlhv1lm4jad99cmg-python3.6-mypy-0.620/lib/python3.6/site-packages/mypy/treetransform.py", line 515, in expr
    new = expr.accept(self)
AttributeError: 'NoneType' object has no attribute 'accept'
demo.py:6: : note: use --pdb to drop into pdb

```

**Comment by AlexWaygood** [comment]
[No longer crashes](https://mypy-play.net/?mypy=latest&python=3.10&gist=f4c8675775f6efb7e3c6ca7acbd43fdd) on mypy 0.941
