### ISSUE TITLE
Dynamically changing class to an object of a Generic class

### ISSUE THREAD

**Issue by trenta3** [python/mypy#5457]
# How to dynamically change class to an object of Generic class
I'm trying to apply the solution to the question https://stackoverflow.com/questions/51804006/changing-class-bases-attribute-and-deepcopy-python-3 in the case where a class inherits from the Generic Class.

*Code*:
```
from copy import deepcopy
from typing import Generic, TypeVar

R = TypeVar('R')
class Container(Generic[R]):
    def __init__(self, x : R) -> None:
        self.x = x

class Consolidate:
    "Class preventing setting of items and attributes"
    def __setattr__(self, key, value):
        raise TypeError("Cannot modify %s of object" % key)

    def __setitem__(self, key, value):
        raise TypeError("Cannot modify %s of object" % key)

def consolidate(obj):
    # generate a new class object that adds `Consolidated` to the hierarchy.
    cls = type(obj)
    consolidated_class = type(cls.__name__ + 'Consolidated', (Consolidate,) + cls.__bases__, {})
    obj.__class__ = consolidated_class

state = Container(1)
theState = deepcopy(state)
print("bases of theState? %s" % str(theState.__class__.__bases__))
consolidate(state)
print("bases of theState? %s" % str(theState.__class__.__bases__))
```

*Output*:
```
bases of theState? (typing.Generic,)
Traceback (most recent call last):
  File "trivial.py", line 26, in <module>
    consolidate(state)
  File "trivial.py", line 20, in consolidate
    consolidated_class = type(cls.__name__ + 'Consolidated', (Consolidate,) + cls.__bases__, {})
  File "/usr/lib64/python3.6/typing.py", line 948, in __new__
    raise TypeError("Cannot inherit from plain Generic")
TypeError: Cannot inherit from plain Generic
```

*Expected*: The new class should inherit from `Generic[R]`

*Asking*: How to have the code run with the new class inheriting from `Generic[R]`?

*Versions*:
```
Python 3.6.6
mypy 0.620, without any flags
```

**Comment by ilevkivskyi** [comment]
This issues doesn't belong here, mypy is a static type checker, while you are asking about runtime behaviour.

In addition I would recommend stop using this pattern, dynamically modifying a class of an object is a bad idea discouraged by the official Python docs.
