### ISSUE TITLE
Tests are failing after a fresh checkout

### ISSUE THREAD

**Issue by dair-targ** [python/mypy#5562]
I've cloned the project and tried to run tests. Here's an exception I'm getting:

```
$ python --version  # fresh virtual env
Python 3.7.0
```

```
$ python3 -m pip install -U .
Processing /Users/vladimirb/Documents/Projects/mypy
  Installing build dependencies ... done
Collecting typed-ast<1.2.0,>=1.1.0 (from mypy==0.630+dev.940c9b9664250660b05d4a57f6bb80011c5e6da0)
  Downloading https://files.pythonhosted.org/packages/d3/08/80b868edff228089469b535add832567a7c79fb6971111ac6271bc3eb06d/typed_ast-1.1.0-cp37-cp37m-macosx_10_9_x86_64.whl (210kB)
    100% |████████████████████████████████| 215kB 3.7MB/s 
Collecting mypy_extensions<0.5.0,>=0.4.0 (from mypy==0.630+dev.940c9b9664250660b05d4a57f6bb80011c5e6da0)
  Downloading https://files.pythonhosted.org/packages/4d/72/8d54e2b296631b9b14961d583e56e90d9d7fba8a240d5ce7f1113cc5e887/mypy_extensions-0.4.1-py2.py3-none-any.whl
Installing collected packages: typed-ast, mypy-extensions, mypy
  Running setup.py install for mypy ... done
Successfully installed mypy-0.630+dev.940c9b9664250660b05d4a57f6bb80011c5e6da0 mypy-extensions-0.4.1 typed-ast-1.1.0
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

```
$ python setup.py develop
/Users/vladimirb/Documents/Projects/mypy/venv/py/lib/python3.7/site-packages/setuptools-39.1.0-py3.7.egg/setuptools/dist.py:388: UserWarning: Normalizing '0.630+dev-940c9b9664250660b05d4a57f6bb80011c5e6da0' to '0.630+dev.940c9b9664250660b05d4a57f6bb80011c5e6da0'
running develop
running egg_info
creating mypy.egg-info
writing mypy.egg-info/PKG-INFO
writing dependency_links to mypy.egg-info/dependency_links.txt
writing entry points to mypy.egg-info/entry_points.txt
writing requirements to mypy.egg-info/requires.txt
writing top-level names to mypy.egg-info/top_level.txt
writing manifest file 'mypy.egg-info/SOURCES.txt'
reading manifest file 'mypy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'mypy.egg-info/SOURCES.txt'
running build_ext
Creating /Users/vladimirb/Documents/Projects/mypy/venv/py/lib/python3.7/site-packages/mypy.egg-link (link to .)
Adding mypy 0.630+dev.940c9b9664250660b05d4a57f6bb80011c5e6da0 to easy-install.pth file
Installing dmypy script to /Users/vladimirb/Documents/Projects/mypy/venv/py/bin
Installing mypy script to /Users/vladimirb/Documents/Projects/mypy/venv/py/bin
Installing stubgen script to /Users/vladimirb/Documents/Projects/mypy/venv/py/bin

Installed /Users/vladimirb/Documents/Projects/mypy
Processing dependencies for mypy==0.630+dev.940c9b9664250660b05d4a57f6bb80011c5e6da0
Searching for mypy-extensions==0.4.1
Best match: mypy-extensions 0.4.1
Adding mypy-extensions 0.4.1 to easy-install.pth file

Using /Users/vladimirb/Documents/Projects/mypy/venv/py/lib/python3.7/site-packages
Searching for typed-ast==1.1.0
Best match: typed-ast 1.1.0
Adding typed-ast 1.1.0 to easy-install.pth file

Using /Users/vladimirb/Documents/Projects/mypy/venv/py/lib/python3.7/site-packages
Finished processing dependencies for mypy==0.630+dev.940c9b9664250660b05d4a57f6bb80011c5e6da0
```

```
$ python setup.py test
/Users/vladimirb/Documents/Projects/mypy/venv/py/lib/python3.7/site-packages/setuptools-39.1.0-py3.7.egg/setuptools/dist.py:388: UserWarning: Normalizing '0.630+dev-940c9b9664250660b05d4a57f6bb80011c5e6da0' to '0.630+dev.940c9b9664250660b05d4a57f6bb80011c5e6da0'
running test
running egg_info
writing mypy.egg-info/PKG-INFO
writing dependency_links to mypy.egg-info/dependency_links.txt
writing entry points to mypy.egg-info/entry_points.txt
writing requirements to mypy.egg-info/requires.txt
writing top-level names to mypy.egg-info/top_level.txt
reading manifest file 'mypy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'mypy.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 111, in <module>
    include_package_data=True,
  File "/Users/vladimirb/Documents/Projects/mypy/venv/py/lib/python3.7/site-packages/setuptools-39.1.0-py3.7.egg/setuptools/__init__.py", line 129, in setup
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/vladimirb/Documents/Projects/mypy/venv/py/lib/python3.7/site-packages/setuptools-39.1.0-py3.7.egg/setuptools/command/test.py", line 226, in run
  File "/Users/vladimirb/Documents/Projects/mypy/venv/py/lib/python3.7/site-packages/setuptools-39.1.0-py3.7.egg/setuptools/command/test.py", line 248, in run_tests
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 347, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 404, in _find_tests
    full_path, pattern, namespace)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 481, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/Users/vladimirb/Documents/Projects/mypy/venv/py/lib/python3.7/site-packages/setuptools-39.1.0-py3.7.egg/setuptools/command/test.py", line 52, in loadTestsFromModule
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/Users/vladimirb/Documents/Projects/mypy/venv/py/lib/python3.7/site-packages/setuptools-39.1.0-py3.7.egg/setuptools/command/test.py", line 38, in loadTestsFromModule
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 123, in loadTestsFromModule
    if isinstance(obj, type) and issubclass(obj, case.TestCase):
  File "/Users/vladimirb/Documents/Projects/mypy/mypy/nodes.py", line 2452, in __getattribute__
    raise AssertionError(object.__getattribute__(self, 'msg'))
AssertionError: fallback can't be filled out until semanal
```

Sorry if that's a known issue - I failed to find any relevant info on that.

**Comment by ilevkivskyi** [comment]
I think this is because of `unittest` test collection routine. I am not sure if we can (or even should) fix this. Normally we use `pytest`, see https://github.com/python/mypy/blob/master/test-data/unit/README.md.

**Comment by dair-targ** [comment]
It appears that to make `python setup.py test` we only need to:
* Add `pytest-runner` into `test-requirements.txt`
* Add following lines into `setup.cfg`:
```
[aliases]
test=pytest
```

Is there any concerns about such a configuration change? If no, I'll create a merge request.

**Comment by gvanrossum** [comment]
I'm not that excited by the "there's more than one way to do it" approach. We run tests with pytest. What's your use case? Why do you need to use `setup.py test`?

**Comment by dair-targ** [comment]
That's fair point - I've missed `Tests` section in the `README.md`. Because of that it came to my surprise that the standard commands (`python setup.py develop test`) are not working despite the project is using setuptools.
