### ISSUE TITLE
Triggering an AssertionError mypy.fixup: "Should never get here in normal mode"

### ISSUE THREAD

**Issue by brettcannon** [python/mypy#5588]
When running https://github.com/python/the-knights-who-say-ni/blob/master/mypy.sh on a checkout of Python's CLA bot, mypy reports some type failures (which is fine). But then if I run the above script again I get:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/brettcannon/Repositories/python/the-knights-who-say-ni/.venv/lib/python3.7/site-packages/mypy/__main__.py", line 11, in <module>
    main(None)
  File "/Users/brettcannon/Repositories/python/the-knights-who-say-ni/.venv/lib/python3.7/site-packages/mypy/main.py", line 91, in main
    res = type_check_only(sources, bin_dir, options, flush_errors, fscache)  # noqa
  File "/Users/brettcannon/Repositories/python/the-knights-who-say-ni/.venv/lib/python3.7/site-packages/mypy/main.py", line 148, in type_check_only
    fscache=fscache)
  File "/Users/brettcannon/Repositories/python/the-knights-who-say-ni/.venv/lib/python3.7/site-packages/mypy/build.py", line 177, in build
    flush_errors, fscache)
  File "/Users/brettcannon/Repositories/python/the-knights-who-say-ni/.venv/lib/python3.7/site-packages/mypy/build.py", line 350, in _build
    graph = dispatch(sources, manager)
  File "/Users/brettcannon/Repositories/python/the-knights-who-say-ni/.venv/lib/python3.7/site-packages/mypy/build.py", line 2560, in dispatch
    process_graph(graph, manager)
  File "/Users/brettcannon/Repositories/python/the-knights-who-say-ni/.venv/lib/python3.7/site-packages/mypy/build.py", line 2846, in process_graph
    process_fresh_modules(graph, prev_scc, manager)
  File "/Users/brettcannon/Repositories/python/the-knights-who-say-ni/.venv/lib/python3.7/site-packages/mypy/build.py", line 2932, in process_fresh_modules
    graph[id].fix_cross_refs()
  File "/Users/brettcannon/Repositories/python/the-knights-who-say-ni/.venv/lib/python3.7/site-packages/mypy/build.py", line 1975, in fix_cross_refs
    self.options.use_fine_grained_cache)
  File "/Users/brettcannon/Repositories/python/the-knights-who-say-ni/.venv/lib/python3.7/site-packages/mypy/fixup.py", line 24, in fixup_module
    node_fixer.visit_symbol_table(tree.names)
  File "/Users/brettcannon/Repositories/python/the-knights-who-say-ni/.venv/lib/python3.7/site-packages/mypy/fixup.py", line 89, in visit_symbol_table
    value.node.accept(self)
  File "/Users/brettcannon/Repositories/python/the-knights-who-say-ni/.venv/lib/python3.7/site-packages/mypy/nodes.py", line 2539, in accept
    return visitor.visit_type_alias(self)
  File "/Users/brettcannon/Repositories/python/the-knights-who-say-ni/.venv/lib/python3.7/site-packages/mypy/fixup.py", line 135, in visit_type_alias
    a.target.accept(self.type_fixer)
  File "/Users/brettcannon/Repositories/python/the-knights-who-say-ni/.venv/lib/python3.7/site-packages/mypy/types.py", line 511, in accept
    return visitor.visit_instance(self)
  File "/Users/brettcannon/Repositories/python/the-knights-who-say-ni/.venv/lib/python3.7/site-packages/mypy/fixup.py", line 149, in visit_instance
    inst.type = lookup_qualified_typeinfo(self.modules, type_ref, self.quick_and_dirty)
  File "/Users/brettcannon/Repositories/python/the-knights-who-say-ni/.venv/lib/python3.7/site-packages/mypy/fixup.py", line 239, in lookup_qualified_typeinfo
    assert quick_and_dirty, "Should never get here in normal mode"
AssertionError: Should never get here in normal mode
```

If I delete `.mypy_cache/` then I can run mypy again without  any error.

**Comment by bcl** [comment]
I'm seeing the same behavior in a couple of projects using aiohttp, updating my venv to use the version from master fixes the crash.

**Comment by ilevkivskyi** [comment]
OK, then I think we can close the issue.
