### ISSUE TITLE
Cascading crashes in daemon when file can't be decoded

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#5961]
Repro (I think): add a non-ASCII character to a type comment.

I got a crash:
```
Traceback (most recent call last):
  File "mypy/build.py", line 1694, in parse_file
  File "mypy/util.py", line 79, in decode_python_encoding
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 6238: ordinal not in range(128)
```

It's possible that the typing comment needs a specific structure; I had
```
        # type: (Optional[Sequence[Text]], Optional[argparse.Namespace], **Any̨) -> argparse.Namespace
```
(Note the funky `y̨` in `**Any̨` -- apparently this was 'y' followed by chr(808): http://www.codetable.net/decimal/808)

**Comment by gvanrossum** [comment]
Hm, the offset in the error message (6238) actually suggests that `ENCODING_RE` scans more than the first two lines of the file...

**Comment by gvanrossum** [comment]
Hum, this only occurs with the daemon in Python 2 mode. There are cascading tracebacks that are worth recording:
```
Daemon crashed!
Traceback (most recent call last):
  File "/Users/guido/src/server/.mypy/venv/lib/python3.6/site-packages/mypy/build.py", line 1695, in parse_file
    manager.options.python_version)
  File "/Users/guido/src/server/.mypy/venv/lib/python3.6/site-packages/mypy/util.py", line 94, in decode_python_encoding
    source_text = source.decode(encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 6333: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/guido/src/server/.mypy/venv/lib/python3.6/site-packages/mypy/server/update.py", line 497, in update_module_isolated
    load_graph(sources, manager, graph, new_modules)
  File "/Users/guido/src/server/.mypy/venv/lib/python3.6/site-packages/mypy/build.py", line 2337, in load_graph
    root_source=True)
  File "/Users/guido/src/server/.mypy/venv/lib/python3.6/site-packages/mypy/build.py", line 1520, in __init__
    self.parse_file()
  File "/Users/guido/src/server/.mypy/venv/lib/python3.6/site-packages/mypy/build.py", line 1707, in parse_file
    "mypy: can't decode file '{}': {}".format(self.path, str(decodeerr))])
mypy.errors.CompileError: mypy: can't decode file 't.py': 'ascii' codec can't decode byte 0xcc in position 6333: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/guido/src/server/.mypy/venv/lib/python3.6/site-packages/mypy/dmypy_server.py", line 186, in serve
    resp = self.run_command(command, data)
  File "/Users/guido/src/server/.mypy/venv/lib/python3.6/site-packages/mypy/dmypy_server.py", line 226, in run_command
    return method(self, **data)
  File "/Users/guido/src/server/.mypy/venv/lib/python3.6/site-packages/mypy/dmypy_server.py", line 269, in cmd_check
    return self.check(sources)
  File "/Users/guido/src/server/.mypy/venv/lib/python3.6/site-packages/mypy/dmypy_server.py", line 304, in check
    res = self.initialize_fine_grained(sources)
  File "/Users/guido/src/server/.mypy/venv/lib/python3.6/site-packages/mypy/dmypy_server.py", line 351, in initialize_fine_grained
    messages = self.fine_grained_manager.update(changed, removed)
  File "/Users/guido/src/server/.mypy/venv/lib/python3.6/site-packages/mypy/server/update.py", line 235, in update
    result = self.update_one(changed_modules, initial_set, removed_set)
  File "/Users/guido/src/server/.mypy/venv/lib/python3.6/site-packages/mypy/server/update.py", line 287, in update_one
    result = self.update_module(next_id, next_path, next_id in removed_set)
  File "/Users/guido/src/server/.mypy/venv/lib/python3.6/site-packages/mypy/server/update.py", line 343, in update_module
    force_removed)
  File "/Users/guido/src/server/.mypy/venv/lib/python3.6/site-packages/mypy/server/update.py", line 500, in update_module_isolated
    assert err.module_with_blocker
AssertionError
```
It is reproducible with and without mypyc, so mypyc is *not* implicated. But running plain `mypy -2` on the same file does not crash, instead it reports:
```
mypy: can't decode file 't.py': 'ascii' codec can't decode byte 0xcc in position 6333: ordinal not in range(128)
```
(In Python 3 the file is decodable because the default encoding changed to UTF-8.)

**Comment by gvanrossum** [comment]
Simple repro (use dmypy run 
```
x = 0  # : Any̨
```
It does have to be in a type comment; if I change `# type` into `# foo` I get no error.

(Also I still cannot repro with plain `dmypy run`; I did this using our internal wrapper script `mypy-daemon`.)

**Comment by gvanrossum** [comment]
(Hum, final update: the repro doesn't require the funky character to be in a type comment, that was just needed to include the file in our build using our internal wrapper script. But I can't repro this with `dmypy run`.)

**Comment by gvanrossum** [comment]
Hm, it looks like this has nothing to do with encodings either, it's just something related to how the daemon handles `CompilationError`. And it appears that I cannot reproduce it any more -- we've since upgraded our internal version of mypy. So I'm going to assume this was due to something that was fixed between Oct 26 and Nov 27, and I'm closing the issue.
