### ISSUE TITLE
Daemon crash on Windows (Python 3.6)

### ISSUE THREAD

**Issue by JukkaL** [python/mypy#6046]
I get this crash when I try using dmypy on Python 3.6 (Windows 7):

```
C:\Users\jukka\python>python -m mypy.dmypy run -- --follow-imports=skip mypy\*.py
Traceback (most recent call last):
  File "C:\Users\jukka\python\venv\lib\site-packages\mypy-0.650+dev.0aa1d5cfda78863eec6b0f1f7b548842d85df1bd-py3.6.egg\mypy\dmypy.py", line 125, in main
    args.action(args)
  File "C:\Users\jukka\python\venv\lib\site-packages\mypy-0.650+dev.0aa1d5cfda78863eec6b0f1f7b548842d85df1bd-py3.6.egg\mypy\dmypy.py", line 241, in do_run
    start_server(args, allow_sources=True)
  File "C:\Users\jukka\python\venv\lib\site-packages\mypy-0.650+dev.0aa1d5cfda78863eec6b0f1f7b548842d85df1bd-py3.6.egg\mypy\dmypy.py", line 200, in start_server

    if daemonize(start_options, timeout=args.timeout, log_file=args.log_file):
  File "C:\Users\jukka\python\venv\lib\site-packages\mypy-0.650+dev.0aa1d5cfda78863eec6b0f1f7b548842d85df1bd-py3.6.egg\mypy\dmypy_server.py", line 64, in daemon
ize
    wShowWindow=0,  # SW_HIDE aka make the window invisible
TypeError: object() takes no parameters
```

Looks like `subprocess.STARTUPINFO` takes no arguments on Python 3.6 and earlier.

**Comment by ethanhs** [comment]
Oh, that is unfortunate. I suppose I will have to use ctypes instead of the wrapper.

**Comment by ethanhs** [comment]
Ah, this will be an easy fix, it looks like they just have a different interface. https://github.com/python/cpython/blob/3.4/Lib/subprocess.py#L398
