### ISSUE TITLE
INTERNAL ERROR (@classmethod shadows @dataclass)

### ISSUE THREAD

**Issue by jessemyers** [python/mypy#6217]
Given `test.py` as: 
```
from dataclasses import dataclass

@dataclass
class Foo:
    bar: str

    @classmethod
    def bar(cls) -> "Foo":
        return cls()
```

and 
```
> python --version
Python 3.7.0
```

and 

```
> pip freeze | grep mypy
mypy==0.660
mypy-extensions==0.4.1
```

I get:

```
> mypy test.py --show-traceback
test.py:4: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.660
Traceback (most recent call last):
  File "/Users/jessemyers/.venvs/microcosm-neo4j/bin/mypy", line 11, in <module>
    sys.exit(console_entry())
  File "/Users/jessemyers/.venvs/microcosm-neo4j/lib/python3.7/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "/Users/jessemyers/.venvs/microcosm-neo4j/lib/python3.7/site-packages/mypy/main.py", line 91, in main
    res = build.build(sources, options, None, flush_errors, fscache)
  File "/Users/jessemyers/.venvs/microcosm-neo4j/lib/python3.7/site-packages/mypy/build.py", line 157, in build
    result = _build(sources, options, alt_lib_path, flush_errors, fscache)
  File "/Users/jessemyers/.venvs/microcosm-neo4j/lib/python3.7/site-packages/mypy/build.py", line 212, in _build
    graph = dispatch(sources, manager)
  File "/Users/jessemyers/.venvs/microcosm-neo4j/lib/python3.7/site-packages/mypy/build.py", line 2246, in dispatch
    process_graph(graph, manager)
  File "/Users/jessemyers/.venvs/microcosm-neo4j/lib/python3.7/site-packages/mypy/build.py", line 2544, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/Users/jessemyers/.venvs/microcosm-neo4j/lib/python3.7/site-packages/mypy/build.py", line 2653, in process_stale_scc
    graph[id].semantic_analysis()
  File "/Users/jessemyers/.venvs/microcosm-neo4j/lib/python3.7/site-packages/mypy/build.py", line 1780, in semantic_analysis
    self.manager.semantic_analyzer.visit_file(self.tree, self.xpath, self.options, patches)
  File "/Users/jessemyers/.venvs/microcosm-neo4j/lib/python3.7/site-packages/mypy/semanal.py", line 303, in visit_file
    self.accept(d)
  File "/Users/jessemyers/.venvs/microcosm-neo4j/lib/python3.7/site-packages/mypy/semanal.py", line 3708, in accept
    node.accept(self)
  File "/Users/jessemyers/.venvs/microcosm-neo4j/lib/python3.7/site-packages/mypy/nodes.py", line 851, in accept
    return visitor.visit_class_def(self)
  File "/Users/jessemyers/.venvs/microcosm-neo4j/lib/python3.7/site-packages/mypy/semanal.py", line 800, in visit_class_def
    defn.defs.accept(self)
  File "/Users/jessemyers/.pyenv/versions/3.7.0/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/Users/jessemyers/.venvs/microcosm-neo4j/lib/python3.7/site-packages/mypy/semanal.py", line 854, in analyze_class_body
    self.apply_class_plugin_hooks(defn)
  File "/Users/jessemyers/.venvs/microcosm-neo4j/lib/python3.7/site-packages/mypy/semanal.py", line 880, in apply_class_plugin_hooks
    hook(ClassDefContext(defn, decorator, self))
  File "/Users/jessemyers/.venvs/microcosm-neo4j/lib/python3.7/site-packages/mypy/plugins/dataclasses.py", line 312, in dataclass_class_maker_callback
    transformer.transform()
  File "/Users/jessemyers/.venvs/microcosm-neo4j/lib/python3.7/site-packages/mypy/plugins/dataclasses.py", line 79, in transform
    attributes = self.collect_attributes()
  File "/Users/jessemyers/.venvs/microcosm-neo4j/lib/python3.7/site-packages/mypy/plugins/dataclasses.py", line 189, in collect_attributes
    assert isinstance(node, Var)
AssertionError:
test.py:4: : note: use --pdb to drop into pdb
```

**Comment by jessemyers** [comment]
Completely understood; not at all important/urgent.

I ran into this issue in the middle of a refactor -- in which my code was in a less-than-ideal form -- and was just excited to be able to report something.

I love the project, keep up the good work.

**Comment by AlexWaygood** [comment]
I [can't reproduce](https://mypy-play.net/?mypy=0.720&python=3.10&gist=324738b3c7b491e47ad2a95521c5688d) this crash on mypy 0.720+ (I [can reproduce](https://mypy-play.net/?mypy=0.711&python=3.10&gist=f5155cf8809edb40f92c56ad211371fa) on mypy <=0.711).
