### ISSUE TITLE
Internal Error 

### ISSUE THREAD

**Issue by gtors** [python/mypy#6218]
mypy: 0.660
python: 3.7
os: linux

```
error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.660

Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/bin/mypy", line 11, in <module>
    sys.exit(console_entry())
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/lib/python3.7/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/lib/python3.7/site-packages/mypy/main.py", line 91, in main
    res = build.build(sources, options, None, flush_errors, fscache)
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/lib/python3.7/site-packages/mypy/build.py", line 157, in build
    result = _build(sources, options, alt_lib_path, flush_errors, fscache)
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/lib/python3.7/site-packages/mypy/build.py", line 212, in _build
    graph = dispatch(sources, manager)
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/lib/python3.7/site-packages/mypy/build.py", line 2192, in dispatch
    graph = load_graph(sources, manager)
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/lib/python3.7/site-packages/mypy/build.py", line 2350, in load_graph
    root_source=True)
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/lib/python3.7/site-packages/mypy/build.py", line 1529, in __init__
    self.parse_file()
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/lib/python3.7/site-packages/mypy/build.py", line 1720, in parse_file
    self.ignore_all or self.options.ignore_errors)
  File "/usr/lib64/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/lib/python3.7/site-packages/mypy/build.py", line 1589, in wrap_context
    yield
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/lib/python3.7/site-packages/mypy/build.py", line 1720, in parse_file
    self.ignore_all or self.options.ignore_errors)
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/lib/python3.7/site-packages/mypy/build.py", line 679, in parse_file
    tree = parse(source, path, id, self.errors, options=self.options)
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/lib/python3.7/site-packages/mypy/parse.py", line 27, in parse
    options=options)
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/lib/python3.7/site-packages/mypy/fastparse.py", line 130, in parse
    ).visit(ast)
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/lib/python3.7/site-packages/mypy/fastparse.py", line 232, in visit
    return visitor(node)
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/lib/python3.7/site-packages/mypy/fastparse.py", line 355, in visit_Module
    body = self.fix_function_overloads(self.translate_stmt_list(mod.body))
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/lib/python3.7/site-packages/mypy/fastparse.py", line 249, in translate_stmt_list
    stmt = self.visit(e)
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/lib/python3.7/site-packages/mypy/fastparse.py", line 232, in visit
    return visitor(node)
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/lib/python3.7/site-packages/mypy/fastparse.py", line 369, in visit_FunctionDef
    f = self.do_func_def(n)
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/lib/python3.7/site-packages/mypy/fastparse.py", line 387, in do_func_def
    args = self.transform_args(n.args, lineno, no_type_check=no_type_check)
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/lib/python3.7/site-packages/mypy/fastparse.py", line 504, in transform_args
    new_args.append(self.make_argument(a, None, ARG_POS, no_type_check))
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/lib/python3.7/site-packages/mypy/fastparse.py", line 546, in make_argument
    arg_type = TypeConverter(self.errors, line=arg.lineno).visit(annotation)
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/lib/python3.7/site-packages/mypy/fastparse.py", line 1108, in visit
    return visitor(node)
  File "/home/user/.local/share/virtualenvs/myproj-cH4jKl0n/lib/python3.7/site-packages/mypy/fastparse.py", line 1249, in visit_Str
    if 'u' in n.kind or self.assume_str_is_unicode:
AttributeError: 'Str' object has no attribute 'kind'
```

**Comment by ilevkivskyi** [comment]
Please update your dependencies `typed-ast >= 1.2.0`. Also I am curious why it is _not_ updated, how did you install mypy? `pip` and other package manager should automatically update dependencies to satisfy requirements.

**Comment by gtors** [comment]
You right, my colleague for some reason specified a concrete version of typed-ast in Pipfile. Thanks!
