### ISSUE TITLE
IndexError when using `follow_imports_for_stubs = True` and `follow_imports = error`

### ISSUE THREAD

**Issue by michael-k** [python/mypy#6375]
#### Are you reporting a bug, or opening a feature request?

A bug.

#### Please insert below the code you are checking with mypy, or a mock-up repro if the source is private. We would appreciate if you try to simplify your case to a minimal repro.

- config:
  ```ini
  [mypy]
  follow_imports = error
  follow_imports_for_stubs = True
  python_version = 3.7
  ```

  (There's no internal error when setting `follow_imports` to `normal` or `follow_imports_for_stubs` to `False`.)

- python code:
  ```python
  from typing import Dict, List


  def account_assume_role_policy_document(values: List[str]) -> dict:
      return {"key": [value for value in values]}  # line 5
  ```

  Note that there's no internal error when using `Dict` instead of `dict` as a return type. Here's the output with `Dict`:

  ```console
  $ mypy --show-traceback foo.py
  foo.py:1: note: Import of 'typing' ignored
  foo.py:1: note: (Using --follow-imports=error, module not passed on command line)
  ```

#### What is the actual behavior/output?

See traceback below.

#### What is the behavior/output you expect?

No internal error.

#### What are the versions of mypy and Python you are using? Do you see the same issue after installing mypy from Git master?

- Python 3.7.2
- mypy: 0.660 and 0.680+dev.ce78d65d68cdd6899e7bc5c25e9f583d76520c50

#### What are the mypy flags you are using? (For example --strict-optional)

I've called it with `mypy foo.py` and the `mypy.ini` from above.

#### If mypy crashed with a traceback, please paste the full traceback below.

<details><summary>Traceback of `mypy --show-traceback foo.py`</summary>

```console
$ mypy --show-traceback foo.py
foo.py:1: note: Import of 'typing' ignored
foo.py:1: note: (Using --follow-imports=error, module not passed on command line)
/usr/local/lib/python3.7/site-packages/mypy/typeshed/stdlib/2and3/builtins.pyi:4: note: Import of 'typing' ignored
/usr/local/lib/python3.7/site-packages/mypy/typeshed/stdlib/2and3/builtins.pyi:11: note: Import of 'abc' ignored
/usr/local/lib/python3.7/site-packages/mypy/typeshed/stdlib/2and3/builtins.pyi:12: note: Import of 'ast' ignored
/usr/local/lib/python3.7/site-packages/mypy/typeshed/stdlib/2and3/builtins.pyi:13: note: Import of 'types' ignored
/usr/local/lib/python3.7/site-packages/mypy/typeshed/stdlib/2and3/builtins.pyi:14: note: Import of 'sys' ignored
foo.py:5: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.680+dev.ce78d65d68cdd6899e7bc5c25e9f583d76520c50
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 10, in <module>
    sys.exit(console_entry())
  File "/usr/local/lib/python3.7/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "/usr/local/lib/python3.7/site-packages/mypy/main.py", line 91, in main
    res = build.build(sources, options, None, flush_errors, fscache)
  File "/usr/local/lib/python3.7/site-packages/mypy/build.py", line 162, in build
    result = _build(sources, options, alt_lib_path, flush_errors, fscache)
  File "/usr/local/lib/python3.7/site-packages/mypy/build.py", line 217, in _build
    graph = dispatch(sources, manager)
  File "/usr/local/lib/python3.7/site-packages/mypy/build.py", line 2388, in dispatch
    process_graph(graph, manager)
  File "/usr/local/lib/python3.7/site-packages/mypy/build.py", line 2688, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/usr/local/lib/python3.7/site-packages/mypy/build.py", line 2795, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/usr/local/lib/python3.7/site-packages/mypy/build.py", line 1947, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/usr/local/lib/python3.7/site-packages/mypy/checker.py", line 282, in check_first_pass
    self.accept(d)
  File "/usr/local/lib/python3.7/site-packages/mypy/checker.py", line 393, in accept
    stmt.accept(self)
  File "/usr/local/lib/python3.7/site-packages/mypy/nodes.py", line 606, in accept
    return visitor.visit_func_def(self)
  File "/usr/local/lib/python3.7/site-packages/mypy/checker.py", line 704, in visit_func_def
    self._visit_func_def(defn)
  File "/usr/local/lib/python3.7/site-packages/mypy/checker.py", line 708, in _visit_func_def
    self.check_func_item(defn, name=defn.name())
  File "/usr/local/lib/python3.7/site-packages/mypy/checker.py", line 770, in check_func_item
    self.check_func_def(defn, typ, name)
  File "/usr/local/lib/python3.7/site-packages/mypy/checker.py", line 932, in check_func_def
    self.accept(item.body)
  File "/usr/local/lib/python3.7/site-packages/mypy/checker.py", line 393, in accept
    stmt.accept(self)
  File "/usr/local/lib/python3.7/site-packages/mypy/nodes.py", line 911, in accept
    return visitor.visit_block(self)
  File "/usr/local/lib/python3.7/site-packages/mypy/checker.py", line 1701, in visit_block
    self.accept(s)
  File "/usr/local/lib/python3.7/site-packages/mypy/checker.py", line 393, in accept
    stmt.accept(self)
  File "/usr/local/lib/python3.7/site-packages/mypy/nodes.py", line 1047, in accept
    return visitor.visit_return_stmt(self)
  File "/usr/local/lib/python3.7/site-packages/mypy/checker.py", line 2639, in visit_return_stmt
    self.check_return_stmt(s)
  File "/usr/local/lib/python3.7/site-packages/mypy/checker.py", line 2672, in check_return_stmt
    allow_none_return=allow_none_func_call)
  File "/usr/local/lib/python3.7/site-packages/mypy/checkexpr.py", line 3190, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.7/site-packages/mypy/nodes.py", line 1764, in accept
    return visitor.visit_dict_expr(self)
  File "/usr/local/lib/python3.7/site-packages/mypy/checkexpr.py", line 2794, in visit_dict_expr
    rv = self.check_call(constructor, args, [nodes.ARG_POS] * len(args), e)[0]
  File "/usr/local/lib/python3.7/site-packages/mypy/checkexpr.py", line 697, in check_call
    object_type)
  File "/usr/local/lib/python3.7/site-packages/mypy/checkexpr.py", line 782, in check_callable_call
    callee, args, arg_kinds, formal_to_actual)
  File "/usr/local/lib/python3.7/site-packages/mypy/checkexpr.py", line 875, in infer_arg_types_in_context
    res[ai] = self.accept(args[ai], callee.arg_types[i])
  File "/usr/local/lib/python3.7/site-packages/mypy/checkexpr.py", line 3190, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.7/site-packages/mypy/nodes.py", line 1779, in accept
    return visitor.visit_tuple_expr(self)
  File "/usr/local/lib/python3.7/site-packages/mypy/checkexpr.py", line 2743, in visit_tuple_expr
    tt = self.accept(item, type_context_items[j])
  File "/usr/local/lib/python3.7/site-packages/mypy/checkexpr.py", line 3190, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.7/site-packages/mypy/nodes.py", line 1828, in accept
    return visitor.visit_list_comprehension(self)
  File "/usr/local/lib/python3.7/site-packages/mypy/checkexpr.py", line 3023, in visit_list_comprehension
    e.generator, 'builtins.list', '<list-comprehension>')
  File "/usr/local/lib/python3.7/site-packages/mypy/checkexpr.py", line 3064, in check_generator_or_comprehension
    [gen.left_expr], [nodes.ARG_POS], gen)[0]
  File "/usr/local/lib/python3.7/site-packages/mypy/checkexpr.py", line 697, in check_call
    object_type)
  File "/usr/local/lib/python3.7/site-packages/mypy/checkexpr.py", line 777, in check_callable_call
    callee, context)
  File "/usr/local/lib/python3.7/site-packages/mypy/checkexpr.py", line 945, in infer_function_type_arguments_using_context
    args = infer_type_arguments(callable.type_var_ids(), ret_type, erased_ctx)
  File "/usr/local/lib/python3.7/site-packages/mypy/infer.py", line 42, in infer_type_arguments
    constraints = infer_constraints(template, actual, SUBTYPE_OF)
  File "/usr/local/lib/python3.7/site-packages/mypy/constraints.py", line 143, in infer_constraints
    return template.accept(ConstraintBuilderVisitor(actual, direction))
  File "/usr/local/lib/python3.7/site-packages/mypy/types.py", line 620, in accept
    return visitor.visit_instance(self)
  File "/usr/local/lib/python3.7/site-packages/mypy/constraints.py", line 313, in visit_instance
    if tvars[i].variance != CONTRAVARIANT:
IndexError: list index out of range
foo.py:5: : note: use --pdb to drop into pdb
```

</details>

<details><summary>How to reproduce (note to myself)</summary>

```console
$ docker run -it --rm -v $(pwd)/foo.py:/code/foo.py -v $(pwd)/mypy.ini:/code/mypy.ini --entrypoint bash python:3.7-stretch
# pip install git+https://github.com/python/mypy.git@master#egg=mypy
# cd /code
# mypy --show_traceback foo.py
```

</details>

**Comment by ilevkivskyi** [comment]
This is an interesting corner case. This combination of flags probably just runs mypy without `typing`, which is a bad idea. I think we need to special case this somehow, to always include some "core" modules.

cc @msullivan

**Comment by JukkaL** [comment]
I can't reproduce this any more. Maybe it has been fixed?
