### ISSUE TITLE
Crash in check_boolean_op()

### ISSUE THREAD

**Issue by srittau** [python/mypy#6388]
Consider:

```python
from typing import TypeVar, Callable

_T = TypeVar("_T")

def restrict() -> Callable[..., _T]:
    pass

@restrict()
def x():
    pass

x and x
```

mypy 0.670 and HEAD (Python 3.5.3) called without special options crashes with the following stack trace:

```
foo.py:12: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.670
Traceback (most recent call last):
  File "./.venv/zzb-intranet/bin/mypy", line 10, in <module>
    sys.exit(console_entry())
  File "/home/srittau/.venv/zzb-intranet/lib/python3.5/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "/home/srittau/.venv/zzb-intranet/lib/python3.5/site-packages/mypy/main.py", line 91, in main
    res = build.build(sources, options, None, flush_errors, fscache)
  File "/home/srittau/.venv/zzb-intranet/lib/python3.5/site-packages/mypy/build.py", line 162, in build
    result = _build(sources, options, alt_lib_path, flush_errors, fscache)
  File "/home/srittau/.venv/zzb-intranet/lib/python3.5/site-packages/mypy/build.py", line 217, in _build
    graph = dispatch(sources, manager)
  File "/home/srittau/.venv/zzb-intranet/lib/python3.5/site-packages/mypy/build.py", line 2360, in dispatch
    process_graph(graph, manager)
  File "/home/srittau/.venv/zzb-intranet/lib/python3.5/site-packages/mypy/build.py", line 2660, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/srittau/.venv/zzb-intranet/lib/python3.5/site-packages/mypy/build.py", line 2767, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/home/srittau/.venv/zzb-intranet/lib/python3.5/site-packages/mypy/build.py", line 1919, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/home/srittau/.venv/zzb-intranet/lib/python3.5/site-packages/mypy/checker.py", line 282, in check_first_pass
    self.accept(d)
  File "/home/srittau/.venv/zzb-intranet/lib/python3.5/site-packages/mypy/checker.py", line 393, in accept
    stmt.accept(self)
  File "/home/srittau/.venv/zzb-intranet/lib/python3.5/site-packages/mypy/nodes.py", line 926, in accept
    return visitor.visit_expression_stmt(self)
  File "/home/srittau/.venv/zzb-intranet/lib/python3.5/site-packages/mypy/checker.py", line 2635, in visit_expression_stmt
    self.expr_checker.accept(s.expr, allow_none_return=True, always_allow_any=True)
  File "/home/srittau/.venv/zzb-intranet/lib/python3.5/site-packages/mypy/checkexpr.py", line 3188, in accept
    typ = node.accept(self)
  File "/home/srittau/.venv/zzb-intranet/lib/python3.5/site-packages/mypy/nodes.py", line 1627, in accept
    return visitor.visit_op_expr(self)
  File "/home/srittau/.venv/zzb-intranet/lib/python3.5/site-packages/mypy/checkexpr.py", line 1865, in visit_op_expr
    return self.check_boolean_op(e, e)
  File "/home/srittau/.venv/zzb-intranet/lib/python3.5/site-packages/mypy/checkexpr.py", line 2341, in check_boolean_op
    assert left_map is not None  # find_isinstance_check guarantees this
AssertionError: 
foo.py:12: : note: use --pdb to drop into pdb
```

**Comment by 97littleleaf11** [comment]
No crash now
