### ISSUE TITLE
Announcement issue for plugin API changes

### ISSUE THREAD

**Issue by msullivan** [python/mypy#6617]
The mypy plugin interface is experimental, unstable, and prone to change. In particular, there are no guarantees about backwards compatibility. Backwards incompatible changes may be made without a deprecation period.

We will, however, attempt to announce breaking changes in this issue, so that plugin developers can subscribe to this issue and be notified.

Breaking changes fall into three broad categories:
1. Changes to the actual plugin API itself
2. Changes to parts of the "implicit plugin API"---that is, internals that plugins are likely to use (representation of types, etc).
3. Changes to things that really aren't plausibly part of the plugin API (but, of course, that some plugins might be using anyway...)

Issues in category 1 will be consistently announced here, issues in category 3 will probably be announced here only if problems are reported, and issues in category 2 will be somewhere in the middle.

**Comment by msullivan** [comment]
And we'll start this off with a belated category 3 announcement:

The default wheels for mypy 0.700 are compiled with mypyc. This breaks monkey-patching of mypy internals.

If you are the author of a mypy plugin that relies on monkey-patching mypy internals, get in touch with us and we can probably find a better approach. (#6598 added hooks needed by the django plugin.)

#6598

**Comment by gvanrossum** [comment]
(Sorry for the accidental unpin. Fixed now.)

**Comment by JukkaL** [comment]
The new semantic analyzer requires changes to some plugins, especially those that modify classes. In particular, hooks may be executed multiple times for the same definitions. PR #7135 added documentation about how to support the new semantic analyzer. 

Note that mypy 0.720 (to be released soon) will enable the semantic analyzer by default, and the next release after that will remove the old semantic analyzer.

PRs #7136, #7132, #7096, #6987, #6984, #6724 and #6515 contain examples of changes that may be needed to plugins.

To test that a plugin works with the semantic analyzer, you should have test cases that cause mypy to analyze things twice. The easiest way to achieve is to add a forward reference to a type at module top level:

```py
forwardref: C   # Forward reference to C causes deferral
class C: pass

# ... followed by whatever you want to test
```

**Comment by msullivan** [comment]
PR #7829 makes all `name` and `fullname` methods in mypy into properties. This will unfortunately require changes to many plugins. We've decided that it is worth removing a long-standing pain point and that it is better to do it sooner than later.

sed can be used to update code to the new version with something like `sed -i -e 's/\.name()/.name/g' -e 's/\.fullname()/.fullname/g'`

If your plugin wishes to support older and newer versions during a transition period, this can be done with these helper functions:
```
from typing import Union
from mypy.nodes import FuncBase, SymbolNode


def fullname(x: Union[FuncBase, SymbolNode]) -> str:
    fn = x.fullname
    if callable(fn):
        return fn()
    return fn


def name(x: Union[FuncBase, SymbolNode]) -> str:
    fn = x.name
    if callable(fn):
        return fn()
    return fn
```
I don't have an automated way to convert code to use these, but if somebody produces one and sends it to me I will update this post.

Sorry for the inconvenience!

**Comment by ilevkivskyi** [comment]
PR https://github.com/python/mypy/pull/7923 changed the internal representation of type aliases in mypy. Previously, type aliases were always eagerly expanded. For example, in this case:
```python
Alias = List[int]
x: Alias
```
the type of the `Var` node associated with `x` was `Instance`, now it will be a `TypeAliasType`. This change can cause subtle bugs in plugins that make decisions using calls like `if isinstance(typ, Instance): ...` as such calls will now return `False` for type aliases.

There are two helper functions `mypy.types.get_proper_type()` and `mypy.types.get_proper_types()` that return expansions for type aliases. Note: if after making the decision on the `isinstance()` call you pass on the original type (and not one of its component) it is recommended to always pass on the unexpanded alias.

There is also a mypy plugin to type-check your mypy plugins, see `misc/proper_plugin.py`, it will flag all "dangerous" `isinstance()` calls.

Sorry for the inconvenience!

**Comment by ilevkivskyi** [comment]
(An additional small reminder related to last two comments: don't forget that a plugin entry point gets the mypy version string, you can use it for more flexibility.)

**Comment by bazilio43** [comment]
> The mypy plugin interface is experimental, unstable, and prone to change. In particular, there are no guarantees about backwards compatibility. Backwards incompatible changes may be made without a deprecation period.
> 
> We will, however, attempt to announce breaking changes in this issue, so that plugin developers can subscribe to this issue and be notified.
> 
> Breaking changes fall into three broad categories:
> 
> 1. Changes to the actual plugin API itself
> 2. Changes to parts of the "implicit plugin API"---that is, internals that plugins are likely to use (representation of types, etc).
> 3. Changes to things that really aren't plausibly part of the plugin API (but, of course, that some plugins might be using anyway...)
> 
> Issues in category 1 will be consistently announced here, issues in category 3 will probably be announced here only if problems are reported, and issues in category 2 will be somewhere in the middle.

**Comment by hauntsaninja** [comment]
[Category 2 change] PR #9951 gets rid of TypeVarDef; use TypeVarType instead. If you're wondering what the difference between them was, so was I, which is why there's only one of them now.
cc @samuelcolvin @sobolevn @oremanj @suned @seandstewart as people who have written code that would be affected.

**Comment by sobolevn** [comment]
Thanks! It affects some of my code:
- https://github.com/dry-python/classes/blob/3bfc2c9b7ad8cc59d2ddeea66acebc3ca12efa5a/classes/contrib/mypy/typeops/call_signatures.py#L104

**Comment by JukkaL** [comment]
#11541 causes mypy to kill the process at the end of a run, without cleaning things up properly. This might affect plugins that want to run something at the end of a run, or that assume that all files are flushed at the end of a run. `--no-fast-exit` can be used as a workaround, as it disables the new behavior. A better idea would be to flush files immediately. 

If this change seems to cause many issues, we could consider a way of registering handlers that get run at the end of a mypy run.

**Comment by 97littleleaf11** [comment]
Deprecated `SemanticAnalyzer.builtin_type` had been removed since https://github.com/python/mypy/commit/5bd2641ab53d4261b78a5f8f09c8d1e71ed3f14a. Please use `named_type` instead.

**Comment by 97littleleaf11** [comment]
PR https://github.com/python/mypy/pull/11332 changes `SemanticAnalyzer.named_type ` to use `fully_qualified_name`. Now we can call it with `builtins` instead of `__builtins__`.

**Comment by JukkaL** [comment]
PR #14435 changes the runtime type of various (but not all!) `fullname` attributes/properties so that missing/empty values are represented using an empty string (`""`) instead of `None`. If a plugin guards against empty fullnames, it may need to updated. For example, consider a check like this:
```py
    if n.fullname is not None:
        # do something with n.fullname
```
It can be updated like this, since an empty string is falsy (this also works with older mypy versions that use `None`):
```py
    if n.fullname:
        # do something with n.fullname
```

**Comment by ikonst** [comment]
PR #15369 adds `get_expression_type` to the `CheckerPluginInterface`. This enables the common scenario in method signature and function signature hooks, where the actual type of an argument affects the rest of the signature.

For example:
```python
first_arg = ctx.args[0][0]
first_arg_type = ctx.api.get_expression_type(first_arg)

return ctx.default_signature.copy_modified(
  arg_types=[first_arg_type, first_arg_type],  # 1st arg affects 2nd arg's type
)
```

**Comment by JukkaL** [comment]
PR #17644 changed the signature of `TypedDictType.__init__` ([link](https://github.com/python/mypy/pull/17644/files#diff-265bbd9d8b179bfc6a75071cd473edbad7afbf73f011b830ac42c38438b60664)). It now has an extra `readonly_keys: set[str]` parameter.

**Comment by BrentWilkins** [comment]
> PR #17644, included in mypy 1.12, changed the signature of `TypedDictType.__init__` ([link](https://github.com/python/mypy/pull/17644/files#diff-265bbd9d8b179bfc6a75071cd473edbad7afbf73f011b830ac42c38438b60664)). It now has an extra `readonly_keys: set[str]` parameter.

I'm seeing a crash from that:

```shell
mypy --check-untyped-defs --show-traceback .
./rest_api/tests/test_api.py:134: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.11.2
Traceback (most recent call last):
  File "mypy/checkexpr.py", line 5830, in accept
  File "mypy/nodes.py", line 1969, in accept
  File "mypy/checkexpr.py", line 480, in visit_call_expr
  File "mypy/checkexpr.py", line 614, in visit_call_expr_inner
  File "mypy/checkexpr.py", line 1467, in check_call_expr_with_callee_type
  File "mypy/checkexpr.py", line 1561, in check_call
  File "mypy/checkexpr.py", line 1803, in check_callable_call
  File "mypy/checkexpr.py", line 1258, in apply_function_plugin
  File ".../my-venv/lib/python3.12/site-packages/mypy_django_plugin/transformers/querysets.py", line 357, in extract_proper_type_queryset_values
    row_type = helpers.make_typeddict(ctx.api, column_types, set(column_types.keys()), set())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../my-venv/lib/python3.12/site-packages/mypy_django_plugin/lib/helpers.py", line 408, in make_typeddict
    typed_dict_type = TypedDictType(
                      ^^^^^^^^^^^^^^
TypeError: 'readonly_keys' is an invalid keyword argument for __init__()
./rest_api/tests/test_api.py:134: : note: use --pdb to drop into pdb
```

My versions:
* django-stubs==5.1.1
* django-stubs-ext==5.1.1
* djangorestframework==3.15.2
* djangorestframework-simplejwt==5.3.1
* mypy==1.11.2
* mypy-boto3==1.35.36
* mypy-boto3-sqs==1.35.0
* mypy-extensions==1.0.0

**Comment by hauntsaninja** [comment]
You need to use a newer version of mypy or older version of django-stubs. This isn't the right issue to get help; I'll lock posting on this issue to maintainers so that plugin authors can follow this issue without noise.

**Comment by hauntsaninja** [comment]
I would be surprised if this broke anything, but https://github.com/python/mypy/pull/18356 will make a few args in the plugin API positional-only

**Comment by ilevkivskyi** [comment]
Since recently, code in `checkmember.py` is used in more contexts, in particular in method/attribute override checks (starting v1.16), and protocol subtyping checks (starting v1.17). This means that the method/attribute plugin hooks may be called in more contexts. (Also note that some related _internal_ functions were moved and/or changed signatures).

**Comment by ilevkivskyi** [comment]
Note that https://github.com/python/mypy/pull/19627 turns `TypeCheck.local_type_map` from method into attribute (for performance reasons). This is a private attribute, but I guess some people may use it, so letting everyone know here just in case.

**Comment by JukkaL** [comment]
In mypy 1.18, the type of `CallableType.variables` was changed from a list to a tuple (#19768). This may impact plugins that assign to attributes. You'll need to assign a tuple or there will be a runtime type error.

**IMPORTANT:** We don't recommend that plugins assign to attributes of type objects, since type objects are effectively considered value objects and should ideally be immutable. This is sometimes hard/impossible to avoid -- if you have a use case that requires assigning to an attribute, feel free to open an issue to discuss alternatives. In the future we may remove the setters from at least some attributes from type objects. It's better to use `copy_modified` methods or construct new instances instead of modifying existing instances. (Technically the type objects are not part of any stable API, but we'll try to avoid making arbitrary changes to them unless there is a good reason to do so.)

**Comment by hauntsaninja** [comment]
In mypy 1.19, #19798 adds a `module` required parameter to `mypy.nodes.TypeAlias`

**Comment by ilevkivskyi** [comment]
Note that `Instance.invalid` attribute will be deleted in v1.20. It was mostly unused anyway, but please let me know if you need it for some reason.

**Comment by ilevkivskyi** [comment]
In mypy v2.0 `SymbolTableNode.node` will became a read-only property. One should normally never mutate it, but if strictly necessary you can instead mutate private `SymbolTableNode._node` in mypy v2.0.
