### ISSUE TITLE
INTERNAL ERROR when dataclass member follows constructor

### ISSUE THREAD

**Issue by khomenko** [python/mypy#6819]
(venv) cureatr@cureatr-vm ~> cat mypy_bug.py
```
import dataclasses
import typing

@dataclasses.dataclass
class Foo:

    def __init__(self, bar=None):
        if bar:
            self.bar = bar

    bar: typing.Optional[int] = None
```
(venv) cureatr@cureatr-vm ~> mypy --show-traceback mypy_bug.py
```
mypy_bug.py:11: error: Name 'bar' already defined on line 9
mypy_bug.py:4: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.700
Traceback (most recent call last):
  File "/site/venv/bin/mypy", line 10, in <module>
    sys.exit(console_entry())
  File "mypy/semanal.py", line 3791, in accept
  File "mypy/nodes.py", line 895, in accept__Node_glue
  File "mypy/nodes.py", line 896, in accept
  File "mypy/semanal.py", line 804, in visit_class_def__StatementVisitor_glue
  File "mypy/semanal.py", line 807, in visit_class_def
  File "mypy/semanal.py", line 825, in analyze_class
  File "mypy/semanal.py", line 833, in analyze_class_body_common
  File "mypy/semanal.py", line 895, in apply_class_plugin_hooks
  File "mypy/plugins/dataclasses.py", line 330, in dataclass_class_maker_callback
  File "mypy/plugins/dataclasses.py", line 96, in transform
  File "mypy/plugins/common.py", line 97, in add_method
AssertionError: All arguments must be fully typed.
mypy_bug.py:4: : note: use --pdb to drop into pdb
```
(venv) cureatr@cureatr-vm ~> python --version
`Python 3.7.1`

**Comment by ilevkivskyi** [comment]
Thanks for reporting! This may be related to https://github.com/python/mypy/issues/6809, in this case however mypy works correctly with `--new-semantic-analyzer`.

**Comment by ilevkivskyi** [comment]
Closing as this is fixed in new semantic analyzer (will be released soon).
