### ISSUE TITLE
Crash when parsing attrs.Attribute type annotation

### ISSUE THREAD

**Issue by Alex-Addy** [python/mypy#6893]
* This is a bug causing `mypy` to crash when evaluating the following code.

```python
from typing import Any
import attr
def _positive_float_validator(_instance: Any, attribute: "attr.Attribute[Any]", value: Any) -> None:
    pass
```

The crash occurs in the same manner when the above is reduced to:
```python
def _test_fn(attribute: "attr.Attribute") -> None:
    pass
```

* What is the behavior/output you expect?
I expected it to correctly handle the above. The crash does not occur when the types are not in strings. E.g. when `"attr.Attribute"` is changed to `attr.Attribute`.

* What are the versions of mypy and Python you are using?
   * Python 3.6.7
   * `mypy` 0.701
   * `mypy-extensions` 0.4.1

* The same error occurs when installing `mypy` from master.
* No additional flags were used. Placing the above code into a standalone file and running `mypy` on it is sufficient to trigger the bug.
* Full traceback (with some info redacted):
```
<file_name>.py: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.701
Traceback (most recent call last):
  File "/home/<virtualenv_path>/bin/mypy", line 10, in <module>
    sys.exit(console_entry())
  File "/home/<virtualenv_path>/lib/python3.6/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "mypy/build.py", line 1767, in __mypyc_generator_helper__
  File "mypy/build.py", line 1906, in parse_file
  File "mypy/build.py", line 703, in parse_file
  File "mypy/parse.py", line 23, in parse
  File "mypy/fastparse.py", line 166, in parse
  File "mypy/fastparse.py", line 274, in visit
  File "mypy/fastparse.py", line 397, in visit_Module
  File "mypy/fastparse.py", line 291, in translate_stmt_list
  File "mypy/fastparse.py", line 274, in visit
  File "mypy/fastparse.py", line 412, in visit_FunctionDef
  File "mypy/fastparse.py", line 426, in do_func_def
  File "mypy/fastparse.py", line 553, in transform_args
  File "mypy/fastparse.py", line 595, in make_argument
  File "mypy/fastparse.py", line 1207, in visit
  File "mypy/fastparse.py", line 1382, in visit_Str
AttributeError: 'Str' object has no attribute 'kind'
signal.py: : note: use --pdb to drop into pdb
```

**Comment by ilevkivskyi** [comment]
It looks like you have a broken install of mypy. What is the version of `typed_ast` do you have?

**Comment by Alex-Addy** [comment]
I have `typed-ast==1.3.5`.

After some more testing in a clean virtualenv it does appear to be a problem with my install.

**Comment by Alex-Addy** [comment]
I now have `virtualenv` crashing but only in my specific project directory. So I think it is safe to say that:
 1. I am cursed.
 2. `mypy` is working just fine.
