### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by thmzlt** [python/mypy#6903]
Python 3.7.2 and Mypy 0.670

Sample code:

```python
from typing import NamedTuple, Type, TypeVar

T = TypeVar("T", bound="Foo")


class Foo(NamedTuple):  # pylint: disable=too-few-public-methods
    id: int
    symbol: str

    @classmethod
    def from_dict(cls: Type[T], data) -> T:
        return cls(data["symbol"])
```

Output:

```
thmzlt@2112 ~/c/vesper> mypy vesper/trade.py --show-traceback
vesper/trade.py:12: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.670
Traceback (most recent call last):
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/bin/.mypy-wrapped", line 11, in <module>
    sys.exit(console_entry())
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/main.py", line 91, in main
    res = build.build(sources, options, None, flush_errors, fscache)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/build.py", line 162, in build
    result = _build(sources, options, alt_lib_path, flush_errors, fscache)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/build.py", line 217, in _build
    graph = dispatch(sources, manager)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/build.py", line 2360, in dispatch
    process_graph(graph, manager)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/build.py", line 2660, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/build.py", line 2767, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/build.py", line 1919, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/checker.py", line 282, in check_first_pass
    self.accept(d)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/checker.py", line 393, in accept
    stmt.accept(self)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/nodes.py", line 846, in accept
    return visitor.visit_class_def(self)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/checker.py", line 1537, in visit_class_def
    self.accept(defn.defs)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/checker.py", line 393, in accept
    stmt.accept(self)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/nodes.py", line 911, in accept
    return visitor.visit_block(self)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/checker.py", line 1701, in visit_block
    self.accept(s)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/checker.py", line 393, in accept
    stmt.accept(self)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/nodes.py", line 689, in accept
    return visitor.visit_decorator(self)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/checker.py", line 3030, in visit_decorator
    self.check_func_item(e.func, name=e.func.name())
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/checker.py", line 770, in check_func_item
    self.check_func_def(defn, typ, name)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/checker.py", line 932, in check_func_def
    self.accept(item.body)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/checker.py", line 393, in accept
    stmt.accept(self)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/nodes.py", line 911, in accept
    return visitor.visit_block(self)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/checker.py", line 1701, in visit_block
    self.accept(s)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/checker.py", line 393, in accept
    stmt.accept(self)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/nodes.py", line 1047, in accept
    return visitor.visit_return_stmt(self)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/checker.py", line 2639, in visit_return_stmt
    self.check_return_stmt(s)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/checker.py", line 2672, in check_return_stmt
    allow_none_return=allow_none_func_call)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/checkexpr.py", line 3188, in accept
    typ = node.accept(self)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/nodes.py", line 1446, in accept
    return visitor.visit_call_expr(self)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/checkexpr.py", line 244, in visit_call_expr
    return self.visit_call_expr_inner(e, allow_none_return=allow_none_return)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/checkexpr.py", line 314, in visit_call_expr_inner
    ret_type = self.check_call_expr_with_callee_type(callee_type, e, fullname, object_type)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/checkexpr.py", line 658, in check_call_expr_with_callee_type
    object_type=object_type)[0]
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/checkexpr.py", line 721, in check_call
    callable_node, arg_messages)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/checkexpr.py", line 695, in check_call
    object_type)
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/checkexpr.py", line 753, in check_callable_call
    if (callee.is_type_obj() and callee.type_object().is_abstract
  File "/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670/lib/python3.7/site-packages/mypy/types.py", line 925, in type_object
    assert isinstance(ret, Instance)
AssertionError:
vesper/trade.py:12: : note: use --pdb to drop into pdb
```

**Comment by ilevkivskyi** [comment]
It was fixed long time ago, please update.

**Comment by thmzlt** [comment]
Just tried again with mypy 0.701. Same error.

**Comment by ilevkivskyi** [comment]
Oh, sorry, I was pretty sure it made it into the previous release, but it looks like no, so you will need to wait for 0.710 (or use the GitHub master).
