### ISSUE TITLE
error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.701

### ISSUE THREAD

**Issue by sjtuphoenix** [python/mypy#6911]
Traceback (most recent call last):
  File "/home/lcao/.local/pipx/venvs/mfgbot/bin/mypy", line 10, in <module>
    sys.exit(console_entry())
  File "mypy/checker.py", line 395, in accept
  File "mypy/nodes.py", line 729, in accept
  File "mypy/checker.py", line 3054, in visit_decorator__StatementVisitor_glue
  File "mypy/checker.py", line 3064, in visit_decorator
  File "mypy/checker.py", line 772, in check_func_item
  File "mypy/checker.py", line 841, in check_func_def
  File "mypy/checker.py", line 602, in is_generator_return_type
  File "mypy/checker.py", line 3547, in named_generic_type
  File "mypy/checker.py", line 3553, in lookup_typeinfo
  File "mypy/checker.py", line 3601, in lookup_qualified
KeyError: 'typing'

**Comment by ethanhs** [comment]
Hello, can you provide an example of code that would cause this error? In addition, please provide the OS, Python, and mypy versions you are using.

**Comment by sjtuphoenix** [comment]
Ubuntu 16.04
python 3.68
mypy version: 0.701, 0.700, 0.670

    @contextmanager
    def _db_connection(self, dbname):
        try:
            yield self._init_db(dbname)

        finally:
            self._cleanup_db(dbname)

It's constantly failing at first line "@contextmanager"

**Comment by JelleZijlstra** [comment]
Your install is almost certainly broken in some way. I'm not sure what the exact problem is, but I'd try starting over from a clean environment.
