### ISSUE TITLE
Error: Invalid type "mypy_extensions.TypedDict" AssertionError: Unexpected RawExpressionType after semantic analysis phase

### ISSUE THREAD

**Issue by BabyWolf** [python/mypy#6913]
My code:
```
@staticmethod
  def _load_data_json(file_name: Path) -> TypedDict['Data', {'type': str, 'name': str, 'power': int}]:
    return json.loads(file_name.read_text())  
```

```
resource_manager.py:51: error: Invalid type "mypy_extensions.TypedDict"
resource_manager.py: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.701
Traceback (most recent call last):
  File "/home/babywolf/dev/sd/.venv/bin/mypy", line 10, in <module>
    sys.exit(console_entry())
  File "/home/babywolf/dev/sd/.venv/lib/python3.7/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "mypy/build.py", line 1767, in __mypyc_generator_helper__
  File "mypy/build.py", line 2052, in finish_passes
  File "mypy/build.py", line 2066, in _patch_indirect_dependencies
  File "mypy/indirection.py", line 25, in find_modules
  File "mypy/indirection.py", line 34, in _visit
  File "mypy/types.py", line 298, in accept
  File "mypy/indirection.py", line 39, in visit_unbound_type__TypeVisitor_glue
  File "mypy/indirection.py", line 40, in visit_unbound_type
  File "mypy/indirection.py", line 34, in _visit
  File "mypy/types.py", line 1419, in accept
  File "mypy/indirection.py", line 93, in visit_raw_expression_type__SyntheticTypeVisitor_glue
  File "mypy/indirection.py", line 94, in visit_raw_expression_type
AssertionError: Unexpected RawExpressionType after semantic analysis phase
resource_manager.py: : note: use --pdb to drop into pdb
```

**Comment by JelleZijlstra** [comment]
Your code is invalid (TypedDicts shouldn't be defined inline), but mypy shouldn't crash on invalid code. Thanks for reporting!

You should instead first define a TypedDict like `Data = TypedDict("Data", {"type": str})`, then use it in annotations as just `-> Data`.

(I took the liberty to edit your post to make the code sample more readable.)

**Comment by ilevkivskyi** [comment]
@Michael0x2a I think you have the most context on `RawExpressionType`, feel free to un-asign yourself if you are busy/not-interested.

**Comment by Michael0x2a** [comment]
Here's a simpler repro of the problem.

```python
Dummy = 3

def load_data_json() -> Dummy[{'any invalid type': str}]:
    return {}

# Needed to trigger '_patch_indirect_dependencies'
out = load_data_json()
```

It seems we indeed don't correctly erase away RawExpressionTypes when the type is actually not a type at all. (E.g. replacing `Dummy = 3` with `class Dummy(Generic[T]): pass` makes the crash go away).
