### ISSUE TITLE
Internal Error when using strings of type names

### ISSUE THREAD

**Issue by MaxG87** [python/mypy#7194]
I have some code that makes `mypy` crash and request a bug report. It derived from the PEP  484 example.

    from abc import ABCMeta, abstractmethod
    from typing import Any, Type, TypeVar
    
    
    class Comparable(metaclass=ABCMeta):
        @abstractmethod
        def __lt__(self, other: Any) -> bool: ...
        # ...  # __gt__ etc. as well
    
    
    CT = TypeVar('CT', bound=Comparable)
    T = TypeVar('T')
    
    
    class Int(Comparable):
        def __init__(self, arg: int):
            self.arg = arg
    
        def __lt__(self, other: 'Int') -> bool:
            return self.arg < other.arg
    
    
    def min(cls: Type[T], x: Any, y: Any) -> T:
        if x < y:
            return x
        else:
            return y
    
    
    foo: int = min(int, 1, 2)
    print(foo)

When invoking `mypy --show-traceback` on it, I get:

    Traceback (most recent call last):
      File "/home/mgoerner/.anaconda3/bin/mypy", line 11, in <module>
        sys.exit(console_entry())
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/__main__.py", line 7, in console_entry
        main(None)
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/main.py", line 91, in main
        res = build.build(sources, options, None, flush_errors, fscache)
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/build.py", line 157, in build
        result = _build(sources, options, alt_lib_path, flush_errors, fscache)
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/build.py", line 212, in _build
        graph = dispatch(sources, manager)
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/build.py", line 2192, in dispatch
        graph = load_graph(sources, manager)
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/build.py", line 2350, in load_graph
        root_source=True)
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/build.py", line 1529, in __init__
        self.parse_file()
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/build.py", line 1720, in parse_file
        self.ignore_all or self.options.ignore_errors)
      File "/home/mgoerner/.anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/build.py", line 1589, in wrap_context
        yield
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/build.py", line 1720, in parse_file
        self.ignore_all or self.options.ignore_errors)
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/build.py", line 679, in parse_file
        tree = parse(source, path, id, self.errors, options=self.options)
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/parse.py", line 27, in parse
        options=options)
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/fastparse.py", line 130, in parse
        ).visit(ast)
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/fastparse.py", line 232, in visit
        return visitor(node)
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/fastparse.py", line 355, in visit_Module
        body = self.fix_function_overloads(self.translate_stmt_list(mod.body))
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/fastparse.py", line 249, in translate_stmt_list
        stmt = self.visit(e)
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/fastparse.py", line 232, in visit
        return visitor(node)
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/fastparse.py", line 565, in visit_ClassDef
        self.as_required_block(n.body, n.lineno),
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/fastparse.py", line 305, in as_required_block
        b = Block(self.fix_function_overloads(self.translate_stmt_list(stmts)))
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/fastparse.py", line 249, in translate_stmt_list
        stmt = self.visit(e)
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/fastparse.py", line 232, in visit
        return visitor(node)
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/fastparse.py", line 369, in visit_FunctionDef
        f = self.do_func_def(n)
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/fastparse.py", line 387, in do_func_def
        args = self.transform_args(n.args, lineno, no_type_check=no_type_check)
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/fastparse.py", line 504, in transform_args
        new_args.append(self.make_argument(a, None, ARG_POS, no_type_check))
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/fastparse.py", line 546, in make_argument
        arg_type = TypeConverter(self.errors, line=arg.lineno).visit(annotation)
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/fastparse.py", line 1108, in visit
        return visitor(node)
      File "/home/mgoerner/.anaconda3/lib/python3.7/site-packages/mypy/fastparse.py", line 1249, in visit_Str
        if 'u' in n.kind or self.assume_str_is_unicode:
    AttributeError: 'Str' object has no attribute 'kind'

I hope this helps.

**Comment by JelleZijlstra** [comment]
What are the versions of `mypy` and `typed-ast` that you are running?

**Comment by msullivan** [comment]
This can occur when the wrong version of `typed-ast` is installed
