### ISSUE TITLE
no longer able to run without installing: ImportError: cannot import name 'MappingProxyType' from 'types' (mypy/types.py)

### ISSUE THREAD

**Issue by mr-c** [python/mypy#7202]
Hello. I'm working on updating the mypy Debian package from 0.670 to 0.720.

During the build process we used to generate a Unix `man`ual page by running the equivalent of `python3 mypy --help` from the root of a source checkout.

This no longer works and generates the following error. Can someone suggest a patch or a workaround?

```
# python3 -VV
Python 3.7.4 (default, Jul 11 2019, 10:43:21) 
[GCC 8.3.0]
# python3 mypy
Could not import runpy module
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 14, in <module>
    import importlib.machinery # importlib first so we can test #15386 via -m
  File "/usr/lib/python3.7/importlib/__init__.py", line 57, in <module>
    import types
  File "mypy/types.py", line 7, in <module>
    from typing import (
  File "/usr/lib/python3.7/typing.py", line 28, in <module>
    import re as stdlib_re  # Avoid confusion with the re we export.
  File "/usr/lib/python3.7/re.py", line 122, in <module>
    import enum
  File "/usr/lib/python3.7/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
ImportError: cannot import name 'MappingProxyType' from 'types' (mypy/types.py)
```

**Comment by mr-c** [comment]
Nevermind, was another unrelated issue on my side; apologies!
