### ISSUE TITLE
Crashes when @overload is used but not defined

### ISSUE THREAD

**Issue by xuhdev** [python/mypy#7209]
Please provide more information to help us understand the issue:

* Are you reporting a bug, or opening a feature request?

Bug.

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```python
import typing

@overload
def func(x: int) -> int: ...

def func(x):
    return x
```

* What is the actual behavior/output?

Crashes.

* What is the behavior/output you expect?

Report `overload` is not defined.

* What are the versions of mypy and Python you are using?

 0.720+dev.dc6da54f50d5443fe46308046719043eba03c84d (master at the time of report)

* What are the mypy flags you are using? (For example --strict-optional)

None.

* If mypy crashed with a traceback, please paste
  the full traceback below.
```

Traceback (most recent call last):
  File "/home/hong/src/mypy/.venv/bin/mypy", line 11, in <module>
    load_entry_point('mypy', 'console_scripts', 'mypy')()
  File "/home/hong/src/mypy/mypy/__main__.py", line 8, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/home/hong/src/mypy/mypy/main.py", line 83, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/home/hong/src/mypy/mypy/build.py", line 164, in build
    result = _build(sources, options, alt_lib_path, flush_errors, fscache, stdout, stderr)                                                                                          
  File "/home/hong/src/mypy/mypy/build.py", line 224, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/hong/src/mypy/mypy/build.py", line 2579, in dispatch
    process_graph(graph, manager)
  File "/home/hong/src/mypy/mypy/build.py", line 2892, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/hong/src/mypy/mypy/build.py", line 2990, in process_stale_scc
    semantic_analysis_for_scc(graph, scc, manager.errors)
  File "/home/hong/src/mypy/mypy/newsemanal/semanal_main.py", line 78, in semantic_analysis_for_scc                                                                                 
    process_functions(graph, scc, patches)
  File "/home/hong/src/mypy/mypy/newsemanal/semanal_main.py", line 238, in process_functions                                                                                        
    patches)
  File "/home/hong/src/mypy/mypy/newsemanal/semanal_main.py", line 274, in process_top_level_function                                                                               
    final_iteration, patches)
  File "/home/hong/src/mypy/mypy/newsemanal/semanal_main.py", line 330, in semantic_analyze_target                                                                                  
    active_type=active_type)
  File "/home/hong/src/mypy/mypy/newsemanal/semanal.py", line 375, in refresh_partial
    self.accept(node)
  File "/home/hong/src/mypy/mypy/newsemanal/semanal.py", line 4550, in accept
    node.accept(self)
  File "/home/hong/src/mypy/mypy/nodes.py", line 505, in accept
    return visitor.visit_overloaded_func_def(self)
  File "/home/hong/src/mypy/mypy/newsemanal/semanal.py", line 641, in visit_overloaded_func_def                                                                                     
    self.add_function_to_symbol_table(defn)
  File "/home/hong/src/mypy/mypy/newsemanal/semanal.py", line 863, in add_function_to_symbol_table                                                                                  
    func._fullname = self.qualified_name(func.name())
  File "/home/hong/src/mypy/mypy/nodes.py", line 501, in name
    assert self.impl is not None
AssertionError:
/home/hong/tmp/type.pyi:3: : note: use --pdb to drop into pdb
```

**Comment by ilevkivskyi** [comment]
Sorry, I tried hard but can't reproduce this. I just get:
```
main:3: error: Name 'overload' is not defined
main:5: error: Name 'func' already defined on line 5
```

Could you please double-check your simplified repro and give any additional details (Python version etc.)

**Comment by xuhdev** [comment]
@ilevkivskyi I found out that crash will only occur if the checked file is a stub file.

**Comment by ilevkivskyi** [comment]
OK, I can confirm this crash (and that it happens only on new analyzer).
