### ISSUE TITLE
Wheels incompatible with Python 3.4 are online

### ISSUE THREAD

**Issue by Juanlu001** [python/mypy#7221]
https://github.com/python/mypy/pull/6592 removed support for Python 3.4. However, no `python_requires` metadata was added to `setup.py`, therefore when one tries to `pip install` mypy from Python 3.4, the `py3-none-any` wheel will be downloaded, and then mypy will crash:

```
(marvin34) juanlu@centauri ~/Satellogic/satellite-api $ pip install mypy
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Collecting mypy
  Downloading https://files.pythonhosted.org/packages/8a/ba/c458622f83d68f6ce9f6e8fe3f9910f0244cd274a0e6dee85f37c985a150/mypy-0.720-py3-none-any.whl (1.6MB)
     |████████████████████████████████| 1.6MB 556kB/s 
Collecting typed-ast<1.5.0,>=1.4.0 (from mypy)
  Downloading https://files.pythonhosted.org/packages/34/de/d0cfe2ea7ddfd8b2b8374ed2e04eeb08b6ee6e1e84081d151341bba596e5/typed_ast-1.4.0.tar.gz (206kB)
     |████████████████████████████████| 215kB 577kB/s 
Collecting typing-extensions>=3.7.4 (from mypy)
  Downloading https://files.pythonhosted.org/packages/27/aa/bd1442cfb0224da1b671ab334d3b0a4302e4161ea916e28904ff9618d471/typing_extensions-3.7.4-py3-none-any.whl
Collecting mypy-extensions<0.5.0,>=0.4.0 (from mypy)
  Using cached https://files.pythonhosted.org/packages/4d/72/8d54e2b296631b9b14961d583e56e90d9d7fba8a240d5ce7f1113cc5e887/mypy_extensions-0.4.1-py2.py3-none-any.whl
Collecting typing>=3.5.3; python_version < "3.5" (from mypy-extensions<0.5.0,>=0.4.0->mypy)
  Downloading https://files.pythonhosted.org/packages/28/b8/a1d6b7cf322f91305bcb5e7d8f6c3028954d1e3e716cddc1cdce2ac63247/typing-3.7.4-py3-none-any.whl
Building wheels for collected packages: typed-ast
  Building wheel for typed-ast (setup.py) ... done
  Stored in directory: /home/juanlu/.cache/pip/wheels/ee/62/05/814eedac709dcbcfb1ff3aae918ed67f7140314b77e420bb5e
Successfully built typed-ast
Installing collected packages: typed-ast, typing-extensions, typing, mypy-extensions, mypy
Successfully installed mypy-0.720 mypy-extensions-0.4.1 typed-ast-1.4.0 typing-3.7.4 typing-extensions-3.7.4
(marvin34) juanlu@centauri ~/Satellogic/satellite-api $ mypy
Traceback (most recent call last):
  File "/home/juanlu/.pyenv/versions/marvin34/bin/mypy", line 6, in <module>
    from mypy.__main__ import console_entry
  File "/home/juanlu/.pyenv/versions/3.4.2/envs/marvin34/lib/python3.4/site-packages/mypy/__main__.py", line 4, in <module>
    from mypy.main import main
  File "/home/juanlu/.pyenv/versions/3.4.2/envs/marvin34/lib/python3.4/site-packages/mypy/main.py", line 12, in <module>
    from mypy import build
  File "/home/juanlu/.pyenv/versions/3.4.2/envs/marvin34/lib/python3.4/site-packages/mypy/build.py", line 56, in <module>
    from mypy.plugins.default import DefaultPlugin
  File "/home/juanlu/.pyenv/versions/3.4.2/envs/marvin34/lib/python3.4/site-packages/mypy/plugins/default.py", line 266
    return UnionType.make_simplified_union([*value_types, ctx.arg_types[1][0]])
                                                       ^
SyntaxError: can use starred expression only as assignment target
```

**Comment by Juanlu001** [comment]
To be clear, #7222 does not fix the existing wheels :) (but I'm not aware of any method to cleanly do it)
