### ISSUE TITLE
"AssertionError: Cannot find component" for local NamedTuple

### ISSUE THREAD

**Issue by karlicoss** [python/mypy#7281]
I've got an obscure bug which I narrowed down to some cache issues when you have a local class inheriting from `NamedTuple`. 

Stacktrace:
```
Traceback (most recent call last):
  File "/home/karlicos/.local/bin/mypy", line 10, in <module>
    sys.exit(console_entry())
  File "/home/karlicos/.local/lib/python3.7/site-packages/mypy/__main__.py", line 8, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 83, in main
  File "mypy/build.py", line 164, in build
  File "mypy/build.py", line 224, in _build
  File "mypy/build.py", line 2579, in dispatch
  File "mypy/build.py", line 2885, in process_graph
  File "mypy/build.py", line 2963, in process_fresh_modules
  File "mypy/build.py", line 1876, in fix_cross_refs
  File "mypy/fixup.py", line 25, in fixup_module
  File "mypy/fixup.py", line 76, in visit_symbol_table
  File "mypy/fixup.py", line 265, in lookup_qualified_stnode
  File "mypy/lookup.py", line 47, in lookup_fully_qualified
AssertionError: Cannot find component 'NT@3' for 'breaking.NT@3
```

Easiest to reproduce with the following script (it's crashing on the last mypy invocation)

```
#!/bin/bash -eux
cd "$(dirname "$0")"

rm -rf .mypy_cache

echo 'from typing import NamedTuple' > breaking.py
echo 'def test():'                  >> breaking.py
echo '  class NT(NamedTuple):'      >> breaking.py
echo '    pass'                     >> breaking.py

echo 'import breaking' > script.py
mypy script.py

echo '' > script.py
mypy script.py

echo 'import breaking' > script.py
mypy script.py
```

Most similar issue to this one I found seems to be https://github.com/python/mypy/issues/2931, but using singleline `NamedTuple` definition (e.g.  `NT = NamedTuple('NT', [])`) doesn't result in failure, so I figured this is worth separate issue.
Using `@dataclass` doesn't result in failure either.

I'm using mypy `0.720`. (upd: still happens on `0.800`)

**Comment by ilevkivskyi** [comment]
This is related to https://github.com/python/mypy/issues/6422 in the sense that a proper fix for that issues should fix this crash as well.

**Comment by languitar** [comment]
Today I was hit by something similar to this (which didn't happen before recreating my tox environment):
```
Traceback (most recent call last):
  File "/home/languitar/src/poetl/.tox/check/bin/mypy", line 11, in <module>
    sys.exit(console_entry())
  File "/home/languitar/src/poetl/.tox/check/lib/python3.7/site-packages/mypy/__main__.py", line 8, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 89, in main
  File "mypy/build.py", line 166, in build
  File "mypy/build.py", line 235, in _build
  File "mypy/build.py", line 2620, in dispatch
  File "mypy/build.py", line 2922, in process_graph
  File "mypy/build.py", line 3000, in process_fresh_modules
  File "mypy/build.py", line 1930, in fix_cross_refs
  File "mypy/fixup.py", line 25, in fixup_module
  File "mypy/fixup.py", line 76, in visit_symbol_table
  File "mypy/fixup.py", line 299, in lookup_qualified_stnode
  File "mypy/lookup.py", line 47, in lookup_fully_qualified
AssertionError: Cannot find component '_strategies' for 'hypothesis._strategies.booleans'
```
This makes mypy unusable for our current project.

**Comment by The-Compiler** [comment]
I have something similar where I had this inside `__init__` of a class:

```python
       pending_download_type = typing.Set[  # pylint: disable=unused-variable
           typing.Tuple[QUrl, downloads.AbstractDownloadItem]]
       self.pending_downloads = set()  # type: pending_download_type
``

and sometimes mypy would crash with:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/florian/proj/qutebrowser/git/.tox/mypy/lib/python3.8/site-packages/mypy/__main__.py", line 12, in <module>
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 89, in main
  File "mypy/build.py", line 166, in build
  File "mypy/build.py", line 235, in _build
  File "mypy/build.py", line 2611, in dispatch
  File "mypy/build.py", line 2911, in process_graph
  File "mypy/build.py", line 2989, in process_fresh_modules
  File "mypy/build.py", line 1919, in fix_cross_refs
  File "mypy/fixup.py", line 25, in fixup_module
  File "mypy/fixup.py", line 89, in visit_symbol_table
  File "mypy/fixup.py", line 45, in visit_type_info
  File "mypy/fixup.py", line 91, in visit_symbol_table
  File "mypy/nodes.py", line 874, in accept
  File "mypy/fixup.py", line 136, in visit_var
  File "mypy/types.py", line 234, in accept
    cr_running = gi_running
  File "mypy/fixup.py", line 169, in visit_type_alias_type
  File "mypy/fixup.py", line 276, in lookup_qualified_alias
  File "mypy/fixup.py", line 290, in lookup_qualified
  File "mypy/fixup.py", line 299, in lookup_qualified_stnode
  File "mypy/lookup.py", line 47, in lookup_fully_qualified
AssertionError: Cannot find component 'pending_download_type' for 'qutebrowser.browser.webkit.mhtml._Downloader.pending_download_type'
```

Usually, rerunning mypy made the issue go away, but sometimes I could trigger it multiple times in a row. I (hopefully) worked around it by doing this:

```diff
diff --git qutebrowser/browser/webkit/mhtml.py qutebrowser/browser/webkit/mhtml.py
index c45bb802d..abdb4b6ea 100644
--- qutebrowser/browser/webkit/mhtml.py
+++ qutebrowser/browser/webkit/mhtml.py
@@ -244,6 +244,10 @@ class MHTMLWriter:
         return msg
 
 
+_PendingDownloadType = typing.Set[
+    typing.Tuple[QUrl, downloads.AbstractDownloadItem]]
+
+
 class _Downloader:
 
     """A class to download whole websites.
@@ -264,9 +268,7 @@ class _Downloader:
         self.target = target
         self.writer = None
         self.loaded_urls = {tab.url()}
-        pending_download_type = typing.Set[  # pylint: disable=unused-variable
-            typing.Tuple[QUrl, downloads.AbstractDownloadItem]]
-        self.pending_downloads = set()  # type: pending_download_type
+        self.pending_downloads = set()  # type: _PendingDownloadType
         self._finished_file = False
         self._used = False
```

Let me know if I can provide more info in some way - I don't have a minimal reproducer since this only happens sometimes, so it's hard to minimize it down.

**Comment by Gollum999** [comment]
I ran into this today.  Recursively deleting all of my `.mypy_cache` directories seems to have fixed the problem.

**Comment by vincent-prz** [comment]
I'm having this issue as well. Version 0.770.

**Comment by bobbyrullo** [comment]
Been running into this all the time :/

**Comment by PaulCordo** [comment]
If you declare the `class` in outside of any method you should be okay (if it's an option for you ofc), it appears to be related to a nested (inside a method) class declaration that inherit from NamedTuple

**Comment by corydolphin** [comment]
Seeing the same thing as well, with code like
```Python
def test_xxx(self) -> None:
    class MockXXX(NamedTuple):
    	x:int

```

**Comment by samuelstevens** [comment]
Also having the same bug with code like:

```python
def some_func() ->
    class Point(NamedTuple):
        x: float
        y: float
```
Moving the class outside the function fixed it for me as well.

**Comment by peake100** [comment]
Running into this today as well. Kind of a bummer as named tuples are a perfect way to declare little local test cases without the overhead of a dataclass

**Comment by peake100** [comment]
Clearing the mypy cache appears to fix it, but as soon as the file is edited the error occurs again, it looks like it's because the line number is part of the type?

Error:

```
Traceback (most recent call last):
  File "/Users/williampeake/venvs/vtc-py-38-py/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/Users/williampeake/venvs/vtc-py-38-py/lib/python3.8/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 90, in main
  File "mypy/build.py", line 179, in build
  File "mypy/build.py", line 253, in _build
  File "mypy/build.py", line 2638, in dispatch
  File "mypy/build.py", line 2955, in process_graph
  File "mypy/build.py", line 3033, in process_fresh_modules
  File "mypy/build.py", line 1977, in fix_cross_refs
  File "mypy/fixup.py", line 26, in fixup_module
  File "mypy/fixup.py", line 77, in visit_symbol_table
  File "mypy/fixup.py", line 301, in lookup_qualified_stnode
  File "mypy/lookup.py", line 47, in lookup_fully_qualified
AssertionError: Cannot find component 'FileInfo@199' for 'generate_tc_table_tests.FileInfo@199'
```

**Comment by andersk** [comment]
A slightly modified version of this test case still crashes on 0.910 and `master`: #10913.

**Comment by mgasner** [comment]
I've also encountered this issue, and removing the mypy cache resolved.

**Comment by coding-today** [comment]
I also had this problem today mypy version is    **0.931** and finally solved it using    `rm -rf .mypy_cache`

**Comment by smackesey** [comment]
@JukkaL Can you reopen this issue? This still occurs.

**Comment by ericbn** [comment]
Making sure I don't override any existing `MYPYPATH` (by appending `:"$MYPYPATH"`) fixed it for me:
```
MYPYPATH=$(dirname "$FILE"):"$MYPYPATH" mypy --namespace-packages --explicit-package-bases "$FILE"
```

**Comment by roedoejet** [comment]
I am using version 0.991 and this is still happening

**Comment by hauntsaninja** [comment]
Could you open a new issue with more details?

**Comment by roedoejet** [comment]
Yes, I'll try to isolate where this is happening and reference this in a new issue

**Comment by ydirson** [comment]
I can reproduce it at will in a venv on Debian 11 with [this code base](https://gitlab.com/omaha-bgg/omaha/-/commits/bug/mypy-7281), the trigger in my case seems to be addition of `frozendict` to the env: I can run `mypy` as many times as I want with no problem, as long as frozendict is the last release (which has no type hints), and as soon as I install their `master` version (with which they seem to still have problems with typing) I can run `mypy` just once, and the assertion triggers on next runs:

Note on `frozendict`: since their type annotations are still incorrect, I added a few `type: ignore[operator]` annotations to my code. Removing any one of those 2 annotation occurences (`Omaha/Core/game.py` lines 369 and 371) makes the assertion go away.

(sorry for the heavy and messy codebase for the repro, make sure to follow those exact steps - hoping this will help nevertheless)

```
tmp$ git clone --recurse-submodules https://gitlab.com/omaha-bgg/omaha.git -b bug/mypy-7281
tmp$ cd omaha/
omaha (master=)$ python3 -m venv env
omaha (master=)$ . env/bin/activate
(env) omaha (master=)$ cd _overlord/
(env) _overlord ((25181ef...))$ pip install -r requirements-dev.txt
(env) _overlord ((25181ef...))$ cd -
(env) omaha (master=)$ pip install -r requirements-dev.txt
(env) omaha (master=)$ mypy
Omaha/Core/game.py:36: error: Module "frozendict" has no attribute "frozendict"  [attr-defined]
...
Found 68 errors in 18 files (checked 80 source files)

$ git clone https://github.com/Marco-Sulla/python-frozendict.git
$ pip install .
$ cd -
(env) omaha (master=)$ mypy
Found 64 errors in 14 files (checked 80 source files)
(env) omaha (bug/mypy-7281=)$ mypy
Traceback (most recent call last):
  File "/home/user/tmp/omaha/env/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/user/tmp/omaha/env/lib/python3.9/site-packages/mypy/__main__.py", line 15, in console_entry
    main()
  File "mypy/main.py", line 95, in main
  File "mypy/main.py", line 174, in run_build
  File "mypy/build.py", line 193, in build
  File "mypy/build.py", line 276, in _build
  File "mypy/build.py", line 2903, in dispatch
  File "mypy/build.py", line 3284, in process_graph
  File "mypy/build.py", line 3365, in process_fresh_modules
  File "mypy/build.py", line 2112, in fix_cross_refs
  File "mypy/fixup.py", line 53, in fixup_module
  File "mypy/fixup.py", line 125, in visit_symbol_table
  File "mypy/fixup.py", line 73, in visit_type_info
  File "mypy/fixup.py", line 111, in visit_symbol_table
  File "mypy/lookup.py", line 59, in lookup_fully_qualified
AssertionError: Cannot find Omaha.Holders.HexBoard.HexBoard.HHexSide.HHexSide@168
```

**Comment by mccauleyp** [comment]
I'm seeing I think the same or similar issue with `mypy==0.991` in a Django context with the `django-stubs==1.13.1`  plugin:
```
  File "mypy/lookup.py", line 49, in lookup_fully_qualified
AssertionError: Cannot find component "WithAnnotations[app__models__sample__Sample, TypedDict('app" for "django_stubs_ext.WithAnnotations[app__models__sample__Sample, TypedDict('app.module.submodule.SampleAnnotations', {'id': uuid.UUID})]"
```
It goes away when I delete `.mypy_cache/` and I can run mypy multiple times after that, but it eventually returns after making seemingly-unrelated changes elsewhere in the codebase.

**Comment by dbetm** [comment]
I'm getting a similar problem

```
Traceback (most recent call last):
  File "venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/Users/x/y/z/venv/lib/python3.8/site-packages/mypy/__main__.py", line 8, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/Users/x/y/z/venv/lib/python3.8/site-packages/mypy/main.py", line 89, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/Users/x/y/z/venv/lib/python3.8/site-packages/mypy/build.py", line 180, in build
    result = _build(
    .
    .
    .
  File "/Users/x/y/z/venv/lib/python3.8/site-packages/mypy/lookup.py", line 47, in lookup_fully_qualified
    assert key in names, "Cannot find component %r for %r" % (key, name)
AssertionError: Cannot find component 'TraceDispatch' for 'prompt_toolkit.application.application.Application.TraceDispatch'
```

I have to run: `rm -rf .mypy_cache` after use mypy each time.

**Comment by hauntsaninja** [comment]
mypy 0.780 is many, many years old. If you can reproduce on latest, please open a new issue with details.
