### ISSUE TITLE
`new_semantic_analyzer = ...` raises AttributeError

### ISSUE THREAD

**Issue by antonagestam** [python/mypy#7523]
Having a setting for `new_semantic_analyzer` in setup.cfg raises an AttributeError for me on master (`mypy 0.730+dev.475148f2b08dbe0126fc3e22c277132b65e47007`). This should probably fall back to the same error message as other unknown options yields :) 

```
Traceback (most recent call last):
  File "/home/anton/.pyenv/versions/fleet-manager-service/bin/mypy", line 10, in <module>
    sys.exit(console_entry())
  File "/home/anton/.pyenv/versions/3.7.0/envs/fleet-manager-service/lib/python3.7/site-packages/mypy/__main__.py", line 8, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/home/anton/.pyenv/versions/3.7.0/envs/fleet-manager-service/lib/python3.7/site-packages/mypy/main.py", line 63, in main
    fscache=fscache)
  File "/home/anton/.pyenv/versions/3.7.0/envs/fleet-manager-service/lib/python3.7/site-packages/mypy/main.py", line 709, in process_options
    parse_config_file(options, config_file, stdout, stderr)
  File "/home/anton/.pyenv/versions/3.7.0/envs/fleet-manager-service/lib/python3.7/site-packages/mypy/config_parser.py", line 132, in parse_config_file
    setattr(options, k, v)
AttributeError: can't set attribute
```

**Comment by onlined** [comment]
This is due to `Options.new_semantic_analyzer` being kept and converted into a property. I will submit a PR.
