### ISSUE TITLE
mypy\typeshed\stdlib\3\functools.pyi:16: error: INTERNAL ERROR

### ISSUE THREAD

**Issue by lmazuel** [python/mypy#7541]
On Python 3.6, with mypy from master:
```shell
> mypy -p azure.core --show-traceback
c:\users\lmazuel\git\azure-sdk-for-python\env3.6\lib\site-packages\mypy\typeshed\stdlib\3\functools.pyi:16: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.730+dev.855076b6a672017f7dbafe3080cf9daa31f5f1f3
Traceback (most recent call last):
  File "C:\Users\lmazuel\Git\azure-sdk-for-python\env3.6\Scripts\mypy-script.py", line 11, in <module>
    load_entry_point('mypy==0.730+dev.855076b6a672017f7dbafe3080cf9daa31f5f1f3', 'console_scripts', 'mypy')()
  File "c:\users\lmazuel\git\azure-sdk-for-python\env3.6\lib\site-packages\mypy\__main__.py", line 8, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "c:\users\lmazuel\git\azure-sdk-for-python\env3.6\lib\site-packages\mypy\main.py", line 88, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "c:\users\lmazuel\git\azure-sdk-for-python\env3.6\lib\site-packages\mypy\build.py", line 164, in build
    result = _build(sources, options, alt_lib_path, flush_errors, fscache, stdout, stderr)
  File "c:\users\lmazuel\git\azure-sdk-for-python\env3.6\lib\site-packages\mypy\build.py", line 229, in _build
    graph = dispatch(sources, manager, stdout)
  File "c:\users\lmazuel\git\azure-sdk-for-python\env3.6\lib\site-packages\mypy\build.py", line 2566, in dispatch
    process_graph(graph, manager)
  File "c:\users\lmazuel\git\azure-sdk-for-python\env3.6\lib\site-packages\mypy\build.py", line 2875, in process_graph
    process_stale_scc(graph, scc, manager)
  File "c:\users\lmazuel\git\azure-sdk-for-python\env3.6\lib\site-packages\mypy\build.py", line 2968, in process_stale_scc
    mypy.semanal_main.semantic_analysis_for_scc(graph, scc, manager.errors)
  File "c:\users\lmazuel\git\azure-sdk-for-python\env3.6\lib\site-packages\mypy\semanal_main.py", line 77, in semantic_analysis_for_scc
    process_top_levels(graph, scc, patches)
  File "c:\users\lmazuel\git\azure-sdk-for-python\env3.6\lib\site-packages\mypy\semanal_main.py", line 202, in process_top_levels
    patches)
  File "c:\users\lmazuel\git\azure-sdk-for-python\env3.6\lib\site-packages\mypy\semanal_main.py", line 330, in semantic_analyze_target
    active_type=active_type)
  File "c:\users\lmazuel\git\azure-sdk-for-python\env3.6\lib\site-packages\mypy\semanal.py", line 378, in refresh_partial
    self.refresh_top_level(node)
  File "c:\users\lmazuel\git\azure-sdk-for-python\env3.6\lib\site-packages\mypy\semanal.py", line 389, in refresh_top_level
    self.accept(d)
  File "c:\users\lmazuel\git\azure-sdk-for-python\env3.6\lib\site-packages\mypy\semanal.py", line 4625, in accept
    node.accept(self)
  File "c:\users\lmazuel\git\azure-sdk-for-python\env3.6\lib\site-packages\mypy\nodes.py", line 927, in accept
    return visitor.visit_class_def(self)
  File "c:\users\lmazuel\git\azure-sdk-for-python\env3.6\lib\site-packages\mypy\semanal.py", line 1022, in visit_class_def
    self.analyze_class(defn)
  File "c:\users\lmazuel\git\azure-sdk-for-python\env3.6\lib\site-packages\mypy\semanal.py", line 1053, in analyze_class
    result = self.analyze_base_classes(bases)
  File "c:\users\lmazuel\git\azure-sdk-for-python\env3.6\lib\site-packages\mypy\semanal.py", line 1416, in analyze_base_classes
    base = self.expr_to_analyzed_type(base_expr, allow_placeholder=True)
  File "c:\users\lmazuel\git\azure-sdk-for-python\env3.6\lib\site-packages\mypy\semanal.py", line 4636, in expr_to_analyzed_type
    self.is_func_scope())
  File "c:\users\lmazuel\git\azure-sdk-for-python\env3.6\lib\site-packages\mypy\semanal_namedtuple.py", line 200, in check_namedtuple
    info = self.build_namedtuple_typeinfo(name, items, types, default_items, node.line)
  File "c:\users\lmazuel\git\azure-sdk-for-python\env3.6\lib\site-packages\mypy\semanal_namedtuple.py", line 353, in build_namedtuple_typeinfo
    strtype = self.api.named_type('__builtins__.str')
  File "c:\users\lmazuel\git\azure-sdk-for-python\env3.6\lib\site-packages\mypy\semanal.py", line 4096, in named_type
    assert isinstance(node, TypeInfo)
AssertionError:
c:\users\lmazuel\git\azure-sdk-for-python\env3.6\lib\site-packages\mypy\typeshed\stdlib\3\functools.pyi:16: : note: use --pdb to drop into pdb
```

Don't have much more detail yet, will try to comment/uncomment code to get the code that breaks.

Thanks!

**Comment by ilevkivskyi** [comment]
This looks like either broken install. Feel free to re-open if you have a more detailed repro.
