### ISSUE TITLE
Mypy crashes when analyzing attribute access of unidiomatic super invocation

### ISSUE THREAD

**Issue by mwchase** [python/mypy#7580]
Bug report: Mypy crashes when analyzing attribute access of unidiomatic super invocation

Encountered using Python 3.7 and mypy 0.730 and master, but not 0.720.

Somewhat reduced reproduction:
```
import typing

T = typing.TypeVar("T")


def _new(_cls: typing.Type[T], cls: typing.Type[T]):
    return super(_cls, cls).__new__
```

Contents of mypy.ini:
```
[mypy]
strict_optional = True
disallow_untyped_calls = True
```

Traceback:
```
version: 0.740+dev.fd9c1a07a984d66e35b502881aee80529c930501
Traceback (most recent call last):
  File "/Users/maxchase/.pyenv/versions/structured-data/bin/mypy", line 10, in <module>
    sys.exit(console_entry())
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/__main__.py", line 8, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/main.py", line 88, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/build.py", line 164, in build
    result = _build(sources, options, alt_lib_path, flush_errors, fscache, stdout, stderr)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/build.py", line 229, in _build
    graph = dispatch(sources, manager, stdout)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/build.py", line 2566, in dispatch
    process_graph(graph, manager)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/build.py", line 2875, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/build.py", line 2974, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/build.py", line 2070, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/checker.py", line 289, in check_first_pass
    self.accept(d)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/checker.py", line 396, in accept
    stmt.accept(self)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/nodes.py", line 668, in accept
    return visitor.visit_func_def(self)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/checker.py", line 721, in visit_func_def
    self._visit_func_def(defn)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/checker.py", line 725, in _visit_func_def
    self.check_func_item(defn, name=defn.name())
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/checker.py", line 787, in check_func_item
    self.check_func_def(defn, typ, name)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/checker.py", line 958, in check_func_def
    self.accept(item.body)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/checker.py", line 396, in accept
    stmt.accept(self)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/nodes.py", line 992, in accept
    return visitor.visit_block(self)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/checker.py", line 1917, in visit_block
    self.accept(s)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/checker.py", line 396, in accept
    stmt.accept(self)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/nodes.py", line 668, in accept
    return visitor.visit_func_def(self)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/checker.py", line 721, in visit_func_def
    self._visit_func_def(defn)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/checker.py", line 725, in _visit_func_def
    self.check_func_item(defn, name=defn.name())
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/checker.py", line 787, in check_func_item
    self.check_func_def(defn, typ, name)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/checker.py", line 958, in check_func_def
    self.accept(item.body)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/checker.py", line 396, in accept
    stmt.accept(self)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/nodes.py", line 992, in accept
    return visitor.visit_block(self)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/checker.py", line 1917, in visit_block
    self.accept(s)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/checker.py", line 396, in accept
    stmt.accept(self)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/nodes.py", line 1128, in accept
    return visitor.visit_return_stmt(self)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/checker.py", line 2940, in visit_return_stmt
    self.check_return_stmt(s)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/checker.py", line 2973, in check_return_stmt
    s.expr, return_type, allow_none_return=allow_none_func_call))
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/checkexpr.py", line 3591, in accept
    typ = self.visit_call_expr(node, allow_none_return=True)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/checkexpr.py", line 264, in visit_call_expr
    return self.visit_call_expr_inner(e, allow_none_return=allow_none_return)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/checkexpr.py", line 313, in visit_call_expr_inner
    callee_type = get_proper_type(self.accept(e.callee, type_context, always_allow_any=True))
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/checkexpr.py", line 3595, in accept
    typ = node.accept(self)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/nodes.py", line 1815, in accept
    return visitor.visit_super_expr(self)
  File "/Users/maxchase/.pyenv/versions/3.7.4/envs/structured-data/lib/python3.7/site-packages/mypy/checkexpr.py", line 3322, in visit_super_expr
    assert False, 'unreachable'
AssertionError: unreachable
```

**Comment by ilevkivskyi** [comment]
Although this is quite exotic use case, I think this is quite important because this is a crash snd a regression.

**Comment by dlax** [comment]
Looks like PR #9173 fixed this issue, so it can be closed.
