### ISSUE TITLE
Special case Enum _generate_next_value_

### ISSUE THREAD

**Issue by dms-cat** [python/mypy#7591]
* Are you reporting a bug, or opening a feature request? Bug, I think :)

I'm trying to set up a convenience Enum subclass:

```python
from enum import Enum
from typing import Any, List


class AutoNameEnum(Enum):
    def _generate_next_value_(name, start: int, count: int, last_values: List[Any]) -> str:  # noqa: N805
        return str(name).lower()
```

I would expect this to work since `Enum` is a core class, but `mypy` reports the following error:

> Signature of "_generate_next_value_" incompatible with supertype "Enum"

It seems any typing of this signature leads to the same error. Typing `name: str` results in the previous error *and*

> Self argument missing for a non-static method (or an invalid type for self)

while stripping all types instead results in the following error:

> Function is missing a type annotation

* What are the versions of mypy and Python you are using?

```text
$ mypy --version
mypy 0.730
$ python --version
Python 3.6.8
```

* What are the mypy flags you are using?

```text
[mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_untyped_defs = true
follow_imports = skip
ignore_missing_imports = true
no_implicit_optional = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_ignores = true
```

* Workaround

```python
def _generate_next_value_(  # type: ignore
    name: str, start: int, count: int, last_values: List[Any]  # noqa: N805
) -> str:
    return name.lower()
```

**Comment by gvanrossum** [comment]
Maybe adding `@staticmethod` helps? Or move the helper out of the class (since it doesn't seem to have anything to do to the class)?

**Comment by dms-cat** [comment]
Oh sweet, `@staticmethod` works:

```python
class AutoNameEnum(Enum):
    @staticmethod
    def _generate_next_value_(name: str, start: int, count: int, last_values: List[Any]) -> str:
        return name.lower()
```

I guess either the PyCharm stubs are incorrect or neither mypy nor flake8 care about redefining a method as static.

It overrides `Enum._generate_next_value_` based on [Ethan Furman's suggestion](https://stackoverflow.com/a/32313954/96588) so I don't think I can move it out of the class. Or am I misunderstanding something about `Enum` completely?

**Comment by gvanrossum** [comment]
Oh wait, I didn't realize that you were *overriding* an internal API. But if `@staticmethod` works let's close this issue. (I *think* mypy was trying to tell you that. :-)

**Comment by kokumura** [comment]
In Python 3.8, `@staticmethod` won't work.

```python
from enum import Enum, auto
from typing import Any, List

class AutoNameEnum(Enum):
    @staticmethod
    def _generate_next_value_(
        name, start: int, count: int, last_values: List[Any]
    ) -> str:
        return str(name).lower()

    foo = auto()
    bar = auto()
```

results:
```
Traceback (most recent call last):
  File "auto_name_enum.py", line 5, in <module>
    class AutoNameEnum(Enum):
  File "auto_name_enum.py", line 12, in AutoNameEnum
    foo = auto()
  File "/Users/okumura/.pyenv/versions/3.8.1/lib/python3.8/enum.py", line 104, in __setitem__
    value.value = self._generate_next_value(key, 1, len(self._member_names), self._last_values[:])
TypeError: 'staticmethod' object is not callable
```

**Comment by Venom1991** [comment]
This problem bit me just now and the @staticmethod approach seems to work in Python 3.9.1 (no exception is being thrown).

**Comment by l0b0** [comment]
@Venom1991 [`@staticmethod` doesn't seem to work in Python 3.9.15](https://github.com/linz/geostore/pull/2601):

```
Run poetry run cdk deploy --all --require-approval never --strict --change-set-name "ci-${GITHUB_RUN_ID}"
  poetry run cdk deploy --all --require-approval never --strict --change-set-name "ci-${GITHUB_RUN_ID}"
  shell: /usr/bin/bash -e {0}
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
    MSYS: winsymlinks:nativestrict
    pythonLocation: /opt/hostedtoolcache/Python/3.9.15/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.9.15/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.15/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.15/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.9.15/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.15/x64/lib
    AWS_DEFAULT_REGION: ap-southeast-2
    CiOidc: arn:aws:iam::***:role/CiOidc
    NonProdOidc: arn:aws:iam::632223577832:role/NonProdOidc
    ProdOidc: arn:aws:iam::715898075157:role/ProdOidc
    AWS_REGION: ap-southeast-2
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***
    GEOSTORE_ENV_NAME: ci3879327544
Traceback (most recent call last):
  File "/home/runner/work/geostore/geostore/app.py", line 7, in <module>
    from infrastructure.application_stack import Application
  File "/home/runner/work/geostore/geostore/infrastructure/application_stack.py", line 8, in <module>
    from .constructs.api import API
  File "/home/runner/work/geostore/geostore/infrastructure/constructs/api.py", line 18, in <module>
    from .table import Table
  File "/home/runner/work/geostore/geostore/infrastructure/constructs/table.py", line 6, in <module>
    from geostore.parameter_store import ParameterName
  File "/home/runner/work/geostore/geostore/geostore/parameter_store.py", line 24, in <module>
    class ParameterName(Enum):
  File "/home/runner/work/geostore/geostore/geostore/parameter_store.py", line 31, in ParameterName
    GIT_COMMIT = auto()
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/enum.py", line 142, in __setitem__
    value.value = self._generate_next_value(
TypeError: 'staticmethod' object is not callable

Subprocess exited with error 1
Error: Process completed with exit code 1.
```
