### ISSUE TITLE
mypy crashes when generating reports for code featuring calls to untyped variadic functions

### ISSUE THREAD

**Issue by benwebber** [python/mypy#7721]
In strict mode, mypy crashes when generating any report for code featuring calls to untyped variadic functions.

I'm not sure what the specific circumstances are, but here is a minimum working example. Dropping into a PDB shell, it apparently fails at the `f1(*args)` call.

```python
# example.py
def f1(*args):
    pass


def f2(*args):
    return f1(*args)  # this is the problem statement
```

The same happens with keyword arguments (`**kwargs`). mypy does not crash if we annotate the return type of `f1`. 

```python
# example.py
def f1(*args) -> None:
    pass


def f2(*args):
    return f1(*args)
```

Note that this only happens when generating reports; mypy can analyze the file just fine.

---

Command:

```
mypy --show-traceback --strict --xml-report xml example.py
```

Output:

```
example.py: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.740+dev.f08e39362024d12c76b79ee65598be92241f4ed8
example.py: : note: use --pdb to drop into pdb
example.py:1: error: Function is missing a type annotation
example.py:5: error: Function is missing a type annotation
example.py:6: error: Call to untyped function "f1" in typed context
Traceback (most recent call last):
  File "./venv/bin/mypy", line 10, in <module>
    sys.exit(console_entry())
  File "./venv/lib/python3.6/site-packages/mypy/__main__.py", line 8, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "./venv/lib/python3.6/site-packages/mypy/main.py", line 88, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "./venv/lib/python3.6/site-packages/mypy/build.py", line 164, in build
    result = _build(sources, options, alt_lib_path, flush_errors, fscache, stdout, stderr)
  File "./venv/lib/python3.6/site-packages/mypy/build.py", line 229, in _build
    graph = dispatch(sources, manager, stdout)
  File "./venv/lib/python3.6/site-packages/mypy/build.py", line 2566, in dispatch
    process_graph(graph, manager)
  File "./venv/lib/python3.6/site-packages/mypy/build.py", line 2875, in process_graph
    process_stale_scc(graph, scc, manager)
  File "./venv/lib/python3.6/site-packages/mypy/build.py", line 2977, in process_stale_scc
    graph[id].finish_passes()
  File "./venv/lib/python3.6/site-packages/mypy/build.py", line 2115, in finish_passes
    free_tree(self.tree)
  File "./venv/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "./venv/lib/python3.6/site-packages/mypy/build.py", line 1845, in wrap_context
    yield
  File "./venv/lib/python3.6/site-packages/mypy/build.py", line 2110, in finish_passes
    manager.report_file(self.tree, self.type_map(), self.options)
  File "./venv/lib/python3.6/site-packages/mypy/build.py", line 756, in report_file
    self.reports.file(file, self.modules, type_map, options)
  File "./venv/lib/python3.6/site-packages/mypy/report.py", line 83, in file
    reporter.on_file(tree, modules, type_map, options)
  File "./venv/lib/python3.6/site-packages/mypy/report.py", line 471, in on_file
    tree.accept(visitor)
  File "./venv/lib/python3.6/site-packages/mypy/nodes.py", line 292, in accept
    return visitor.visit_mypy_file(self)
  File "./venv/lib/python3.6/site-packages/mypy/stats.py", line 89, in visit_mypy_file
    super().visit_mypy_file(o)
  File "./venv/lib/python3.6/site-packages/mypy/traverser.py", line 35, in visit_mypy_file
    d.accept(self)
  File "./venv/lib/python3.6/site-packages/mypy/nodes.py", line 668, in accept
    return visitor.visit_func_def(self)
  File "./venv/lib/python3.6/site-packages/mypy/stats.py", line 139, in visit_func_def
    super().visit_func_def(o)
  File "./venv/lib/python3.6/site-packages/mypy/traverser.py", line 54, in visit_func_def
    self.visit_func(o)
  File "./venv/lib/python3.6/site-packages/mypy/traverser.py", line 51, in visit_func
    o.body.accept(self)
  File "./venv/lib/python3.6/site-packages/mypy/nodes.py", line 992, in accept
    return visitor.visit_block(self)
  File "./venv/lib/python3.6/site-packages/mypy/traverser.py", line 39, in visit_block
    s.accept(self)
  File "./venv/lib/python3.6/site-packages/mypy/nodes.py", line 1128, in accept
    return visitor.visit_return_stmt(self)
  File "./venv/lib/python3.6/site-packages/mypy/traverser.py", line 104, in visit_return_stmt
    o.expr.accept(self)
  File "./venv/lib/python3.6/site-packages/mypy/nodes.py", line 1532, in accept
    return visitor.visit_call_expr(self)
  File "./venv/lib/python3.6/site-packages/mypy/stats.py", line 225, in visit_call_expr
    self.record_call_target_precision(o)
  File "./venv/lib/python3.6/site-packages/mypy/stats.py", line 234, in record_call_target_precision
    self.record_callable_target_precision(o, callee_type)
  File "./venv/lib/python3.6/site-packages/mypy/stats.py", line 253, in record_callable_target_precision
    lambda n: typemap[o.args[n]])
  File "./venv/lib/python3.6/site-packages/mypy/argmap.py", line 105, in map_formals_to_actuals
    actual_arg_type)
  File "./venv/lib/python3.6/site-packages/mypy/argmap.py", line 70, in map_actuals_to_formals
    actualt = get_proper_type(actual_arg_type(ai))
  File "./venv/lib/python3.6/site-packages/mypy/stats.py", line 253, in <lambda>
    lambda n: typemap[o.args[n]])
KeyError: <mypy.nodes.NameExpr object at 0x106e97c48>
Generated XML report: ./xml/index.xml
```

Versions:

```
$ python --version
Python 3.6.7
$ mypy --version
mypy 0.740+dev.f08e39362024d12c76b79ee65598be92241f4ed8
```

(Note: I trimmed local paths from the output.)

**Comment by ilevkivskyi** [comment]
I can confirm this on master. The crash only happens when both `--strict` and a star-expression in a call are used.

The cause may be that something modifies the argument expression in place. At least the argument at the crash site should be `StarExpr`, not `NameExpr`.

**Comment by JukkaL** [comment]
This doesn't seem to crash any more on master.
