### ISSUE TITLE
mypy fails with mypyc, even with empty file

### ISSUE THREAD

**Issue by xoolive** [python/mypy#7797]
Steps to reproduce:
- pip install mypy # that's 0.740 here, also same with HEAD on github
- pip install mypyc
- create an empty file foo.py

```
mypy foo.py
```

```
Traceback (most recent call last):
  File "/home/xo/.conda/envs/intel37/bin/mypy", line 6, in <module>
    from mypy.__main__ import console_entry
  File "/home/xo/.conda/envs/intel37/lib/python3.7/site-packages/mypy/__main__.py", line 4, in <module>
    from mypy.main import main
  File "mypy/main.py", line 12, in <module>
  File "/home/xo/.conda/envs/intel37/lib/python3.7/site-packages/mypy/build.py", line 33, in <module>
    from mypy.semanal import SemanticAnalyzer
  File "/home/xo/.conda/envs/intel37/lib/python3.7/site-packages/mypy/semanal.py", line 84, in <module>
    from mypy.messages import best_matches, MessageBuilder, pretty_or
  File "/home/xo/.conda/envs/intel37/lib/python3.7/site-packages/mypy/messages.py", line 28, in <module>
    from mypy.typetraverser import TypeTraverserVisitor
  File "mypy/typetraverser.py", line 14, in <module>
SystemError: null argument to internal routine
```

This combination may seem weird but the traceback is not helping much when this happens...

**Comment by msullivan** [comment]
I'm very confused by this. There isn't a mypyc pypi package.

**Comment by xoolive** [comment]
My mistake. It is https://pypi.org/project/mypy-mypyc/
I edit the comment above.

**Comment by JelleZijlstra** [comment]
I think that `mypy-mypyc` package is dead? Currently mypyc is just distributed through mypy itself. Maybe we should put a notice on the `mypy-mypyc` package so people don't use it.

**Comment by xoolive** [comment]
Yes it’s dead but puts a mess obviously.

Or how about pushing a new empty version doing nothing but upgrading vanilla mypy? (Don’t know whether that would be considered orthodox...)

**Comment by msullivan** [comment]
Putting an empty version up with a warning seems reasonable. I can do that at some point.
