### ISSUE TITLE
0.750: self check fails under Python 3.8

### ISSUE THREAD

**Issue by mr-c** [python/mypy#8047]
Found while updating the mypy package for Debian:
```
python3.8 -m mypy 	--config-file /build/mypy-0.750/mypy_self_check.ini -p mypy
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/build/mypy-0.750/mypy/__main__.py", line 12, in <module>
    main(None, sys.stdout, sys.stderr)
  File "/build/mypy-0.750/mypy/main.py", line 89, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/build/mypy-0.750/mypy/build.py", line 166, in build
    result = _build(
  File "/build/mypy-0.750/mypy/build.py", line 235, in _build
    graph = dispatch(sources, manager, stdout)
  File "/build/mypy-0.750/mypy/build.py", line 2620, in dispatch
    process_graph(graph, manager)
  File "/build/mypy-0.750/mypy/build.py", line 2929, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/build/mypy-0.750/mypy/build.py", line 3028, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/build/mypy-0.750/mypy/build.py", line 2119, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/build/mypy-0.750/mypy/checker.py", line 292, in check_first_pass
    self.accept(d)
  File "/build/mypy-0.750/mypy/checker.py", line 399, in accept
    stmt.accept(self)
  File "/build/mypy-0.750/mypy/nodes.py", line 939, in accept
    return visitor.visit_class_def(self)
  File "/build/mypy-0.750/mypy/checker.py", line 1719, in visit_class_def
    self.accept(defn.defs)
  File "/build/mypy-0.750/mypy/checker.py", line 399, in accept
    stmt.accept(self)
  File "/build/mypy-0.750/mypy/nodes.py", line 1004, in accept
    return visitor.visit_block(self)
  File "/build/mypy-0.750/mypy/checker.py", line 1970, in visit_block
    self.accept(s)
  File "/build/mypy-0.750/mypy/checker.py", line 399, in accept
    stmt.accept(self)
  File "/build/mypy-0.750/mypy/nodes.py", line 766, in accept
    return visitor.visit_decorator(self)
  File "/build/mypy-0.750/mypy/checker.py", line 3397, in visit_decorator
    self.check_func_item(e.func, name=e.func.name)
  File "/build/mypy-0.750/mypy/checker.py", line 790, in check_func_item
    self.check_func_def(defn, typ, name)
  File "/build/mypy-0.750/mypy/checker.py", line 973, in check_func_def
    self.accept(item.body)
  File "/build/mypy-0.750/mypy/checker.py", line 399, in accept
    stmt.accept(self)
  File "/build/mypy-0.750/mypy/nodes.py", line 1004, in accept
    return visitor.visit_block(self)
  File "/build/mypy-0.750/mypy/checker.py", line 1970, in visit_block
    self.accept(s)
  File "/build/mypy-0.750/mypy/checker.py", line 399, in accept
    stmt.accept(self)
  File "/build/mypy-0.750/mypy/nodes.py", line 1195, in accept
    return visitor.visit_if_stmt(self)
  File "/build/mypy-0.750/mypy/checker.py", line 3091, in visit_if_stmt
    self.accept(b)
  File "/build/mypy-0.750/mypy/checker.py", line 399, in accept
    stmt.accept(self)
  File "/build/mypy-0.750/mypy/nodes.py", line 1004, in accept
    return visitor.visit_block(self)
  File "/build/mypy-0.750/mypy/checker.py", line 1970, in visit_block
    self.accept(s)
  File "/build/mypy-0.750/mypy/checker.py", line 399, in accept
    stmt.accept(self)
  File "/build/mypy-0.750/mypy/nodes.py", line 1153, in accept
    return visitor.visit_assert_stmt(self)
  File "/build/mypy-0.750/mypy/checker.py", line 3132, in visit_assert_stmt
    self.expr_checker.accept(s.expr)
  File "/build/mypy-0.750/mypy/checkexpr.py", line 3624, in accept
    typ = node.accept(self)
  File "/build/mypy-0.750/mypy/nodes.py", line 1544, in accept
    return visitor.visit_call_expr(self)
  File "/build/mypy-0.750/mypy/checkexpr.py", line 263, in visit_call_expr
    return self.visit_call_expr_inner(e, allow_none_return=allow_none_return)
  File "/build/mypy-0.750/mypy/checkexpr.py", line 340, in visit_call_expr_inner
    ret_type = self.check_call_expr_with_callee_type(callee_type, e, fullname,
  File "/build/mypy-0.750/mypy/checkexpr.py", line 731, in check_call_expr_with_callee_type
    return self.check_call(callee_type, e.args, e.arg_kinds, e,
  File "/build/mypy-0.750/mypy/checkexpr.py", line 790, in check_call
    return self.check_callable_call(callee, args, arg_kinds, context, arg_names,
  File "/build/mypy-0.750/mypy/checkexpr.py", line 898, in check_callable_call
    new_ret_type = self.apply_function_plugin(
  File "/build/mypy-0.750/mypy/checkexpr.py", line 630, in apply_function_plugin
    return callback(
  File "/build/mypy-0.750/misc/proper_plugin.py", line 41, in isinstance_proper_hook
    if is_special_target(right):
  File "/build/mypy-0.750/misc/proper_plugin.py", line 51, in is_special_target
    if right.type_object().fullname() == 'builtins.tuple':
TypeError: 'str' object is not callable
/build/mypy-0.750/mypy/nodes.py:539: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.750
```
```
# python3.8 -m mypy --pdb --config-file /build/mypy-0.750/mypy_self_check.ini -p mypy
/build/mypy-0.750/mypy/nodes.py:539: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.750
Dropping into pdb
> /build/mypy-0.750/misc/proper_plugin.py(51)is_special_target()
-> if right.type_object().fullname() == 'builtins.tuple':
(Pdb) p right
def (line: builtins.int =, column: builtins.int =) -> mypy.types.ProperType
(Pdb) p right.type_object()
<TypeInfo mypy.types.ProperType>
(Pdb) p right.type_object().fullname 
'mypy.types.ProperType'
(Pdb) p right.type_object().fullname()
*** TypeError: 'str' object is not callable

```

**Comment by mr-c** [comment]
Looks like e97377c454a1d5c019e9c56871d5f229db6b47b2 was incomplete, I'll send a PR

**Comment by mr-c** [comment]
Mea culpa, we were including our own copy of `proper_plugin` (as it isn't part of the source dist) and it had gotten out of sync.
