### ISSUE TITLE
mypy crash when changing Protocol-based Callable into a Callable type alias

### ISSUE THREAD

**Issue by achimnol** [python/mypy#8058]
On Python 3.8.0 on macOS with mypy 0.750, I encountered the following error which is affected by the existence of mypy cache:
```console
$ rm -rf .mypy_cache

$ python -m mypy src examples tests
examples/simple-server-thrift.py:31: error: Argument "serializer" to "Peer" has incompatible type "Callable[[Optional[Any]], bytes]"; expected "AbstractSerializer"
examples/simple-server-thrift.py:32: error: Argument "deserializer" to "Peer" has incompatible type "Callable[[bytes], Optional[Any]]"; expected "AbstractDeserializer"
examples/simple-client-thrift.py:23: error: Argument "serializer" to "Peer" has incompatible type "Callable[[Optional[Any]], bytes]"; expected "AbstractSerializer"
examples/simple-client-thrift.py:24: error: Argument "deserializer" to "Peer" has incompatible type "Callable[[bytes], Optional[Any]]"; expected "AbstractDeserializer"
Found 4 errors in 2 files (checked 39 source files)

$ fg
[1]  - 71504 continued  vi src/callosum/rpc/channel.py
```

Here I edited the type definition to use `AbstractSerializer = Callable[[Optional[Any], bytes]` instead of a Protocol based callable which defines a `def __call__(self, o: Optional[Any]) -> bytes: ...`.

```console
[1]  + 71504 suspended  vi src/callosum/rpc/channel.py

$ python -m mypy src examples tests
Traceback (most recent call last):
  File "/home/joongi/.pyenv/versions/3.8.0/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/joongi/.pyenv/versions/3.8.0/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/joongi/.pyenv/versions/callosum/lib/python3.8/site-packages/mypy/__main__.py", line 12, in <module>
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 89, in main
  File "mypy/build.py", line 166, in build
  File "mypy/build.py", line 235, in _build
  File "mypy/build.py", line 2620, in dispatch
  File "mypy/build.py", line 2922, in process_graph
  File "mypy/build.py", line 3000, in process_fresh_modules
  File "mypy/build.py", line 1930, in fix_cross_refs
  File "mypy/fixup.py", line 25, in fixup_module
  File "mypy/fixup.py", line 89, in visit_symbol_table
  File "mypy/fixup.py", line 45, in visit_type_info
  File "mypy/fixup.py", line 91, in visit_symbol_table
  File "mypy/nodes.py", line 766, in accept
  File "mypy/fixup.py", line 115, in visit_decorator
  File "mypy/nodes.py", line 676, in accept
  File "mypy/fixup.py", line 99, in visit_func_def
  File "mypy/types.py", line 1096, in accept
  File "mypy/fixup.py", line 182, in visit_callable_type
  File "mypy/types.py", line 792, in accept
  File "mypy/fixup.py", line 153, in visit_instance
  File "mypy/fixup.py", line 267, in lookup_qualified_typeinfo
AssertionError: Should never get here in normal mode, got TypeAlias:callosum.abc.AbstractDeserializer instead of TypeInfo

$ rm -rf .mypy_cache

$ python -m mypy src examples tests
src/callosum/pubsub/channel.py:57: error: Cannot assign to a method
src/callosum/pubsub/channel.py:57: error: Incompatible types in assignment (expression has type "Callable[[Optional[Any]], bytes]", variable has type "Callable[[], bytes]")
src/callosum/pubsub/channel.py:78: error: Argument 1 to "encode" of "PubSubMessage" has incompatible type "Callable[[], bytes]"; expected "Callable[[Optional[Any]], bytes]"
src/callosum/pubsub/channel.py:135: error: Cannot assign to a method
src/callosum/pubsub/channel.py:135: error: Invalid self argument "Consumer" to attribute function "_deserializer" with type "Callable[[bytes], Optional[Any]]"
src/callosum/pubsub/channel.py:135: error: Incompatible types in assignment (expression has type "Callable[[bytes], Optional[Any]]", variable has type "Callable[[], Optional[Any]]")
src/callosum/pubsub/channel.py:167: error: Invalid self argument "Consumer" to attribute function "_deserializer" with type "Callable[[bytes], Optional[Any]]"
src/callosum/pubsub/channel.py:167: error: Argument 2 to "decode" of "PubSubMessage" has incompatible type "Callable[[], Optional[Any]]"; expected "Callable[[bytes], Optional[Any]]"
src/callosum/rpc/channel.py:100: error: Cannot assign to a method
src/callosum/rpc/channel.py:100: error: Incompatible types in assignment (expression has type "Callable[[Optional[Any]], bytes]", variable has type "Callable[[], bytes]")
src/callosum/rpc/channel.py:101: error: Cannot assign to a method
src/callosum/rpc/channel.py:101: error: Invalid self argument "Peer" to attribute function "_deserializer" with type "Callable[[bytes], Optional[Any]]"
src/callosum/rpc/channel.py:101: error: Incompatible types in assignment (expression has type "Callable[[bytes], Optional[Any]]", variable has type "Callable[[], Optional[Any]]")
src/callosum/rpc/channel.py:164: error: Invalid self argument "Peer" to attribute function "_deserializer" with type "Callable[[bytes], Optional[Any]]"
src/callosum/rpc/channel.py:164: error: Argument 2 to "decode" of "RPCMessage" has incompatible type "Callable[[], Optional[Any]]"; expected "Callable[[bytes], Optional[Any]]"
src/callosum/rpc/channel.py:200: error: Argument 1 to "encode" of "RPCMessage" has incompatible type "Callable[[], bytes]"; expected "Callable[[Optional[Any]], bytes]"
Found 16 errors in 2 files (checked 39 source files)
```

Tried to reproduce this issue with a minimal example, but I could not. :sad:

**Comment by achimnol** [comment]
lablup/callosum@5b5b9ff is the commit where I saw this error.
Interchaging the definition of `AbstractSerializer` & `AbstractDeserializer` from/to protocols and callable aliases triggers the mypy crash.

**Comment by achimnol** [comment]
While working with the above commit, I also encountered #708.

**Comment by JukkaL** [comment]
@ilevkivskyi The crash might be related to the new type alias implementation. Any thougts?

**Comment by ilevkivskyi** [comment]
@achimnol Could you please give exact steps to reproduce? I tried checking out the commit you mentioned running mypy, then replacing protocols with commented out aliases, but this didn't cause the crash. I also tried the parent commit with the same result.

**Comment by achimnol** [comment]
I'm trying to reproduce this with a minimal self-contained code example, like:
![image](https://user-images.githubusercontent.com/555156/70064691-4bd7e180-162d-11ea-85cb-29e37916180c.png)
but no gain yet.

In the Callosum's source tree, try commenting out one and the other defintions of `AbstractSerializer` and `AbstractDeserializer` back and forth (`src/callosum/abc.py`), as seen in:
![image](https://user-images.githubusercontent.com/555156/70064827-817cca80-162d-11ea-987e-522f8d7b6b93.png)
Running mypy without clearing the cache crashes as reported. (Type errors in the code are expected but mypy shouldn't crash.)

**Comment by ilevkivskyi** [comment]
@achimnol 
> try commenting out one and the other defintions

This is not what I want, I has been doing this for half an hour with no success (i.e. no crash). What I need is a clear sequence like:
1. Check out commit `xxxx`
2. Clean mypy cache
3. Run that mypy command
4. Edit file `yyy` this way (show diff)
5. Run mypy again
6. etc

**Comment by achimnol** [comment]
Okay, here it is (I just followed these steps and could reproduce it on a new, clean installation):
1. `mkdir temp-callosum`
2. `cd temp-callosum`
3. `pyenv virtualenv 3.8.0 venv-temp-callosum`
4. `git clone https://github.com/lablup/callosum .` and `git checkout 5b5b9ff`
5. `pyenv local venv-temp-callosum`
6. `pip install -U pip setuptools`
7. `pip install -U -e '.[test]'`
8. `python -m mypy src tests examples`
   - Here you will see 4 type errors related to serializers.
9. `vi src/callosum/abc.py`
   - Remove comments from the type alias definitions in the line 47 and 48.
   - Comment out the protocol defintions at the lines 35 to 44.
   - Add `Callable` in the `typing` imports on the top.
10. `python -m mypy src tests examples`
    - mypy crahses as reported.
11. `rm -rf .mypy_cache`
12. `python -m mypy src tests examples`
    - mypy does not crash but reports different type errors related to serializers.

**Comment by achimnol** [comment]
The diff for the step 9 is here:
```diff
diff --git a/src/callosum/abc.py b/src/callosum/abc.py
index fc3d4c1..51b94e1 100644
--- a/src/callosum/abc.py
+++ b/src/callosum/abc.py
@@ -4,6 +4,7 @@ import abc
 from typing import (
     Any, Final, Optional,
     Tuple,
+    Callable,
     Protocol,
 )

@@ -31,21 +32,21 @@ A sentinel object that represents task cancellation.
 CANCELLED: Final = Sentinel()


-class AbstractSerializer(Protocol):
-
-    def __call__(self, obj: Optional[Any]) -> bytes:
-        ...
-
-
-class AbstractDeserializer(Protocol):
-
-    def __call__(self, data: bytes) -> Optional[Any]:
-        ...
+# class AbstractSerializer(Protocol):
+#
+#     def __call__(self, obj: Optional[Any]) -> bytes:
+#         ...
+#
+#
+# class AbstractDeserializer(Protocol):
+#
+#     def __call__(self, data: bytes) -> Optional[Any]:
+#         ...


 # FIXME: python/mypy#8058
-# AbstractSerializer = Callable[[Optional[Any]], bytes]
-# AbstractDeserializer = Callable[[bytes], Optional[Any]]
+AbstractSerializer = Callable[[Optional[Any]], bytes]
+AbstractDeserializer = Callable[[bytes], Optional[Any]]


 class AbstractMessage(metaclass=abc.ABCMeta):
```

**Comment by ilevkivskyi** [comment]
OK, I tried this on Linux Mint (don't have Ubuntu 18.04) and it still doesn't crash. I however used `venv` instead of `pyenv` to create the virtual environment. But if this is the reason, it means something is likely wrong with your install/environment, not with mypy itself. But it is hard to tell what exactly. Maybe someone else will be able to reproduce this.

**Comment by ilevkivskyi** [comment]
Btw the original four errors you see are because of argument _names_, you can make them "anonymous" by using `__data` and `__obj` in the protocols (this fixes the four errors). Or since you are on Python 3.8 you can try the new positional-only arguments (I didn't test this however).

**Comment by achimnol** [comment]
Making them positional-only arguments resolves the first type errors. Thanks for the tip!
I'm now observing some other cases that after chaging type/class definitions I need to manually clear the mypy cache to get the correct type-check results, even without explicit crashes...

**Comment by achimnol** [comment]
Also I just realized that using callable protocols is a workaround for #708.

**Comment by JukkaL** [comment]
Closing since we don't have a simple way to reproduce and there has been no activity in a long time. We can reopen this if somebody can find a reproducer.
