### ISSUE TITLE
stubgen semanal.py:4130: AssertionError on assert isinstance(node, TypeInfo)

### ISSUE THREAD

**Issue by dset0x** [python/mypy#8098]
Stubgen seems to fail in the same way for all packages I have tried it on on my system.

- Python 3.6.6
- mypy 0.760+dev.5680f5c5a8f506b7f8daebafaedc6d2a1514b56b

```
$ stubgen eliot/ # https://eliot.readthedocs.io/en/stable/index.html
/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/typeshed/stdlib/3/functools.pyi:16: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.760+dev.5680f5c5a8f506b7f8daebafaedc6d2a1514b56b
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.6.6/bin/stubgen", line 11, in <module>
    load_entry_point('mypy==0.760+dev.5680f5c5a8f506b7f8daebafaedc6d2a1514b56b', 'console_scripts', 'stubgen')()
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/stubgen.py", line 1551, in main
    generate_stubs(options)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/stubgen.py", line 1417, in generate_stubs
    generate_asts_for_modules(py_modules, options.parse_only, mypy_opts, options.verbose)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/stubgen.py", line 1350, in generate_asts_for_modules
    res = build(list(py_modules), mypy_options)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/build.py", line 167, in build
    sources, options, alt_lib_path, flush_errors, fscache, stdout, stderr, extra_plugins
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/build.py", line 235, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/build.py", line 2622, in dispatch
    process_graph(graph, manager)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/build.py", line 2931, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/build.py", line 3024, in process_stale_scc
    mypy.semanal_main.semantic_analysis_for_scc(graph, scc, manager.errors)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal_main.py", line 77, in semantic_analysis_for_scc
    process_top_levels(graph, scc, patches)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal_main.py", line 202, in process_top_levels
    patches)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal_main.py", line 330, in semantic_analyze_target
    active_type=active_type)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal.py", line 378, in refresh_partial
    self.refresh_top_level(node)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal.py", line 389, in refresh_top_level
    self.accept(d)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal.py", line 4659, in accept
    node.accept(self)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/nodes.py", line 939, in accept
    return visitor.visit_class_def(self)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal.py", line 1029, in visit_class_def
    self.analyze_class(defn)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal.py", line 1088, in analyze_class
    if self.analyze_namedtuple_classdef(defn):
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal.py", line 1126, in analyze_namedtuple_classdef
    defn, self.is_stub_file)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal_namedtuple.py", line 62, in analyze_namedtuple_classdef
    defn.name, items, types, default_items, defn.line)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal_namedtuple.py", line 356, in build_namedtuple_typeinfo
    strtype = self.api.named_type('__builtins__.str')
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal.py", line 4130, in named_type
    assert isinstance(node, TypeInfo)
AssertionError:
/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/typeshed/stdlib/3/functools.pyi:16: : note: use --pdb to drop into pdb
```

I've been unable to check the type of `node` because trying to do anything with a debugger or print it results in something along the lines of:
```
/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/typeshed/stdlib/3/functools.pyi:16: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.760+dev.5680f5c5a8f506b7f8daebafaedc6d2a1514b56b
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.6.6/bin/stubgen", line 11, in <module>
    load_entry_point('mypy==0.760+dev.5680f5c5a8f506b7f8daebafaedc6d2a1514b56b', 'console_scripts', 'stubgen')()
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/stubgen.py", line 1551, in main
    generate_stubs(options)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/stubgen.py", line 1417, in generate_stubs
    generate_asts_for_modules(py_modules, options.parse_only, mypy_opts, options.verbose)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/stubgen.py", line 1350, in generate_asts_for_modules
    res = build(list(py_modules), mypy_options)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/build.py", line 167, in build
    sources, options, alt_lib_path, flush_errors, fscache, stdout, stderr, extra_plugins
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/build.py", line 235, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/build.py", line 2622, in dispatch
    process_graph(graph, manager)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/build.py", line 2931, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/build.py", line 3024, in process_stale_scc
    mypy.semanal_main.semantic_analysis_for_scc(graph, scc, manager.errors)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal_main.py", line 77, in semantic_analysis_for_scc
    process_top_levels(graph, scc, patches)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal_main.py", line 202, in process_top_levels
    patches)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal_main.py", line 330, in semantic_analyze_target
    active_type=active_type)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal.py", line 378, in refresh_partial
    self.refresh_top_level(node)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal.py", line 389, in refresh_top_level
    self.accept(d)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal.py", line 4662, in accept
    node.accept(self)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/nodes.py", line 939, in accept
    return visitor.visit_class_def(self)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal.py", line 1029, in visit_class_def
    self.analyze_class(defn)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal.py", line 1088, in analyze_class
    if self.analyze_namedtuple_classdef(defn):
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal.py", line 1126, in analyze_namedtuple_classdef
    defn, self.is_stub_file)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal_namedtuple.py", line 62, in analyze_namedtuple_classdef
    defn.name, items, types, default_items, defn.line)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal_namedtuple.py", line 356, in build_namedtuple_typeinfo
    strtype = self.api.named_type('__builtins__.str')
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal.py", line 4134, in named_type
    if args:
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/site-packages/mypy/semanal.py", line 4134, in named_type
    if args:
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/bdb.py", line 51, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/bdb.py", line 69, in dispatch_line
    self.user_line(frame)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/pdb.py", line 261, in user_line
    self.interaction(frame, None)
  File "/home/user/wpib/lib/python3.6/site-packages/IPython/core/debugger.py", line 289, in interaction
    OldPdb.interaction(self, frame, traceback)
  File "/home/user/wpib/lib/python3.6/site-packages/pdb.py", line 249, in interaction
    self.cmdloop()
  File "/home/user/wpib/lib/python3.6/site-packages/IPython/terminal/debugger.py", line 99, in cmdloop
    stop = self.onecmd(line)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/pdb.py", line 418, in onecmd
    return cmd.Cmd.onecmd(self, line)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/cmd.py", line 216, in onecmd
    return self.default(line)
  File "/home/user/wpib/lib/python3.6/site-packages/pdb.py", line 468, in default
    return pdb.Pdb.default(self, line)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/pdb.py", line 383, in default
    self.error(traceback.format_exception_only(*exc_info)[-1].strip())
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/pdb.py", line 456, in error
    print('***', msg, file=self.stdout)
  File "/home/user/.pyenv/versions/3.6.6/lib/python3.6/codecs.py", line 377, in write
    self.stream.write(data)
TypeError: write() argument must be str, not bytes
```

**Comment by hauntsaninja** [comment]
Closing since I can't repro, `stubgen` works for me on `eliot` and in general
