### ISSUE TITLE
Mypy (Official) PyCharm plugin tracebacks with mypy, and running mypy outside PyCharm gives an error

### ISSUE THREAD

**Issue by dan-stromberg** [python/mypy#8527]
Hi.

* Are you reporting a bug, or opening a feature request?
This seems to be a bug in mypy or PyCharm or a dependency.

* Please insert below the code you are checking with mypy,
#!/usr/bin/env python3

def fibonacci_sequence():
    """Generate the fibonacii sequence forever."""
    value1, value2 = 1, 1
    while True:
        yield value1
        value1, value2 = value2, value1 + value2

def main():
    for index, fibonacci_number in zip(range(10), fibonacci_sequence()):
        print(index, fibonacci_number)

main()

* What is the actual behavior/output?
A traceback.

* What is the behavior/output you expect?
I want mypy to say the code is fine - even if I sprinkle in some types using MonkeyType or manually.  Or to detect a problem if I intentionally (or unintentionally) add a type error.

* What are the versions of mypy and Python you are using?
mypy 0.770 and CPython 3.7.5 inside PyCharm.  mypy 0.761 exhibits the same problem.
mypy 0.761 and CPython 3.6.9 outside PyCharm also have trouble.

I do not know how to do install mypy master within PyCharm - I'm mostly a vim user.  I allowed PyCharm to install mypy for me, hoping that would be compatible with PyCharm.  Then I downgraded it to 0.761 inside PyCharm.

Also, running mypy outside PyCharm at the command line produces an error, albeit a (possibly!) different one.

* What are the mypy flags you are using? (For example --strict-optional)
What PyCharm passes it, in the case of PyCharm, or no arguments, in the case of running mypy outside PyCharm at the command line.

* If mypy crashed with a traceback, please paste
  the full traceback below.
Daemon crashed!
Traceback (most recent call last):
  File "mypy/dmypy_server.py", line 225, in serve
  File "mypy/dmypy_server.py", line 268, in run_command
  File "mypy/dmypy_server.py", line 327, in cmd_run
  File "mypy/dmypy_server.py", line 380, in check
  File "mypy/dmypy_server.py", line 401, in initialize_fine_grained
  File "mypy/build.py", line 166, in build
  File "mypy/build.py", line 235, in _build
  File "mypy/build.py", line 2558, in dispatch
  File "mypy/build.py", line 2778, in load_graph
  File "mypy/build.py", line 1816, in __init__
  File "mypy/build.py", line 2006, in parse_file
  File "mypy/build.py", line 752, in parse_file
  File "mypy/parse.py", line 25, in parse
  File "mypy/fastparse.py", line 163, in parse
  File "mypy/fastparse.py", line 316, in visit
  File "mypy/fastparse.py", line 478, in visit_Module
AttributeError: 'TypeIgnore' object has no attribute 'tag'
Daemon started

Here's the error from running mypy on my python test script "tst.py":
/home/dstromberg/.local/lib/python3.6/site-packages/mypy/typeshed/stdlib/2and3/builtins.pyi: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
If this issue continues with mypy master, please report a bug at https://github.com/python/mypy/issues
version: 0.761
/home/dstromberg/.local/lib/python3.6/site-packages/mypy/typeshed/stdlib/2and3/builtins.pyi: : note: please use --show-traceback to print a traceback when reporting a bug

mypy 0.770+dev.20f7f2dd71c21bde4d3d99f9ab69bf6670c7fa03  at the commandline gives a similar error.

BTW, I tried the unofficial mypy plugin for PyCharm first, and never uninstalled it.  PyCharm appears to have been smart enough to uninstall it for me when I switched to Mypy (Official).

Please advise?

Thanks for the cool tool!

**Comment by dan-stromberg** [comment]
Here's the traceback from running mypy master outside PyCharm:
$ mypy --show-traceback tst.py 
below cmd output started 2020 Wed Mar 11 04:17:04 PM PDT
/home/dstromberg/.local/lib/python3.6/site-packages/mypy/typeshed/stdlib/2and3/builtins.pyi: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.770+dev.20f7f2dd71c21bde4d3d99f9ab69bf6670c7fa03
Traceback (most recent call last):
  File "/home/dstromberg/.local/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/dstromberg/.local/lib/python3.6/site-packages/mypy/__main__.py", line 8, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/home/dstromberg/.local/lib/python3.6/site-packages/mypy/main.py", line 89, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/home/dstromberg/.local/lib/python3.6/site-packages/mypy/build.py", line 181, in build
    sources, options, alt_lib_path, flush_errors, fscache, stdout, stderr, extra_plugins
  File "/home/dstromberg/.local/lib/python3.6/site-packages/mypy/build.py", line 249, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/dstromberg/.local/lib/python3.6/site-packages/mypy/build.py", line 2596, in dispatch
    graph = load_graph(sources, manager)
  File "/home/dstromberg/.local/lib/python3.6/site-packages/mypy/build.py", line 2817, in load_graph
    caller_state=st, caller_line=st.dep_line_map.get(dep, 1))
  File "/home/dstromberg/.local/lib/python3.6/site-packages/mypy/build.py", line 1851, in __init__
    self.parse_file()
  File "/home/dstromberg/.local/lib/python3.6/site-packages/mypy/build.py", line 2042, in parse_file
    self.ignore_all or self.options.ignore_errors)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/dstromberg/.local/lib/python3.6/site-packages/mypy/build.py", line 1918, in wrap_context
    yield
  File "/home/dstromberg/.local/lib/python3.6/site-packages/mypy/build.py", line 2042, in parse_file
    self.ignore_all or self.options.ignore_errors)
  File "/home/dstromberg/.local/lib/python3.6/site-packages/mypy/build.py", line 766, in parse_file
    tree = parse(source, path, id, self.errors, options=self.options)
  File "/home/dstromberg/.local/lib/python3.6/site-packages/mypy/parse.py", line 29, in parse
    options=options)
  File "/home/dstromberg/.local/lib/python3.6/site-packages/mypy/fastparse.py", line 166, in parse
    ).visit(ast)
  File "/home/dstromberg/.local/lib/python3.6/site-packages/mypy/fastparse.py", line 316, in visit
    return visitor(node)
  File "/home/dstromberg/.local/lib/python3.6/site-packages/mypy/fastparse.py", line 478, in visit_Module
    parsed = parse_type_ignore_tag(ti.tag)  # type: ignore[attr-defined]
AttributeError: 'TypeIgnore' object has no attribute 'tag'
/home/dstromberg/.local/lib/python3.6/site-packages/mypy/typeshed/stdlib/2and3/builtins.pyi: : note: use --pdb to drop into pdb

Thanks.

**Comment by ethanhs** [comment]
I am unable to reproduce with https://mypy-play.net/?mypy=latest&python=3.8&flags=check-untyped-defs&gist=147fc4c662aac502b64ae6fba17372c1

I think your installation may be broken? Can you uninstall mypy and install again?

**Comment by dan-stromberg** [comment]
I uninstalled and reinstalled, but still the same problem:

```
$ python3.6 -m pip uninstall mypy # --show-traceback tst.py 
below cmd output started 2020 Thu Mar 12 08:30:13 AM PDT
Found existing installation: mypy 0.770+dev.20f7f2dd71c21bde4d3d99f9ab69bf6670c7fa03
Uninstalling mypy-0.770+dev.20f7f2dd71c21bde4d3d99f9ab69bf6670c7fa03:
  Would remove:
    /home/dstromberg/.local/bin/dmypy
    /home/dstromberg/.local/bin/mypy
    /home/dstromberg/.local/bin/mypyc
    /home/dstromberg/.local/bin/stubgen
    /home/dstromberg/.local/bin/stubtest
    /home/dstromberg/.local/lib/python3.6/site-packages/mypy-0.770+dev.20f7f2dd71c21bde4d3d99f9ab69bf6670c7fa03.dist-info/*
    /home/dstromberg/.local/lib/python3.6/site-packages/mypy/*
    /home/dstromberg/.local/lib/python3.6/site-packages/mypyc/*
Proceed (y/n)? y
  Successfully uninstalled mypy-0.770+dev.20f7f2dd71c21bde4d3d99f9ab69bf6670c7fa03
above cmd output done    2020 Thu Mar 12 08:30:16 AM PDT
dstromberg@dstromberg-inspiron-5570:~/PycharmProjects/mypy-test x86_64-pc-linux-gnu 3789

$ python3.6 -m mypy --show-traceback tst.py 
below cmd output started 2020 Thu Mar 12 08:30:19 AM PDT
/usr/bin/python3.6: No module named mypy
above cmd output done    2020 Thu Mar 12 08:30:19 AM PDT
dstromberg@dstromberg-inspiron-5570:~/PycharmProjects/mypy-test x86_64-pc-linux-gnu 3789

$ python3.6 -m pip install mypy # --show-traceback tst.py 
below cmd output started 2020 Thu Mar 12 08:30:40 AM PDT
Defaulting to user installation because normal site-packages is not writeable
Collecting mypy
  Downloading mypy-0.770-cp36-cp36m-manylinux1_x86_64.whl (21.7 MB)
     |################################| 21.7 MB 12.1 MB/s 
Requirement already satisfied: typed-ast<1.5.0,>=1.4.0 in /usr/local/lib/python3.6/dist-packages (from mypy) (1.4.0)
Requirement already satisfied: typing-extensions>=3.7.4 in /home/dstromberg/.local/lib/python3.6/site-packages (from mypy) (3.7.4.1)
Requirement already satisfied: mypy-extensions<0.5.0,>=0.4.3 in /home/dstromberg/.local/lib/python3.6/site-packages (from mypy) (0.4.3)
Installing collected packages: mypy
Successfully installed mypy-0.770
above cmd output done    2020 Thu Mar 12 08:30:49 AM PDT
dstromberg@dstromberg-inspiron-5570:~/PycharmProjects/mypy-test x86_64-pc-linux-gnu 3789

$ python3.6 -m mypy --show-traceback tst.py 
below cmd output started 2020 Thu Mar 12 08:30:54 AM PDT
/home/dstromberg/.local/lib/python3.6/site-packages/mypy/typeshed/stdlib/2and3/builtins.pyi: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.770
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "mypy/build.py", line 1918, in wrap_context
  File "mypy/build.py", line 2041, in parse_file
  File "mypy/build.py", line 766, in parse_file
  File "mypy/parse.py", line 25, in parse
  File "mypy/fastparse.py", line 163, in parse
  File "mypy/fastparse.py", line 316, in visit
  File "mypy/fastparse.py", line 478, in visit_Module
AttributeError: 'TypeIgnore' object has no attribute 'tag'
/home/dstromberg/.local/lib/python3.6/site-packages/mypy/typeshed/stdlib/2and3/builtins.pyi: : note: use --pdb to drop into pdb
```

Any further suggestions?

BTW, I believe PyCharm is using a different CPython.  PyCharm has 3.7, but my /usr/bin/python3 is 3.6.

**Comment by dan-stromberg** [comment]
I'm using python3 -m pip install --user mypy
That's perhaps less common than installing into a virtual environment.

**Comment by dan-stromberg** [comment]
I just tried the following:
$ mv ~/.local{,.nopers}

$ python3.6 -m pip install --user mypy
Collecting mypy
  Using cached https://files.pythonhosted.org/packages/b0/f4/5a08a46e808d234e65e9f036451d124dd9053a6024c77479eb8d0d7a82e0/mypy-0.770-cp36-cp36m-manylinux1_x86_64.whl
Collecting typing-extensions>=3.7.4 (from mypy)
  Using cached https://files.pythonhosted.org/packages/03/92/705fe8aca27678e01bbdd7738173b8e7df0088a2202c80352f664630d638/typing_extensions-3.7.4.1-py3-none-any.whl
Collecting mypy-extensions<0.5.0,>=0.4.3 (from mypy)
  Using cached https://files.pythonhosted.org/packages/5c/eb/975c7c080f3223a5cdaff09612f3a5221e4ba534f7039db34c35d95fa6a5/mypy_extensions-0.4.3-py2.py3-none-any.whl
Requirement already satisfied: typed-ast<1.5.0,>=1.4.0 in /usr/local/lib/python3.6/dist-packages (from mypy) (1.4.0)
Installing collected packages: typing-extensions, mypy-extensions, mypy
Successfully installed mypy-0.770 mypy-extensions-0.4.3 typing-extensions-3.7.4.1
WARNING: You are using pip version 19.1.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
above cmd output done    2020 Thu Mar 12 12:39:10 PM PDT
dstromberg@dstromberg-inspiron-5570:~/PycharmProjects/mypy-test x86_64-pc-linux-gnu 3789

$ python3.6 -m mypy --show-traceback tst.py 
/home/dstromberg/.local/lib/python3.6/site-packages/mypy/typeshed/stdlib/2and3/builtins.pyi: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.770
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "mypy/build.py", line 1918, in wrap_context
  File "mypy/build.py", line 2041, in parse_file
  File "mypy/build.py", line 766, in parse_file
  File "mypy/parse.py", line 25, in parse
  File "mypy/fastparse.py", line 163, in parse
  File "mypy/fastparse.py", line 316, in visit
  File "mypy/fastparse.py", line 478, in visit_Module
AttributeError: 'TypeIgnore' object has no attribute 'tag'
/home/dstromberg/.local/lib/python3.6/site-packages/mypy/typeshed/stdlib/2and3/builtins.pyi: : note: use --pdb to drop into pdb

**Comment by dan-stromberg** [comment]
This helped at the command line:
sudo python3 -m pip uninstall mypy mypy-extensions typed-ast typing-extensions

I got the list of things to uninstall using pepdeptree.

**Comment by dan-stromberg** [comment]
And doing the same for /usr/bin/python3.7 fixed things inside of PyCharm.

Thanks.
