### ISSUE TITLE
`dmypy --follow-imports=normal` on master crashes

### ISSUE THREAD

**Issue by vjpr** [python/mypy#8751]
I installed git master, and tried to use the new `dmypy --follow-imports-normal` feature on my codebase.

* Are you reporting a bug, or opening a feature request?

Bug

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

* What is the actual behavior/output?

* What is the behavior/output you expect?

* What are the versions of mypy and Python you are using?

dmypy 0.770+dev.3b279045634891533d9c992df6ccbc7189499a8c

Python 3.8.1

*  Do you see the same issue after installing mypy from Git master?

Its only a problem in Git master

* What are the mypy flags you are using? (For example --strict-optional)

```
dmypy run . -- --follow-imports=normal
```

* If mypy crashed with a traceback, please paste
  the full traceback below.

```
Daemon crashed!
Traceback (most recent call last):
  File "/Users/Vaughan/.pyenv/versions/3.8.1/lib/python3.8/site-packages/mypy/dmypy_server.py", line 223, in serve
    resp = self.run_command(command, data)
  File "/Users/Vaughan/.pyenv/versions/3.8.1/lib/python3.8/site-packages/mypy/dmypy_server.py", line 266, in run_command
    return method(self, **data)
  File "/Users/Vaughan/.pyenv/versions/3.8.1/lib/python3.8/site-packages/mypy/dmypy_server.py", line 325, in cmd_run
    return self.check(sources, is_tty, terminal_width)
  File "/Users/Vaughan/.pyenv/versions/3.8.1/lib/python3.8/site-packages/mypy/dmypy_server.py", line 387, in check
    messages = self.fine_grained_increment_follow_imports(sources)
  File "/Users/Vaughan/.pyenv/versions/3.8.1/lib/python3.8/site-packages/mypy/dmypy_server.py", line 562, in fine_grained_increment_follow_imports
    changed, new_files = self.find_reachable_changed_modules(
  File "/Users/Vaughan/.pyenv/versions/3.8.1/lib/python3.8/site-packages/mypy/dmypy_server.py", line 677, in find_reachable_changed_modules
    worklist.append(BuildSource(graph[dep].path,
KeyError: 'cryptography.hazmat.primitives.asymmetric.dh'
```

**Comment by ethanhs** [comment]
Could you share a bit more about what code this is checking?

**Comment by vjpr** [comment]
197 source files of company repo. It doesn't crash with `--follow-imports=error|skip`.

With `--follow-imports=error` there are about 60 errors about packages not being found.

**Comment by vjpr** [comment]
```
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import ciphers, hashes
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.serialization import (
    load_der_public_key,
    load_pem_private_key,
)
from cryptography.x509 import load_der_x509_certificate, load_pem_x509_certificate
```

**Comment by vjpr** [comment]
The error shows up sporadically for different packages.

**Comment by JukkaL** [comment]
@vjpr Can you check if this still happens with the latest mypy, which added support for `--follow-imports=normal` in dmypy?

**Comment by JukkaL** [comment]
Closing since there is no repro and no recent activity.
