### ISSUE TITLE
Internal error for TypedDict

### ISSUE THREAD

**Issue by arnimarj** [python/mypy#8920]
When running `mypy --strict --show-traceback ../bug.py` on the latest master for this:

```python
from typing_extensions import TypedDict


class SomeDict(TypedDict):
    key: str

    def foo(self) -> None:
        return None
```
... I get the following output:

```
../bug.py:7: error: Invalid statement in TypedDict definition; expected "field_name: field_type"
../bug.py: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.770+dev.273a86557e6e76acd52e6588230aa8e4ac5de532
Traceback (most recent call last):
  File "/home/arni/dohop/mypy/venv/bin/mypy", line 10, in <module>
    sys.exit(console_entry())
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/__main__.py", line 8, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/main.py", line 89, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/build.py", line 181, in build
    sources, options, alt_lib_path, flush_errors, fscache, stdout, stderr, extra_plugins
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/build.py", line 252, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/build.py", line 2626, in dispatch
    process_graph(graph, manager)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/build.py", line 2949, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/build.py", line 3041, in process_stale_scc
    mypy.semanal_main.semantic_analysis_for_scc(graph, scc, manager.errors)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/semanal_main.py", line 84, in semantic_analysis_for_scc
    check_type_arguments(graph, scc, errors)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/semanal_main.py", line 360, in check_type_arguments
    state.tree.accept(analyzer)
  File "/home/arni/.pyenv/versions/3.7.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/build.py", line 1919, in wrap_context
    yield
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/semanal_main.py", line 360, in check_type_arguments
    state.tree.accept(analyzer)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/nodes.py", line 295, in accept
    return visitor.visit_mypy_file(self)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/semanal_typeargs.py", line 39, in visit_mypy_file
    super().visit_mypy_file(o)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/traverser.py", line 35, in visit_mypy_file
    d.accept(self)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/nodes.py", line 940, in accept
    return visitor.visit_class_def(self)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/semanal_typeargs.py", line 50, in visit_class_def
    super().visit_class_def(defn)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/mixedtraverser.py", line 28, in visit_class_def
    super().visit_class_def(o)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/traverser.py", line 71, in visit_class_def
    o.defs.accept(self)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/nodes.py", line 1005, in accept
    return visitor.visit_block(self)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/semanal_typeargs.py", line 54, in visit_block
    super().visit_block(o)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/traverser.py", line 39, in visit_block
    s.accept(self)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/nodes.py", line 677, in accept
    return visitor.visit_func_def(self)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/traverser.py", line 54, in visit_func_def
    self.visit_func(o)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/semanal_typeargs.py", line 46, in visit_func
    super().visit_func(defn)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/mixedtraverser.py", line 23, in visit_func
    self.visit_optional_type(o.type)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/mixedtraverser.py", line 91, in visit_optional_type
    t.accept(self)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/types.py", line 1098, in accept
    return visitor.visit_callable_type(self)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/typetraverser.py", line 52, in visit_callable_type
    t.fallback.accept(self)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/types.py", line 794, in accept
    return visitor.visit_instance(self)
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/semanal_typeargs.py", line 70, in visit_instance
    for (i, arg), tvar in zip(enumerate(t.args), info.defn.type_vars):
  File "/home/arni/dohop/mypy/venv/lib/python3.7/site-packages/mypy/nodes.py", line 2660, in __getattribute__
    raise AssertionError(object.__getattribute__(self, 'msg'))
AssertionError: fallback can't be filled out until semanal
../bug.py: : note: use --pdb to drop into pdb
```

( I know the class method is non-sensical. I was re-factoring some code, and hadn't fully cleaned up the code when running mypy)

**Comment by JukkaL** [comment]
This also happens without using `--strict`.

**Comment by 97littleleaf11** [comment]
Should we still construct the class info even when `semanal_typeddict/analyze_typeddict_classdef_fields` has detected a TypedDict containing any invalid member?

**Comment by 97littleleaf11** [comment]
Related: https://github.com/python/mypy/issues/9280

**Comment by 97littleleaf11** [comment]
Fixed by https://github.com/python/mypy/pull/11126
Can we just close it?
