### ISSUE TITLE
Internal error: TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by gsalgado** [python/mypy#9188]
mypy HEAD (as well as 0.782) crashes with the following internal error whereas 0.740 (and earlier) works fine

Code in question is this: https://github.com/ethereum/trinity/blob/79b5e5318ce0679bff8b6eb8e17f21631d1b5eac/trinity/db/orm.py#L27

```
(trinity) salgado@t495~/src/snakecharmers/trinity (issue-1919) $ mypy --show-traceback -p trinity.db --config-file /home/salgado/src/snakecharmers/trinity/mypy.ini
/home/salgado/src/snakecharmers/trinity/trinity/db/orm.py:27: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.790+dev.a5455bd9f37825d24415e46a4d278d71502c9d07
Traceback (most recent call last):
  File "/home/salgado/virtualenvs/trinity/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/mypy/__main__.py", line 8, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/mypy/main.py", line 89, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/mypy/build.py", line 180, in build
    result = _build(
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/mypy/build.py", line 252, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/mypy/build.py", line 2626, in dispatch
    process_graph(graph, manager)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/mypy/build.py", line 2949, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/mypy/build.py", line 3041, in process_stale_scc
    mypy.semanal_main.semantic_analysis_for_scc(graph, scc, manager.errors)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/mypy/semanal_main.py", line 78, in semantic_analysis_for_scc
    process_top_levels(graph, scc, patches)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/mypy/semanal_main.py", line 199, in process_top_levels
    deferred, incomplete, progress = semantic_analyze_target(next_id, state,
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/mypy/semanal_main.py", line 326, in semantic_analyze_target
    analyzer.refresh_partial(refresh_node,
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/mypy/semanal.py", line 357, in refresh_partial
    self.refresh_top_level(node)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/mypy/semanal.py", line 368, in refresh_top_level
    self.accept(d)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/mypy/semanal.py", line 4691, in accept
    node.accept(self)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/mypy/nodes.py", line 1063, in accept
    return visitor.visit_assignment_stmt(self)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/mypy/semanal.py", line 1943, in visit_assignment_stmt
    self.apply_dynamic_class_hook(s)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/mypy/semanal.py", line 2194, in apply_dynamic_class_hook
    hook(DynamicClassDefContext(call, lval.name, self))
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/sqlmypy.py", line 156, in decl_info_hook
    add_metadata_var(ctx, info)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/sqlmypy.py", line 119, in add_metadata_var
    add_var_to_class('metadata', typ, info)
  File "/home/salgado/virtualenvs/trinity/lib/python3.8/site-packages/sqlmypy.py", line 81, in add_var_to_class
    var._fullname = info.fullname() + '.' + name
TypeError: 'str' object is not callable
/home/salgado/src/snakecharmers/trinity/trinity/db/orm.py:27: : note: use --pdb to drop into p
```

**Comment by gsalgado** [comment]
Nevermind, it was an issue in the sqlmypy plugin

**Comment by aviau** [comment]
Can you tell us what was the issue?

**Comment by gsalgado** [comment]
https://github.com/dropbox/sqlalchemy-stubs/issues/145
