### ISSUE TITLE
INTERNAL ERROR on `issubclass` assertion on unrelated class

### ISSUE THREAD

**Issue by lummax** [python/mypy#9198]
`mypy` version: `0.790+dev.65186ae1e23fd44f1d7e6aa2c4458bdf55640742` / `0.7.82` crashes on the following code (`0.761` has no issue with the code):

```python
class ClassA:
    def attribute(self):
        return None


class ClassB:
    attribute = None

    @classmethod
    def create(cls):
        assert not issubclass(cls, ClassA)

ClassB.create()
```

```
./build/dependencies/python3.7-venv/bin/mypy --show-traceback reproducer.py
```

<details>
<summary>Traceback:</summary>
<p>

```
reproducer.py:11: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.790+dev.65186ae1e23fd44f1d7e6aa2c4458bdf55640742
reproducer.py:11: : note: use --pdb to drop into pdb
Traceback (most recent call last):
  File "./build/dependencies/python3.7-venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/__main__.py", line 8, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/main.py", line 89, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/build.py", line 181, in build
    sources, options, alt_lib_path, flush_errors, fscache, stdout, stderr, extra_plugins
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/build.py", line 252, in _build
    graph = dispatch(sources, manager, stdout)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/build.py", line 2626, in dispatch
    process_graph(graph, manager)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/build.py", line 2949, in process_graph
    process_stale_scc(graph, scc, manager)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/build.py", line 3047, in process_stale_scc
    graph[id].type_check_first_pass()
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/build.py", line 2107, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/checker.py", line 294, in check_first_pass
    self.accept(d)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/checker.py", line 401, in accept
    stmt.accept(self)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/nodes.py", line 940, in accept
    return visitor.visit_class_def(self)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/checker.py", line 1724, in visit_class_def
    self.accept(defn.defs)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/checker.py", line 401, in accept
    stmt.accept(self)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/nodes.py", line 1005, in accept
    return visitor.visit_block(self)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/checker.py", line 1973, in visit_block
    self.accept(s)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/checker.py", line 401, in accept
    stmt.accept(self)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/nodes.py", line 767, in accept
    return visitor.visit_decorator(self)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/checker.py", line 3565, in visit_decorator
    self.check_func_item(e.func, name=e.func.name)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/checker.py", line 792, in check_func_item
    self.check_func_def(defn, typ, name)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/checker.py", line 975, in check_func_def
    self.accept(item.body)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/checker.py", line 401, in accept
    stmt.accept(self)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/nodes.py", line 1005, in accept
    return visitor.visit_block(self)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/checker.py", line 1973, in visit_block
    self.accept(s)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/checker.py", line 401, in accept
    stmt.accept(self)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/nodes.py", line 1154, in accept
    return visitor.visit_assert_stmt(self)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/checker.py", line 3304, in visit_assert_stmt
    true_map, else_map = self.find_isinstance_check(s.expr)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/checker.py", line 3967, in find_isinstance_check
    if_map, else_map = self.find_isinstance_check_helper(node)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/checker.py", line 4174, in find_isinstance_check_helper
    left, right = self.find_isinstance_check_helper(node.expr)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/checker.py", line 3995, in find_isinstance_check_helper
    return self.infer_issubclass_maps(node, expr, type_map)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/checker.py", line 4888, in infer_issubclass_maps
    yes_map, no_map = self.conditional_type_map_with_intersection(expr, vartype, type)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/checker.py", line 4928, in conditional_type_map_with_intersection
    intersection = self.intersect_instances([v, t], expr)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/checker.py", line 3781, in intersect_instances
    self.check_multiple_inheritance(info)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/checker.py", line 1852, in check_multiple_inheritance
    self.check_compatibility(name, base, base2, typ)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/checker.py", line 1911, in check_compatibility
    ok = is_equivalent(first_type, second_type)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/subtypes.py", line 153, in is_equivalent
    ignore_pos_arg_names=ignore_pos_arg_names)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/subtypes.py", line 97, in is_subtype
    ignore_promotions=ignore_promotions)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/subtypes.py", line 139, in _is_subtype
    ignore_promotions=ignore_promotions))
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/types.py", line 1786, in accept
    return visitor.visit_partial_type(self)
  File "XXX/build/dependencies/python3.7-venv/lib/python3.7/site-packages/mypy/subtypes.py", line 459, in visit_partial_type
    raise RuntimeError
RuntimeError: 
```
</p>
</details>

**Comment by ilevkivskyi** [comment]
This one is interesting. We didn't see partial type crashes in a while. Here the issue seems to be that we partial type (created by `None` assignment) still exists when we call ` check_multiple_inheritance()`.

cc @Michael0x2a who may have more context on this.

**Comment by 97littleleaf11** [comment]
> Here the issue seems to be that the partial type (created by `None` assignment) still exists when we call ` check_multiple_inheritance()`.

Yeah. The type of `classB.attribute` is stored as `partial None` in the symbol table.

**Comment by hauntsaninja** [comment]
This was fixed by https://github.com/python/mypy/pull/11134
