### ISSUE TITLE
mypy crashes with AttributeError

### ISSUE THREAD

**Issue by tdemin** [python/mypy#9280]
mypy v0.782 with Python 3.8 fails at checking [this file](https://git.tdem.in/tdemin/amber/src/branch/refactoring/20200627_newapi/project_amber/models.py):

```
% mypy --show-traceback
project_amber/models.py: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.782
Traceback (most recent call last):
  File "/home/tdemin/.cache/pypoetry/virtualenvs/project-amber-255IN1jW-py3.8/bin/mypy", line 10, in <module>
    sys.exit(console_entry())
  File "mypy/build.py", line 1919, in wrap_context
  File "mypy/semanal_main.py", line 360, in check_type_arguments
  File "mypy/nodes.py", line 294, in accept
  File "mypy/semanal_typeargs.py", line 39, in visit_mypy_file
  File "mypy/traverser.py", line 35, in visit_mypy_file
  File "mypy/nodes.py", line 939, in accept
  File "mypy/semanal_typeargs.py", line 50, in visit_class_def
  File "mypy/mixedtraverser.py", line 28, in visit_class_def
  File "mypy/traverser.py", line 71, in visit_class_def
  File "mypy/nodes.py", line 1004, in accept
  File "mypy/semanal_typeargs.py", line 54, in visit_block
  File "mypy/traverser.py", line 39, in visit_block
  File "mypy/nodes.py", line 766, in accept
  File "mypy/traverser.py", line 76, in visit_decorator
  File "mypy/nodes.py", line 676, in accept
  File "mypy/traverser.py", line 54, in visit_func_def
  File "mypy/semanal_typeargs.py", line 46, in visit_func
  File "mypy/mixedtraverser.py", line 23, in visit_func
  File "mypy/mixedtraverser.py", line 91, in visit_optional_type
  File "mypy/types.py", line 1098, in accept
  File "mypy/typetraverser.py", line 52, in visit_callable_type
  File "mypy/types.py", line 794, in accept
  File "mypy/semanal_typeargs.py", line 70, in visit_instance
AttributeError: attribute 'defn' of 'TypeInfo' undefined
project_amber/models.py: : note: use --pdb to drop into pdb
```

The output changes when running mypy v0.790 from git master with system Python 3.8.5:

```
project_amber/models.py: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.790+dev.5e9682143720263466f0aaed1924ccb218160ee0
Traceback (most recent call last):
  File "/usr/bin/mypy", line 33, in <module>
    sys.exit(load_entry_point('mypy==0.790+dev.5e9682143720263466f0aaed1924ccb218160ee0', 'console_scripts', 'mypy')())
  File "/usr/lib/python3.8/site-packages/mypy/__main__.py", line 8, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/usr/lib/python3.8/site-packages/mypy/main.py", line 89, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/usr/lib/python3.8/site-packages/mypy/build.py", line 180, in build
    result = _build(
  File "/usr/lib/python3.8/site-packages/mypy/build.py", line 252, in _build
    graph = dispatch(sources, manager, stdout)
  File "/usr/lib/python3.8/site-packages/mypy/build.py", line 2628, in dispatch
    process_graph(graph, manager)
  File "/usr/lib/python3.8/site-packages/mypy/build.py", line 2951, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/usr/lib/python3.8/site-packages/mypy/build.py", line 3043, in process_stale_scc
    mypy.semanal_main.semantic_analysis_for_scc(graph, scc, manager.errors)
  File "/usr/lib/python3.8/site-packages/mypy/semanal_main.py", line 84, in semantic_analysis_for_scc
    check_type_arguments(graph, scc, errors)
  File "/usr/lib/python3.8/site-packages/mypy/semanal_main.py", line 360, in check_type_arguments
    state.tree.accept(analyzer)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3.8/site-packages/mypy/build.py", line 1920, in wrap_context
    yield
  File "/usr/lib/python3.8/site-packages/mypy/semanal_main.py", line 360, in check_type_arguments
    state.tree.accept(analyzer)
  File "/usr/lib/python3.8/site-packages/mypy/nodes.py", line 295, in accept
    return visitor.visit_mypy_file(self)
  File "/usr/lib/python3.8/site-packages/mypy/semanal_typeargs.py", line 39, in visit_mypy_file
    super().visit_mypy_file(o)
  File "/usr/lib/python3.8/site-packages/mypy/traverser.py", line 35, in visit_mypy_file
    d.accept(self)
  File "/usr/lib/python3.8/site-packages/mypy/nodes.py", line 940, in accept
    return visitor.visit_class_def(self)
  File "/usr/lib/python3.8/site-packages/mypy/semanal_typeargs.py", line 50, in visit_class_def
    super().visit_class_def(defn)
  File "/usr/lib/python3.8/site-packages/mypy/mixedtraverser.py", line 28, in visit_class_def
    super().visit_class_def(o)
  File "/usr/lib/python3.8/site-packages/mypy/traverser.py", line 71, in visit_class_def
    o.defs.accept(self)
  File "/usr/lib/python3.8/site-packages/mypy/nodes.py", line 1005, in accept
    return visitor.visit_block(self)
  File "/usr/lib/python3.8/site-packages/mypy/semanal_typeargs.py", line 54, in visit_block
    super().visit_block(o)
  File "/usr/lib/python3.8/site-packages/mypy/traverser.py", line 39, in visit_block
    s.accept(self)
  File "/usr/lib/python3.8/site-packages/mypy/nodes.py", line 767, in accept
    return visitor.visit_decorator(self)
  File "/usr/lib/python3.8/site-packages/mypy/traverser.py", line 76, in visit_decorator
    o.func.accept(self)
  File "/usr/lib/python3.8/site-packages/mypy/nodes.py", line 677, in accept
    return visitor.visit_func_def(self)
  File "/usr/lib/python3.8/site-packages/mypy/traverser.py", line 54, in visit_func_def
    self.visit_func(o)
  File "/usr/lib/python3.8/site-packages/mypy/semanal_typeargs.py", line 46, in visit_func
    super().visit_func(defn)
  File "/usr/lib/python3.8/site-packages/mypy/mixedtraverser.py", line 23, in visit_func
    self.visit_optional_type(o.type)
  File "/usr/lib/python3.8/site-packages/mypy/mixedtraverser.py", line 91, in visit_optional_type
    t.accept(self)
  File "/usr/lib/python3.8/site-packages/mypy/types.py", line 1098, in accept
    return visitor.visit_callable_type(self)
  File "/usr/lib/python3.8/site-packages/mypy/typetraverser.py", line 52, in visit_callable_type
    t.fallback.accept(self)
  File "/usr/lib/python3.8/site-packages/mypy/types.py", line 794, in accept
    return visitor.visit_instance(self)
  File "/usr/lib/python3.8/site-packages/mypy/semanal_typeargs.py", line 70, in visit_instance
    for (i, arg), tvar in zip(enumerate(t.args), info.defn.type_vars):
  File "/usr/lib/python3.8/site-packages/mypy/nodes.py", line 2660, in __getattribute__
    raise AssertionError(object.__getattribute__(self, 'msg'))
AssertionError: fallback can't be filled out until semanal
```

mypy is set up with `setup.cfg` as follows:

```
[mypy]
files = project_amber
namespace_packages = true
[mypy-bcrypt.*]
ignore_missing_imports = true
[mypy-flask_sqlalchemy.*]
ignore_missing_imports = true
[mypy-flask_cors.*]
ignore_missing_imports = true
```

The part that confuses mypy appears to be this class (without `type: ignore` mypy gives out a typing error `Invalid statement in TypedDict definition; expected "field_name: field_type"`, but doesn't crash):

```py
from typing import TypedDict, Any, cast

class JSONTask(TypedDict, total=False):
    ...
    @staticmethod  # type: ignore
    def validate(d: Any) -> bool:
        ...
        return True
```

I don't think this is how it should be, as Python works just fine with this code:

![image](https://user-images.githubusercontent.com/26599554/89706320-f010e580-d97d-11ea-8c39-517377d949a4.png)

**Comment by tdemin** [comment]
I just noticed that the file I linked uses `typing.cast` the wrong way (should be `cast(dict, d)`).

This doesn't influence this error in any way, correcting it and trimming `validate()` to `return True` will result in the same error.

**Comment by gvanrossum** [comment]
The point remains that according to PEP 589 you cannot have anything but field definitions in a subclass of TypedDict. That makes this crash low priority. (Though if you submit a reasonable fix we’ll consider it.)

**Comment by 97littleleaf11** [comment]
mypy doesn't crash on this now. however the error msg is not clear yet.

**Comment by AlexWaygood** [comment]
> mypy doesn't crash on this now. 

I can still [reproduce the crash](https://mypy-play.net/?mypy=latest&python=3.10&flags=show-traceback%2Cwarn-unreachable&gist=8b3362330f461ba4e1da2c1b1af1d0fa) on 0.941

**Comment by JukkaL** [comment]
I can't reproduce the crash using 0.961, but it crashes on 0.941. The crash seems to be fixed.
