### ISSUE TITLE
BUG: AttributeError: 'TypeIgnore' object has no attribute 'tag'

### ISSUE THREAD

**Issue by albkurIV** [python/mypy#9292]
Using python 3.5.4 in an Anaconda Environment but I did not tried master, due I need an official release for that. 
In jenkins I rollback the environment to rev=0 and update mypy (but with pip due to the python3.5.4)

I call mypy with (there are a lot of files I include this way, just listed 3 of them for better overview): 
```
python -m mypy C:/jenkins_workspace/workspace/MyProject/Build/GUI_compiled/communication.py C:/jenkins_workspace/workspace/MyProject/Build/GUI_compiled/tests/notebook/test_component_controller.py C:/jenkins_workspace/workspace/MyProject/Build/GUI_compiled/tests/notebook/test_configuration.py --config-file=mypy.ini --show-traceback
```

```
Please report a bug at https://github.com/python/mypy/issues
version: 0.782
Traceback (most recent call last):
  File "C:\Anaconda3\envs\myEnv\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\envs\myEnv\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "mypy\build.py", line 1919, in wrap_context
  File "mypy\build.py", line 2003, in parse_file
  File "mypy\build.py", line 771, in parse_file
  File "mypy\parse.py", line 25, in parse
  File "mypy\fastparse.py", line 165, in parse
  File "mypy\fastparse.py", line 319, in visit
  File "mypy\fastparse.py", line 481, in visit_Module
AttributeError: 'TypeIgnore' object has no attribute 'tag'
```

mypy.ini
```
[mypy]
python_version = 3.5
allow_untyped_globals=True
allow_redefinition  = True
warn_unused_configs = True
disallow_untyped_calls = False
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = False
disallow_untyped_decorators = False
warn_unused_ignores = True
ignore_errors = False
follow_imports_for_stubs = False

[mypy-PIL.*]
ignore_missing_imports = True

[mypy-zmq.*]
ignore_missing_imports = True

[mypy-xlwt.*]
ignore_missing_imports = True
```

**Comment by albkurIV** [comment]
I solved it by performing:
```
pip uninstall mypy mypy-extensions typed-ast typing-extensions
```

and reinstalling versions:
```
    - mypy==0.782
    - mypy-extensions==0.4.3
    - typed-ast==1.4.1
    - typing-extensions==3.7.4.2
```

but it seems as a relict from previous versions.

**Comment by gvanrossum** [comment]
Looks like something out of control of the mypy project.
