### ISSUE TITLE
'NoneType' object has no attribute 'type' mypy v0.620

### ISSUE THREAD

**Issue by compwron** [python/mypy#9295]
* Are you reporting a bug, or opening a feature request?
Bug

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.
```
from os import path
try:
    from dotenv import load_dotenv
    dotenv_path = path.join(path.dirname(__file__), '../..', '.env')
    if path.exists(dotenv_path):
        load_dotenv(dotenv_path)
except ImportError:
    pass
```

* What is the actual behavior/output?
* If mypy crashed with a traceback, please paste
  the full traceback below.
```
$ mypy . --ignore-missing-imports --show-traceback
./config/__init__.py:6: error: INTERNAL ERROR -- please report a bug at https://github.com/python/mypy/issues version: 0.620
Traceback (most recent call last):
  File "/Users/me/.pyenv/versions/reponame/bin/mypy", line 11, in <module>
    sys.exit(console_entry())
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/__main__.py", line 7, in console_entry
    main(None)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/main.py", line 91, in main
    res = type_check_only(sources, bin_dir, options, flush_errors, fscache)  # noqa
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/main.py", line 148, in type_check_only
    fscache=fscache)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/build.py", line 177, in build
    flush_errors, fscache)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/build.py", line 350, in _build
    graph = dispatch(sources, manager)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/build.py", line 2560, in dispatch
    process_graph(graph, manager)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/build.py", line 2853, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/build.py", line 2976, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/build.py", line 2151, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/checker.py", line 253, in check_first_pass
    self.accept(d)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/checker.py", line 352, in accept
    stmt.accept(self)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/nodes.py", line 1093, in accept
    return visitor.visit_try_stmt(self)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/checker.py", line 2508, in visit_try_stmt
    self.visit_try_without_finally(s, try_frame=bool(s.finally_body))
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/checker.py", line 2543, in visit_try_without_finally
    self.accept(s.body)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/checker.py", line 352, in accept
    stmt.accept(self)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/nodes.py", line 873, in accept
    return visitor.visit_block(self)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/checker.py", line 1514, in visit_block
    self.accept(s)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/checker.py", line 352, in accept
    stmt.accept(self)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/nodes.py", line 1054, in accept
    return visitor.visit_if_stmt(self)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/checker.py", line 2410, in visit_if_stmt
    self.accept(b)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/checker.py", line 352, in accept
    stmt.accept(self)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/nodes.py", line 873, in accept
    return visitor.visit_block(self)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/checker.py", line 1514, in visit_block
    self.accept(s)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/checker.py", line 352, in accept
    stmt.accept(self)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/nodes.py", line 888, in accept
    return visitor.visit_expression_stmt(self)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/checker.py", line 2306, in visit_expression_stmt
    self.expr_checker.accept(s.expr, allow_none_return=True, always_allow_any=True)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/checkexpr.py", line 2856, in accept
    typ = self.visit_call_expr(node, allow_none_return=True)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/checkexpr.py", line 308, in visit_call_expr
    ret_type = self.check_call_expr_with_callee_type(callee_type, e, fullname, object_type)
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/checkexpr.py", line 545, in check_call_expr_with_callee_type
    object_type=object_type)[0]
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/checkexpr.py", line 584, in check_call
    if (callee.is_type_obj() and callee.type_object().is_abstract
  File "/Users/me/.pyenv/versions/3.7.0/envs/reponame/lib/python3.7/site-packages/mypy/types.py", line 804, in is_type_obj
    return self.fallback.type.is_metaclass()
AttributeError: 'NoneType' object has no attribute 'type'
./config/__init__.py:6: : note: use --pdb to drop into pdb
```

* What are the versions of mypy and Python you are using?
  Do you see the same issue after installing mypy from Git master?
`mypy==0.620`
Python 3.7.0

* What are the mypy flags you are using? (For example --strict-optional)
`mypy . --ignore-missing-imports --show-traceback`

**Comment by hauntsaninja** [comment]
Closing, since that mypy version is over two years old. Feel free to reopen if you can repro with a newer version of mypy.

**Comment by ethanhs** [comment]
FWIW I cannot repro this on 0.782
