### ISSUE TITLE
Internal error when handling generic class

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/mypy#9448]
I have some code which includes these lines:
```
_From = TypeVar("_From", date, None)
_Until = TypeVar("_Until", date, None)

class TimePeriod(ClauseElement, Generic[_From, _Until]):
    @classmethod
    def day(cls, day: date):
        return cls(day, day)  # Expected None?

    def __init__(self, from_day: _From = None, until_day: _Until = None, column="date"):
        if from_day and until_day and from_day > until_day:  # Right operand is never evaluated?
```

It's giving me several errors that don't make sense to me, plus hitting an internal error as well:
```
logic/analytics/time_period.py:38: error: Argument 1 to "TimePeriod" has incompatible type "date"; expected "None"  [arg-type]
logic/analytics/time_period.py:38: error: Argument 2 to "TimePeriod" has incompatible type "date"; expected "None"  [arg-type]
logic/analytics/time_period.py:47: error: Right operand of 'and' is never evaluated  [unreachable]
logic/analytics/time_period.py:56: error: Right operand of 'and' is never evaluated  [unreachable]
logic/analytics/time_period.py:51: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.782
Traceback (most recent call last):
  File "mypy/checker.py", line 401, in accept
  File "mypy/nodes.py", line 1062, in accept
  File "mypy/checker.py", line 2011, in visit_assignment_stmt
  File "mypy/checker.py", line 2150, in check_assignment
  File "mypy/checker.py", line 2821, in infer_variable_type
  File "mypy/sametypes.py", line 31, in is_same_type
  File "mypy/types.py", line 1786, in accept
  File "mypy/sametypes.py", line 162, in visit_partial_type
RuntimeError:
logic/analytics/time_period.py:51: : note: use --pdb to drop into pdb
```

Why does it seem to think the value will always be None? Am I misunderstanding TypeVar?

The end goal is to have some methods like:
`def foo(self: TimePeriod[date, date]):`
which can only be used if the class was initialised without None.

**Comment by gvanrossum** [comment]
I cannot reproduce the crash with just the fragment you show. I also don't see the errors about "right argument not evaluated" . Is the code open source? What mypy flags did you specify?

(And yes, you probably misunderstand some aspect of generics, but I haven't figured out which yet. :-)

**Comment by Dreamsorcerer** [comment]
Ah, you're right, it only occurs when assigning the values to an attribute. This complete piece of code seems to still trigger it for me:

```
from datetime import date, datetime, time, timedelta
from typing import Generic, Iterable, Optional, TypeVar

from sqlalchemy.sql.expression import ClauseElement


_From = TypeVar("_From", date, None)
_Until = TypeVar("_Until", date, None)


class TimePeriod(ClauseElement, Generic[_From, _Until]):
    @classmethod
    def day(cls, day: date):
        return cls(day, day)

    def __init__(self, from_day: _From = None, until_day: _Until = None, column="date"):

        if from_day and until_day and from_day > until_day:
            raise ValueError("Start date needs to precede end date: from {} to {}".format(from_day, until_day))

        self.from_day = from_day
        self.until_day = until_day
```

Mypy config looks like:
```
[mypy]
# db-operations/ and subfolders need a rename.
check_untyped_defs = True
disallow_any_generics = True
files = hooks/, integrations/, logic/, models/, ops/, test/, web/, conftest.py, cr-insert.py, environment.py, kopernio_http.py, run_local.py, runserver.py, settings.py
follow_imports_for_stubs = True
platform = linux
plugins = sqlmypy
show_error_codes = True
strict_equality = True
warn_no_return = True
warn_redundant_casts = True
warn_return_any = True
warn_unused_configs = True
warn_unused_ignores = True
warn_unreachable = True
```

**Comment by Dreamsorcerer** [comment]
The approach I've been trying to use, is based on the Mypy docs here: https://mypy.readthedocs.io/en/latest/more_types.html#restricted-methods-in-generic-classes

**Comment by gvanrossum** [comment]
Minimal example for the crash:
```
 from typing import Generic, TypeVar

T = TypeVar("T", int, str)
S = TypeVar("S", int, None)

class C(Generic[T, S]):
    def func(self, arg: S):
        self.attr = arg  # Crash here
```
Note that `T` needs to be present and needs to have two upper bounds, even though it is unused.

**Comment by gvanrossum** [comment]
Also, regarding the other errors, if I take your example code except for the last line, and use your mypy.ini, I immediately get a complaint about the mysql plugin. If I comment out that line in the ini file, I get
```
u.py:4: error: Cannot find implementation or library stub for module named 'sqlalchemy.sql.expression'  [import]
u.py:4: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
u.py:14: error: Argument 1 to "TimePeriod" has incompatible type "date"; expected "None"  [arg-type]
u.py:14: error: Argument 2 to "TimePeriod" has incompatible type "date"; expected "None"  [arg-type]
u.py:18: error: Right operand of 'and' is never evaluated  [unreachable]
```
The errors on line 14 (about `cls(day, day)`) seem somewhat understandable, since in a class method you don't know what the typevars are.

The error on line 18 (about `and`) seems wrong -- it looks like it believes that `from_day` and `until_day` are always false (removing the default argument value has no effect on this). If I change these to `from_day is not None and until_day is not None and ...` I get an additional complaint that the left operand is always true. This looks like a bug in shortcutting using type variables.

**Comment by gvanrossum** [comment]
PS. You may want to create new issues about the regular errors if you disagree -- let's use this issue for the crash.

**Comment by ethanhs** [comment]
Neither Guido's nor Dreamsorcerers's minimal reproductions crash on master.

**Comment by Dreamsorcerer** [comment]
Also fine on latest stable release. Thanks.
