### ISSUE TITLE
Internal error when identifier in except clause shadows imported module name

### ISSUE THREAD

**Issue by ethframe** [python/mypy#9615]
**Crash Report**

Mypy crashes while analysing a `try` statement in which one of the `except` clauses uses the same identifier as one of the imported modules.

**Traceback**

```
bug.py:3: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.790
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "mypy\checker.py", line 401, in accept
  File "mypy\nodes.py", line 1235, in accept
  File "mypy\checker.py", line 3350, in visit_try_stmt
  File "mypy\checker.py", line 3403, in visit_try_without_finally
  File "mypy\checker.py", line 2053, in check_assignment
  File "mypy\checker.py", line 2799, in check_lvalue
TypeError: mypy.nodes.Var object expected; got mypy.nodes.MypyFile
bug.py:3: : note: use --pdb to drop into pdb
```

**To Reproduce**

bug.py contents:

```python
import re

try:
    pass
except Exception as re:
    pass
```

Command: `mypy bug.py`

**Your Environment**

- Mypy version used: 0.790
- Mypy command-line flags: none
- Mypy configuration options from `mypy.ini` (and other config files): none
- Python version used: 3.6.8
- Operating system and version: Windows 10 2004

**Comment by andrewgodwin** [comment]
It's worth noting that a very similar problem occurs when the identifier in the `except` clause is declared `global`, but that identifier is not declared in the outside scope:

```
# Note that e is not defined out here
def main()
    global e
    try:
        ...
    except Exception as e:
        pass
```

This results in `TypeError: mypy.nodes.Var object expected; got None`
