### ISSUE TITLE
Last release of mypy that supports python3.4 is broken

### ISSUE THREAD

**Issue by hackaugusto** [python/mypy#9641]
I totally understand if no package would be release just to make `pip install mypy` work. Just in case this issue is found by somebody else, [the blog documents that support was dropped at 0.700](https://mypy-lang.blogspot.com/2019/04/mypy-0700-released-up-to-4x-faster.html), `pip install mypy==0.670` is the last working release of mypy for py3.4

**Bug Report**

As the title says

**To Reproduce**

```sh
cd /tmp
python3.4 -m venv test
source ./test/bin/activate
pip install mypy # this installs mypy-0.720
mypy # raises the exception bellow
```
```python
Traceback (most recent call last):
  File "/tmp/test/bin/mypy", line 7, in <module>
    from mypy.__main__ import console_entry
  File "/tmp/test/lib64/python3.4/site-packages/mypy/__main__.py", line 4, in <module>
    from mypy.main import main
  File "/tmp/test/lib64/python3.4/site-packages/mypy/main.py", line 12, in <module>
    from mypy import build
  File "/tmp/test/lib64/python3.4/site-packages/mypy/build.py", line 56, in <module>
    from mypy.plugins.default import DefaultPlugin
  File "/tmp/test/lib64/python3.4/site-packages/mypy/plugins/default.py", line 266
    return UnionType.make_simplified_union([*value_types, ctx.arg_types[1][0]])
                                                       ^
SyntaxError: can use starred expression only as assignment target
```

**Expected Behavior**

It would just be nice to be able to install mypy on an old venv.

**Comment by astrojuanlu** [comment]
Duplicate: https://github.com/python/mypy/issues/7221

**Comment by JelleZijlstra** [comment]
Python 3.4's end of life was in March of 2019. We're not going to fix it.
