### ISSUE TITLE
Module has no attribute "__cached__"

### ISSUE THREAD

**Issue by asottile** [python/mypy#9726]
**Bug Report**

Modules have a `__cached__` attribute which points at the pyc location.  mypy does not understand this attribute

Here's an example bit of code:

```python
import copyreg
print(copyreg.__cached__)

OUTPUT = '''\
/usr/lib/python3.8/__pycache__/copyreg.cpython-38.pyc
'''
```

**To Reproduce**

(Write your steps here:)

1. Run mypy against the sample file

**Expected Behavior**

I expect no errors

**Actual Behavior**

```console
$ mypy t.py
t.py:2: error: Module has no attribute "__cached__"
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

- **`sys.version`**: `'3.8.5 (default, Jul 28 2020, 12:59:40) \n[GCC 9.3.0]'`
- **`os.name`**: `'posix'`
- **`sys.platform`**: `'linux'`
- **`platform.system()`**: `'Linux'`
- **`platform.python_implementation()`**: `'CPython'`
- **`sys.implementation.name`**: `'cpython'`
- **`sysconfig.get_platform()`**: `'linux-x86_64'`

```console
$ mypy --version
mypy 0.790
```

**Comment by JelleZijlstra** [comment]
Sounds like we should just add this to `types.ModuleType` in typeshed?

**Comment by asottile** [comment]
so, the problem is I don't think all modules get this attribute 🤔 -- this might make it similar to the problem with `__path__` as well

for example namespace packages don't get it:

```
$ mkdir x
$ python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import x
>>> x.__cached__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'x' has no attribute '__cached__'
```

also I don't think native modules get this either:

```console
$ python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import _yaml
>>> _yaml.__cached__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module '_yaml' has no attribute '__cached__'
```
