### ISSUE TITLE
IndexError in analyze_super

### ISSUE THREAD

**Issue by gvanrossum** [python/mypy#991]
I don't know what the source was, this happened a minute into analyzing 600+ files. How to debug this further?
```
Traceback (most recent call last):
  File "/Users/guido/v3/bin/mypy", line 6, in <module>
    main(__file__)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/main.py", line 49, in main
    type_check_only(sources, bin_dir, options)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/main.py", line 92, in type_check_only
    python_path=options.python_path)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/build.py", line 197, in build
    result = manager.process(initial_states)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/build.py", line 379, in process
    next.process()
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/build.py", line 849, in process
    self.type_checker().visit_file(self.tree, self.tree.path)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/checker.py", line 371, in visit_file
    self.accept(d)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/checker.py", line 378, in accept
    typ = node.accept(self)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/nodes.py", line 473, in accept
    return visitor.visit_class_def(self)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/checker.py", line 866, in visit_class_def
    self.accept(defn.defs)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/checker.py", line 378, in accept
    typ = node.accept(self)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/nodes.py", line 514, in accept
    return visitor.visit_block(self)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/checker.py", line 939, in visit_block
    self.accept(s)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/checker.py", line 378, in accept
    typ = node.accept(self)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/nodes.py", line 370, in accept
    return visitor.visit_func_def(self)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/checker.py", line 431, in visit_func_def
    self.check_func_item(defn, name=defn.name())
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/checker.py", line 464, in check_func_item
    self.check_func_def(defn, typ, name)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/checker.py", line 545, in check_func_def
    self.accept_in_frame(item.body)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/checker.py", line 391, in accept_in_frame
    answer = self.accept(node, type_context)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/checker.py", line 378, in accept
    typ = node.accept(self)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/nodes.py", line 514, in accept
    return visitor.visit_block(self)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/checker.py", line 939, in visit_block
    self.accept(s)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/checker.py", line 378, in accept
    typ = node.accept(self)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/nodes.py", line 528, in accept
    return visitor.visit_expression_stmt(self)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/checker.py", line 1305, in visit_expression_stmt
    self.accept(s.expr)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/checker.py", line 378, in accept
    typ = node.accept(self)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/nodes.py", line 973, in accept
    return visitor.visit_call_expr(self)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/checker.py", line 1741, in visit_call_expr
    return self.expr_checker.visit_call_expr(e)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/checkexpr.py", line 113, in visit_call_expr
    self.accept(e.callee)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/checkexpr.py", line 1324, in accept
    return self.chk.accept(node, context)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/checker.py", line 378, in accept
    typ = node.accept(self)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/nodes.py", line 1180, in accept
    return visitor.visit_super_expr(self)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/checker.py", line 1816, in visit_super_expr
    return self.expr_checker.visit_super_expr(e)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/checkexpr.py", line 1194, in visit_super_expr
    t = self.analyze_super(e, False)
  File "/Users/guido/v3/lib/python3.5/site-packages/mypy/checkexpr.py", line 1204, in analyze_super
    e.info.mro[1])
IndexError: list index out of range
```

**Comment by JukkaL** [comment]
You can add a print to `visit_super_expr` in `mypy/checker.py` to print the line number of the super expression object where this fails (`e.line`). You can also get the file path from `self.errors.file`. That should give you the source of the failure.

We should probably do this automatically when there is an uncaught exception. I think `TypeChecker.accept` could catch exceptions and print out context or something.

**Comment by gvanrossum** [comment]
Annoyingly, once this started crashing I haven't been able to get it to not crash. :-(

**Comment by JukkaL** [comment]
Now mypy should give file and line number information on a crash in type checker.

**Comment by gvanrossum** [comment]
Closing, there's not enough information here to repro it, and we've had a bunch of updates to the mro code.
