### ISSUE TITLE
INTERNAL ERROR running against a Trio PR

### ISSUE THREAD

**Issue by altendky** [python/mypy#9967]
**Crash Report**

I apologize but I don't know which change I made that triggered this.  I was quickly reworking to `_Fn = TypeVar("_Fn", bound=Callable[..., Any])` a few places from `_F` and `_C` and maybe more before and during that and then the crash and then kids and lunch and...  `:[`

Edit: Here is a patch that makes the internal error go away.

```diff
diff --git a/trio/_core/_run.py b/trio/_core/_run.py
index 114a5194..9e95816c 100644
--- a/trio/_core/_run.py
+++ b/trio/_core/_run.py
@@ -80,7 +80,7 @@ DEADLINE_HEAP_MIN_PRUNE_THRESHOLD = 1000
 
 _NO_SEND = object()
 
-_Fn = TypeVar("_fn", bound=Callable[..., Any])
+_Fn = TypeVar("_Fn", bound=Callable[..., Any])
 
 
 # Decorator to mark methods public. This does nothing by itself, but
```

**Traceback**

```
trio/_core/_run.py:83: error: String argument 1 '_fn' to TypeVar(...) does not match variable name '_Fn'  [misc]
trio/_core/_run.py:83: error: Argument "bound" to "TypeVar" has incompatible type "object"; expected "Union[None, Type[Any], str]"  [arg-type]
trio/_core/_run.py:88: error: Variable "trio._core._run._Fn" is not valid as a type  [valid-type]
trio/_core/_run.py:88: note: See https://mypy.readthedocs.io/en/latest/common_issues.html#variables-vs-type-aliases
trio/_threads.py:253: error: Name '_AF' is not defined  [name-defined]
trio/_threads.py:291: error: Name 'unprotected_afn' already defined on line 289  [no-redef]
trio/_socket.py:304: error: Type of decorated function contains type "Any" ("Callable[[VarArg(Any), KwArg(Any)], Any]")  [misc]
trio/_socket.py:595: error: Signature of "family" incompatible with supertype "SocketType"  [override]
trio/_socket.py:599: error: Signature of "type" incompatible with supertype "SocketType"  [override]
trio/_socket.py:606: error: Signature of "proto" incompatible with supertype "SocketType"  [override]
trio/_socket.py:610: error: Signature of "did_shutdown_SHUT_WR" incompatible with supertype "SocketType"  [override]
trio/_socket.py:926: error: Type of decorated function contains type "Any" ("Callable[[_SocketType, VarArg(Any)], Any]")  [misc]
trio/_socket.py:945: error: Type of decorated function contains type "Any" ("Callable[[_SocketType, VarArg(Any)], Any]")  [misc]
/home/altendky/repos/trio/tmp/trio/trio/_core/_run.py:1438: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.810+dev.37d29fcb30dce646573b487f2c9375cee457724c
Traceback (most recent call last):
  File "/home/altendky/repos/trio/tmp/trio/venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/main.py", line 90, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/build.py", line 179, in build
    result = _build(
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/build.py", line 253, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/build.py", line 2632, in dispatch
    process_graph(graph, manager)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/build.py", line 2958, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/build.py", line 3056, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/build.py", line 2130, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/checker.py", line 294, in check_first_pass
    self.accept(d)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/checker.py", line 401, in accept
    stmt.accept(self)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/nodes.py", line 950, in accept
    return visitor.visit_class_def(self)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/checker.py", line 1723, in visit_class_def
    self.accept(defn.defs)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/checker.py", line 401, in accept
    stmt.accept(self)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/nodes.py", line 1015, in accept
    return visitor.visit_block(self)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/checker.py", line 1972, in visit_block
    self.accept(s)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/checker.py", line 401, in accept
    stmt.accept(self)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/nodes.py", line 526, in accept
    return visitor.visit_overloaded_func_def(self)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/checker.py", line 434, in visit_overloaded_func_def
    self._visit_overloaded_func_def(defn)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/checker.py", line 461, in _visit_overloaded_func_def
    self.check_overlapping_overloads(defn)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/checker.py", line 482, in check_overlapping_overloads
    assert isinstance(inner_type, CallableType)
AssertionError: 
/home/altendky/repos/trio/tmp/trio/trio/_core/_run.py:1438: : note: use --pdb to drop into pdb
```

<details> <summary>Full session</summary>

```console
$ git clone https://github.com/altendky/trio
Cloning into 'trio'...
remote: Enumerating objects: 195, done.
remote: Counting objects: 100% (195/195), done.
remote: Compressing objects: 100% (144/144), done.
remote: Total 18530 (delta 89), reused 98 (delta 51), pack-reused 18335
Receiving objects: 100% (18530/18530), 5.69 MiB | 8.98 MiB/s, done.
Resolving deltas: 100% (13681/13681), done.
```
```console
$ cd trio
```
```console
$ git checkout 484f13f124f614cde356b50dbbf53f29731dcfc0
Note: switching to '484f13f124f614cde356b50dbbf53f29731dcfc0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 484f13f1 use present mypy master
```
```console
$ python3.9 -m venv venv
```
```console
$ venv/bin/python --version --version
Python 3.9.1 (default, Jan  6 2021, 10:22:00) 
[GCC 9.3.0]
```
```console
$ venv/bin/python -m pip install --upgrade pip setuptools wheel
Collecting pip
  Using cached pip-21.0-py3-none-any.whl (1.5 MB)
Collecting setuptools
  Using cached setuptools-52.0.0-py3-none-any.whl (784 kB)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: pip, setuptools, wheel
  Attempting uninstall: pip
    Found existing installation: pip 20.2.3
    Uninstalling pip-20.2.3:
      Successfully uninstalled pip-20.2.3
  Attempting uninstall: setuptools
    Found existing installation: setuptools 49.2.1
    Uninstalling setuptools-49.2.1:
      Successfully uninstalled setuptools-49.2.1
Successfully installed pip-21.0 setuptools-52.0.0 wheel-0.36.2
```
```console
$ venv/bin/python -m pip install --requirement test-requirements.txt
Collecting mypy@ git+https://github.com/python/mypy@37d29fcb30dce646573b487f2c9375cee457724c
  Cloning https://github.com/python/mypy (to revision 37d29fcb30dce646573b487f2c9375cee457724c) to /tmp/pip-install-p45zbfzu/mypy_99b38262e2ca42e78859b9d1be71322d
  Running command git clone -q https://github.com/python/mypy /tmp/pip-install-p45zbfzu/mypy_99b38262e2ca42e78859b9d1be71322d
  Running command git rev-parse -q --verify 'sha^37d29fcb30dce646573b487f2c9375cee457724c'
  Running command git fetch -q https://github.com/python/mypy 37d29fcb30dce646573b487f2c9375cee457724c
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting appdirs==1.4.4
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting astor==0.8.1
  Using cached astor-0.8.1-py2.py3-none-any.whl (27 kB)
Collecting astroid==2.4.2
  Using cached astroid-2.4.2-py3-none-any.whl (213 kB)
Collecting async-generator==1.10
  Using cached async_generator-1.10-py3-none-any.whl (18 kB)
Collecting attrs==20.3.0
  Using cached attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Collecting backcall==0.2.0
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting black==20.8b1
  Using cached black-20.8b1-py3-none-any.whl
Collecting cffi==1.14.4
  Using cached cffi-1.14.4-cp39-cp39-manylinux1_x86_64.whl (405 kB)
Collecting click==7.1.2
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting coverage==5.3.1
  Using cached coverage-5.3.1-cp39-cp39-manylinux2010_x86_64.whl (244 kB)
Collecting cryptography==3.3.1
  Using cached cryptography-3.3.1-cp36-abi3-manylinux2010_x86_64.whl (2.6 MB)
Collecting decorator==4.4.2
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting flake8==3.8.4
  Using cached flake8-3.8.4-py2.py3-none-any.whl (72 kB)
Collecting idna==2.10
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting immutables==0.14
  Using cached immutables-0.14-cp39-cp39-linux_x86_64.whl
Collecting iniconfig==1.1.1
  Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting ipython-genutils==0.2.0
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting ipython==7.19.0
  Using cached ipython-7.19.0-py3-none-any.whl (784 kB)
Collecting isort==5.7.0
  Using cached isort-5.7.0-py3-none-any.whl (104 kB)
Collecting jedi==0.18.0
  Using cached jedi-0.18.0-py2.py3-none-any.whl (1.4 MB)
Collecting lazy-object-proxy==1.4.3
  Using cached lazy_object_proxy-1.4.3-cp39-cp39-linux_x86_64.whl
Collecting mccabe==0.6.1
  Using cached mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting mypy-extensions==0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting outcome==1.1.0
  Using cached outcome-1.1.0-py2.py3-none-any.whl (9.7 kB)
Collecting packaging==20.8
  Using cached packaging-20.8-py2.py3-none-any.whl (39 kB)
Collecting parso==0.8.1
  Using cached parso-0.8.1-py2.py3-none-any.whl (93 kB)
Collecting pathspec==0.8.1
  Using cached pathspec-0.8.1-py2.py3-none-any.whl (28 kB)
Collecting pexpect==4.8.0
  Using cached pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Collecting pickleshare==0.7.5
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting pluggy==0.13.1
  Using cached pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting prompt-toolkit==3.0.11
  Using cached prompt_toolkit-3.0.11-py3-none-any.whl (358 kB)
Collecting ptyprocess==0.7.0
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting py==1.10.0
  Using cached py-1.10.0-py2.py3-none-any.whl (97 kB)
Collecting pycodestyle==2.6.0
  Using cached pycodestyle-2.6.0-py2.py3-none-any.whl (41 kB)
Collecting pycparser==2.20
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting pyflakes==2.2.0
  Using cached pyflakes-2.2.0-py2.py3-none-any.whl (66 kB)
Collecting pygments==2.7.4
  Using cached Pygments-2.7.4-py3-none-any.whl (950 kB)
Collecting pylint==2.6.0
  Using cached pylint-2.6.0-py3-none-any.whl (325 kB)
Collecting pyopenssl==20.0.1
  Using cached pyOpenSSL-20.0.1-py2.py3-none-any.whl (54 kB)
Collecting pyparsing==2.4.7
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting pytest-cov==2.11.1
  Using cached pytest_cov-2.11.1-py2.py3-none-any.whl (20 kB)
Collecting pytest==6.1.2
  Using cached pytest-6.1.2-py3-none-any.whl (272 kB)
Collecting regex==2020.11.13
  Using cached regex-2020.11.13-cp39-cp39-manylinux2014_x86_64.whl (732 kB)
Collecting six==1.15.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting sniffio==1.2.0
  Using cached sniffio-1.2.0-py3-none-any.whl (10 kB)
Collecting sortedcontainers==2.3.0
  Using cached sortedcontainers-2.3.0-py2.py3-none-any.whl (29 kB)
Collecting toml==0.10.2
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting traitlets==5.0.5
  Using cached traitlets-5.0.5-py3-none-any.whl (100 kB)
Collecting trustme==0.6.0
  Using cached trustme-0.6.0-py2.py3-none-any.whl (14 kB)
Collecting typed-ast==1.4.2
  Using cached typed_ast-1.4.2-cp39-cp39-manylinux1_x86_64.whl (769 kB)
Collecting typing-extensions==3.7.4.3
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting wcwidth==0.2.5
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting wrapt==1.12.1
  Using cached wrapt-1.12.1-cp39-cp39-linux_x86_64.whl
Requirement already satisfied: setuptools>=18.5 in ./venv/lib/python3.9/site-packages (from ipython==7.19.0->-r test-requirements.txt (line 48)) (52.0.0)
Building wheels for collected packages: mypy
  Building wheel for mypy (PEP 517) ... done
  Created wheel for mypy: filename=mypy-0.810+dev.37d29fcb30dce646573b487f2c9375cee457724c-py3-none-any.whl size=2520253 sha256=b990d62239f9138edff2872006d9ecc173a1e8810164f0723fb991f03b881819
  Stored in directory: /home/altendky/.cache/pip/wheels/07/53/e0/d045fb7c08e8a5d2dc09ffe202f58b15823611f212a8db75cf
Successfully built mypy
Installing collected packages: pyparsing, pycparser, wrapt, wcwidth, toml, six, py, ptyprocess, pluggy, parso, packaging, lazy-object-proxy, ipython-genutils, iniconfig, cffi, attrs, typing-extensions, typed-ast, traitlets, regex, pytest, pygments, pyflakes, pycodestyle, prompt-toolkit, pickleshare, pexpect, pathspec, mypy-extensions, mccabe, jedi, isort, idna, decorator, cryptography, coverage, click, backcall, astroid, appdirs, trustme, sortedcontainers, sniffio, pytest-cov, pyopenssl, pylint, outcome, mypy, ipython, immutables, flake8, black, async-generator, astor
Successfully installed appdirs-1.4.4 astor-0.8.1 astroid-2.4.2 async-generator-1.10 attrs-20.3.0 backcall-0.2.0 black-20.8b1 cffi-1.14.4 click-7.1.2 coverage-5.3.1 cryptography-3.3.1 decorator-4.4.2 flake8-3.8.4 idna-2.10 immutables-0.14 iniconfig-1.1.1 ipython-7.19.0 ipython-genutils-0.2.0 isort-5.7.0 jedi-0.18.0 lazy-object-proxy-1.4.3 mccabe-0.6.1 mypy-0.810+dev.37d29fcb30dce646573b487f2c9375cee457724c mypy-extensions-0.4.3 outcome-1.1.0 packaging-20.8 parso-0.8.1 pathspec-0.8.1 pexpect-4.8.0 pickleshare-0.7.5 pluggy-0.13.1 prompt-toolkit-3.0.11 ptyprocess-0.7.0 py-1.10.0 pycodestyle-2.6.0 pycparser-2.20 pyflakes-2.2.0 pygments-2.7.4 pylint-2.6.0 pyopenssl-20.0.1 pyparsing-2.4.7 pytest-6.1.2 pytest-cov-2.11.1 regex-2020.11.13 six-1.15.0 sniffio-1.2.0 sortedcontainers-2.3.0 toml-0.10.2 traitlets-5.0.5 trustme-0.6.0 typed-ast-1.4.2 typing-extensions-3.7.4.3 wcwidth-0.2.5 wrapt-1.12.1
```
```console
$ venv/bin/pip freeze --all
appdirs==1.4.4
astor==0.8.1
astroid==2.4.2
async-generator==1.10
attrs==20.3.0
backcall==0.2.0
black==20.8b1
cffi==1.14.4
click==7.1.2
coverage==5.3.1
cryptography==3.3.1
decorator==4.4.2
flake8==3.8.4
idna==2.10
immutables==0.14
iniconfig==1.1.1
ipython==7.19.0
ipython-genutils==0.2.0
isort==5.7.0
jedi==0.18.0
lazy-object-proxy==1.4.3
mccabe==0.6.1
mypy @ git+https://github.com/python/mypy@37d29fcb30dce646573b487f2c9375cee457724c
mypy-extensions==0.4.3
outcome==1.1.0
packaging==20.8
parso==0.8.1
pathspec==0.8.1
pexpect==4.8.0
pickleshare==0.7.5
pip==21.0
pluggy==0.13.1
prompt-toolkit==3.0.11
ptyprocess==0.7.0
py==1.10.0
pycodestyle==2.6.0
pycparser==2.20
pyflakes==2.2.0
Pygments==2.7.4
pylint==2.6.0
pyOpenSSL==20.0.1
pyparsing==2.4.7
pytest==6.1.2
pytest-cov==2.11.1
regex==2020.11.13
setuptools==52.0.0
six==1.15.0
sniffio==1.2.0
sortedcontainers==2.3.0
toml==0.10.2
traitlets==5.0.5
trustme==0.6.0
typed-ast==1.4.2
typing-extensions==3.7.4.3
wcwidth==0.2.5
wheel==0.36.2
wrapt==1.12.1
```
```console
$ venv/bin/mypy -p trio --show-error-codes --platform linux --show-traceback
trio/_core/_run.py:83: error: String argument 1 '_fn' to TypeVar(...) does not match variable name '_Fn'  [misc]
trio/_core/_run.py:83: error: Argument "bound" to "TypeVar" has incompatible type "object"; expected "Union[None, Type[Any], str]"  [arg-type]
trio/_core/_run.py:88: error: Variable "trio._core._run._Fn" is not valid as a type  [valid-type]
trio/_core/_run.py:88: note: See https://mypy.readthedocs.io/en/latest/common_issues.html#variables-vs-type-aliases
trio/_threads.py:253: error: Name '_AF' is not defined  [name-defined]
trio/_threads.py:291: error: Name 'unprotected_afn' already defined on line 289  [no-redef]
trio/_socket.py:304: error: Type of decorated function contains type "Any" ("Callable[[VarArg(Any), KwArg(Any)], Any]")  [misc]
trio/_socket.py:595: error: Signature of "family" incompatible with supertype "SocketType"  [override]
trio/_socket.py:599: error: Signature of "type" incompatible with supertype "SocketType"  [override]
trio/_socket.py:606: error: Signature of "proto" incompatible with supertype "SocketType"  [override]
trio/_socket.py:610: error: Signature of "did_shutdown_SHUT_WR" incompatible with supertype "SocketType"  [override]
trio/_socket.py:926: error: Type of decorated function contains type "Any" ("Callable[[_SocketType, VarArg(Any)], Any]")  [misc]
trio/_socket.py:945: error: Type of decorated function contains type "Any" ("Callable[[_SocketType, VarArg(Any)], Any]")  [misc]
/home/altendky/repos/trio/tmp/trio/trio/_core/_run.py:1438: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.810+dev.37d29fcb30dce646573b487f2c9375cee457724c
Traceback (most recent call last):
  File "/home/altendky/repos/trio/tmp/trio/venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/main.py", line 90, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/build.py", line 179, in build
    result = _build(
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/build.py", line 253, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/build.py", line 2632, in dispatch
    process_graph(graph, manager)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/build.py", line 2958, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/build.py", line 3056, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/build.py", line 2130, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/checker.py", line 294, in check_first_pass
    self.accept(d)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/checker.py", line 401, in accept
    stmt.accept(self)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/nodes.py", line 950, in accept
    return visitor.visit_class_def(self)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/checker.py", line 1723, in visit_class_def
    self.accept(defn.defs)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/checker.py", line 401, in accept
    stmt.accept(self)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/nodes.py", line 1015, in accept
    return visitor.visit_block(self)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/checker.py", line 1972, in visit_block
    self.accept(s)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/checker.py", line 401, in accept
    stmt.accept(self)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/nodes.py", line 526, in accept
    return visitor.visit_overloaded_func_def(self)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/checker.py", line 434, in visit_overloaded_func_def
    self._visit_overloaded_func_def(defn)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/checker.py", line 461, in _visit_overloaded_func_def
    self.check_overlapping_overloads(defn)
  File "/home/altendky/repos/trio/tmp/trio/venv/lib/python3.9/site-packages/mypy/checker.py", line 482, in check_overlapping_overloads
    assert isinstance(inner_type, CallableType)
AssertionError: 
/home/altendky/repos/trio/tmp/trio/trio/_core/_run.py:1438: : note: use --pdb to drop into pdb
```

</details>

**To Reproduce**

```bash
git clone https://github.com/altendky/trio
cd trio
git checkout 484f13f124f614cde356b50dbbf53f29731dcfc0
python3.9 -m venv venv
venv/bin/python --version --version
venv/bin/python -m pip install --upgrade pip setuptools wheel
venv/bin/python -m pip install --requirement test-requirements.txt
venv/bin/pip freeze --all
venv/bin/mypy -p trio --show-error-codes --platform linux --show-traceback
```

**Your Environment**

- Mypy version used: `git+https://github.com/python/mypy@37d29fcb30dce646573b487f2c9375cee457724c`
- Mypy command-line flags: `-p trio --show-error-codes --platform linux --show-traceback`
- Mypy configuration options from `mypy.ini` (and other config files):
```ini
[mypy]
# TODO: run mypy against several OS/version combos in CI
# https://mypy.readthedocs.io/en/latest/command_line.html#platform-configuration

# Be flexible about dependencies that don't have stubs yet (like pytest)
ignore_missing_imports = True

# Be strict about use of Mypy
warn_unused_ignores = True
warn_unused_configs = True
warn_redundant_casts = True
warn_return_any = True

# Avoid subtle backsliding
disallow_any_decorated = True
disallow_incomplete_defs = True
disallow_subclassing_any = True

# Enable gradually / for new modules
check_untyped_defs = False
disallow_untyped_calls = False
disallow_untyped_defs = False

# DO NOT use `ignore_errors`; it doesn't apply
# downstream and users have to deal with them.
```
- Python version used:
```
Python 3.9.1 (default, Jan  6 2021, 10:22:00) 
[GCC 9.3.0]
```
- Operating system and version:
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```

**Comment by pranavrajpal** [comment]
I think this is similar to the problem in #8356 (as described in https://github.com/python/mypy/issues/8356#issuecomment-884655875). I'd guess that the problem is that the error with the `_Fn` type variable causes the return type of the `_public` decorator [here](https://github.com/altendky/trio/blob/484f13f124f614cde356b50dbbf53f29731dcfc0/trio/_core/_run.py#L1446) to be changed to something other than a callable.

**Comment by pranavrajpal** [comment]
Simplified example:
```python
from typing import Any, Callable, Union, overload, TypeVar

_Fn = TypeVar("_fn", bound=Callable[..., Any])


def _public(fn: _Fn) -> _Fn:
    return fn


@overload
def func(a: int) -> int:
    ...


@overload
def func(a: str) -> str:
    ...


@_public
def func(a: Union[int, str]) -> Union[int, str]:
    pass
```

Running with `mypy run.py --show-traceback` (with or without incremental mode):
```
run.py:3: error: String argument 1 "_fn" to TypeVar(...) does not match variable name "_Fn"
run.py:3: error: Argument "bound" to "TypeVar" has incompatible type "object"; expected "Union[None, Type[Any], str]"
run.py:6: error: Variable "run._Fn" is not valid as a type
run.py:6: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
run.py:10: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.920+dev.9cbd2103abbc2afb518bbfe727b7c3e7bcd55f3a
Traceback (most recent call last):
  File "/home/pranav/.local/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/pranav/.local/lib/python3.8/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/home/pranav/.local/lib/python3.8/site-packages/mypy/main.py", line 87, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "/home/pranav/.local/lib/python3.8/site-packages/mypy/main.py", line 165, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/home/pranav/.local/lib/python3.8/site-packages/mypy/build.py", line 180, in build
    result = _build(
  File "/home/pranav/.local/lib/python3.8/site-packages/mypy/build.py", line 256, in _build
    graph = dispatch(sources, manager, stdout)
  File "/home/pranav/.local/lib/python3.8/site-packages/mypy/build.py", line 2712, in dispatch
    process_graph(graph, manager)
  File "/home/pranav/.local/lib/python3.8/site-packages/mypy/build.py", line 3043, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/home/pranav/.local/lib/python3.8/site-packages/mypy/build.py", line 3141, in process_stale_scc
    graph[id].type_check_first_pass()
  File "/home/pranav/.local/lib/python3.8/site-packages/mypy/build.py", line 2177, in type_check_first_pass
    self.type_checker().check_first_pass()
  File "/home/pranav/.local/lib/python3.8/site-packages/mypy/checker.py", line 315, in check_first_pass
    self.accept(d)
  File "/home/pranav/.local/lib/python3.8/site-packages/mypy/checker.py", line 421, in accept
    stmt.accept(self)
  File "/home/pranav/.local/lib/python3.8/site-packages/mypy/nodes.py", line 555, in accept
    return visitor.visit_overloaded_func_def(self)
  File "/home/pranav/.local/lib/python3.8/site-packages/mypy/checker.py", line 454, in visit_overloaded_func_def
    self._visit_overloaded_func_def(defn)
  File "/home/pranav/.local/lib/python3.8/site-packages/mypy/checker.py", line 481, in _visit_overloaded_func_def
    self.check_overlapping_overloads(defn)
  File "/home/pranav/.local/lib/python3.8/site-packages/mypy/checker.py", line 509, in check_overlapping_overloads
    assert isinstance(inner_type, CallableType)
AssertionError: 
run.py:10: : note: use --pdb to drop into pdb
```
